CREATE VIEW LISTADO_VENTAS
AS
SELECT 
C.DOCUMENT_ID AS TIP_DOC,              
C.NUMBER_SERIE AS SERIE,               
C.NUMBER_DOCUMENT  AS NUMERO,              
CONVERT(VARCHAR(10),C.DOCUMENT_DATE,103)AS FECHA_DOC,              
CONVERT(VARCHAR(10),C.CADUCATE_DATE,103)AS FECHA_VENC,              
CONVERT(NUMERIC(22,2),C.AMOUNT,0) AS IMPORTE_ORIG,                         
C.SALES_REP_ID,
S.NAME AS VEND,                            
C.CUSTOMER_ID +' '+C.CUSTOMER_NAME AS CLIENTE,              
CONVERT(NUMERIC(22,2),(ISNULL(C.AMOUNT,0)/((L.TAX_PERCENT+100)/100))) MON_AFECT,              
CONVERT(NUMERIC(22,2),ISNULL(L.COMISION,0)) AS COMIS,              
CONVERT(NUMERIC(22,2),(ISNULL(C.AMOUNT,0)/((L.TAX_PERCENT+100)/100))* ISNULL(L.COMISION,0)/100) AS MON_COMIS              
FROM DBO.RECEIVABLE C             
INNER JOIN DBO.RECEIVABLE_LINE L              
ON C.DOCUMENT_ID=L.DOCUMENT_ID AND  C.NUMBER_SERIE=L.NUMBER_SERIE              
AND C.NUMBER_DOCUMENT=L.NUMBER_DOCUMENT              
INNER JOIN DBO.SALES_REP S              
ON S.ID=C.SALES_REP_ID              
WHERE  C.STATUS='V'               
AND L.COMISION >0  
GROUP BY C.DOCUMENT_ID,C.NUMBER_SERIE,C.NUMBER_DOCUMENT,C.DOCUMENT_DATE,C.CADUCATE_DATE,  
C.AMOUNT,C.SALES_REP_ID,S.NAME,C.CUSTOMER_ID,  
C.CUSTOMER_NAME,L.TAX_PERCENT  ,L.COMISION

--SELECT * FROM      LISTADO_VENTAS
          

