
CREATE VIEW vwCarteraPend 
 AS 
 SELECT RTRIM(CUSTOMER.NAME) AS cnomcli, CUSTOMER_BALANCE.* 
 FROM DBO.CUSTOMER_BALANCE INNER JOIN DBO.CUSTOMER ON CUSTOMER_BALANCE.CUSTOMER_ID = CUSTOMER.ID 
 WHERE AMOUNT_BALANCE <> 0 AND  CUSTOMER_BALANCE.ACCOUNT<>'S'
