create view [vwMoresMesIngSal] 
as 
	select VWSAL.WAREHOUSE_ID,VWSAL.PART_ID,VWSAL.DATE_DOCUMENT,
	0.0 as ENTR,VWSAL.SALIDA AS SALI,VWSAL.AVERAGE_COST,
	VWSAL.CURRENCY_TYPE,VWSAL.CURRENCY_EXCHANGE,VWSAL.UNIT_PART,
	VWSAL.TYPE_TRANS,VWSAL.TRANS_ID,VWSAL.DOCUMENT_ID,VWSAL.NUMBER_DOCUMENT,
	VWSAL.ITEM,VWSAL.STATUS_VALUE 
from vwMoresmesSAL VWSAL 
	union all 
		select VWING.WAREHOUSE_ID,VWING.PART_ID,VWING.DATE_DOCUMENT,
				VWING.ENTRADA as ENTR ,0.0 as SALI,
				VWING.AVERAGE_COST,VWING.CURRENCY_TYPE,VWING.CURRENCY_EXCHANGE,
				VWING.UNIT_PART,VWING.TYPE_TRANS,VWING.TRANS_ID,
				VWING.DOCUMENT_ID,VWING.NUMBER_DOCUMENT,VWING.ITEM,
				VWING.STATUS_VALUE from vwMoresmesING VWING


