create view [dbo].[vwMoresmesSAL] 
as 
	select A.WAREHOUSE_ID,A.PART_ID,A.QTY AS SALIDA,A.AVERAGE_COST,
			B.CURRENCY_TYPE,B.CURRENCY_EXCHANGE,A.UNIT_PART,B.DATE_DOCUMENT,B.TYPE_TRANS,
			B.TRANS_ID,B.DOCUMENT_ID,B.NUMBER_DOCUMENT,A.ITEM,A.STATUS_VALUE 
	from WAREHOUSE_TRANS as B 
		inner join (WAREHOUSE_TRANS_LINE as A left join PART as M 
		on A.PART_ID=M.ID) on (B.NUMBER_DOCUMENT=A.NUMBER_DOCUMENT) 
		and (B.DOCUMENT_ID=A.DOCUMENT_ID) and (B.WAREHOUSE_ID=A.WAREHOUSE_ID) 
	where (((B.TYPE_TRANS)='S') 
		and (not(B.DOCUMENT_ID='GS' and B.TRANS_ID='GF' and B.STATUS_GUIA='F')) 
		and ((B.STATUS_GUIA)<>'A')) 
		and not(M.IS_STOCKED='N' and M.IS_LOT='N' and M.SERIES='N' 
		and A.PART_ID<>'TEXTO')



