CREATE TABLE [dbo].[ACCOUNT_BANK] (
    [BANK_ID]          VARCHAR (2)   NULL,
    [ACCOUNT_BANK_ID]  VARCHAR (20)  NULL,
    [ACCOUNT_BANK_DES] VARCHAR (100) NULL,
    [NUMBER_ACCOUNT]   VARCHAR (18)  NULL,
    [CURRENCY_ID]      VARCHAR (2)   NULL,
    [TYPE_DOC]         VARCHAR (2)   NULL
);



