CREATE TABLE [dbo].[ACCOUNT_PARAMETERS] (
    [RECEIVE_TYPE] VARCHAR (2)  NOT NULL,
    [ACCOUNT]      VARCHAR (18) NULL,
    [ACCOUNT_US]   VARCHAR (18) NULL,
    [ACCOUNT1]     VARCHAR (18) NULL,
    [ACCOUNT2]     VARCHAR (18) NULL,
    [CCOST]        VARCHAR (18) NULL
);

