CREATE TABLE [dbo].[ADM_NIVELES] (
    [COD_NIVEL] CHAR (2)     NOT NULL,
    [DES_NIVEL] VARCHAR (50) NULL,
    [ADMIN_SN]  CHAR (1)     NULL,
    CONSTRAINT [PK_NIVELES] PRIMARY KEY CLUSTERED ([COD_NIVEL] ASC)
);

