CREATE TABLE [dbo].[ADM_MODULE_SECURITY] (
    [MODULE_ID]   VARCHAR (2)   NOT NULL,
    [USER_ID]     VARCHAR (10)  NOT NULL,
    [EXE_ID]      VARCHAR (50)  NOT NULL,
    [NOM_EXE]     VARCHAR (80)  NULL,
    [IS_VISIBLE]  VARCHAR (1)   NULL,
    [CREATE_DATE] SMALLDATETIME NULL,
    [CREATE_USER] VARCHAR (50)  NULL,
    [COMPUTER_ID] VARCHAR (100) NULL
);

