CREATE TABLE [dbo].[ADM_MENU_SECURITY] (
    [MODULE_ID]   VARCHAR (2)   NOT NULL,
    [USER_ID]     VARCHAR (10)  NOT NULL,
    [IS_VISIBLE]  VARCHAR (1)   NULL,
    [CREATE_DATE] DATETIME      NULL,
    [CREATE_USER] VARCHAR (50)  NULL,
    [COMPUTER_ID] VARCHAR (100) NULL,
    CONSTRAINT [PK_MENU_SEC] PRIMARY KEY CLUSTERED ([MODULE_ID] ASC, [USER_ID] ASC)
);

