CREATE TABLE [dbo].[ADMINISTRATOR] (
    [ID]          VARCHAR (5)   NOT NULL,
    [NAME]        VARCHAR (10)  NULL,
    [PASSWORD]    VARCHAR (8)   NULL,
    [CREATE_DATE] SMALLDATETIME NULL,
    [DELETE_DATE] SMALLDATETIME NULL
);

