CREATE TABLE [dbo].[ALMACEN_OSINERG] (
    [COD_DMAY]     VARCHAR (10) NULL,
    [DES_DMAY]     VARCHAR (80) NULL,
    [COD_OPER]     VARCHAR (10) NULL,
    [COD_ALMACEN]  VARCHAR (10) NULL,
    [TIPO_ALMACEN] VARCHAR (10) NULL
);

