CREATE TABLE [dbo].[ALMACEN] (
    [CODALMACEN]       VARCHAR (2)  NOT NULL,
    [DESALMACEN]       VARCHAR (25) NULL,
    [CODTIPO]          VARCHAR (2)  NULL,
    [FISCALALMACEN]    VARCHAR (2)  NULL,
    [COD_INTERNO_SCOP] VARCHAR (50) NULL
);

