CREATE TABLE [dbo].[AUTO_USER_ORDERS] (
    [USER_ID]       VARCHAR (50)  NOT NULL,
    [AUTO_STATUS]   VARCHAR (1)   NULL,
    [PASSWORD_USER] VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([USER_ID] ASC)
);

