CREATE TABLE [dbo].[BANK_IMPORT] (
    [BANK_ID]       VARCHAR (3)   NOT NULL,
    [NUMBER_IMPORT] VARCHAR (13)  NOT NULL,
    [NUM_FAC]       VARCHAR (20)  NULL,
    [DATE_FAC]      SMALLDATETIME NULL,
    [COB_EXT]       VARCHAR (20)  NULL,
    [DATE_CADUCATE] SMALLDATETIME NULL,
    CONSTRAINT [PK_BANK_IMPORT] PRIMARY KEY CLUSTERED ([BANK_ID] ASC, [NUMBER_IMPORT] ASC)
);

