CREATE TABLE [dbo].[CENTER_COST] (
    [COST_CENTER_ID]          VARCHAR (41)  NOT NULL,
    [COST_CENTER_DESCRIPTION] VARCHAR (100) NULL,
    [CREATE_DATE]             DATETIME      NULL,
    [IS_STATUS]               VARCHAR (1)   NULL,
    [USER_ID]                 VARCHAR (100) NULL,
    [LAST_MODIFY_DATE]        DATETIME      NULL,
    [COMPUTER_ID]             VARCHAR (100) NULL,
    [USER_MODIFIED]           VARCHAR (100) NULL,
    [NODE_ID]                 VARCHAR (41)  NULL,
    [NODE_KEY]                VARCHAR (41)  NULL,
    [LEVEL_CCOST]             VARCHAR (1)   NULL,
    CONSTRAINT [PK__CENTER_COST__403A8C7D] PRIMARY KEY CLUSTERED ([COST_CENTER_ID] ASC),
    CONSTRAINT [CK__CENTER_CO__IS_ST__3F466844] CHECK ([IS_STATUS] = 0 or [IS_STATUS] = 1)
);

