CREATE TABLE [dbo].[CO_TB_REP_BG10] (
    [RB_IDAREA]    VARCHAR (2)   NULL,
    [RB_NOAREA]    VARCHAR (100) NULL,
    [RB_IDMOD]     VARCHAR (2)   NULL,
    [RB_NOMOD]     VARCHAR (100) NULL,
    [RB_NUCUENTA]  VARCHAR (10)  NULL,
    [RB_NOCUENTA]  VARCHAR (100) NULL,
    [RB_IMPORTE]   FLOAT (53)    NULL,
    [RB_ULT_LINEA] VARCHAR (2)   NULL,
    [RB_IMPORTE2]  FLOAT (53)    NULL,
    [RB_TIT_MOV]   VARCHAR (100) NULL
);

