CREATE TABLE [dbo].[CO_TB_ASIENTO_DET] (
    [AD_IDCAB]         INT           NOT NULL,
    [AD_SECUENCIA]     INT           NOT NULL,
    [AD_CUENTA]        VARCHAR (20)  NULL,
    [AD_TANEXO]        INT           NULL,
    [AD_IDANEXO]       VARCHAR (15)  NULL,
    [AD_TDOC]          VARCHAR (3)   NULL,
    [AD_SDOC]          VARCHAR (10)  NULL,
    [AD_NDOC]          VARCHAR (20)  NULL,
    [AD_FDOC]          DATETIME      NULL,
    [AD_VDOC]          DATETIME      NULL,
    [AD_DEBE]          FLOAT (53)    NULL,
    [AD_HABER]         FLOAT (53)    NULL,
    [AD_TCAM]          FLOAT (53)    NULL,
    [AD_SEC_ORI_DES]   INT           NULL,
    [AD_IDCC]          VARCHAR (50)  NULL,
    [AD_ES_DESTINO]    INT           NULL,
    [AD_IDMEDIOPAGO]   VARCHAR (3)   NULL,
    [AD_MONTO_ORI]     FLOAT (53)    NULL,
    [AD_PORCE_DESTINO] FLOAT (53)    NULL,
    [AD_ES_CONCI]      INT           NULL,
    [AD_ANHO_CONI]     INT           NULL,
    [AD_MES_CONCI]     INT           NULL,
    [AD_ES_INAFECTO]   INT           NULL,
    [AD_IDMONEDA]      INT           NULL,
    [AD_TDOC_REF]      VARCHAR (3)   NULL,
    [AD_SDOC_REF]      VARCHAR (10)  NULL,
    [AD_NDOC_REF]      VARCHAR (20)  NULL,
    [AD_FDOC_REF]      DATETIME      NULL,
    [AD_VDOC_REF]      DATETIME      NULL,
    [AD_GLOSA]         VARCHAR (100) NULL,
    CONSTRAINT [PK_CO_TB_ASIENTO_DET] PRIMARY KEY CLUSTERED ([AD_IDCAB] ASC, [AD_SECUENCIA] ASC)
);

