CREATE TABLE [dbo].[CO_TB_PARAMETROS] (
    [CTA_IGV]       VARCHAR (50) NULL,
    [CTA_DIF_GAN]   VARCHAR (50) NULL,
    [CTA_DIF_PER]   VARCHAR (50) NULL,
    [CTA_RETEN_RH]  VARCHAR (50) NULL,
    [CTA_BASE_HONO] VARCHAR (50) NULL,
    [CTA_ISC]       VARCHAR (50) NULL
);

