CREATE TABLE [dbo].[COMPANY_TYPE] (
    [COMPANY_TYPE_ID]  VARCHAR (2)   NULL,
    [DESCRIPTION]      VARCHAR (80)  NULL,
    [CREATE_DATE]      DATETIME      NULL,
    [USER_ID]          VARCHAR (100) NULL,
    [LAST_MODIFY_DATE] DATETIME      NULL,
    [USER_MODIFIED]    VARCHAR (100) NULL,
    [COMPUTER_ID]      VARCHAR (100) NULL
);

