CREATE TABLE [dbo].[CREDIT_LIMIT] (
    [CUSTOMER_ID]  VARCHAR (11)    NULL,
    [CURRENCY_ID]  VARCHAR (2)     NULL,
    [AMOUNT_LIMIT] NUMERIC (15, 6) NULL,
    [COMMENT]      VARCHAR (50)    NULL,
    [CREATE_DATE]  SMALLDATETIME   NULL,
    [USER_ID]      VARCHAR (8)     NULL
);

