CREATE TABLE [dbo].[CURRENCY_IMPORT] (
    [CURRTIPIMP_ID]  VARCHAR (3)     NOT NULL,
    [CURRENCY_MONTH] VARCHAR (2)     NOT NULL,
    [CURRENCY_YEAR]  VARCHAR (4)     NOT NULL,
    [EQUIVALENCE]    NUMERIC (15, 9) NULL
);

