CREATE TABLE [dbo].[CURRENCY_IMPORT_TYPE] (
    [CURRTIPIMP_ID] VARCHAR (3)  NOT NULL,
    [DESCRIPTION]   VARCHAR (20) NULL,
    [SYMBOL]        VARCHAR (2)  NULL,
    [COUNTRY_ID]    VARCHAR (3)  NULL
);

