CREATE TABLE [dbo].[CURRENCY_EXCHANGE] (
    [CURRENCY_ID]   VARCHAR (2)     NOT NULL,
    [CURRENCY_DATE] DATETIME        NOT NULL,
    [BUY_RATE]      NUMERIC (15, 6) NULL,
    [BUY_EQUIV]     NUMERIC (15, 6) NULL,
    [SELL_RATE]     NUMERIC (15, 6) NULL,
    [SELL_EQUIV]    NUMERIC (15, 6) NULL
);

