CREATE TABLE [dbo].[CUSTOMER_BALANCE] (
    [CUSTOMER_ID]        VARCHAR (11)    NULL,
    [DOCUMENT_ID]        VARCHAR (2)     NULL,
    [NUMBER_DOC]         VARCHAR (10)    NULL,
    [DOC_DATE]           DATETIME        NULL,
    [CADUCATE_DATE]      SMALLDATETIME   NULL,
    [DOCUMENT_REF]       VARCHAR (2)     NULL,
    [NUMBER_REF]         VARCHAR (10)    NULL,
    [SALES_ID]           VARCHAR (2)     NULL,
    [AMOUNT]             NUMERIC (15, 6) NULL,
    [AMOUNT_BALANCE]     NUMERIC (15, 6) NULL,
    [CURRENCY_ID]        VARCHAR (2)     NULL,
    [SELL_RATE]          NUMERIC (12, 5) NULL,
    [IS_DR_CR]           VARCHAR (1)     NULL,
    [STATUS]             VARCHAR (1)     NULL,
    [CREATE_DATE]        DATETIME        NULL,
    [LAST_MODIFIED]      DATETIME        NULL,
    [USER_ID]            VARCHAR (8)     NULL,
    [ACCOUNT]            VARCHAR (21)    NULL,
    [AMOUNT_COMM]        NUMERIC (15, 6) NULL,
    [TYPE_REC]           VARCHAR (2)     NULL,
    [REFERENCE_DATE]     DATETIME        NULL,
    [IS_CHECK_DIF]       VARCHAR (1)     NULL,
    [AMOUNT_BALANCE_INI] NUMERIC (15, 6) NULL,
    [TERMS]              VARCHAR (4)     NULL,
    [PLACE_SALES]        VARCHAR (2)     NULL,
    [BANK_ID]            VARCHAR (2)     NULL,
    [BANK_DESCRIPTION]   VARCHAR (100)   NULL,
    [AMOUNT_PER]         NUMERIC (15, 6) NULL,
    [PERCENT_PER]        NUMERIC (15, 6) NULL,
    [ACCOUNT_PER]        VARCHAR (18)    NULL,
    [CUST_AUTO]          CHAR (1)        NULL,
    [SERIE_AUX]          VARCHAR (50)    NULL,
    [NUM_DOC_AUX]        VARCHAR (50)    NULL
);

