CREATE TABLE [dbo].[CUSTOMS_IMPORT] (
    [NUMBER_IMPORT] VARCHAR (13) NOT NULL,
    [CUSTOMS_ID]    VARCHAR (3)  NOT NULL,
    [COTECNA]       VARCHAR (20) NULL,
    [COB_EXT]       VARCHAR (20) NULL,
    [SECURE]        VARCHAR (20) NULL,
    [COUNTRY_ID]    VARCHAR (3)  NULL,
    CONSTRAINT [PK_CUSTOMS_IMPORT] PRIMARY KEY CLUSTERED ([NUMBER_IMPORT] ASC, [CUSTOMS_ID] ASC)
);

