CREATE TABLE [dbo].[CUSTOMER] (
    [ID]                      VARCHAR (20)    NOT NULL,
    [NAME]                    VARCHAR (150)   NULL,
    [ADDR]                    VARCHAR (100)   NULL,
    [PHONE]                   VARCHAR (30)    NULL,
    [VAT_REGISTRATION]        VARCHAR (11)    NULL,
    [NUMBER_DOC]              VARCHAR (11)    NULL,
    [DISCOUNT_PERCENT]        NUMERIC (15, 6) NULL,
    [TERMS_TYPE]              VARCHAR (4)     NULL,
    [STATUS]                  VARCHAR (1)     NULL,
    [OPEN_DATE]               SMALLDATETIME   NULL,
    [CONTACT]                 VARCHAR (200)   NULL,
    [STATE_ID]                VARCHAR (8)     NULL,
    [CREATE_USER]             VARCHAR (8)     NULL,
    [CREATE_DATE]             SMALLDATETIME   NULL,
    [MODIFY_DATE]             SMALLDATETIME   NULL,
    [TYPE_PRICE]              VARCHAR (2)     NULL,
    [SALES_ID]                VARCHAR (2)     NULL,
    [SELL_ZONE]               VARCHAR (8)     NULL,
    [COUNTRY]                 VARCHAR (30)    NULL,
    [DEPARTMENT]              VARCHAR (30)    NULL,
    [PROVINCE]                VARCHAR (30)    NULL,
    [ADDR_DLV]                VARCHAR (100)   NULL,
    [CURRENCY_CREDIT_LIMIT]   VARCHAR (2)     NULL,
    [CREDIT_LIMIT_US]         NUMERIC (15, 6) NULL,
    [CREDIT_LIMIT]            NUMERIC (15, 6) NULL,
    [BALANCE]                 NUMERIC (15, 6) NULL,
    [BALANCE_US]              NUMERIC (15, 6) NULL,
    [OBSERV]                  VARCHAR (30)    NULL,
    [TOTAL_LETTER]            NUMERIC (15, 6) NULL,
    [TOTAL_RECEIVABLE]        NUMERIC (15, 6) NULL,
    [TOTAL_CHECK]             NUMERIC (15, 6) NULL,
    [TOTAL_LETTER_PROTESTED]  NUMERIC (15, 6) NULL,
    [CUSTOMER_TYPE]           VARCHAR (2)     NULL,
    [BUSINESS_TYPE]           VARCHAR (2)     NULL,
    [TERRITORY]               VARCHAR (2)     NULL,
    [ROUTE]                   VARCHAR (2)     NULL,
    [SEGMENT]                 VARCHAR (3)     NULL,
    [SEGMENT_LOCATION]        VARCHAR (3)     NULL,
    [BANK_ID]                 VARCHAR (3)     NULL,
    [ACCOUNT_NO]              VARCHAR (12)    NULL,
    [DATE_REVIEW]             VARCHAR (8)     NULL,
    [HOUR_VISIT]              VARCHAR (20)    NULL,
    [ATTENTION_TYPE]          VARCHAR (2)     NULL,
    [FAX_NUMBER]              VARCHAR (15)    NULL,
    [EMAIL]                   VARCHAR (80)    NULL,
    [WEBSITE]                 VARCHAR (80)    NULL,
    [COMMENT]                 VARCHAR (250)   NULL,
    [IS_PRIMARY]              VARCHAR (1)     NOT NULL,
    [RETENTION]               VARCHAR (1)     NULL,
    [DOCUMENT_TYPE_PERSON_ID] VARCHAR (2)     NULL,
    [TYPE_COMPANY]            VARCHAR (80)    NULL,
    [ACCOUNT_LOCAL]           VARCHAR (50)    NULL,
    [ACCOUNT_EXTERNAL]        VARCHAR (50)    NULL
);

