CREATE TABLE [dbo].[delete_receivable_line] (
    [DOCUMENT_ID]        VARCHAR (2)     NULL,
    [NUMBER_SERIE]       VARCHAR (3)     NULL,
    [NUMBER_DOCUMENT]    VARCHAR (7)     NULL,
    [ITEM]               VARCHAR (2)     NULL,
    [PART_ID]            VARCHAR (20)    NULL,
    [QTY]                NUMERIC (15, 6) NULL,
    [PRICE_SALES]        NUMERIC (15, 6) NULL,
    [PRICE_ORI]          NUMERIC (15, 6) NULL,
    [DISCOUNT]           NUMERIC (15, 6) NULL,
    [AMOUNT_TAX]         NUMERIC (15, 6) NULL,
    [TAX_PERCENT]        NUMERIC (15, 6) NULL,
    [AMOUNT_US]          NUMERIC (15, 6) NULL,
    [AMOUNT]             NUMERIC (15, 6) NULL,
    [UNIT]               VARCHAR (6)     NULL,
    [STATUS]             VARCHAR (1)     NULL,
    [PART_SERIE]         VARCHAR (20)    NULL,
    [WAREHOUSE_ID]       VARCHAR (2)     NULL,
    [TEXT_DESCRIPTION]   VARCHAR (100)   NULL,
    [DFTR]               VARCHAR (1)     NULL,
    [STOCK]              VARCHAR (1)     NULL,
    [PART_DESCRIPTION]   VARCHAR (64)    NULL,
    [QTY_REF]            NUMERIC (15, 6) NULL,
    [DISCOUNT_PERCENT]   NUMERIC (15, 6) NULL,
    [BALANCE_PART]       NUMERIC (15, 6) NULL,
    [DISCOUNT_CUSTOMER]  NUMERIC (15, 6) NULL,
    [DISCOUNT_SP]        NUMERIC (15, 6) NULL,
    [PART_LOT]           VARCHAR (20)    NULL,
    [NUMBER_GUIA]        VARCHAR (10)    NULL,
    [PART_TAX]           BIT             NULL,
    [DISCOUNT1]          NUMERIC (15, 6) NULL,
    [DISCOUNT2]          NUMERIC (15, 6) NULL,
    [PERCENT1]           NUMERIC (15, 6) NULL,
    [PERCENT2]           NUMERIC (15, 6) NULL,
    [PRICE_LIST_ID]      VARCHAR (2)     NULL,
    [SHIPPER_QTY]        NUMERIC (15, 6) NULL,
    [BUDGET_ID]          VARCHAR (50)    NULL,
    [ORDER_ID]           VARCHAR (20)    NULL,
    [BRUTE_QTY]          NUMERIC (15, 6) NULL,
    [DISCOUNT_QTY_BRUTE] NUMERIC (15, 6) NULL,
    [UM_REFERENCE]       VARCHAR (6)     NULL,
    [QTY_REFERENCE]      NUMERIC (15, 6) NULL,
    [COMISION]           NUMERIC (22, 9) NULL,
    [TIPOISC]            FLOAT (53)      NULL,
    [ISCPOR]             FLOAT (53)      NULL,
    [ISC]                FLOAT (53)      NULL
);

