CREATE TABLE [dbo].[delete_receivable] (
    [DOCUMENT_ID]         VARCHAR (2)     NULL,
    [NUMBER_SERIE]        VARCHAR (3)     NULL,
    [NUMBER_DOCUMENT]     VARCHAR (7)     NULL,
    [DOCUMENT_DATE]       DATETIME        NULL,
    [CADUCATE_DATE]       DATETIME        NULL,
    [DR_CR]               VARCHAR (1)     NULL,
    [SALES_REP_ID]        VARCHAR (2)     NULL,
    [PLACE_SALES]         VARCHAR (2)     NULL,
    [NUMBER_QUOTE]        VARCHAR (10)    NULL,
    [NUMBER_ORDER_PUR]    VARCHAR (20)    NULL,
    [CFDESCPG]            VARCHAR (50)    NULL,
    [POINT_ORIG]          VARCHAR (50)    NULL,
    [POINT_BOARD]         VARCHAR (50)    NULL,
    [POINT_ARRIVAL]       VARCHAR (50)    NULL,
    [RECEIVABLE_TYPE]     VARCHAR (2)     NULL,
    [CUSTOMER_ID]         VARCHAR (11)    NULL,
    [CUSTOMER_NAME]       VARCHAR (150)   NULL,
    [CUSTOMER_ADDR]       VARCHAR (100)   NULL,
    [VAT_REGISTRATION]    VARCHAR (11)    NULL,
    [WAREHOUSE_ID]        VARCHAR (2)     NULL,
    [AMOUNT]              NUMERIC (15, 6) NULL,
    [TERMS_ID]            VARCHAR (4)     NULL,
    [BALANCE]             NUMERIC (15, 6) NULL,
    [SELL_RATE]           NUMERIC (15, 6) NULL,
    [CURRENCY_ID]         VARCHAR (2)     NULL,
    [DOCUMENT_REF]        VARCHAR (2)     NULL,
    [SERIE_REF]           VARCHAR (3)     NULL,
    [NUMBER_REF]          VARCHAR (7)     NULL,
    [NUMBER_ORDER]        VARCHAR (10)    NULL,
    [CREATE_DATE]         DATETIME        NULL,
    [LAST_MODIFIED]       DATETIME        NULL,
    [STATUS]              VARCHAR (1)     NULL,
    [USER_ID]             VARCHAR (8)     NULL,
    [COMMENT]             VARCHAR (100)   NULL,
    [IS_GUIA_REC]         VARCHAR (1)     NULL,
    [NUMBER_REGISTRATION] VARCHAR (11)    NULL,
    [DISCOUNT_PERCENT]    NUMERIC (15, 6) NULL,
    [DISCOUNT_PERCENT_SP] NUMERIC (15, 6) NULL,
    [CARD_ID]             VARCHAR (2)     NULL,
    [NUMBER_CARD]         VARCHAR (15)    NULL,
    [AMOUNT_CARD_US]      NUMERIC (15, 6) NULL,
    [AMOUNT_CARD]         NUMERIC (15, 6) NULL,
    [BANK_CHECK]          VARCHAR (3)     NULL,
    [NUMBER_CHECK]        VARCHAR (15)    NULL,
    [AMOUNT_CH_US]        NUMERIC (15, 6) NULL,
    [AMOUNT_CH]           NUMERIC (15, 6) NULL,
    [VOUCHER_ID]          VARCHAR (4)     NULL,
    [NUMBER_TRA]          VARCHAR (6)     NULL,
    [AMOUNT_TAX]          NUMERIC (15, 6) NULL,
    [DISCOUNTV]           NUMERIC (15, 6) NULL,
    [DISCOUNTP]           NUMERIC (15, 6) NULL,
    [LIST_GUIA]           VARCHAR (64)    NULL,
    [IS_PRINT]            BIT             NULL,
    [DISCOUNT_RECIVABLE]  NUMERIC (15, 6) NULL,
    [IS_CLOSED]           BIT             NULL,
    [SUB_ID]              VARCHAR (2)     NULL,
    [TOTAL_ERROR]         NUMERIC (15, 6) NULL,
    [PROMISE_DAYS]        INT             NULL,
    [SHIPPER_TYPE]        VARCHAR (2)     NULL,
    [ZONE_FREIGTH]        VARCHAR (2)     NULL,
    [AMOUNT_FREIGTH]      NUMERIC (15, 6) NULL,
    [IS_GUIA]             BIT             NULL,
    [IS_CASH_BANK]        BIT             NULL,
    [TAX_TYPE]            INT             NULL,
    [REC_AUTO]            CHAR (1)        NULL,
    [TRAMA_ID]            VARCHAR (50)    NULL,
    [VEHICULO_ID]         VARCHAR (100)   NULL,
    [EMPTRA_ID]           VARCHAR (100)   NULL,
    [ISC]                 FLOAT (53)      NULL
);

