CREATE TABLE [dbo].[DET_PED_PND] (
    [NUM_PED] VARCHAR (10)  NULL,
    [MOTIVO1] VARCHAR (100) NULL,
    [MOTIVO2] VARCHAR (100) NULL,
    [MOTIVO3] VARCHAR (100) NULL,
    [MOTIVO4] VARCHAR (100) NULL,
    [MOTIVO5] VARCHAR (100) NULL,
    [MOTIVO6] VARCHAR (100) NULL,
    [MOTIVO7] VARCHAR (100) NULL
);

