CREATE TABLE [dbo].[DOCUMENT_TYPE_PERSON] (
    [DOCUMENT_TYPE_ID] NCHAR (2)     NULL,
    [DESCRIPTION]      VARCHAR (100) NULL,
    [CREATE_DATE]      DATETIME      NULL,
    [USER_ID]          VARCHAR (100) NULL,
    [LAST_MODIFY_DATE] DATETIME      NULL,
    [USER_MODIFIED]    VARCHAR (100) NULL,
    [COMPUTER_ID]      VARCHAR (100) NULL
);

