CREATE TABLE [dbo].[DOCUMENT_TYPE] (
    [TYPE_ID]       VARCHAR (3)  NOT NULL,
    [NAME]          VARCHAR (50) NULL,
    [ACCOUNT_ID]    VARCHAR (2)  NULL,
    [SUNAT_ID]      VARCHAR (2)  NULL,
    [IS_SERIE]      BIT          CONSTRAINT [DF_DOCUMENT_TYPE_IS_SERIE] DEFAULT (0) NOT NULL,
    [IS_MINUS]      BIT          CONSTRAINT [DF_DOCUMENT_TYPE_IS_MINUS] DEFAULT (0) NOT NULL,
    [IS_SYSTEM_DOC] BIT          CONSTRAINT [DF_DOCUMENT_TYPE_IS_SYSTEM_DOC] DEFAULT (0) NOT NULL
);

