CREATE TABLE [dbo].[ESTADO_PRODUCTO] (
    [CODIGO_PRO]    VARCHAR (20)    NOT NULL,
    [DESCRIPCION]   VARCHAR (64)    NULL,
    [ESTADO]        BIT             NULL,
    [PROYVENTAS]    NUMERIC (15, 6) NULL,
    [TIEMPOENTREGA] NUMERIC (15, 6) NULL,
    [CANTTRANSITO]  NUMERIC (15, 6) NULL,
    [GLOSATRANSITO] VARCHAR (80)    NULL,
    [LIDER]         VARCHAR (50)    NULL
);

