CREATE TABLE [dbo].[FORMAT_REPORT] (
    [COMPANY_ID]    VARCHAR (50) NULL,
    [FORMAT_ID]     VARCHAR (10) NOT NULL,
    [DOCUMENT_TYPE] VARCHAR (2)  NOT NULL,
    [REPORT_NAME]   VARCHAR (20) NULL,
    [NAME]          VARCHAR (50) NULL
);

