CREATE TABLE [dbo].[GUARANTOR] (
    [CUSTOMER_ID]     VARCHAR (20) NOT NULL,
    [CUSTOMER_NAME]   VARCHAR (70) NULL,
    [NAME_GUARANTOR]  VARCHAR (50) NULL,
    [REP_GUARANTOR]   VARCHAR (50) NULL,
    [ADDR_GUARANTOR]  VARCHAR (70) NULL,
    [PHONE_GUARANTOR] VARCHAR (8)  NULL,
    [DOC_GUARANTOR]   VARCHAR (11) NULL
);

