CREATE TABLE [dbo].[HISTORY_RECEIVABLE] (
    [INVOICE_ID] VARCHAR (20)    NULL,
    [STATUS]     VARCHAR (4)     NULL,
    [AMOUNT]     NUMERIC (15, 6) NULL,
    [DATE]       SMALLDATETIME   NULL
);

