CREATE TABLE [dbo].[HOJA_COSTOS] (
    [HCNUMIMPOR]   VARCHAR (13)    NULL,
    [HCNUMLIQUI]   VARCHAR (20)    NULL,
    [HCTIPO]       VARCHAR (1)     NULL,
    [HCITEM]       VARCHAR (3)     NULL,
    [HCCODARTIC]   VARCHAR (18)    NULL,
    [HCDESARTIC]   VARCHAR (60)    NULL,
    [HCCANTIDAD]   NUMERIC (23, 2) NULL,
    [HCVALORFOB]   NUMERIC (23, 2) NULL,
    [HCFLETE]      NUMERIC (23, 2) NULL,
    [HCCSEGURO]    NUMERIC (23, 2) NULL,
    [HCTOTALCFR]   NUMERIC (23, 2) NULL,
    [HCGASTOSVPE]  NUMERIC (23, 2) NULL,
    [HCADVAL]      NUMERIC (23, 2) NULL,
    [HCGASAGEN]    NUMERIC (23, 2) NULL,
    [HCAGADUANA]   NUMERIC (23, 2) NULL,
    [HFLETECON]    NUMERIC (23, 2) NULL,
    [HCSEGURO]     NUMERIC (23, 2) NULL,
    [HCGASBAN]     NUMERIC (23, 2) NULL,
    [HCTRANSPORTE] NUMERIC (23, 2) NULL,
    [HCCOSTOTOT]   NUMERIC (23, 2) NULL,
    [HCCOSTOUNI]   NUMERIC (23, 6) NULL
);

