CREATE TABLE [dbo].[IMPORT_ORDER] (
    [ID]                 VARCHAR (13)    NOT NULL,
    [VENDOR_ID]          VARCHAR (11)    NULL,
    [DOCUMENT_DATE]      SMALLDATETIME   NULL,
    [PROMISE_DATE]       SMALLDATETIME   NULL,
    [AMOUNT]             FLOAT (53)      NULL,
    [CURRENCY_ID_IMP]    VARCHAR (4)     NULL,
    [EQUIVALENCE_US]     FLOAT (53)      NULL,
    [CURRENCY_EXCHANGE]  FLOAT (53)      NULL,
    [SOLIINSP]           VARCHAR (16)    NULL,
    [GUIATRAN]           VARCHAR (16)    NULL,
    [AMOUNT_LIQ]         FLOAT (53)      NULL,
    [LLIQREAL]           BIT             NULL,
    [AMOUNT_BALANCE]     FLOAT (53)      NULL,
    [AMOUNT_BALANCE_LIQ] FLOAT (53)      NULL,
    [COMMENT]            VARCHAR (100)   NULL,
    [LREAL]              BIT             NULL,
    [TYPE_ORDER]         VARCHAR (2)     NULL,
    [NUMBER_LIQ]         VARCHAR (20)    NULL,
    [NADVALOR]           FLOAT (53)      NULL,
    [ITINERANT]          VARCHAR (13)    NULL,
    [CPACKING]           VARCHAR (13)    NULL,
    [CURR_EXCHANGE_TYPE] VARCHAR (3)     NULL,
    [TIPPREIMP]          VARCHAR (3)     NULL,
    [STATUS_ID]          VARCHAR (2)     NULL,
    [AMOUNT_FLETE]       NUMERIC (20, 2) NULL,
    [NUMBER_IMPORT_INT]  VARCHAR (13)    NULL,
    [SECURE]             NUMERIC (20, 2) NULL,
    [USER_ID]            VARCHAR (8)     NULL,
    [CREATE_DATE]        SMALLDATETIME   NULL,
    [UPDATE_DATE]        SMALLDATETIME   NULL
);

