CREATE TABLE [dbo].[INVOICE] (
    [INVOICE_ID]     VARCHAR (20) NULL,
    [BANK_ID]        VARCHAR (3)  NULL,
    [COMMENT]        VARCHAR (30) NULL,
    [STATUS]         VARCHAR (4)  NULL,
    [LAST_STATUS]    VARCHAR (4)  NULL,
    [NUMBER_ACCOUNT] VARCHAR (20) NULL,
    [BANK_NUMBER]    VARCHAR (20) NULL
);

