CREATE TABLE [dbo].[KARDEX_DIARIO] (
    [CODIGO]        VARCHAR (20)    NULL,
    [ALMACEN]       VARCHAR (4)     NULL,
    [FECHA]         VARCHAR (10)    NULL,
    [SALDO_INICIAL] NUMERIC (15, 6) NULL,
    [CANT_INGRESO]  NUMERIC (15, 6) NULL,
    [CANT_SALIDA]   NUMERIC (15, 6) NULL,
    [SALDO_FINAL]   NUMERIC (15, 6) NULL
);

