CREATE TABLE [dbo].[LETTER] (
    [LETTER_ID]        VARCHAR (10) NULL,
    [BANK_ID]          VARCHAR (3)  NULL,
    [COMMENT]          VARCHAR (30) NULL,
    [STATUS_ACT]       VARCHAR (4)  NULL,
    [STATUS_LAST]      VARCHAR (4)  NULL,
    [PLACE_SHIP]       VARCHAR (15) NULL,
    [GUARANTOR_NAME]   VARCHAR (40) NULL,
    [GUARANTOR_PHONE]  VARCHAR (25) NULL,
    [GUARANTOR_ADDR]   VARCHAR (50) NULL,
    [GUARANTOR_NAME2]  VARCHAR (40) NULL,
    [GUARANTOR_ADDR2]  VARCHAR (50) NULL,
    [GUARANTOR_PHONE2] VARCHAR (25) NULL,
    [LETTER_ORIG]      VARCHAR (10) NULL,
    [NUMBER_ACCOUNT]   VARCHAR (20) NULL,
    [NUMBER_BANK]      VARCHAR (21) NULL,
    [TYPE_DOC]         VARCHAR (2)  NULL
);

