CREATE TABLE [dbo].[LETTER_EXCHANGE_PAY] (
    [ID]            VARCHAR (6)     NULL,
    [DATE_EXCHANGE] SMALLDATETIME   NULL,
    [VOUCHER_ID]    VARCHAR (6)     NULL,
    [CREATE_DATE]   SMALLDATETIME   NULL,
    [USER_ID]       VARCHAR (8)     NULL,
    [STATUS]        VARCHAR (1)     NULL,
    [ACCEPT_DATE]   SMALLDATETIME   NULL,
    [SELL_RATE]     NUMERIC (15, 6) NULL,
    [CURRENCY_ID]   VARCHAR (2)     NULL,
    [CUSTOMER_ID]   VARCHAR (11)    NULL
);

