CREATE TABLE [dbo].[LIQUIDATE_IMPORT] (
    [ID]           VARCHAR (13) NOT NULL,
    [NUMBER_LIQ]   VARCHAR (20) NOT NULL,
    [WAREHOUSE_ID] VARCHAR (2)  NOT NULL,
    [NUMBER_PARTE] VARCHAR (10) NOT NULL,
    [LREAL]        BIT          CONSTRAINT [DF_LIQUIDATE_IMPORT_LREAL] DEFAULT (0) NOT NULL
);

