CREATE TABLE [dbo].[MAETRAN] (
    [TRACODIGO]  NVARCHAR (11) NULL,
    [TRANOMBRE]  NVARCHAR (40) NULL,
    [TRADIR]     NVARCHAR (50) NULL,
    [TRATELEF]   NVARCHAR (25) NULL,
    [TRARUC]     NVARCHAR (20) NULL,
    [TRAESTADO]  NVARCHAR (1)  NULL,
    [TRAFECCRE]  SMALLDATETIME NULL,
    [TRARAZEMP]  NVARCHAR (50) NULL,
    [TRARUCEMP]  NVARCHAR (11) NULL,
    [TRADIREMP]  NVARCHAR (50) NULL,
    [TRATELEMP]  NVARCHAR (25) NULL,
    [TRAPLACA]   NVARCHAR (10) NULL,
    [TRABREVE]   NVARCHAR (15) NULL,
    [MODELOVEH]  NVARCHAR (50) NULL,
    [NROINSCRIP] NVARCHAR (50) NULL
);

