CREATE TABLE [dbo].[MASTER_HELP] (
    [TYPE_ID]       VARCHAR (8)   NULL,
    [ID]            VARCHAR (8)   NULL,
    [DESCRIPTION]   VARCHAR (40)  NULL,
    [CADUCATE_DAYS] VARCHAR (3)   NULL,
    [NIVEL]         VARCHAR (2)   NULL,
    [CREATE_DATE]   SMALLDATETIME NULL,
    [HOUR]          VARCHAR (6)   NULL,
    [IS_MINUS]      BIT           CONSTRAINT [DF_MASTER_HELP_IS_MINUS] DEFAULT (0) NOT NULL,
    [IS_VALUE]      BIT           CONSTRAINT [DF_MASTER_HELP_IS_VALUE] DEFAULT (0) NOT NULL,
    [IS_FOB]        BIT           CONSTRAINT [DF_MASTER_HELP_IS_FOB] DEFAULT (0) NOT NULL
);

