CREATE TABLE [dbo].[MENU_INVENTORY] (
    [MENU_ID]            VARCHAR (20) NOT NULL,
    [MENU_DESCRIPTION]   VARCHAR (80) NULL,
    [INTERNAL_NAME_MENU] VARCHAR (48) NULL,
    [IS_VISIBLE]         BIT          NULL
);

