CREATE TABLE [dbo].[MENU_LEVEL4] (
    [MENU_ID_LEVEL1]   VARCHAR (2)   NOT NULL,
    [MENU_ID_LEVEL2]   VARCHAR (4)   NOT NULL,
    [MENU_ID_LEVEL3]   VARCHAR (6)   NOT NULL,
    [MENU_ID]          VARCHAR (8)   NOT NULL,
    [MENU_DESCRIPTION] VARCHAR (80)  NULL,
    [MENU_IMAGE]       VARCHAR (80)  NULL,
    [MENU_EXE_ID]      VARCHAR (100) NULL,
    [ORDER_COL]        VARCHAR (3)   NULL
);

