CREATE TABLE [dbo].[MENU_LEVEL2] (
    [MENU_ID_LEVEL1]   VARCHAR (2)   NOT NULL,
    [MENU_ID]          VARCHAR (4)   NOT NULL,
    [MENU_DESCRIPTION] VARCHAR (80)  NULL,
    [MENU_IMAGE]       VARCHAR (80)  NULL,
    [MENU_EXE_ID]      VARCHAR (100) NULL,
    [ORDER_COL]        VARCHAR (3)   NULL
);

