CREATE TABLE [dbo].[MENU] (
    [ID_MENU]            VARCHAR (10) NOT NULL,
    [DESCRIPTION_MENU]   VARCHAR (70) NULL,
    [INTERNAL_NAME_MENU] VARCHAR (50) NULL,
    [IS_VISIBLE]         BIT          NULL,
    [ID_EXE]             VARCHAR (10) NULL
);

