CREATE TABLE [dbo].[NUMBER_DOCUMENT_PURCHASE] (
    [ID]          VARCHAR (2)  NOT NULL,
    [DESCRIPTION] VARCHAR (70) NULL,
    [NUMBER_INI]  FLOAT (53)   NULL,
    [NUMBER_FIN]  FLOAT (53)   NULL,
    [NUMBER]      FLOAT (53)   NULL,
    [USER_ID]     VARCHAR (5)  NULL,
    [NAME_FORMAT] VARCHAR (20) NULL
);

