CREATE TABLE [dbo].[PARAMETERS] (
    [COMPANY_ID]        VARCHAR (50)   NULL,
    [CURRENCY_ID]       VARCHAR (2)    NULL,
    [IS_PRICE_TAX]      BIT            CONSTRAINT [DF_PARAMETERS_IS_PRICE_TAX] DEFAULT (0) NULL,
    [IS_SALES_DOC]      BIT            CONSTRAINT [DF_PARAMETERS_IS_SALES_DOC] DEFAULT (0) NOT NULL,
    [IS_BOUNCER]        BIT            CONSTRAINT [DF_PARAMETERS_IS_BOUNCER] DEFAULT (0) NOT NULL,
    [IS_BILL_PROTESTED] BIT            CONSTRAINT [DF_PARAMETERS_IS_BILL_PROTESTED] DEFAULT (0) NOT NULL,
    [IS_BILL_CADUCATE]  BIT            CONSTRAINT [DF_PARAMETERS_IS_BILL_CADUCATE] DEFAULT (0) NOT NULL,
    [IS_CREDIT_LIMIT]   BIT            CONSTRAINT [DF_PARAMETERS_IS_CREDIT_LIMIT] DEFAULT (0) NOT NULL,
    [AMOUNT_TAX]        NUMERIC (5, 2) NULL,
    [TYPE_ENTER]        VARCHAR (1)    CONSTRAINT [DF_PARAMETERS_TYPE_ENTER] DEFAULT (0) NULL,
    [SELL_ENTRY]        VARCHAR (2)    NULL,
    [ACCOUNT_ANNEXED]   VARCHAR (2)    NULL,
    [AUTOMATIC_NUMBER]  BIT            CONSTRAINT [DF_PARAMETERS_AUTOMATIC_NUMBER] DEFAULT (0) NOT NULL,
    [PRINT_QUESTION]    BIT            CONSTRAINT [DF_PARAMETERS_PRINT_QUESTION] DEFAULT (0) NOT NULL,
    [DESCRIPTION]       BIT            CONSTRAINT [DF_PARAMETERS_DESCRIPTION] DEFAULT (0) NULL,
    [SCREEN]            BIT            CONSTRAINT [DF_PARAMETERS_SCREEN] DEFAULT (0) NULL,
    [IS_INCLUDE_TAX]    BIT            CONSTRAINT [DF_PARAMETERS_IS_INCLUDE_TAX] DEFAULT (0) NULL,
    [PRICE_INCLUDE_TAX] BIT            CONSTRAINT [DF_PARAMETERS_PRICE_INCLUDE_TAX] DEFAULT (0) NULL,
    [IS_NOT_GUIA]       BIT            CONSTRAINT [DF_PARAMETERS_IS_NOT_GUIA] DEFAULT (0) NULL,
    [IS_CASH]           BIT            CONSTRAINT [DF_PARAMETERS_IS_CASH] DEFAULT (0) NULL
);

