CREATE TABLE [dbo].[PARAMETROS_CTAS] (
    [TYPE_DOC]  VARCHAR (2)  NOT NULL,
    [ACOUNT]    VARCHAR (18) NULL,
    [ACOUNT_US] VARCHAR (18) NULL,
    [ACOUNT_1]  VARCHAR (18) NULL,
    [ACOUNT_2]  VARCHAR (18) NULL,
    [CCOST]     VARCHAR (18) NULL
);

