CREATE TABLE [dbo].[PART] (
    [ID]                  VARCHAR (20)    NOT NULL,
    [ID_FAB]              VARCHAR (40)    NULL,
    [DESCRIPTION]         VARCHAR (64)    NULL,
    [DESCRIPTION_OPT]     VARCHAR (64)    NULL,
    [FAMILY]              VARCHAR (8)     NULL,
    [MODEL]               VARCHAR (8)     NULL,
    [UNIT_OF_MEASUREMENT] VARCHAR (6)     NULL,
    [GROUP_ID]            VARCHAR (11)    NULL,
    [ACCOUNT]             VARCHAR (18)    NULL,
    [SERIES]              VARCHAR (1)     NULL,
    [UNIT_PRICE]          NUMERIC (15, 6) DEFAULT (0) NULL,
    [DISCOUNT]            NUMERIC (15, 6) DEFAULT (0) NULL,
    [PRICE_BUY]           NUMERIC (15, 6) DEFAULT (0) NULL,
    [VENDOR_ID_PART]      VARCHAR (50)    NULL,
    [CREATE_DATE]         SMALLDATETIME   NULL,
    [LOCATION]            VARCHAR (12)    NULL,
    [IS_STOCKED]          VARCHAR (1)     NULL,
    [CREATE_USER]         VARCHAR (8)     NULL,
    [STATUS]              VARCHAR (1)     NULL,
    [DATE_CADUCATE]       SMALLDATETIME   NULL,
    [CURRENCY_ID]         VARCHAR (2)     NULL,
    [TYPE_PART]           VARCHAR (2)     NULL,
    [COMMENT]             VARCHAR (2000)  NULL,
    [IS_LOT]              VARCHAR (1)     NULL,
    [WEIGHT]              NUMERIC (15, 6) DEFAULT (0) NULL,
    [CST_POR]             NUMERIC (15, 6) DEFAULT (0) NULL,
    [VAT_POR]             NUMERIC (15, 6) DEFAULT (0) NULL,
    [HOUR_UPDATE]         SMALLDATETIME   NULL,
    [IS_FREE_PRICE]       VARCHAR (1)     NULL,
    [IS_PRICE_VAT]        VARCHAR (1)     NULL,
    [COMMISSION_SALES]    NUMERIC (15, 6) DEFAULT (0) NULL,
    [IS_VAT]              BIT             DEFAULT (0) NOT NULL,
    [COLOR]               VARCHAR (20)    NULL,
    [MARK]                VARCHAR (20)    NULL,
    [PICTURE]             VARCHAR (255)   NULL,
    [HEIGHT]              VARCHAR (10)    NULL,
    [REFERENCE]           VARCHAR (6)     NULL,
    [ID_AUTONUMERIC]      INT             DEFAULT (0) NULL,
    [LAST_DATE_BUY]       SMALLDATETIME   NULL,
    [LAST_VENDOR]         VARCHAR (50)    NULL,
    [LAST_COUNTRY_VENDOR] VARCHAR (15)    NULL,
    [CUSTOMS_TARIFF_ID]   VARCHAR (14)    NULL,
    [PRICE_FOB]           FLOAT (53)      NULL,
    [PRICE_CIF]           FLOAT (53)      NULL,
    [CURRENCY_FOB]        VARCHAR (2)     NULL,
    [CURRENCY_CIF]        VARCHAR (2)     NULL,
    [MODEL1]              VARCHAR (50)    NULL,
    [ORIGEN]              CHAR (1)        NULL,
    [ACCOUNT_INTERNAL_ID] VARCHAR (50)    NULL,
    [ACCOUNT_INV]         VARCHAR (50)    NULL,
    [ACCOUNT_PAY]         VARCHAR (50)    NULL,
    [ISCPOR]              NUMERIC (15, 6) NULL,
    [TIPOISC]             INT             NULL,
    [ISC_UNDCONV]         VARCHAR (6)     NULL,
    [ISC_EQUICONV]        FLOAT (53)      NULL,
    [ISC_IMPCONV]         FLOAT (53)      NULL,
    [ISC_IMPORTE]         FLOAT (53)      NULL
);

