CREATE TABLE [dbo].[PURCHASE_QUOTE] (
    [ID]            VARCHAR (10)    NOT NULL,
    [DOCUMENT_DATE] SMALLDATETIME   NULL,
    [VENDOR_ID]     VARCHAR (11)    NULL,
    [CURRENCY_ID]   VARCHAR (2)     NULL,
    [COMMENT]       VARCHAR (250)   NULL,
    [COMMENT_COT]   VARCHAR (250)   NULL,
    [QUOTE_DATE]    SMALLDATETIME   NULL,
    [SCTIPCAM]      NUMERIC (15, 6) NULL,
    [SCVALIDEZ]     VARCHAR (80)    NULL,
    [SCTIEMENT]     VARCHAR (80)    NULL,
    [SCFORPAG]      VARCHAR (80)    NULL,
    [SCNCOTIZ]      VARCHAR (12)    NULL,
    [CREATE_DATE]   SMALLDATETIME   NULL,
    [UPDATE_DATE]   SMALLDATETIME   NULL,
    [USER_ID]       VARCHAR (8)     NULL,
    [PROJECT_ID]    VARCHAR (20)    NULL
);

