CREATE TABLE [dbo].[PURCHASE_FACT_SUPPLIER_L] (
    [ID]               VARCHAR (13)    NOT NULL,
    [TYPE]             VARCHAR (2)     NOT NULL,
    [ITEM]             BIGINT          NOT NULL,
    [PART_ID]          VARCHAR (20)    NULL,
    [PART_DESCRIPTION] VARCHAR (60)    NULL,
    [UNIT]             VARCHAR (6)     NULL,
    [UNIT_REFERENCE]   VARCHAR (6)     NULL,
    [FACTOR_REFERENCE] NUMERIC (15, 6) NULL,
    [QTY]              NUMERIC (15, 6) NULL,
    [PRICE]            NUMERIC (15, 6) NULL,
    [DISCOUNT_PER]     NUMERIC (15, 6) NULL,
    [DISCOUNT]         NUMERIC (15, 6) NULL,
    [AMOUNT_TAX]       NUMERIC (15, 6) NULL,
    [PERCENT_TAX]      NUMERIC (15, 6) NULL,
    [PRICE_NET]        NUMERIC (15, 6) NULL,
    [AMOUNT_TOTAL]     NUMERIC (15, 6) NULL,
    [AMOUNT_TOTAL_NET] NUMERIC (15, 6) NULL,
    [QTY_ENTER]        NUMERIC (15, 6) NULL,
    [QTY_OUT]          NUMERIC (15, 6) NULL,
    [STATUS_ID]        VARCHAR (2)     NULL,
    [COMMENT1]         VARCHAR (60)    NULL,
    [TEXT_COMMENT]     TEXT            NULL,
    [IS_VAT]           BIT             NULL,
    [PRICE_UNIT]       NUMERIC (15, 6) NULL,
    [CCOST_ID]         VARCHAR (18)    NULL,
    [OPT_AFECTO]       VARCHAR (1)     NULL
);

