CREATE TABLE [dbo].[PURCHASE_CAB] (
    [ID]                    INT             IDENTITY (1, 1) NOT NULL,
    [DOCUMENT_ID]           VARCHAR (2)     NULL,
    [NUMBER_SERIE]          VARCHAR (3)     NULL,
    [NUMBER_DOCUMENT]       VARCHAR (7)     NULL,
    [DOCUMENT_DATE]         SMALLDATETIME   NULL,
    [CADUCATE_DATE]         SMALLDATETIME   NULL,
    [DR_CR]                 VARCHAR (1)     NULL,
    [NUMBER_QUOTE]          VARCHAR (10)    NULL,
    [NUMBER_ORDER_PUR]      VARCHAR (20)    NULL,
    [VENDOR_ID]             VARCHAR (11)    NULL,
    [VAT_REGISTRATION]      VARCHAR (11)    NULL,
    [WAREHOUSE_ID]          VARCHAR (2)     NULL,
    [AMOUNT]                NUMERIC (15, 6) NULL,
    [BALANCE]               NUMERIC (15, 6) NULL,
    [CURRENCY_EXCHANGE]     NUMERIC (15, 6) NULL,
    [CURRENCY_ID]           VARCHAR (2)     NULL,
    [DOCUMENT_ID_REFER]     VARCHAR (2)     NULL,
    [NUMBER_SERIE_REFER]    VARCHAR (3)     NULL,
    [NUMBER_DOCUMENT_REFER] VARCHAR (7)     NULL,
    [CREATE_DATE]           SMALLDATETIME   NULL,
    [UPDATE_DATE]           SMALLDATETIME   NULL,
    [STATUS]                VARCHAR (1)     NULL,
    [USER_ID]               VARCHAR (8)     NULL,
    [COMMENT]               VARCHAR (80)    NULL,
    [AMOUNT_TAX]            NUMERIC (12, 5) NULL,
    [EXCHANGE_TYPE]         VARCHAR (3)     NULL,
    [BUYER_ID]              VARCHAR (50)    NULL,
    [DESTINY_ID]            VARCHAR (50)    NULL,
    [ANEX_REFER]            VARCHAR (50)    NULL,
    [PURCHASE_TYPE]         VARCHAR (2)     NULL,
    [SERVICE]               VARCHAR (1)     NULL,
    [PERCENT_TAX]           NUMERIC (12, 5) NULL,
    [IS_VAT]                BIT             NOT NULL
);

