CREATE TABLE [dbo].[PURCHASE_VOUCHER] (
    [COMPANY_ID]          VARCHAR (3)     NULL,
    [ID]                  VARCHAR (5)     NULL,
    [CUSTOMER_ID]         VARCHAR (11)    NULL,
    [CUSTOMER_NAME]       VARCHAR (50)    NULL,
    [TYPE_DOC]            VARCHAR (2)     NULL,
    [SERIE]               VARCHAR (4)     NULL,
    [NUMBER_DOC]          VARCHAR (17)    NULL,
    [DATE]                SMALLDATETIME   NULL,
    [CADUCATE_DATE]       SMALLDATETIME   NULL,
    [ENTER_DATE]          SMALLDATETIME   NULL,
    [CURRENCY_EXCHANGE]   VARCHAR (2)     NULL,
    [AMOUNT]              NUMERIC (15, 6) NULL,
    [BUY_RATE]            NUMERIC (15, 6) NULL,
    [PURCHASE_ORDER]      VARCHAR (13)    NULL,
    [DESCRIPTION]         VARCHAR (40)    NULL,
    [BUYER_ID]            VARCHAR (2)     NULL,
    [STATUS]              VARCHAR (1)     NULL,
    [AMOUNT_BALANCE]      NUMERIC (15, 6) NULL,
    [AMOUNT_PROGRAMMED]   NUMERIC (15, 6) NULL,
    [IS_EXCHANGE]         BIT             NOT NULL,
    [ACCOUNT]             VARCHAR (12)    NULL,
    [TERMS]               VARCHAR (40)    NULL,
    [SERIE_REF]           VARCHAR (4)     NULL,
    [NUMBER_REF]          VARCHAR (17)    NULL,
    [TYPE_DOC_REF]        VARCHAR (2)     NULL,
    [SUB_ID]              VARCHAR (2)     NULL,
    [EXCHANGE_TYPE]       VARCHAR (3)     NULL,
    [CREATE_DATE]         SMALLDATETIME   NULL,
    [VENDOR_TYPE]         VARCHAR (2)     NULL,
    [ACCOUNT_DEST]        VARCHAR (12)    NULL,
    [CCOST]               VARCHAR (6)     NULL,
    [VAT_REGISTRATION]    VARCHAR (11)    NULL,
    [IS_ENTERED]          BIT             NOT NULL,
    [TYPE]                VARCHAR (2)     NULL,
    [PURCHASE_STATUS]     BIT             NOT NULL,
    [PURCHASE_DEST]       VARCHAR (3)     NULL,
    [VOUCHER_ID]          VARCHAR (6)     NULL,
    [BALANCE_INITIAL]     BIT             NOT NULL,
    [CASH_ID]             VARCHAR (3)     NULL,
    [TERM_DAYS]           NUMERIC (15, 6) NULL,
    [IS_VAT]              VARCHAR (1)     NULL,
    [YEAR_MONTH]          VARCHAR (6)     NULL,
    [CONCEPT]             VARCHAR (5)     NULL,
    [REFERENCE_DATE]      SMALLDATETIME   NULL,
    [AMOUNT_TAX]          NUMERIC (15, 6) NULL,
    [PERCENT_TAX]         NUMERIC (15, 6) NULL,
    [EXCHANGE_SP]         NUMERIC (15, 6) NULL,
    [CAN_DATE]            SMALLDATETIME   NULL,
    [IS_VALIDATE]         BIT             NOT NULL,
    [NUMBER_PERCENT]      NUMERIC (15, 6) NULL,
    [REGISTER_VOUCHER_ID] BIT             NOT NULL,
    [HONORIFIC]           BIT             NOT NULL,
    [RENT4]               NUMERIC (15, 6) NULL,
    [SOLIDARITY_TAX]      NUMERIC (15, 6) NULL,
    [AMOUNT_HONOR]        NUMERIC (15, 6) NULL,
    [BANK_ID]             VARCHAR (2)     NULL,
    [BANK_AGENCY]         VARCHAR (20)    NULL,
    [BANK_LETTER]         VARCHAR (20)    NULL,
    [AMOUNT_CIF]          NUMERIC (15, 6) NULL,
    [TAXABLE_BASE]        NUMERIC (15, 6) NULL,
    [CONT_DATE]           SMALLDATETIME   NULL
);

