CREATE TABLE [dbo].[PURCHASE_FACT_SUPPLIER] (
    [ID]                    VARCHAR (13)    NOT NULL,
    [TYPE]                  VARCHAR (2)     NOT NULL,
    [DOCUMENT_DATE]         SMALLDATETIME   NULL,
    [VENDOR_ID]             VARCHAR (11)    NULL,
    [NUMBER_ESTIMATING]     VARCHAR (15)    NULL,
    [CURRENCY_TYPE]         VARCHAR (2)     NULL,
    [TERMS_NAME]            VARCHAR (40)    NULL,
    [SELL_RATE]             NUMERIC (12, 5) NULL,
    [PROMISE_DATE]          SMALLDATETIME   NULL,
    [COMMENT]               VARCHAR (80)    NULL,
    [AUTORIZED_ID]          VARCHAR (3)     NULL,
    [BUYER_PURCHASE_ID]     VARCHAR (2)     NULL,
    [TIME_DLV]              VARCHAR (80)    NULL,
    [ADDR_DLV]              VARCHAR (60)    NULL,
    [STATUS_ID]             VARCHAR (2)     NULL,
    [AMOUNT]                NUMERIC (15, 6) NULL,
    [DISCOUNT]              NUMERIC (15, 6) NULL,
    [AMOUNT_TAX]            NUMERIC (15, 6) NULL,
    [AMOUNT_SALES]          NUMERIC (15, 6) NULL,
    [UPDATE_DATE]           SMALLDATETIME   NULL,
    [UPDATE_HOUR]           VARCHAR (8)     NULL,
    [USER_ID]               VARCHAR (8)     NULL,
    [CURR_EXCHANGE_TYPE]    VARCHAR (3)     NULL,
    [NAME_FACT]             VARCHAR (70)    NULL,
    [VAT_REGISTRATION_FACT] VARCHAR (11)    NULL,
    [ADDR_FACT]             VARCHAR (50)    NULL,
    [REFER_DOCUMENT_TYPE]   VARCHAR (2)     NULL,
    [REFER_DOCUMENT_NUMBER] VARCHAR (13)    NULL,
    [SERIE]                 VARCHAR (10)    NULL,
    [EXPIRATION_DATE]       SMALLDATETIME   NULL,
    [BUDGET_ID]             VARCHAR (50)    NULL,
    [ORDER_BUY_ID]          VARCHAR (50)    NULL,
    [NOTE_IN_ID]            VARCHAR (50)    NULL,
    [WAREHOUSE_ID]          VARCHAR (50)    NULL,
    [AMOUNT_INAFEC]         NUMERIC (15, 6) NULL,
    [ISC]                   NUMERIC (15, 6) NULL
);

