CREATE TABLE [dbo].[RECEIVABLE_LIST_LINE_PAY] (
    [ID]                 VARCHAR (6)      NULL,
    [ITEM]               VARCHAR (3)      NULL,
    [TYPE_DOC]           VARCHAR (2)      NULL,
    [NUMBER_DOC]         VARCHAR (20)     NULL,
    [TYPE_OPERATION]     VARCHAR (1)      NULL,
    [REC_ID]             VARCHAR (2)      NULL,
    [DATE]               SMALLDATETIME    NULL,
    [AMOUNT]             NUMERIC (15, 6)  NULL,
    [CURRENCY_ID]        VARCHAR (2)      NULL,
    [SELL_RATE]          NUMERIC (15, 10) NULL,
    [CREATE_DATE]        SMALLDATETIME    NULL,
    [USER_ID]            VARCHAR (8)      NULL,
    [COMMENT]            VARCHAR (30)     NULL,
    [SALES_ID]           VARCHAR (2)      NULL,
    [BANK_ID]            VARCHAR (3)      NULL,
    [BANK_DESCRIPTION]   VARCHAR (100)    NULL,
    [DOC_REF]            VARCHAR (2)      NULL,
    [NUM_REF]            VARCHAR (21)     NULL,
    [LIST_ID]            INT              IDENTITY (1, 1) NOT NULL,
    [IS_CASH_BANK]       BIT              CONSTRAINT [DF_receivable_list_line_pay_IS_CASH_BANK] DEFAULT (0) NULL,
    [AMOUNT_PER]         NUMERIC (15, 6)  NULL,
    [BANK_BUSSINESS_ID]  VARCHAR (30)     NULL,
    [ACCOUNT_BANK_CHECK] VARCHAR (20)     NULL,
    [PAY_AUTO]           CHAR (1)         NULL,
    [ANNEX_ID_AUX]       VARCHAR (50)     NULL,
    [DOCUMET_ID]         VARCHAR (2)      NULL,
    [NUMBER_SERIE]       VARCHAR (5)      NULL,
    [NUMBER_DOCUMENT]    VARCHAR (20)     NULL,
    [MEDIOS_PAGO]        VARCHAR (20)     NULL
);

