CREATE TABLE [dbo].[REPORT_LANGUAGE] (
    [LANGUAGE_ID] VARCHAR (100) NOT NULL,
    [REPORT]      VARCHAR (100) NULL,
    [MODULO]      VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_REPORT_LANGUAGE] PRIMARY KEY CLUSTERED ([LANGUAGE_ID] ASC, [MODULO] ASC)
);

