CREATE TABLE [dbo].[REQUIREMENT] (
    [ID]            VARCHAR (10)  NOT NULL,
    [TYPE]          VARCHAR (2)   NOT NULL,
    [REQUIRED_USER] VARCHAR (3)   NULL,
    [REQUIRED_DATE] SMALLDATETIME NULL,
    [COMMENT]       VARCHAR (250) NULL,
    [AREA_ID]       VARCHAR (6)   NULL,
    [STATUS]        VARCHAR (1)   NULL,
    [CREATE_DATE]   SMALLDATETIME NULL,
    [UPDATE_DATE]   SMALLDATETIME NULL,
    [USER_ID]       VARCHAR (8)   NULL,
    [PROJECT_ID]    VARCHAR (20)  NULL
);

