CREATE TABLE [dbo].[RPTANALISFAM] (
    [FAMILIA]      VARCHAR (8) NULL,
    [TIPMOV]       VARCHAR (1) NULL,
    [COD_MOV]      VARCHAR (2) NULL,
    [INGRESOSMN]   FLOAT (53)  NULL,
    [SALIDASMN]    FLOAT (53)  NULL,
    [INGRESOSME]   FLOAT (53)  NULL,
    [SALIDASME]    FLOAT (53)  NULL,
    [INGRESOSCANT] FLOAT (53)  NULL,
    [SALIDASCANT]  FLOAT (53)  NULL
);

