CREATE TABLE [dbo].[SALES_CCOST_LINE] (
    [SUBD_ID]         NVARCHAR (2)    NULL,
    [VOUCHER_ID]      NVARCHAR (4)    NULL,
    [ITEM]            VARCHAR (5)     NULL,
    [DATE]            SMALLDATETIME   NULL,
    [ACCOUNT]         NVARCHAR (18)   NULL,
    [TYPE_ANEX]       NVARCHAR (13)   NULL,
    [NUMBER_DOCUMENT] NVARCHAR (23)   NULL,
    [DATE_DOCUMENT]   SMALLDATETIME   NULL,
    [CCOST_MOV]       NVARCHAR (6)    NULL,
    [AMOUNT_DR]       NUMERIC (20, 2) NULL,
    [AMOUNT_CR]       NUMERIC (20, 2) NULL,
    [AMOUNT_DR_US]    NUMERIC (20, 2) NULL,
    [AMOUNT_CR_US]    NUMERIC (20, 2) NULL,
    [COMMENT]         NVARCHAR (60)   NULL,
    [IS_CHECK]        BIT             NOT NULL,
    [IS_AUTO]         BIT             NOT NULL,
    [IS_CCOST]        BIT             NOT NULL,
    [IS_BUY]          BIT             NOT NULL,
    [IS_SALES]        BIT             NOT NULL,
    [IS_TRANS]        BIT             NOT NULL,
    [IS_DEST]         BIT             NOT NULL,
    [ACCOUNT_DEST]    NVARCHAR (18)   NULL,
    [CADUCATE_DATE]   SMALLDATETIME   NULL,
    [IS_PROV]         BIT             NOT NULL,
    [WAREHOUSE_ID]    VARCHAR (10)    NULL,
    [CURRENCY_MOV]    VARCHAR (2)     NULL
);

