CREATE TABLE [dbo].[SALINIXFAM] (
    [AFAMILIA]  VARCHAR (8)      NULL,
    [CATIPMOV]  VARCHAR (1)      NULL,
    [CACODMOV]  VARCHAR (2)      NULL,
    [SALDOCANT] NUMERIC (38, 6)  NULL,
    [SALDOMN]   NUMERIC (38, 12) NULL,
    [SALDOME]   NUMERIC (38, 12) NULL
);

