CREATE TABLE [dbo].[STATUS_LETTER] (
    [STATUS_ID]   VARCHAR (4)  NOT NULL,
    [CURRENCY_ID] VARCHAR (2)  NOT NULL,
    [DESCRIPTION] VARCHAR (50) NULL,
    [ACCOUNT]     VARCHAR (18) NULL,
    [EVENT]       VARCHAR (4)  NULL
);

