CREATE TABLE [dbo].[STATUS_INVOICE] (
    [STATUS]      VARCHAR (4)  NULL,
    [CURRENT_ID]  VARCHAR (2)  NULL,
    [DESCRIPTION] VARCHAR (50) NULL,
    [ACCOUNT]     VARCHAR (18) NULL,
    [EVENT]       VARCHAR (4)  NULL
);

