CREATE TABLE [dbo].[STOCK_SERIE] (
    [WAREHOUSE_ID]   VARCHAR (2)   NOT NULL,
    [PART_ID]        VARCHAR (20)  NOT NULL,
    [SERIE]          VARCHAR (20)  NOT NULL,
    [EFFECTIVE_DATE] SMALLDATETIME NULL,
    [CADUCATE_DATE]  SMALLDATETIME NULL,
    [QTY_ON_HAND]    FLOAT (53)    NULL,
    [QTY_RESERVE]    FLOAT (53)    NULL
);

