CREATE TABLE [dbo].[TABLA_FINAL_RENTABILIDAD] (
    [FAMILY]          VARCHAR (8)      NULL,
    [MODEL]           VARCHAR (8)      NULL,
    [DESCRIPTION_OPT] VARCHAR (64)     NULL,
    [VAL1]            NUMERIC (38, 12) NULL,
    [COSTOMN1]        NUMERIC (38, 9)  NULL,
    [VAL2]            NUMERIC (38, 12) NULL,
    [COSTOMN2]        NUMERIC (38, 9)  NULL,
    [VAL3]            NUMERIC (38, 12) NULL,
    [COSTOMN3]        NUMERIC (38, 9)  NULL,
    [VAL4]            NUMERIC (38, 12) NULL,
    [COSTOMN4]        NUMERIC (38, 9)  NULL,
    [VAL5]            NUMERIC (38, 12) NULL,
    [COSTOMN5]        NUMERIC (38, 9)  NULL,
    [VAL6]            NUMERIC (38, 12) NULL,
    [COSTOMN6]        NUMERIC (38, 9)  NULL,
    [VAL7]            NUMERIC (38, 12) NULL,
    [COSTOMN7]        NUMERIC (38, 9)  NULL,
    [VAL8]            NUMERIC (38, 12) NULL,
    [COSTOMN8]        NUMERIC (38, 9)  NULL,
    [VAL9]            NUMERIC (38, 12) NULL,
    [COSTOMN9]        NUMERIC (38, 9)  NULL,
    [VAL10]           NUMERIC (38, 12) NULL,
    [COSTOMN10]       NUMERIC (38, 9)  NULL,
    [VAL11]           NUMERIC (38, 12) NULL,
    [COSTOMN11]       NUMERIC (38, 9)  NULL,
    [VAL12]           NUMERIC (38, 12) NULL,
    [COSTOMN12]       NUMERIC (38, 9)  NULL
);

