CREATE TABLE [dbo].[tabla_x_articulo] (
    [CUSTOMER_ID]       VARCHAR (11)    NULL,
    [CUSTOMER_NAME]     VARCHAR (150)   NULL,
    [PART_ID]           VARCHAR (20)    NULL,
    [PART_DESCRIPTION]  VARCHAR (64)    NULL,
    [QTY]               NUMERIC (15, 6) NULL,
    [UNIT]              VARCHAR (6)     NULL,
    [AMOUNT]            NUMERIC (15, 6) NULL,
    [AMOUNT_US]         NUMERIC (15, 6) NULL,
    [CURRENCY_ID]       VARCHAR (2)     NULL,
    [AMOUNT_TAX]        NUMERIC (15, 6) NULL,
    [CURRENCY_EXCHANGE] NUMERIC (15, 6) NULL,
    [DOCUMENT_ID]       VARCHAR (2)     NULL,
    [NUMBER_SERIE]      VARCHAR (3)     NULL,
    [NUMBER_DOCUMENT]   VARCHAR (7)     NULL,
    [IS_GUIA_REC]       VARCHAR (1)     NULL,
    [PRICE_ORI]         NUMERIC (15, 6) NULL,
    [IS_STOCKED]        VARCHAR (1)     NULL,
    [SERIES]            VARCHAR (1)     NULL,
    [IS_LOT]            VARCHAR (1)     NULL,
    [DISCOUNT]          NUMERIC (15, 6) NULL,
    [DISCOUNT_CUSTOMER] NUMERIC (15, 6) NULL,
    [DISCOUNT_SP]       NUMERIC (15, 6) NULL,
    [PART_TAX]          BIT             NOT NULL,
    [TAX_PERCENT]       NUMERIC (15, 6) NULL,
    [AMOUNT_TAX_CAB]    NUMERIC (15, 6) NULL,
    [DOCUMENT_DATE]     DATETIME        NULL,
    [COSTOMN]           NUMERIC (15, 9) NULL,
    [COSTOME]           NUMERIC (15, 9) NULL
);

