CREATE TABLE [dbo].[TABLA_MEDIARIA_TRANSACCIONES_DE_INVENTARIOS] (
    [TRANS_ID]  VARCHAR (2)   NULL,
    [IS_IN_OUT] VARCHAR (1)   NULL,
    [FECHA]     VARCHAR (60)  NULL,
    [IN_VALUE]  FLOAT (53)    NULL,
    [OUT_VALUE] FLOAT (53)    NULL,
    [NAME]      VARCHAR (150) NULL
);

