CREATE TABLE [dbo].[TABLADECLIENTES_CUSTOMER_ID] (
    [DOCUMENT_DATE]   DATETIME        NULL,
    [CUSTOMER_ID]     VARCHAR (11)    NULL,
    [CUSTOMER_NAME]   VARCHAR (150)   NULL,
    [QTY]             NUMERIC (38, 6) NULL,
    [AMOUNT]          NUMERIC (38, 6) NULL,
    [AMOUNT_US]       NUMERIC (38, 6) NULL,
    [CURRENCY_ID]     VARCHAR (2)     NULL,
    [AMOUNT_TAX]      NUMERIC (38, 6) NULL,
    [NUMBER_DOCUMENT] VARCHAR (7)     NULL,
    [DOCUMENT_ID]     VARCHAR (2)     NULL
);

