CREATE TABLE [dbo].[TABLA_SUMA_YEAR_ANTERIOR] (
    [FECHA]     VARCHAR (60) NULL,
    [IN_VALUE]  FLOAT (53)   NULL,
    [OUT_VALUE] FLOAT (53)   NULL,
    [TRANS_ID]  VARCHAR (2)  NULL,
    [IS_IN_OUT] VARCHAR (2)  NULL,
    [NAME]      VARCHAR (2)  NULL
);

