CREATE TABLE [dbo].[TABLADECLIENTES2] (
    [CUSTOMER_ID]   VARCHAR (11)    NULL,
    [CUSTOMER_NAME] VARCHAR (150)   NULL,
    [QTY]           NUMERIC (38, 6) NULL,
    [AMOUNT]        NUMERIC (38, 6) NULL,
    [AMOUNT_US]     NUMERIC (38, 6) NULL,
    [CURRENCY_ID]   VARCHAR (2)     NULL,
    [AMOUNT_TAX]    NUMERIC (38, 6) NULL
);

