CREATE TABLE [dbo].[tabla_ventas_mensuales_por_articulo] (
    [PLACE_SALES]         VARCHAR (2)      NULL,
    [PART_ID]             VARCHAR (20)     NULL,
    [DESCRIPTION]         VARCHAR (64)     NULL,
    [UNIT_OF_MEASUREMENT] VARCHAR (6)      NULL,
    [CANTIDAD1]           NUMERIC (38, 6)  NULL,
    [VAL1]                NUMERIC (38, 12) NULL,
    [CANTIDAD2]           FLOAT (53)       NULL,
    [VAL2]                FLOAT (53)       NULL,
    [CANTIDAD3]           FLOAT (53)       NULL,
    [VAL3]                FLOAT (53)       NULL,
    [CANTIDAD4]           FLOAT (53)       NULL,
    [VAL4]                FLOAT (53)       NULL,
    [CANTIDAD5]           FLOAT (53)       NULL,
    [VAL5]                FLOAT (53)       NULL,
    [CANTIDAD6]           FLOAT (53)       NULL,
    [VAL6]                FLOAT (53)       NULL,
    [CANTIDAD7]           FLOAT (53)       NULL,
    [VAL7]                FLOAT (53)       NULL,
    [CANTIDAD8]           FLOAT (53)       NULL,
    [VAL8]                FLOAT (53)       NULL,
    [CANTIDAD9]           FLOAT (53)       NULL,
    [VAL9]                FLOAT (53)       NULL,
    [CANTIDAD10]          FLOAT (53)       NULL,
    [VAL10]               FLOAT (53)       NULL,
    [CANTIDAD11]          FLOAT (53)       NULL,
    [VAL11]               FLOAT (53)       NULL,
    [CANTIDAD12]          FLOAT (53)       NULL,
    [VAL12]               FLOAT (53)       NULL
);

