CREATE TABLE [dbo].[tablacinco] (
    [WAREHOUSE_ID]      VARCHAR (2)     NOT NULL,
    [DOCUMENT_ID]       VARCHAR (2)     NOT NULL,
    [NUMBER_DOCUMENT]   VARCHAR (10)    NOT NULL,
    [ITEM]              INT             NOT NULL,
    [PART_ID]           VARCHAR (20)    NULL,
    [REF_ID]            VARCHAR (40)    NULL,
    [QTY]               NUMERIC (15, 6) NULL,
    [QTY_DLV]           NUMERIC (15, 6) NULL,
    [QTY_REF]           NUMERIC (15, 6) NULL,
    [QTY_INVOICED]      NUMERIC (15, 6) NULL,
    [NUM_ORDER]         VARCHAR (6)     NULL,
    [UNIT_PRICE]        NUMERIC (15, 6) NULL,
    [AVERAGE_COST]      NUMERIC (15, 6) NULL,
    [AMOUNT_SALES]      NUMERIC (15, 6) NULL,
    [DISCOUNT]          NUMERIC (15, 6) NULL,
    [STOCK]             VARCHAR (50)    NULL,
    [AMOUNT_TAX]        NUMERIC (15, 6) NULL,
    [AMOUNT]            NUMERIC (15, 6) NULL,
    [AMOUNT_US]         NUMERIC (15, 6) NULL,
    [NUMBER_SERIE]      VARCHAR (20)    NULL,
    [STATUS_DOC]        VARCHAR (1)     NULL,
    [DATE_DOC]          DATETIME        NULL,
    [CCOST_ID]          VARCHAR (10)    NULL,
    [WAREHOUSE_REF]     VARCHAR (2)     NULL,
    [TEXT_COMMENT]      VARCHAR (1)     NULL,
    [STATUS]            VARCHAR (1)     NULL,
    [TRANS_ID]          VARCHAR (2)     NULL,
    [VAL_AMOUNT]        NUMERIC (15, 6) NULL,
    [NUM_VOUCHER]       VARCHAR (6)     NULL,
    [CURRENCY_ID]       VARCHAR (2)     NULL,
    [TYPE]              VARCHAR (1)     NULL,
    [TYPE_EXCHANGE]     NUMERIC (15, 6) NULL,
    [PRICE_SALES]       NUMERIC (15, 6) NULL,
    [TOTAL_SALES]       VARCHAR (2)     NULL,
    [DATE_CADUCATE]     DATETIME        NULL,
    [RETURN_AMOUNT]     NUMERIC (15, 6) NULL,
    [AUTHORIZED]        VARCHAR (3)     NULL,
    [PART_DESCRIPTION]  VARCHAR (64)    NULL,
    [DISCOUNT_PERCENT]  NUMERIC (15, 6) NULL,
    [TAX_PERCENT]       NUMERIC (15, 6) NULL,
    [DISCOUNT_CUST]     NUMERIC (15, 6) NULL,
    [DISCOUNT_SP]       NUMERIC (15, 6) NULL,
    [NUMBER_INVOICE]    VARCHAR (10)    NULL,
    [NUMBER_LOT]        VARCHAR (20)    NULL,
    [UNIT_PART]         VARCHAR (6)     NULL,
    [ORDER_MANUFACT_ID] VARCHAR (20)    NULL,
    [EQUIP_ID]          VARCHAR (10)    NULL,
    [FREIGTH]           NUMERIC (15, 6) NULL,
    [ITEMI]             VARCHAR (10)    NULL,
    [QTY_BRUTE]         NUMERIC (15, 6) NULL,
    [DISCOUNT_PER_QTY]  NUMERIC (15, 6) NULL,
    [STATUS_VALUE]      BIT             NOT NULL,
    [UNIT_REFERENCE]    VARCHAR (6)     NULL,
    [QTY_REFERENCE]     NUMERIC (15, 6) NULL,
    [COMMENT]           VARCHAR (50)    NULL,
    [REFERENCE]         VARCHAR (50)    NULL,
    [ACCOUNT]           VARCHAR (18)    NULL,
    [COMMENT_TEXT]      TEXT            NULL,
    [PROJECT_ID]        VARCHAR (20)    NULL
);

