CREATE TABLE [dbo].[TOOLBOX_OPTIONS] (
    [MODULE_ID]  VARCHAR (2)  NOT NULL,
    [OPTION_DES] VARCHAR (50) NULL,
    [EXE_ID]     VARCHAR (20) NOT NULL,
    [IMAGE_NOM]  VARCHAR (80) NULL,
    [MENU_ID]    VARCHAR (15) NULL,
    [LEVEL_ID]   VARCHAR (5)  NULL,
    [ORDER_OPT]  VARCHAR (2)  NOT NULL,
    [USER_ID]    VARCHAR (50) NOT NULL
);

