CREATE TABLE [dbo].[TRANSACTION_CHECK] (
    [TYPE_DOC]        VARCHAR (2)  NOT NULL,
    [NUMBER]          VARCHAR (10) NOT NULL,
    [CURRENCY_ID]     VARCHAR (2)  NULL,
    [BANK_ID]         VARCHAR (2)  NOT NULL,
    [NUMBER_CHECK]    VARCHAR (10) NOT NULL,
    [CURRENCY_CHECK]  VARCHAR (2)  NULL,
    [AMOUNT]          MONEY        NULL,
    [NUMBER_EXCHANGE] CHAR (6)     NULL
);

