CREATE TABLE [dbo].[TRANSFER_PARAMETERS] (
    [NAMEBDSOURCE]      VARCHAR (200) NULL,
    [NAMEBDDESTINE]     VARCHAR (200) NULL,
    [ACCOUNT_1]         VARCHAR (14)  NULL,
    [ACCOUNT_2]         VARCHAR (14)  NULL,
    [ACCOUNT_3]         VARCHAR (14)  NULL,
    [ACCOUNT_4]         VARCHAR (2)   NULL,
    [ACCOUNT_5]         VARCHAR (100) NULL,
    [ACCOUNT_6]         VARCHAR (100) NULL,
    [NAMESERVERSOURCE]  VARCHAR (200) NULL,
    [NAMESERVERDESTINE] VARCHAR (200) NULL
);

