CREATE TABLE [dbo].[USER_ACCESS_RECEIVE] (
    [USER_ID]    VARCHAR (8)  NOT NULL,
    [COMPANY_ID] VARCHAR (3)  NOT NULL,
    [MENU_ID]    VARCHAR (10) NOT NULL,
    [IS_VISIBLE] BIT          NOT NULL
);

