CREATE TABLE [dbo].[USER_PURCHASE] (
    [USER_ID]    NVARCHAR (8)  NOT NULL,
    [COMPANY_ID] NVARCHAR (3)  NOT NULL,
    [PASSWORD]   NVARCHAR (8)  NULL,
    [LEVEL]      NVARCHAR (1)  NULL,
    [NAME]       NVARCHAR (32) NULL
);

