CREATE TABLE [dbo].[USER_ACCESS_SALES] (
    [USER_ID]    VARCHAR (8)  NOT NULL,
    [COMPANY_ID] VARCHAR (5)  NOT NULL,
    [MENU_ID]    VARCHAR (10) NOT NULL,
    [IS_VISIBLE] BIT          NOT NULL
);

