CREATE TABLE [dbo].[USER_INVENTORY] (
    [USER_ID]    VARCHAR (8)  NOT NULL,
    [COMPANY_ID] VARCHAR (3)  NOT NULL,
    [PASSWORD]   VARCHAR (8)  NULL,
    [LEVEL]      VARCHAR (1)  NULL,
    [NAME]       VARCHAR (32) NULL
);

