CREATE TABLE [dbo].[USER_ACCESS_PURCHASE] (
    [USER_ID]    NVARCHAR (8)  NOT NULL,
    [COMPANY_ID] NVARCHAR (5)  NOT NULL,
    [MENU_ID]    NVARCHAR (10) NOT NULL,
    [IS_VISIBLE] BIT           NOT NULL
);

