CREATE TABLE [dbo].[VENDOR] (
    [ID]                      VARCHAR (11)    NOT NULL,
    [NAME]                    VARCHAR (100)   NULL,
    [VAT_REGISTRATION]        VARCHAR (11)    NULL,
    [ADDR]                    VARCHAR (100)   NULL,
    [STATE_ID]                VARCHAR (8)     NULL,
    [COUNTRY_ID]              VARCHAR (3)     NULL,
    [PHONE]                   VARCHAR (30)    NULL,
    [FAX_NUMBER]              VARCHAR (30)    NULL,
    [EMAIL]                   VARCHAR (50)    NULL,
    [WEBSITE]                 VARCHAR (50)    NULL,
    [TYPE_VENDOR_ID]          VARCHAR (2)     NULL,
    [STATUS]                  VARCHAR (1)     NULL,
    [CONTACT]                 VARCHAR (70)    NULL,
    [CONTACT_POSITION]        VARCHAR (30)    NULL,
    [CONTACT_PHONE]           VARCHAR (30)    NULL,
    [CONTACT_EMAIL]           VARCHAR (50)    NULL,
    [REPRESENT]               VARCHAR (70)    NULL,
    [REPRESENT_POSITION]      VARCHAR (30)    NULL,
    [REPRESENT_PHONE]         VARCHAR (30)    NULL,
    [REPRESENT_EMAIL]         VARCHAR (50)    NULL,
    [CREATE_DATE]             SMALLDATETIME   NULL,
    [CREATE_USER]             VARCHAR (8)     NULL,
    [MODIFY_DATE]             SMALLDATETIME   NULL,
    [COMMENT]                 VARCHAR (255)   NULL,
    [BALANCE]                 NUMERIC (18, 5) NULL,
    [BALANCE_US]              NUMERIC (18, 5) NULL,
    [DOCUMENT_TYPE_PERSON_ID] VARCHAR (2)     NULL,
    [TYPE_COMPANY]            VARCHAR (2)     NULL,
    [ACCOUNT_LOCAL]           VARCHAR (50)    NULL,
    [ACCOUNT_EXTERNAL]        VARCHAR (50)    NULL
);

