CREATE TABLE [dbo].[VMART] (
    [PLACE_SALES]         VARCHAR (2)      NULL,
    [SALES_REP_ID]        VARCHAR (2)      NULL,
    [NAME]                VARCHAR (30)     NULL,
    [PART_ID]             VARCHAR (20)     NULL,
    [DESCRIPTION]         VARCHAR (64)     NULL,
    [UNIT_OF_MEASUREMENT] VARCHAR (6)      NULL,
    [CANTIDAD1]           NUMERIC (38, 6)  NULL,
    [VALORMN1]            NUMERIC (38, 12) NULL,
    [VALORME1]            NUMERIC (38, 22) NULL,
    [CANTIDAD2]           FLOAT (53)       NULL,
    [VALORMN2]            FLOAT (53)       NULL,
    [VALORME2]            FLOAT (53)       NULL,
    [CANTIDAD3]           FLOAT (53)       NULL,
    [VALORMN3]            FLOAT (53)       NULL,
    [VALORME3]            FLOAT (53)       NULL,
    [CANTIDAD4]           FLOAT (53)       NULL,
    [VALORMN4]            FLOAT (53)       NULL,
    [VALORME4]            FLOAT (53)       NULL,
    [CANTIDAD5]           FLOAT (53)       NULL,
    [VALORMN5]            FLOAT (53)       NULL,
    [VALORME5]            FLOAT (53)       NULL,
    [CANTIDAD6]           FLOAT (53)       NULL,
    [VALORMN6]            FLOAT (53)       NULL,
    [VALORME6]            FLOAT (53)       NULL,
    [CANTIDAD7]           FLOAT (53)       NULL,
    [VALORMN7]            FLOAT (53)       NULL,
    [VALORME7]            FLOAT (53)       NULL,
    [CANTIDAD8]           FLOAT (53)       NULL,
    [VALORMN8]            FLOAT (53)       NULL,
    [VALORME8]            FLOAT (53)       NULL,
    [CANTIDAD9]           FLOAT (53)       NULL,
    [VALORMN9]            FLOAT (53)       NULL,
    [VALORME9]            FLOAT (53)       NULL,
    [CANTIDAD10]          FLOAT (53)       NULL,
    [VALORMN10]           FLOAT (53)       NULL,
    [VALORME10]           FLOAT (53)       NULL,
    [CANTIDAD11]          FLOAT (53)       NULL,
    [VALORMN11]           FLOAT (53)       NULL,
    [VALORME11]           FLOAT (53)       NULL,
    [CANTIDAD12]          FLOAT (53)       NULL,
    [VALORMN12]           FLOAT (53)       NULL,
    [VALORME12]           FLOAT (53)       NULL
);

