CREATE TABLE [dbo].[VOUCHER_REC] (
    [ID]         VARCHAR (2)  NULL,
    [VOUCHER_ID] VARCHAR (4)  NULL,
    [MONTH]      VARCHAR (6)  NULL,
    [INVOICE_ID] VARCHAR (12) NULL,
    [STATUS]     VARCHAR (4)  NULL
);

