CREATE TABLE [dbo].[VOUCHER] (
    [ID]          VARCHAR (2) NULL,
    [VOUCHER_ID]  VARCHAR (4) NULL,
    [MONTH]       VARCHAR (6) NULL,
    [LIST]        VARCHAR (6) NULL,
    [CURRENCY_ID] VARCHAR (2) NULL
);

