CREATE PROCEDURE ACT_NUMERACION_COMPRAS
@ANIO VARCHAR(4),
@MES VARCHAR(2)
AS

DECLARE @ID VARCHAR(13)
DECLARE @REFER_DOCUMENT_TYPE VARCHAR(2)
DECLARE @REFER_DOCUMENT_NUMBER VARCHAR(13)
DECLARE @SERIE VARCHAR(10)
DECLARE @CONTADOR INT
DECLARE @NUM_VOUCHER VARCHAR(13)

SET @CONTADOR=1

DECLARE CURSORA CURSOR FOR
SELECT ID, REFER_DOCUMENT_TYPE, REFER_DOCUMENT_NUMBER, SERIE 
FROM dbo.PURCHASE_FACT_SUPPLIER WHERE YEAR(PROMISE_DATE)=@ANIO
AND MONTH(PROMISE_DATE)=@MES
OPEN CURSORA
FETCH NEXT FROM CURSORA
INTO @ID, @REFER_DOCUMENT_TYPE, @REFER_DOCUMENT_NUMBER, @SERIE
WHILE @@FETCH_STATUS=0
BEGIN
	SET @NUM_VOUCHER=@MES+'-'+DBO.FormateaconCeros(@CONTADOR,7)
	
	UPDATE dbo.PURCHASE_FACT_SUPPLIER SET ID=@NUM_VOUCHER
	WHERE ID=@ID AND REFER_DOCUMENT_TYPE=@REFER_DOCUMENT_TYPE AND 
	REFER_DOCUMENT_NUMBER=@REFER_DOCUMENT_NUMBER AND SERIE=@SERIE
	UPDATE dbo.PURCHASE_FACT_SUPPLIER_L SET ID=@NUM_VOUCHER
	WHERE ID=@ID
	
	SET @CONTADOR=@CONTADOR+1

FETCH NEXT FROM CURSORA
INTO @ID, @REFER_DOCUMENT_TYPE, @REFER_DOCUMENT_NUMBER, @SERIE
END
CLOSE CURSORA
DEALLOCATE CURSORA