create procedure [dbo].[ACT_QTY_FT]  
@DOC VARCHAR(5),  
@SERIE VARCHAR(5),  
@NUMBER VARCHAR(10),  
@ALMACEN VARCHAR(3)  
AS  
  
DECLARE @PART_ID VARCHAR(10)  
DECLARE CURSOR1 CURSOR FOR  
SELECT DISTINCT PART_ID FROM dbo.RECEIVABLE_LINE WHERE NUMBER_DOCUMENT=@NUMBER AND  
NUMBER_SERIE=@SERIE AND DOCUMENT_ID=@DOC  
OPEN CURSOR1  
FETCH NEXT FROM CURSOR1  
INTO @PART_ID  
WHILE @@FETCH_STATUS=0  
BEGIN  
 exec ACT_QTY_LOTE_2010_AL_CON_ARTICULO @ALMACEN,@PART_ID  
FETCH NEXT FROM CURSOR1  
INTO @PART_ID  
END  
CLOSE CURSOR1  
DEALLOCATE CURSOR1  
--SELECT * FROM RECEIVABLE_LINE  
  
