CREATE PROCEDURE ACTUALIZA_PART
 AS
DECLARE @FAMILY_ID VARCHAR(30)
DECLARE  @ID VARCHAR(30)
DECLARE @NAME VARCHAR(50)

DECLARE ACTU CURSOR FOR
SELECT DISTINCT * FROM LINES ORDER BY ID
OPEN ACTU
FETCH NEXT FROM ACTU
INTO @FAMILY_ID,@ID,@NAME

WHILE @@FETCH_STATUS=0
BEGIN
	UPDATE PART SET DESCRIPTION_OPT=@NAME
	WHERE MODEL=@ID AND FAMILY=@FAMILY_ID
FETCH NEXT FROM ACTU
INTO @FAMILY_ID,@ID,@NAME
END
CLOSE ACTU
DEALLOCATE ACTU

