CREATE PROCEDURE ACTUALIZAR_LA_TABLA_RECEIVABLE_PRUEBA 
 AS
DECLARE @NUMBER_DOCUMENT VARCHAR(15)
DECLARE @AMOUNT_TAX NUMERIC(22,9)
DECLARE @IGV NUMERIC(22,9)
DECLARE @CONTADOR INT
SET @CONTADOR=0
DECLARE @INDICE INT
DECLARE @INDICEDOS INT
DECLARE @EXTRA_UNO VARCHAR(15)
DECLARE @EXTRA_DOS VARCHAR(15)

DECLARE ACTUALIZADOR CURSOR FOR

SELECT NUMBER_DOCUMENT,AMOUNT_TAX FROM RECEIVABLE
WHERE YEAR(DOCUMENT_DATE)='2010' AND MONTH(DOCUMENT_DATE)>='03' AND STATUS<>'A' 
ORDER BY NUMBER_DOCUMENT

OPEN ACTUALIZADOR
FETCH NEXT FROM ACTUALIZADOR
INTO @NUMBER_DOCUMENT,@AMOUNT_TAX
WHILE @@FETCH_STATUS=0
BEGIN
SELECT @IGV=ROUND(SUM(AMOUNT_TAX),2) FROM RECEIVABLE_LINE
WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT

SET @INDICE=CHARINDEX('.',CONVERT(VARCHAR,@IGV))
SET @INDICEDOS=CHARINDEX('.',CONVERT(VARCHAR,@AMOUNT_TAX))
SET @EXTRA_UNO=SUBSTRING(CONVERT(VARCHAR,@IGV),1,@INDICE-1)
SET @EXTRA_DOS=SUBSTRING(CONVERT(VARCHAR,@AMOUNT_TAX),1,@INDICEDOS-1)

IF @EXTRA_UNO<>@EXTRA_DOS
BEGIN
PRINT @NUMBER_DOCUMENT
END
FETCH NEXT FROM ACTUALIZADOR
INTO @NUMBER_DOCUMENT,@AMOUNT_TAX
END
CLOSE ACTUALIZADOR
DEALLOCATE ACTUALIZADOR