CREATE PROCEDURE ACTUALIZA_JULIO_R_Y_RL
 AS


DECLARE @NUMBER_DOCUMENT VARCHAR(15)

DECLARE JULIO CURSOR FOR

SELECT NUMBER_DOCUMENT FROM RECEIVABLE_PRUEBA WHERE STATUS<>'A' AND DOCUMENT_DATE>='01/03/2010' AND DOCUMENT_DATE<='31/03/2010' 
ORDER BY DOCUMENT_DATE

OPEN JULIO
FETCH NEXT FROM JULIO
INTO @NUMBER_DOCUMENT
WHILE @@FETCH_STATUS=0
BEGIN
	INSERT INTO JULIO SELECT NUMBER_DOCUMENT,AMOUNT,AMOUNT_TAX FROM RECEIVABLE_PRUEBA WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT
	INSERT INTO JULIO_RL SELECT NUMBER_DOCUMENT,SUM(AMOUNT)AS AMOUNT,SUM(AMOUNT_TAX)AS AMOUNT_TAX FROM RECEIVABLE_LINE_PRUEBA WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT 	GROUP BY  NUMBER_DOCUMENT
	FETCH NEXT FROM JULIO
	INTO @NUMBER_DOCUMENT
END
CLOSE JULIO
DEALLOCATE JULIO