CREATE PROCEDURE ACTUALIZA_R_Y_RL
 AS
DECLARE @NUMBER_DOCUMENT VARCHAR(15)
DECLARE @ITEM VARCHAR(2)
DECLARE @QTY NUMERIC(22,9)
DECLARE @AMOUNT_TAX NUMERIC(22,9)
DECLARE @PRICE_ORI NUMERIC(22,9)
DECLARE @IGV NUMERIC(22,9)
DECLARE @POSICION INT
DECLARE @EXTRA_AMOUNT_TAX VARCHAR(10)
DECLARE @POSICION_IGV INT
DECLARE @EXTRA_IGV VARCHAR(10)
DECLARE @IGV_OFICIAL NUMERIC(22,9)
DECLARE ACTUALIZA CURSOR FOR

select RL.NUMBER_DOCUMENT,RL.ITEM,RL.QTY,RL.AMOUNT_TAX,RL.PRICE_ORI
 from receivable_LINE RL INNER JOIN RECEIVABLE R ON R.NUMBER_DOCUMENT=RL.NUMBER_DOCUMENT
Where  RL.STATUS <> 'A' and  RL.PART_ID<>'TEXTO'   AND YEAR(R.DOCUMENT_DATE)='2010' AND 
MONTH(R.DOCUMENT_DATE)>='03'
ORDER BY R.NUMBER_DOCUMENT

OPEN ACTUALIZA
FETCH NEXT FROM ACTUALIZA
INTO @NUMBER_DOCUMENT,@ITEM,@QTY,@AMOUNT_TAX,@PRICE_ORI
WHILE @@FETCH_STATUS=0
	BEGIN
		SET @IGV=@QTY*@PRICE_ORI
		SET  @POSICION=CHARINDEX('.',CONVERT(VARCHAR,@AMOUNT_TAX))
		SET @EXTRA_AMOUNT_TAX=SUBSTRING(CONVERT(VARCHAR,@AMOUNT_TAX),1,@POSICION-1)
		SET @POSICION_IGV=CHARINDEX('.',CONVERT(VARCHAR,@IGV))
		SET @EXTRA_IGV=SUBSTRING(CONVERT(VARCHAR,@IGV),1,@POSICION_IGV-1)
		
		IF @EXTRA_AMOUNT_TAX=@EXTRA_IGV
			BEGIN
				SET @IGV_OFICIAL=@AMOUNT_TAX*0.19
				UPDATE RECEIVABLE_LINE SET AMOUNT_TAX=@IGV_OFICIAL
				WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND ITEM=@ITEM				
			END	
		FETCH NEXT FROM ACTUALIZA
		INTO @NUMBER_DOCUMENT,@ITEM,@QTY,@AMOUNT_TAX,@PRICE_ORI
	END
CLOSE ACTUALIZA
DEALLOCATE ACTUALIZA