CREATE proc [dbo].[ADM_INSERT_PARAMETROS]  
@BDV VARCHAR(50),  
@FECHAV DATETIME,  
@EMPRESAV VARCHAR(150),  
@DIRECCIONV VARCHAR(200),  
@RUCV VARCHAR(20),  
@PCV VARCHAR(30)  
AS  
  
EXEC('INSERT INTO '+@PCV+'(NOMBD,FECHA_TRABAJO,NOMEMPRESA,DIRECCION,RUC)   
VALUES('''+@BDV+''','''+@FECHAV+''','''+@EMPRESAV+''','''+@DIRECCIONV+''','''+@RUCV+''')')  
  