CREATE PROCEDURE CO_REP_COBRANZA_COMISION
@FECINI AS VARCHAR(10),          
@FECFIN AS VARCHAR(10),
@SALES_REP_ID AS VARCHAR(10),
@TABLA AS VARCHAR(50)                          
AS
EXEC('SELECT  DISTINCT
DOCUMENT_TYPE_ID AS TIP_DOC,
DOCUMENT_SERIE AS SERIE, 
DOCUMENT_NUMBER  AS NUMERO,
CONVERT(VARCHAR(10),C.DOCUMENT_DATE,103)AS FECHA_DOC,
CONVERT(NUMERIC(22,3),(ISNULL(A.AMOUNT_CR,0)-(ISNULL(A.AMOUNT_CR,0)*L.TAX_PERCENT/100))) AS MONTO,
CONVERT(NUMERIC(22,3),ISNULL(L.COMISION,0)) AS PCTJ_COMISION,
CONVERT(NUMERIC(22,3),(((ISNULL(A.AMOUNT_CR,0)-(ISNULL(A.AMOUNT_CR,0)*L.TAX_PERCENT/100))* ISNULL(L.COMISION,0))/100)) AS MONT_COMISION,
C.SALES_REP_ID,
S.NAME,
C.CUSTOMER_NAME AS ADICIONAL,
ISNULL(A.AMOUNT_CR,0) AS ADICIONAL1
FROM  ACTIVITY_LINE A
INNER JOIN	'+@TABLA+'.dbo.RECEIVABLE C
ON A.DOCUMENT_TYPE_ID=DOCUMENT_ID AND A.DOCUMENT_SERIE=NUMBER_SERIE 
AND A.DOCUMENT_NUMBER=NUMBER_DOCUMENT
INNER JOIN	'+@TABLA+'.dbo.RECEIVABLE_LINE L
ON C.DOCUMENT_ID=L.DOCUMENT_ID AND  C.NUMBER_SERIE=L.NUMBER_SERIE
AND C.NUMBER_DOCUMENT=L.NUMBER_DOCUMENT
INNER JOIN '+@TABLA+'.dbo.SALES_REP S
ON S.ID=C.SALES_REP_ID
WHERE
 A.CURRENCY_DOCUMENT=''1''
AND A.OPE_TYPE_DESCRIPTION=''Ingreso''
AND C.DOCUMENT_DATE BETWEEN '''+@FECINI+''' AND '''+@FECFIN
+''' AND C.SALES_REP_ID='''+@SALES_REP_ID+''' ')

