

  
CREATE PROC [dbo].[CO_SP_S_CTAS_10_SOBREGIRO]  
@P_PERIODO INT = 2013
AS  
  
SELECT PC_NUM_CTA FROM CO_TB_PLANCTAS   
WHERE PC_NUM_CTA LIKE '10%'  AND PC_IDTIPO_MOV = 2  
AND PC_PERIODO = @P_PERIODO  
  

