

CREATE PROC [dbo].[CO_SP_S_DETALLE_COMPRO]
@P_TD VARCHAR(3),
@P_SD VARCHAR(10),
@P_ND VARCHAR(20)
AS

SELECT A.*,B.ACCOUNT_INTERNAL_ID FROM RECEIVABLE_LINE A INNER JOIN PART B ON A.PART_ID = B.ID
WHERE DOCUMENT_ID = @P_TD AND 
NUMBER_SERIE = @P_SD AND NUMBER_DOCUMENT = @P_ND

