create PROC CO_SP_S_BI_CTA10    
@P_PERIODO INT = 2013    
AS    
    
SELECT AD_CUENTA,PC_DES_CTA,ban.NAME,ban.ACCOUNT_BANK_ID,PC_IDMONEDA,    
SUM(AD_DEBE) AS DEBE,SUM(AD_HABER) AS HABER    
FROM     
CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
INNER JOIN CO_TB_PLANCTAS C ON B.AD_CUENTA = C.PC_NUM_CTA    
inner join 
(SELECT A.*,B.* FROM BANK A       
   inner join account_bank b on a.ID = b.bank_id ) ban on B.AD_CUENTA = ban.number_account  

--LEFT JOIN CO_TB_BANCO_CTACTE D ON B.AD_IDCUENTA = D.BC_IDCUENTA AND  BC_PERIODO = @P_PERIODO    
--LEFT JOIN CO_TB_BANCO E ON D.BC_IDBANCO = E.BA_ID    
    
WHERE AC_ANHO = @P_PERIODO     
--AND AC_IDEMPRESA = @P_EMPRESA    
AND AC_ESTADO = 1    
--AND PC_IDEMPRESA = @P_EMPRESA    
AND PC_PERIODO = @P_PERIODO    
AND PC_IDTIPO_MOV = 2    
--AND PC_IDTIPO_MOV_DET IN(2,3)    
--and AC_IDSUBDIARIO <> '11'  
AND AD_CUENTA LIKE '10%'      
    
GROUP BY AD_CUENTA,PC_DES_CTA,ban.NAME,ban.ACCOUNT_BANK_ID,PC_IDMONEDA    
ORDER BY 1