

CREATE PROC [dbo].[CO_SP_S_RESUL_BAL_COMPRO_CTA89]            
@PANHO INT = 2011,					--NUMERO DE AÑO          
@PMES INT = 2,						--NUMERO DE MES          
@CUENTA_INI VARCHAR(50)='10',		--NUMERO DE CUENTA CONTABLE          
@CUENTA_FIN VARCHAR(50)='999999',	--NUMERO DE CUENTA CONTABLE          
@CUENTA_RESULTADO VARCHAR(20)='89'	--NUMERO DE CUENTA DE RESULTADO    
AS            
    
DECLARE @RESULTADO float     
SET @RESULTADO = (    
            
SELECT             
--(CASE WHEN SUM(AD_DEBE) - SUM(AD_HABER) > 0 THEN  ABS(SUM(AD_DEBE) - SUM(AD_HABER)) ELSE 0 END) AS SALDO_DEUDOR,            
--(CASE WHEN SUM(AD_DEBE) - SUM(AD_HABER) < 0 THEN  ABS(SUM(AD_DEBE) - SUM(AD_HABER)) ELSE 0 END) AS SALDO_ACREEDOR            
SUM(AD_DEBE) - SUM(AD_HABER)    
FROM  CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID=B.AD_IDCAB            
WHERE  AC_ANHO  = @PANHO             
 AND AC_MES  <= @PMES             
 AND LEFT(AD_CUENTA,1) IN (1,2,3,4,5)           
 AND AD_CUENTA BETWEEN @CUENTA_INI AND @CUENTA_FIN          
--GROUP BY AD_CUENTA            
--WHERE  PC_NUM_CUENTA BETWEEN @CUENTA_INI AND @CUENTA_FIN          
)    
    
SELECT @RESULTADO    
    
UPDATE CO_TB_REP_BG10 SET RB_IMPORTE = @RESULTADO    
WHERE RB_NUCUENTA = @CUENTA_RESULTADO    
    
--select * from SG_CO_TB_REP_BG10

