CREATE PROC CO_SP_S_BI_CTA42    
@P_PERIODO INT = 2013    
AS    
    
SELECT AD_CUENTA,PC_DES_CTA,    
C.VAT_REGISTRATION,C.NAME,    
ISNULL(C.BUSINESS,0) AS 'AN_TIPO_DOC',C.VAT_REGISTRATION,    
SUM(AD_HABER) - SUM(AD_DEBE)  AS 'SALDO'    
FROM     
CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
LEFT JOIN ANNEXED C ON B.AD_IDANEXO = C.ID    
INNER JOIN CO_TB_PLANCTAS D ON B.AD_CUENTA = D.PC_NUM_CTA     
WHERE AC_ANHO = @P_PERIODO     
AND AC_ESTADO = 1    
AND AD_CUENTA LIKE '42%'    
AND D.PC_PERIODO = @P_PERIODO     
--AND AC_IDSUBDIARIO <> '11'  
AND C.TYPE = 2  
GROUP BY AD_CUENTA,PC_DES_CTA,C.VAT_REGISTRATION,C.NAME,ISNULL(C.BUSINESS,0),C.VAT_REGISTRATION
HAVING SUM(AD_HABER) <> SUM(AD_DEBE)    
ORDER BY 1 