

CREATE PROC [dbo].[CO_SP_I_PLANCTAS]
@P_NUM_CTA VARCHAR(20),
@P_DES_CTA VARCHAR(150),
@P_IDMONEDA INT,
@P_IDTIPO_MOV INT,
@P_IDTIPO_ANEXO INT,
@P_PERIODO INT,
@P_ES_CC INT,
@P_DES_D VARCHAR(20) ,
@P_DES_H VARCHAR(20) ,
@P_ES_EFE INT,
@P_ES_CTA INT,
@P_ES_MP INT
AS

INSERT INTO CO_TB_PLANCTAS(PC_NUM_CTA,PC_DES_CTA,PC_IDMONEDA,PC_IDTIPO_MOV,PC_IDTIPO_ANEXO,PC_PERIODO,PC_ES_CC,PC_DES_D,PC_DES_H,PC_ES_EFE, PC_ES_CTA ,PC_ES_MP)
VALUES(@P_NUM_CTA ,@P_DES_CTA ,@P_IDMONEDA ,@P_IDTIPO_MOV ,@P_IDTIPO_ANEXO ,@P_PERIODO ,@P_ES_CC ,@P_DES_D,@P_DES_H,@P_ES_EFE, @P_ES_CTA ,@P_ES_MP)

