

CREATE PROC [dbo].[CO_SP_S_PLANCTAS_MOV]    
@P_PERIODO INT = 2013    
AS    
    
SELECT  PC_NUM_CTA,PC_DES_CTA,
PC_IDMONEDA,PC_IDTIPO_MOV,
PC_IDTIPO_ANEXO,PC_PERIODO,
isnull(PC_ES_CC,0)as 'PC_ES_CC',isnull(PC_ES_MP,0)   as 'PC_ES_MP'  ,PC_ES_EFE,
PC_ES_CTA
FROM CO_TB_PLANCTAS     
WHERE PC_PERIODO = @P_PERIODO  AND PC_IDTIPO_MOV = 2  
ORDER BY PC_NUM_CTA    

