

CREATE PROC [dbo].[CO_SP_D_ASIENTO_CAB]
@P_ID BIGINT = 0,
@P_IDSUBDIARIO VARCHAR(2)='01',
@P_ANHO INT = 2013,
@P_MES INT = 5
AS

DELETE FROM CO_TB_ASIENTO_CAB
WHERE AC_ID = @P_ID 
AND AC_IDSUBDIARIO = @P_IDSUBDIARIO
AND AC_ANHO = @P_ANHO
AND AC_MES = @P_MES

DELETE FROM CO_TB_ASIENTO_DET
WHERE AD_IDCAB = @P_ID 

