

  
CREATE PROC [dbo].[CO_SP_U_BAL_GRAL_1]    
@P_CUENTA VARCHAR(50)='101001',    
@P_PERIODO INT = 2011,    
@P_MES INT = 8,    
@P_ACUMULADO INT = 1    
AS    
    
DECLARE @SALDO NUMERIC(20,2)    
    
IF @P_ACUMULADO  = 1 BEGIN    
    
SET @SALDO = (SELECT SUM(B.AD_DEBE)-SUM(B.AD_HABER)     
    FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
    WHERE A.AC_ANHO = @P_PERIODO AND AC_MES <= @P_MES 
    AND AD_CUENTA = @P_CUENTA    
    )    
END ELSE BEGIN    
    
SET @SALDO = (SELECT SUM(B.AD_DEBE)-SUM(B.AD_HABER)     
    FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
    WHERE A.AC_ANHO = @P_PERIODO AND AC_MES = @P_MES 
    AND AD_CUENTA = @P_CUENTA    
    )    
    
END    
    
    
    
IF @SALDO < 0 BEGIN    
 if @P_CUENTA like '104%' begin  
  UPDATE  CO_TB_REP_BG10 SET RB_IMPORTE = isnull(RB_IMPORTE,0) + ABS(isnull(@SALDO,0))    
  WHERE RB_IDAREA = 2 AND RB_IDMOD=3 AND RB_NUCUENTA = 10    
 end else begin  
  UPDATE  CO_TB_REP_BG10 SET RB_IMPORTE = isnull(RB_IMPORTE,0) + isnull(@SALDO,0)    
  WHERE RB_IDAREA = 1 AND RB_IDMOD=1 AND RB_NUCUENTA = 10    
 end  
  
END ELSE BEGIN    
 UPDATE  CO_TB_REP_BG10 SET RB_IMPORTE = isnull(RB_IMPORTE,0) + ABS(isnull(@SALDO,0))    
 WHERE RB_IDAREA = 1 AND RB_IDMOD=1 AND RB_NUCUENTA = 10    
END    
    
    

