

CREATE PROC [dbo].[CO_SP_S_CTA_PROVISION]
@P_SUBDIARIO VARCHAR(2)= '01',
@P_RUC VARCHAR(15)= '10421489799'  ,
@P_TD VARCHAR(3) = 'FT',  
@P_SD VARCHAR(10) = '0033',  
@P_ND VARCHAR(20) = '0000396'  
AS  
SELECT ISNULL(AD_CUENTA,'')  AS 'RESULTADO'
FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET  B ON A.AC_ID = B.AD_IDCAB
WHERE AD_TDOC = @P_TD AND AD_SDOC = @P_SD AND AD_NDOC = @P_ND 
AND  AD_IDANEXO = @P_RUC AND AC_IDSUBDIARIO = @P_SUBDIARIO

