
CREATE PROC [dbo].[CO_SP_S_VOUCHER01]      
@P_IDCAB INT = 88,  --CODIGO DE CABECERA      
@P_PERIODO INT = 2011 --NUMERO DE PEROIDO      
AS      
SELECT AD_CUENTA ,      
PC_DES_CTA AS 'PC_DESCRIPCION',      
CAST(A.AD_IDANEXO AS VARCHAR(5)) AD_IDANEXO,      
A.AD_TDOC,A.AD_SDOC,A.AD_NDOC,(CASE WHEN AD_IDMONEDA = 2 THEN 'U$' ELSE 'S/.' END) AS MONEDA,AD_TCAM AS TC,      
(CASE WHEN AD_TCAM > 0 THEN A.AD_MONTO_ORI ELSE 0 END) AS DOL,      
A.AD_DEBE,A.AD_HABER      
FROM CO_TB_ASIENTO_DET A INNER JOIN CO_TB_PLANCTAS  B       
ON A.AD_CUENTA = B.PC_NUM_CTA       
WHERE A.AD_IDCAB = @P_IDCAB  AND PC_PERIODO = @P_PERIODO   
order by AD_SECUENCIA
