
CREATE PROC [dbo].[CO_SP_U_ANNEXED]
@P_ID	VARCHAR	(40),
@P_TYPE	VARCHAR	(4),
@P_VAT_REGISTRATION	VARCHAR	(22),
@P_NAME	VARCHAR	(100),
@P_REFERENCE	VARCHAR	(100),
@P_ADDR	VARCHAR	(100),
@P_PHONE	VARCHAR	(30),
@P_REPRESENTATIVE	VARCHAR	(100),
@P_BUSINESS	VARCHAR	(100)

AS

UPDATE ANNEXED SET NAME = @P_NAME,BUSINESS = @P_BUSINESS
WHERE TYPE = @P_TYPE AND VAT_REGISTRATION = @P_VAT_REGISTRATION

