

      
CREATE PROC [dbo].[CO_SP_S_DAOT_DET]          
@P_ANHO INT  = 2012,          
@P_TIPO INT  = 1,  --1=COMPRAS,2=VENTAS          
@P_TOPE FLOAT = 7200
AS          
          
IF @P_TIPO = 1 BEGIN       --COMPRAS
      
      SELECT AD_IDANEXO,'DESCRIP PROVEEDOR' AS 'AN_DESCRIPCION',AD_TDOC,AD_SDOC,AD_NDOC,AD_FDOC,
      AC_IDSUBDIARIO +'-'+RIGHT('00'+ CAST(AC_MES AS VARCHAR(2)),2)+ '-'+CAST(AC_NUM_VOUCHER AS VARCHAR(10))AS 'AC_NUM_VOUCHER' ,
      ROUND(((AD_DEBE + AD_HABER)/1.18),2) * (case when  AD_TDOC = 'NC' then -1 else 1 end)   AS   'BASE',
      ROUND((AD_DEBE + AD_HABER) - (((AD_DEBE + AD_HABER)/1.18)),2) * (case when  AD_TDOC = 'NC' then -1 else 1 end)  AS 'IGV',
      (AD_DEBE + AD_HABER)  * (case when  AD_TDOC = 'NC' then -1 else 1 end)  AS 'TOTAL'
      FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB 
      WHERE AD_TANEXO = 2 AND AC_ANHO = @P_ANHO AND AC_IDSUBDIARIO = '01'
      AND AD_IDANEXO IN
      (
      SELECT AD_IDANEXO  
      FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB 
      WHERE AD_TANEXO = 2 AND AC_ANHO = @P_ANHO AND AC_IDSUBDIARIO = '01'
      GROUP BY AD_IDANEXO
      HAVING  SUM(ROUND(((AD_HABER - AD_DEBE )/1.18),2)) > @P_TOPE 
      )    
     
       
 END ELSE BEGIN          
       
     SELECT AD_IDANEXO,'DESCRIP CLIENTE' AS 'AN_DESCRIPCION',AD_TDOC,AD_SDOC,AD_NDOC,AD_FDOC,
      AC_IDSUBDIARIO +'-'+RIGHT('00'+ CAST(AC_MES AS VARCHAR(2)),2)+ '-'+CAST(AC_NUM_VOUCHER AS VARCHAR(10))AS 'AC_NUM_VOUCHER' ,
      ROUND(((AD_DEBE + AD_HABER)/1.18),2) * (case when  AD_TDOC = 'NC' then -1 else 1 end)   AS   'BASE',
      ROUND((AD_DEBE + AD_HABER) - (((AD_DEBE + AD_HABER)/1.18)),2) * (case when  AD_TDOC = 'NC' then -1 else 1 end)  AS 'IGV',
      (AD_DEBE + AD_HABER)  * (case when  AD_TDOC = 'NC' then -1 else 1 end)  AS 'TOTAL'
      FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB 
      WHERE AD_TANEXO = 1 AND AC_ANHO = @P_ANHO AND AC_IDSUBDIARIO = '02'
      AND AD_IDANEXO IN
      (
      SELECT AD_IDANEXO  
      FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB 
      WHERE AD_TANEXO = 1 AND AC_ANHO = @P_ANHO AND AC_IDSUBDIARIO = '02'
      GROUP BY AD_IDANEXO
      HAVING  SUM(ROUND(((AD_DEBE - AD_HABER)/1.18),2)) > @P_TOPE 
      )    
       
       
 END 

