create PROC CO_SP_U_PARAMETROS  
@P_IGV VARCHAR(50),  
@P_DIF_GAN VARCHAR(50),   
@P_DIF_PER VARCHAR(50),  
@P_RETEN_RH VARCHAR(50),  
@P_BASE_HONO VARCHAR(50)  ,
@P_ISC VARCHAR(50)  
AS  
  
UPDATE CO_TB_PARAMETROS SET   
CTA_IGV = @P_IGV,  
CTA_DIF_GAN = @P_DIF_GAN,  
CTA_DIF_PER = @P_DIF_PER,  
CTA_RETEN_RH = @P_RETEN_RH,  
CTA_BASE_HONO = @P_BASE_HONO,
CTA_ISC = @P_ISC