

CREATE PROC [dbo].[CO_SP_S_PLANCTAS]
@P_PERIODO INT = 2013
AS

SELECT  PC_NUM_CTA,PC_DES_CTA,PC_IDMONEDA,PC_IDTIPO_MOV,PC_IDTIPO_ANEXO,PC_PERIODO,PC_ES_CC ,PC_DES_D,PC_DES_H,PC_ES_EFE,PC_ES_CTA,PC_ES_MP
FROM CO_TB_PLANCTAS 
WHERE PC_PERIODO = @P_PERIODO
ORDER BY PC_NUM_CTA

