

CREATE PROC [dbo].[CO_SP_I_ASIENTO_CAB]  
@P_IDSUBDIARIO VARCHAR(2),  
@P_NUM_VOUCHER INT,  
@P_ANHO INT,  
@P_MES INT,  
@P_FEC_VOUCHER DATETIME,  
@P_IDMONEDA INT,  
@P_DEBE FLOAT,  
@P_HABER FLOAT,  
@P_ESTADO INT,  
@P_GLOSA_VOU VARCHAR(100),  
@P_ES_INTERFACE INT  ,
@P_IDPLANILLA VARCHAR(6)
AS  
  
INSERT INTO CO_TB_ASIENTO_CAB(AC_IDSUBDIARIO,AC_NUM_VOUCHER,AC_ANHO,AC_MES,AC_FEC_VOUCHER,AC_IDMONEDA,AC_DEBE,  
AC_HABER,AC_ESTADO,AC_GLOSA_VOU,AC_ES_INTERFACE,AC_IDPLANILLA)  
VALUES(@P_IDSUBDIARIO ,@P_NUM_VOUCHER ,@P_ANHO ,@P_MES ,@P_FEC_VOUCHER ,@P_IDMONEDA ,  
@P_DEBE ,@P_HABER ,@P_ESTADO,@P_GLOSA_VOU ,@P_ES_INTERFACE,@P_IDPLANILLA)  
  
SELECT @@IDENTITY  


