

CREATE PROC [dbo].[CO_SP_S_CAJA_EGRE_DET]
@P_ID VARCHAR(6) = '000003'
AS
SELECT A.*,B.ACCOUNT FROM RECEIVABLE_LIST_LINE_PAY A INNER JOIN TYPE_RECEIVE_PAY B ON A.REC_ID = B.RECEIVE_ID
WHERE  ID = @P_ID
ORDER BY ITEM


