CREATE  PROC [DBO].[CO_SP_GET_ASIENTOS_EDIT]    
@P_ID BIGINT = 466,    
@P_IDSUBDIARIO VARCHAR(2)='03',    
@P_ANHO INT = 2013,    
@P_MES INT = 2    
AS    
    
SELECT * FROM CO_TB_ASIENTO_CAB    
WHERE AC_ID = @P_ID     
AND AC_IDSUBDIARIO = @P_IDSUBDIARIO    
AND AC_ANHO = @P_ANHO    
AND AC_MES = @P_MES    
    
SELECT AD_IDCAB,AD_SECUENCIA,AD_CUENTA,AD_TANEXO,AD_IDANEXO,AD_TDOC,AD_SDOC,AD_NDOC,    
CONVERT (CHAR(10), AD_FDOC, 103) AS 'AD_FDOC',    
CONVERT (CHAR(10), AD_VDOC, 103) AS 'AD_VDOC',    
AD_DEBE,AD_HABER,AD_TCAM,AD_SEC_ORI_DES,AD_IDCC,AD_ES_DESTINO,AD_IDMEDIOPAGO,AD_MONTO_ORI,AD_PORCE_DESTINO,    
AD_ES_CONCI,AD_ANHO_CONI,AD_MES_CONCI,AD_ES_INAFECTO,AD_IDMONEDA,AD_TDOC_REF,AD_SDOC_REF,AD_NDOC_REF,    
CONVERT (CHAR(10), AD_FDOC_REF, 103) AS 'AD_FDOC_REF',    
CONVERT (CHAR(10), AD_VDOC_REF, 103) AS 'AD_VDOC_REF',    
B.PC_DES_CTA    ,AD_GLOSA
FROM CO_TB_ASIENTO_DET A INNER JOIN CO_TB_PLANCTAS B ON A.AD_CUENTA = B.PC_NUM_CTA     
WHERE AD_IDCAB = @P_ID AND B.PC_PERIODO = @P_ANHO    
ORDER BY AD_SECUENCIA  