CREATE PROC [dbo].[CO_SP_S_COMPROBA_COMPRAS]    
@P_AYO INT = 2013,    
@P_MES INT = 7    
AS    
    
SELECT VENDOR_ID,REFER_DOCUMENT_TYPE,SERIE,REFER_DOCUMENT_NUMBER,DOCUMENT_DATE,EXPIRATION_DATE,    
(CASE WHEN CURRENCY_TYPE = 'MN' THEN 1 ELSE 2 END) AS 'CURRENCY_TYPE',    
AMOUNT,AMOUNT_TAX,AMOUNT_SALES ,SELL_RATE,NAME_FACT,a.ID  ,  
ISNULL(ACCOUNT_LOCAL,'') AS 'CTA42_SOLES'  ,  
ISNULL(ACCOUNT_EXTERNAL,'') AS 'CTA42_DOLAR'  
FROM PURCHASE_FACT_SUPPLIER  a inner join vendor b on a.VENDOR_ID = b.id  
WHERE YEAR(DOCUMENT_DATE)= @P_AYO AND MONTH(DOCUMENT_DATE)= @P_MES    
ORDER BY DOCUMENT_DATE,REFER_DOCUMENT_NUMBER    