CREATE PROC [DBO].[CO_SP_S_DETALLE_COMPRAS]    
@P_ID VARCHAR(13) = '0001811',    
@P_PERIODO INT = 2013    
AS    
    
SELECT A.*,B.ACCOUNT_PAY AS 'CUENTA60' ,PC_DES_D,PC_DES_H    
FROM PURCHASE_FACT_SUPPLIER_L A     
INNER JOIN PART B ON A.PART_ID = B.ID    
INNER JOIN CO_TB_PLANCTAS C  ON B.ACCOUNT_PAY = C.PC_NUM_CTA     
WHERE A.ID = @P_ID AND C.PC_PERIODO = @P_PERIODO    
ORDER BY CAST(ITEM AS INT)    
