create PROC CO_SP_S_BI_CTA12  
@P_PERIODO INT = 2013  
AS  
  
SELECT AD_CUENTA,C.BUSINESS,C.VAT_REGISTRATION,C.NAME,  
SUM(AD_DEBE) - SUM(AD_HABER) AS SALDO,  
MIN(AD_FDOC) AS FECHA_EMISION    
FROM   
CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB  
INNER JOIN ANNEXED C ON B.AD_IDANEXO = C.ID 
  
WHERE AC_ANHO = @P_PERIODO   
--AND AC_IDEMPRESA = @P_EMPRESA  
AND AC_ESTADO = 1  
AND C.TYPE = 1
AND AD_CUENTA LIKE '12%'  
GROUP BY AD_CUENTA,C.BUSINESS,C.VAT_REGISTRATION,C.NAME
HAVING SUM(AD_DEBE) <> SUM(AD_HABER)  
ORDER BY 1  