 
    
    
    
CREATE PROC [dbo].[CO_SP_S_COMPROBA_VENTAS]    
@P_AYO INT = 2013,    
@P_MES INT = 2    
AS    
    
SELECT DOCUMENT_ID,NUMBER_SERIE,NUMBER_DOCUMENT,DOCUMENT_DATE,CADUCATE_DATE,CUSTOMER_ID,    
ABS(AMOUNT) AS 'AMOUNT',SELL_RATE,    
(CASE WHEN CURRENCY_ID='MN' THEN 1 ELSE 2 END) AS 'CURRENCY_ID',    
A.COMMENT,ABS(AMOUNT_TAX) AS 'AMOUNT_TAX',    
A.STATUS,CUSTOMER_NAME ,CAST(0 AS BIT ) AS 'CONTA',   
ISNULL(ACCOUNT_LOCAL,'') AS 'CTA12_SOLES'  ,  
ISNULL(ACCOUNT_EXTERNAL,'') AS 'CTA12_DOLAR'  ,isnull(ISC,0) as 'ISC'
  
FROM RECEIVABLE A INNER JOIN CUSTOMER B ON A.CUSTOMER_ID = B.ID    
WHERE YEAR(DOCUMENT_DATE)= @P_AYO AND MONTH(DOCUMENT_DATE)= @P_MES    
ORDER BY DOCUMENT_DATE,NUMBER_DOCUMENT    