create PROC CO_SP_S_BI_CTA14    
@P_PERIODO INT = 2013    
AS    
    
SELECT AD_CUENTA,ISNULL(C.BUSINESS,0)AS 'AN_TIPO_DOC',C.VAT_REGISTRATION,
ISNULL(C.NAME,PC_DES_CTA) AS 'AN_DESCRIPCION',    
SUM(AD_DEBE) - SUM(AD_HABER) AS SALDO,    
MIN(AD_FDOC) AS FECHA_EMISION      
FROM     
CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
LEFT JOIN ANNEXED C ON B.AD_IDANEXO = C.ID    
INNER JOIN CO_TB_PLANCTAS D ON B.AD_CUENTA = D.PC_NUM_CTA     
WHERE AC_ANHO = @P_PERIODO     
--AND AC_IDEMPRESA = @P_EMPRESA    
--AND D.PC_IDEMPRESA = @P_EMPRESA    
AND D.PC_PERIODO = @P_PERIODO     
AND AC_ESTADO = 1    
AND AD_CUENTA LIKE '14%'    
--AND AC_IDSUBDIARIO <> '11'  
GROUP BY AD_CUENTA,ISNULL(C.BUSINESS,0),C.VAT_REGISTRATION,ISNULL(C.NAME,PC_DES_CTA)
--HAVING SUM(AD_DEBE) <> SUM(AD_HABER)    
ORDER BY 1 