

CREATE PROC [dbo].[CO_SP_I_SUBDIARIO]
@P_ID	VARCHAR	(2),
@P_DESCRIPCION	VARCHAR(100),
@P_ABREVIATURA	VARCHAR	(10),
@P_ES_APER	INT	,
@P_ES_CIER	INT	,
@P_ISTATUS	INT	,
@P_IDOPERACION	INT	,
@P_ES_DIFCAM	INT	

AS

INSERT INTO CO_TB_SUBDIARIO(SD_ID,SD_DESCRIPCION,SD_ABREVIATURA,SD_ES_APER,SD_ES_CIER,SD_ISTATUS,SD_IDOPERACION,SD_ES_DIFCAM)
VALUES(@P_ID	,@P_DESCRIPCION	,@P_ABREVIATURA	,@P_ES_APER	,@P_ES_CIER	,@P_ISTATUS	,@P_IDOPERACION,@P_ES_DIFCAM)	


