

   
CREATE PROC [dbo].[CO_SP_S_BG_1]    
@PIDCLASE INT = 1,  --CODIGO DE CLASE  
@PIDGRUPO INT = 1,  --CODIGODE GRUPO  
@PCUENTA VARCHAR(10)='10',  --NUMERO DE CUENTA CONTABLE  
@PANHO INT = 2011,   --NUMERO DE AÑO  
@PMES INT = 2,    --NUMERO DE MES  
@PMENSUAL INT = 1   --INDICADOR FLAG SI ES MENSUAL O ACUMULADO  
AS    
DECLARE @IMPOR NUMERIC(20,2)    
DECLARE @NOM_CLASE VARCHAR(100)    
DECLARE @NOM_GRUPO VARCHAR(100)    
DECLARE @NOM_CUENTA VARCHAR(100)    
DECLARE @TIT_MOV VARCHAR(100)    
    
IF @PMENSUAL = 1 BEGIN  
  
 SELECT @IMPOR =(CASE WHEN @PIDCLASE BETWEEN 1 AND 1 THEN  SUM(B.AD_DEBE)-SUM(B.AD_HABER) ELSE SUM(B.AD_HABER)-SUM(B.AD_DEBE) END)     
 FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
 WHERE A.AC_ANHO = @PANHO AND AC_MES = @PMES 
 AND LEFT(AD_CUENTA,LEN(@PCUENTA))= @PCUENTA    
 GROUP BY LEFT(AD_CUENTA,LEN(@PCUENTA))    
    
END ELSE BEGIN  
  
 SELECT @IMPOR =(CASE WHEN @PIDCLASE BETWEEN 1 AND 1 THEN  SUM(B.AD_DEBE)-SUM(B.AD_HABER) ELSE SUM(B.AD_HABER)-SUM(B.AD_DEBE) END)     
 FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
 WHERE A.AC_ANHO = @PANHO AND AC_MES <= @PMES 
 AND LEFT(AD_CUENTA,LEN(@PCUENTA))= @PCUENTA    
 GROUP BY LEFT(AD_CUENTA,LEN(@PCUENTA))    
  
END  
    
SET @NOM_CLASE = (SELECT CBG_DESCRIPCION FROM CO_TB_CLASES_BG WHERE CBG_ID = @PIDCLASE)    
SET @NOM_GRUPO = (SELECT GBG_DESCRIPCION FROM CO_TB_GRUPOS_BG WHERE GBG_ID = @PIDGRUPO)    
SET @NOM_CUENTA = (SELECT PC_DES_CTA FROM CO_TB_PLANCTAS WHERE PC_NUM_CTA = @PCUENTA AND PC_PERIODO = @PANHO)    
    
IF @PIDCLASE = 1 BEGIN SET @TIT_MOV = 'TOTAL DEL ACTIVO' END    
IF @PIDCLASE = 2 BEGIN SET @TIT_MOV = 'TOTAL DEL PASIVO' END    
IF @PIDCLASE = 3 BEGIN SET @TIT_MOV = 'TOTAL DEL PATRIMONIO' END    
    
INSERT INTO CO_TB_REP_BG10(RB_IDAREA,RB_NOAREA,RB_IDMOD,RB_NOMOD,RB_NUCUENTA,RB_NOCUENTA,RB_IMPORTE,RB_TIT_MOV)    
VALUES(@PIDCLASE,@NOM_CLASE,@PIDGRUPO,@NOM_GRUPO, @PCUENTA,@NOM_CUENTA,ISNULL(@IMPOR,0),@TIT_MOV)  
  
  



