

CREATE PROC [dbo].[CO_SP_S_EXISTE_NUM_VOU]
@P_NUM_VOU VARCHAR(20)='2',
@P_IDSUBDIARIO VARCHAR(2)='01',
@P_ANHO INT = 2013,
@P_MES INT = 5
AS

SELECT ISNULL(COUNT(*),0) FROM CO_TB_ASIENTO_CAB
WHERE AC_NUM_VOUCHER = @P_NUM_VOU
AND AC_IDSUBDIARIO = @P_IDSUBDIARIO
AND AC_ANHO = @P_ANHO
AND AC_MES = @P_MES 


