




create PROC [dbo].[CO_SP_S_SALDOCTA_SOL]      
@P_CUENTA VARCHAR(20)='104125',      
@P_AYO INT = 2012,      
@P_MES INT = 1
AS      
      
SELECT   (ISNULL(SUM(AD_DEBE),0)- ISNULL(SUM(AD_HABER),0)) AS 'SALDO'      
FROM CO_TB_ASIENTO_CAB a
INNER JOIN CO_TB_ASIENTO_DET b ON a.AC_ID = b.AD_IDCAB  
WHERE AC_ANHO = @P_AYO AND AC_MES <= @P_MES 
AND AD_CUENTA = @P_CUENTA AND AC_ESTADO = 1




