

CREATE PROC [dbo].[CO_SP_I_CTA_ANT_MES]    
@P_ANHO INT = 2013,    
@P_MES INT = 3,    
@P_PC VARCHAR(100) = 'OMS'    
AS    

DELETE FROM CO_TB_CTAS_ANT_MES_TMP WHERE CA_PC = @P_PC 

INSERT INTO CO_TB_CTAS_ANT_MES_TMP(CA_CTA,CA_PC)    

SELECT DISTINCT AD_CUENTA,@P_PC   
FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB         
WHERE AC_MES <= @P_MES AND AC_ANHO = @P_ANHO 


