

CREATE PROC [dbo].[CO_SP_A_ASIENTO_CAB]
@P_ID BIGINT = 0,
@P_IDSUBDIARIO VARCHAR(2)='01',
@P_ANHO INT = 2013,
@P_MES INT = 5
AS

UPDATE CO_TB_ASIENTO_CAB
SET AC_ESTADO = 0,
AC_DEBE = 0,
AC_HABER = 0
WHERE AC_ID = @P_ID 
AND AC_IDSUBDIARIO = @P_IDSUBDIARIO
AND AC_ANHO = @P_ANHO
AND AC_MES = @P_MES

UPDATE CO_TB_ASIENTO_DET SET AD_DEBE = 0,
AD_HABER = 0,
AD_MONTO_ORI = 0
WHERE AD_IDCAB = @P_ID 



