

CREATE PROC [dbo].[CO_SP_GET_ASIENTOS]
@P_IDSUBDIARIO VARCHAR(2)='01',
@P_ANHO INT = 2013,
@P_MES INT = 5
AS

SELECT AC_ID,AC_NUM_VOUCHER,AC_FEC_VOUCHER,
(CASE WHEN AC_IDMONEDA = 1 THEN 'MN' ELSE 'ME' END) AS 'AC_IDMONEDA' ,
AC_DEBE,AC_HABER,
 (case when AC_ESTADO = 1 then 'E' else 'A' end) as 'AC_ESTADO',

AC_GLOSA_VOU,AC_ES_INTERFACE FROM CO_TB_ASIENTO_CAB
WHERE AC_IDSUBDIARIO = @P_IDSUBDIARIO
AND AC_ANHO = @P_ANHO
AND AC_MES = @P_MES
ORDER BY AC_NUM_VOUCHER

