CREATE PROC CO_SP_S_BI_CTA46    
@P_PERIODO INT = 2013        
AS        
        
SELECT AD_CUENTA,ISNULL(C.BUSINESS,0) AS 'AN_TIPO_DOC',C.VAT_REGISTRATION,C.NAME,        
MIN(AD_FDOC) AS FECHA_EMISION      ,    
SUM(AD_HABER) - SUM(AD_DEBE) AS SALDO        
    
FROM         
CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB        
LEFT JOIN ANNEXED C ON B.AD_IDANEXO = C.ID    
        
WHERE AC_ANHO = @P_PERIODO         
AND AC_ESTADO = 1        
AND AD_CUENTA LIKE '46%'        
--and AC_IDSUBDIARIO <> '11'  
GROUP BY AD_CUENTA,ISNULL(C.BUSINESS,0),C.VAT_REGISTRATION,C.NAME      
HAVING SUM(AD_HABER) <> SUM(AD_DEBE)        
ORDER BY 1 