create PROC [DBO].[CO_SP_S_RECI_HONO]    
@P_AYO INT = 2013,    
@P_MES INT = 2    
AS    
    
SELECT VENDOR_ID,REFER_DOCUMENT_TYPE,SERIE,REFER_DOCUMENT_NUMBER,DOCUMENT_DATE,EXPIRATION_DATE,    
(CASE WHEN CURRENCY_TYPE = 'MN' THEN 1 ELSE 2 END) AS 'CURRENCY_TYPE',    
AMOUNT,AMOUNT_TAX,AMOUNT_SALES ,SELL_RATE,NAME_FACT,A.ID  ,  
ISNULL(ACCOUNT_LOCAL,'') AS 'CTA424_SOLES'  ,  
ISNULL(ACCOUNT_EXTERNAL,'') AS 'CTA424_DOLAR'  
FROM PURCHASE_FACT_SUPPLIER  A INNER JOIN VENDOR B ON A.VENDOR_ID = B.ID  
WHERE YEAR(DOCUMENT_DATE)= @P_AYO AND MONTH(DOCUMENT_DATE)= @P_MES AND B.STATUS = 'H' AND A.TYPE = 'RH'
ORDER BY DOCUMENT_DATE,REFER_DOCUMENT_NUMBER    
