

CREATE PROC [dbo].[CO_SP_S_EXIS_COMPROBA_VENTAS]
@P_TD VARCHAR(3),
@P_SD VARCHAR(10),
@P_ND VARCHAR(20),
@P_RUC VARCHAR(15)
AS
SELECT ISNULL(COUNT(*) ,0)
FROM CO_TB_ASIENTO_DET 
WHERE AD_TDOC = @P_TD AND AD_SDOC = @P_SD AND AD_NDOC = @P_ND AND  AD_IDANEXO = @P_RUC

