
CREATE PROC [dbo].[CO_SP_I_ANNEXED]
@P_ID	VARCHAR	(40),
@P_TYPE	VARCHAR	(4),
@P_VAT_REGISTRATION	VARCHAR	(22),
@P_NAME	VARCHAR	(100),
@P_REFERENCE	VARCHAR	(100),
@P_ADDR	VARCHAR	(100),
@P_PHONE	VARCHAR	(30),
@P_REPRESENTATIVE	VARCHAR	(100),
@P_BUSINESS	VARCHAR	(100)

AS

INSERT INTO ANNEXED(ID,TYPE,VAT_REGISTRATION,NAME,REFERENCE,ADDR,PHONE,REPRESENTATIVE,BUSINESS)
VALUES(@P_ID,@P_TYPE,@P_VAT_REGISTRATION,@P_NAME,@P_REFERENCE,@P_ADDR,@P_PHONE,@P_REPRESENTATIVE,@P_BUSINESS)


