CREATE PROC [dbo].[CO_SP_S_PLANCTAS_BYID]    
@P_NUM_CTA VARCHAR(20) = '40111000',    
@P_PERIODO INT  = 2013  
AS    
    
SELECT  PC_NUM_CTA,PC_DES_CTA,PC_IDMONEDA,PC_IDTIPO_MOV,ISNULL(PC_IDTIPO_ANEXO,0) AS 'PC_IDTIPO_ANEXO',  
PC_PERIODO,isnull(PC_ES_CC,0)as 'PC_ES_CC' ,PC_DES_D,PC_DES_H,PC_ES_EFE,PC_ES_CTA,isnull(PC_ES_MP,0)   as 'PC_ES_MP'    
FROM CO_TB_PLANCTAS     
WHERE PC_NUM_CTA = @P_NUM_CTA AND PC_PERIODO = @P_PERIODO
