

CREATE PROC [dbo].[CO_SP_S_SALDOCTA_DOL]      
@P_CUENTA VARCHAR(20)='104125',      
@P_AYO INT = 2012,      
@P_MES INT = 2
AS      
SELECT   (ISNULL(SUM((CASE WHEN AD_DEBE > 0 THEN AD_MONTO_ORI ELSE 0 END)),0) - ISNULL(SUM((CASE WHEN AD_HABER > 0 THEN AD_MONTO_ORI ELSE 0 END)),0)) AS 'SALDO'      
FROM SG_CO_TB_ASIENTO_CAB a     
INNER JOIN SG_CO_TB_ASIENTO_DET b ON AD_IDCAB = AC_ID          
WHERE AC_ANHO = @P_AYO AND AC_MES <= @P_MES 
AND AD_CUENTA = @P_CUENTA AND AC_ESTADO = 1  


