

CREATE PROC [dbo].[CO_SP_S_GRUPOBG_CUENTAS]    
@P_IDGRUPO INT,--CODIGO DE GRUPO    
@P_PERIODO INT  
AS    
  
SELECT GC_IDCUENTA,PC_NUM_CTA,PC_DES_CTA    
FROM CO_TB_GRUPOBG_CUENTAS A INNER JOIN   
   (SELECT * FROM CO_TB_PLANCTAS WHERE PC_PERIODO = @P_PERIODO) B   
 ON A.GC_IDCUENTA = B.PC_NUM_CTA  
WHERE GC_IDGRUPO = @P_IDGRUPO 

