

CREATE PROC [dbo].[CO_SP_S_CAJA_ING_DET]  
@P_ID VARCHAR(6) = '000001'  
AS  
SELECT A.*,B.ACCOUNT FROM RECEIVABLE_LIST_LINE A INNER JOIN TYPE_RECEIVE B ON A.REC_ID = B.RECEIVE_ID  
WHERE  ID = @P_ID  
ORDER BY ITEM  

