


CREATE PROC [dbo].[CO_SP_U_SUBDIARIO]
@P_ID	VARCHAR	(2),
@P_DESCRIPCION	VARCHAR(100),
@P_ABREVIATURA	VARCHAR	(10),
@P_ES_APER	INT	,
@P_ES_CIER	INT	,
@P_ISTATUS	INT	,
@P_IDOPERACION	INT	,
@P_ES_DIFCAM	INT	

AS

UPDATE CO_TB_SUBDIARIO SET SD_DESCRIPCION = @P_DESCRIPCION,
SD_ABREVIATURA = @P_ABREVIATURA,
SD_ES_APER = @P_ES_APER,
SD_ES_CIER = @P_ES_CIER,
SD_ISTATUS = @P_ISTATUS,
SD_IDOPERACION = @P_IDOPERACION,
SD_ES_DIFCAM = @P_ES_DIFCAM
WHERE SD_ID = @P_ID


