

CREATE PROC [dbo].[CO_SP_S_SUBDIARIO_OPE]
@P_IDOPE INT = '01'
AS

SELECT  SD_ID,SD_DESCRIPCION,SD_ABREVIATURA,SD_ES_APER,SD_ES_CIER,SD_ISTATUS,SD_IDOPERACION,SD_ES_DIFCAM 
FROM CO_TB_SUBDIARIO 
WHERE SD_IDOPERACION = @P_IDOPE


