

CREATE PROC [dbo].[CO_SP_S_EXIS_PLANILLA]
@P_SUBDIARIO VARCHAR(2)= '04',
@P_IDPLANILLA VARCHAR(6) = '000003'
AS 
SELECT ISNULL(COUNT(*),0) 
FROM CO_TB_ASIENTO_CAB 
WHERE AC_IDPLANILLA = @P_IDPLANILLA AND AC_IDSUBDIARIO = @P_SUBDIARIO


