



CREATE PROC [dbo].[CO_TB_S_DIFCAMBIO_PROVE]  
@P_AYO INT = 2012,  
@P_TC_FINMES FLOAT = 2.69  
AS  
  
  
--CREAMOS SUNA TABLA TEMPORAL(VARIABLE TIPO TABLA)  
DECLARE @RESULTADO TABLE(CUENTA VARCHAR(10), DOCUMENTO VARCHAR(20), ANEXO VARCHAR(200), GANANCIA FLOAT,PERDIDA FLOAT,ANEXOID INT)  
  
  
  
  
DECLARE @P_ID_DET INT  
  
--_________________________________________  
DECLARE C_DOCPEN CURSOR  
FOR  
SELECT   

min(cast(AD_IDCAB as varchar(10))+ AD_IDANEXO+AD_TDOC+AD_SDOC+AD_NDOC)

FROM CO_TB_ASIENTO_DET A           
INNER JOIN CO_TB_ASIENTO_CAB B ON A.AD_IDCAB = B.AC_ID          
WHERE   
AC_ANHO = @P_AYO  
AND AD_TCAM > 0  
AND AC_IDSUBDIARIO NOT IN ('04','05')  
AND A.AD_CUENTA IN( SELECT PC_NUM_CTA FROM CO_TB_PLANCTAS WHERE PC_PERIODO = @P_AYO AND PC_IDTIPO_ANEXO = 2)  
GROUP BY AD_IDANEXO,AD_TDOC,AD_SDOC,AD_NDOC          
HAVING SUM(AD_DEBE)-SUM(AD_HABER)<>0       
  
  
OPEN C_DOCPEN  
FETCH NEXT FROM C_DOCPEN  
INTO @P_ID_DET  
WHILE @@FETCH_STATUS = 0  
BEGIN  
  
  
--DATOS DE CALCULO  
DECLARE @IMPORTE_PROVI_DOL FLOAT  
DECLARE @IMPORTE_PROVI_SOL FLOAT  
DECLARE @IMPORTE_ACTUAL_SOL FLOAT  
DECLARE @DIFERENCIA FLOAT  
  
SET @IMPORTE_PROVI_DOL = (SELECT AD_MONTO_ORI FROM CO_TB_ASIENTO_DET WHERE cast(AD_IDCAB as varchar(10))+ AD_IDANEXO+AD_TDOC+AD_SDOC+AD_NDOC = @P_ID_DET)  
SET @IMPORTE_PROVI_SOL = (SELECT (CASE WHEN AD_DEBE > 0 THEN AD_DEBE ELSE AD_HABER END)  FROM CO_TB_ASIENTO_DET WHERE cast(AD_IDCAB as varchar(10))+ AD_IDANEXO+AD_TDOC+AD_SDOC+AD_NDOC = @P_ID_DET)  
SET @IMPORTE_ACTUAL_SOL = ROUND(@IMPORTE_PROVI_DOL * @P_TC_FINMES,2)  
  
SET @DIFERENCIA =ROUND( @IMPORTE_PROVI_SOL - @IMPORTE_ACTUAL_SOL,2)  
  
  
  
  
--DATOS DEL DETALLE  
  
DECLARE @CUENTA VARCHAR(10)  
DECLARE @DOCUMENTO VARCHAR(20)  
DECLARE @ANEXO VARCHAR(100)  
DECLARE @ANEXOID INT  
  
SET @CUENTA = (SELECT AD_CUENTA FROM CO_TB_ASIENTO_DET WHERE cast(AD_IDCAB as varchar(10))+ AD_IDANEXO+AD_TDOC+AD_SDOC+AD_NDOC = @P_ID_DET)  
SET @DOCUMENTO = (SELECT AD_TDOC+' - '+AD_SDOC+' - '+AD_NDOC FROM CO_TB_ASIENTO_DET WHERE cast(AD_IDCAB as varchar(10))+ AD_IDANEXO+AD_TDOC+AD_SDOC+AD_NDOC = @P_ID_DET)  
SET @ANEXOID = (SELECT AD_IDANEXO FROM CO_TB_ASIENTO_DET WHERE cast(AD_IDCAB as varchar(10))+ AD_IDANEXO+AD_TDOC+AD_SDOC+AD_NDOC = @P_ID_DET)  
SET @ANEXO = (SELECT ID+' - '+NAME FROM VENDOR WHERE ID = @ANEXOID)  
  
INSERT INTO @RESULTADO SELECT @CUENTA,@DOCUMENTO,@ANEXO,ABS((CASE WHEN  @DIFERENCIA > 0 THEN @DIFERENCIA ELSE 0 END)),  
       ABS((CASE WHEN  @DIFERENCIA < 0 THEN @DIFERENCIA ELSE 0 END)),@ANEXOID  
  
  
  
--PRINT @P_ID_DET   
  
FETCH NEXT FROM C_DOCPEN  
INTO @P_ID_DET  
END  
CLOSE C_DOCPEN  
DEALLOCATE C_DOCPEN  
  
  
  
SELECT * FROM @RESULTADO ORDER BY DOCUMENTO

