CREATE PROCEDURE CORREGIR_DOCUMENTOS_EN_RECEIVABLE_LINE
AS

DECLARE @NUMBER_DOCUMENT VARCHAR(10)
DECLARE @DOCUMENT_ID VARCHAR(5)
DECLARE @WAREHOUSE_ID VARCHAR(2)
DECLARE @NUMBER_REF VARCHAR(10)
DECLARE @DOCUMENT_ID_DOS VARCHAR(5)
DECLARE @WAREHOUSE_ID_DOS VARCHAR(2)
DECLARE @N FLOAT

DECLARE CURSOR1 CURSOR FOR
SELECT DOCUMENT_ID,NUMBER_DOCUMENT,WAREHOUSE_ID FROM RECEIVABLE_LINE WHERE  COMISION IS NULL
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 
INTO @DOCUMENT_ID,@NUMBER_DOCUMENT,@WAREHOUSE_ID
WHILE @@FETCH_STATUS=0
BEGIN
	SELECT TOP 1 @N=(COMISION) FROM RECEIVABLE_LINE WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@WAREHOUSE_ID AND COMISION IS NOT NULL AND DOCUMENT_ID=@DOCUMENT_ID
	IF @N IS NOT NULL
	BEGIN
		INSERT INTO NUM_DOC_ELIMINADOS(DOCUMENT_ID,NUMBER_DOCUMENT) VALUES(@DOCUMENT_ID,@NUMBER_DOCUMENT)
		UPDATE RECEIVABLE_LINE SET COMISION=@N WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@WAREHOUSE_ID  AND COMISION IS NULL AND DOCUMENT_ID=@DOCUMENT_ID
	END
	ELSE
	BEGIN
		SELECT @NUMBER_REF=NUMBER_REF,@DOCUMENT_ID_DOS=DOCUMENT_ID,@WAREHOUSE_ID_DOS=WAREHOUSE_ID FROM RECEIVABLE WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@WAREHOUSE_ID AND DOCUMENT_ID=@DOCUMENT_ID
		SELECT TOP 1 @N=COMISION FROM RECEIVABLE_LINE WHERE NUMBER_DOCUMENT=@NUMBER_REF AND WAREHOUSE_ID=@WAREHOUSE_ID_DOS AND DOCUMENT_ID=@DOCUMENT_ID_DOS
		INSERT INTO NUM_DOC_ELIMINADOS(DOCUMENT_ID,NUMBER_DOCUMENT) VALUES(@DOCUMENT_ID,@NUMBER_DOCUMENT)
		UPDATE RECEIVABLE_LINE SET COMISION=@N WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@WAREHOUSE_ID AND COMISION IS NULL AND DOCUMENT_ID=@DOCUMENT_ID
	END
	FETCH NEXT FROM CURSOR1
	INTO @DOCUMENT_ID,@NUMBER_DOCUMENT,@WAREHOUSE_ID
END
CLOSE CURSOR1
DEALLOCATE CURSOR1