CREATE PROCEDURE CORREGIR_NC
@ALMACEN VARCHAR(5)
AS

DECLARE @NUMBER_DOCUMENT VARCHAR(10)
DECLARE @NUMBER_REF VARCHAR(10)
DECLARE @N FLOAT

DECLARE CURSOR1 CURSOR FOR
SELECT NUMBER_DOCUMENT FROM RECEIVABLE_LINE WHERE DOCUMENT_ID='NC' AND WAREHOUSE_ID=@ALMACEN AND  COMISION IS NULL
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 
INTO @NUMBER_DOCUMENT
WHILE @@FETCH_STATUS=0
BEGIN
	SELECT TOP 1 @N=(COMISION) FROM RECEIVABLE_LINE WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@ALMACEN AND COMISION IS NOT NULL
	IF @N IS NOT NULL
	BEGIN
		UPDATE RECEIVABLE_LINE SET COMISION=@N WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@ALMACEN  AND COMISION IS NULL
	END
	ELSE
	BEGIN
		SELECT @NUMBER_REF=NUMBER_REF FROM RECEIVABLE WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@ALMACEN
		SELECT TOP 1 @N=COMISION FROM RECEIVABLE_LINE WHERE NUMBER_DOCUMENT=@NUMBER_REF AND WAREHOUSE_ID=@ALMACEN
		UPDATE RECEIVABLE_LINE SET COMISION=@N WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@ALMACEN AND COMISION IS NULL
	END
	FETCH NEXT FROM CURSOR1
	INTO @NUMBER_DOCUMENT
END
CLOSE CURSOR1
DEALLOCATE CURSOR1