
CREATE PROC CX_SP_I_CUSTOMER_BALANCE
@P_CUSTOMER_ID VARCHAR(11),
@P_DOCUMENT_ID VARCHAR(2),
@P_NUMBER_DOC VARCHAR(10),
@P_DOC_DATE DATETIME,
@P_CADUCATE_DATE SMALLDATETIME,
@P_DOCUMENT_REF VARCHAR(2),
@P_NUMBER_REF VARCHAR(10),
@P_SALES_ID VARCHAR(2),
@P_AMOUNT FLOAT,
@P_AMOUNT_BALANCE FLOAT,
@P_CURRENCY_ID VARCHAR(2),
@P_SELL_RATE FLOAT,
@P_IS_DR_CR VARCHAR(1),
@P_STATUS VARCHAR(1),
@P_CREATE_DATE DATETIME,
@P_LAST_MODIFIED DATETIME,
@P_USER_ID VARCHAR(8),
@P_ACCOUNT VARCHAR(21),
@P_AMOUNT_COMM FLOAT,
@P_TYPE_REC VARCHAR(2),
@P_REFERENCE_DATE DATETIME,
@P_IS_CHECK_DIF VARCHAR(1),
@P_AMOUNT_BALANCE_INI FLOAT,
@P_TERMS VARCHAR(4),
@P_PLACE_SALES VARCHAR(2),
@P_BANK_ID VARCHAR(2),
@P_BANK_DESCRIPTION VARCHAR(100),
@P_AMOUNT_PER FLOAT,
@P_PERCENT_PER FLOAT,
@P_ACCOUNT_PER VARCHAR(18),
@P_CUST_AUTO CHAR(1),
@P_SERIE_AUX VARCHAR(50),
@P_NUM_DOC_AUX VARCHAR(50)
AS

INSERT INTO CUSTOMER_BALANCE(CUSTOMER_ID
,DOCUMENT_ID
,NUMBER_DOC
,DOC_DATE
,CADUCATE_DATE
,DOCUMENT_REF
,NUMBER_REF
,SALES_ID
,AMOUNT
,AMOUNT_BALANCE
,CURRENCY_ID
,SELL_RATE
,IS_DR_CR
,STATUS
,CREATE_DATE
,LAST_MODIFIED
,USER_ID
,ACCOUNT
,AMOUNT_COMM
,TYPE_REC
,REFERENCE_DATE
,IS_CHECK_DIF
,AMOUNT_BALANCE_INI
,TERMS
,PLACE_SALES
,BANK_ID
,BANK_DESCRIPTION
,AMOUNT_PER
,PERCENT_PER
,ACCOUNT_PER
,CUST_AUTO
,SERIE_AUX
,NUM_DOC_AUX)
VALUES(@P_CUSTOMER_ID ,
@P_DOCUMENT_ID ,
@P_NUMBER_DOC ,
@P_DOC_DATE ,
@P_CADUCATE_DATE ,
@P_DOCUMENT_REF ,
@P_NUMBER_REF ,
@P_SALES_ID ,
@P_AMOUNT ,
@P_AMOUNT_BALANCE ,
@P_CURRENCY_ID ,
@P_SELL_RATE ,
@P_IS_DR_CR ,
@P_STATUS ,
@P_CREATE_DATE ,
@P_LAST_MODIFIED ,
@P_USER_ID ,
@P_ACCOUNT ,
@P_AMOUNT_COMM ,
@P_TYPE_REC ,
@P_REFERENCE_DATE ,
@P_IS_CHECK_DIF ,
@P_AMOUNT_BALANCE_INI ,
@P_TERMS ,
@P_PLACE_SALES,
@P_BANK_ID ,
@P_BANK_DESCRIPTION ,
@P_AMOUNT_PER ,
@P_PERCENT_PER ,
@P_ACCOUNT_PER ,
@P_CUST_AUTO ,
@P_SERIE_AUX ,
@P_NUM_DOC_AUX )