CREATE PROC CX_SP_S_RECEIVABLE_DET  
@P_ID VARCHAR(6)='000113'  
AS  
SELECT ITEM,TYPE_DOC,NUMBER_DOC,REC_ID,DATE as 'FECHA_COB',AMOUNT,CURRENCY_ID,SELL_RATE,COMMENT  
FROM RECEIVABLE_LIST_LINE  
WHERE ID = @P_ID  
order by ITEM