CREATE PROC CX_SP_S_RECEIVABLE_ID
AS
DECLARE @P_ULTIMO VARCHAR(6)
SET @P_ULTIMO = (SELECT ISNULL(MAX(ID),0) FROM RECEIVABLE_LIST)
SET @P_ULTIMO = RIGHT('000000' + cast((CAST(@P_ULTIMO AS INT) + 1) as varchar(6)),6)
SELECT @P_ULTIMO