CREATE PROC CX_SP_I_PART  
@P_ID VARCHAR(20),  
@P_ID_FAB VARCHAR(40),  
@P_FAMILY VARCHAR(8),  
@P_UNIT_OF_MEASUREMENT VARCHAR(6),  
@P_SERIES VARCHAR(1),  
@P_IS_STOCKED VARCHAR(1),  
@P_IS_LOT VARCHAR(1),  
@P_VAT_POR FLOAT,  
@P_IS_VAT BIT,  
@P_ACCOUNT_INTERNAL_ID VARCHAR(50),  
@P_ACCOUNT_INV VARCHAR(50),  
@P_ACCOUNT_PAY VARCHAR(50),  
@P_ISCPOR FLOAT,  
@P_TIPOISC INT  ,
@P_MODEL VARCHAR(8)
AS  
INSERT INTO PART(ID ,ID_FAB ,FAMILY ,UNIT_OF_MEASUREMENT ,SERIES ,IS_STOCKED ,IS_LOT ,VAT_POR ,  
IS_VAT ,ACCOUNT_INTERNAL_ID ,ACCOUNT_INV ,ACCOUNT_PAY ,ISCPOR,TIPOISC,MODEL)  
VALUES(@P_ID ,@P_ID_FAB ,@P_FAMILY ,@P_UNIT_OF_MEASUREMENT ,@P_SERIES ,@P_IS_STOCKED ,@P_IS_LOT ,  
@P_VAT_POR ,@P_IS_VAT ,@P_ACCOUNT_INTERNAL_ID ,@P_ACCOUNT_INV ,@P_ACCOUNT_PAY ,@P_ISCPOR,@P_TIPOISC,@P_MODEL)