CREATE PROC CX_SP_U_SALES_REP
@P_ID	VARCHAR	(2),
@P_NAME	VARCHAR	(30),
@P_ADDR	VARCHAR	(100),
@P_PHONE	VARCHAR	(8),
@P_EMAIL	VARCHAR	(30),
@P_VAT_REGISTRATION	VARCHAR	(11)
AS

UPDATE SALES_REP SET NAME= @P_NAME, 
ADDR = @P_ADDR, 
PHONE = @P_PHONE, 
EMAIL = @P_EMAIL,
VAT_REGISTRATION=@P_VAT_REGISTRATION
WHERE ID = @P_ID