
CREATE PROC CX_SP_U_RECEIVABLE_LIST
@P_ID	VARCHAR(6),
@P_DATE	SMALLDATETIME,
@P_AMOUNT	FLOAT,
@P_AMOUNT_US	FLOAT,
@P_AMOUNT_CH_DIF	FLOAT,
@P_AMOUNT_CH_DIF_US	FLOAT,
@P_VOUCHER_ID	VARCHAR(6),
@P_STATUS	VARCHAR(1),
@P_CREATE_DATE	SMALLDATETIME,
@P_USER_ID	VARCHAR(8),
@P_SALES_ID	VARCHAR(2),
@P_VOUCHER_ID_US	VARCHAR(6)
AS
UPDATE RECEIVABLE_LIST SET 
DATE = @P_DATE,AMOUNT = @P_AMOUNT,AMOUNT_US = @P_AMOUNT_US,AMOUNT_CH_DIF = @P_AMOUNT_CH_DIF,
AMOUNT_CH_DIF_US = @P_AMOUNT_CH_DIF_US,VOUCHER_ID = @P_VOUCHER_ID,
STATUS = @P_STATUS,CREATE_DATE = @P_CREATE_DATE,USER_ID = @P_USER_ID,SALES_ID = @P_SALES_ID,
VOUCHER_ID_US = @P_VOUCHER_ID
WHERE ID = @P_ID