
CREATE PROC CX_SP_I_RECEIVABLE_LIST
@P_ID	VARCHAR(6),
@P_DATE	SMALLDATETIME,
@P_AMOUNT	FLOAT,
@P_AMOUNT_US	FLOAT,
@P_AMOUNT_CH_DIF	FLOAT,
@P_AMOUNT_CH_DIF_US	FLOAT,
@P_VOUCHER_ID	VARCHAR(6),
@P_STATUS	VARCHAR(1),
@P_CREATE_DATE	SMALLDATETIME,
@P_USER_ID	VARCHAR(8),
@P_SALES_ID	VARCHAR(2),
@P_VOUCHER_ID_US	VARCHAR(6)
AS
INSERT INTO RECEIVABLE_LIST(ID,DATE,AMOUNT,AMOUNT_US,AMOUNT_CH_DIF,AMOUNT_CH_DIF_US,VOUCHER_ID,
STATUS,CREATE_DATE,USER_ID,SALES_ID,VOUCHER_ID_US)
VALUES(@P_ID,@P_DATE,@P_AMOUNT,@P_AMOUNT_US,@P_AMOUNT_CH_DIF,@P_AMOUNT_CH_DIF_US,@P_VOUCHER_ID,
@P_STATUS,@P_CREATE_DATE,@P_USER_ID,@P_SALES_ID,@P_VOUCHER_ID_US)