CREATE PROC CX_SP_S_U_TYPE_RECEIVE
@P_TYPE VARCHAR(1),
@P_RECEIVE_ID VARCHAR(2),
@P_DESCRIPTION VARCHAR(50),
@P_CURRENCY_ID VARCHAR(2),
@P_ACCOUNT VARCHAR(18),
@P_VENDOR_ID INT,
@P_BANK_ID INT,
@P_USER_ID varchar(8),
@P_DATE SMALLDATETIME,
@P_EFFECTIVE_DATE smalldatetime,
@P_IS_CHECK_DIF INT,
@P_IS_APPL INT,
@P_TRANS_TYPE INT,
@P_IS_CREDIT_CARD INT
AS

UPDATE TYPE_RECEIVE SET 
TYPE = @P_TYPE,
RECEIVE_ID= @P_RECEIVE_ID,
DESCRIPTION= @P_DESCRIPTION,
CURRENCY_ID= @P_CURRENCY_ID,
ACCOUNT= @P_ACCOUNT,
VENDOR_ID= @P_VENDOR_ID,
BANK_ID= @P_BANK_ID,
USER_ID= @P_USER_ID,
DATE= @P_DATE,
EFFECTIVE_DATE= @P_EFFECTIVE_DATE,
IS_CHECK_DIF= @P_IS_CHECK_DIF,
IS_APPL= @P_IS_APPL,
TRANS_TYPE= @P_TRANS_TYPE,
IS_CREDIT_CARD= @P_IS_CREDIT_CARD
WHERE RECEIVE_ID = @P_RECEIVE_ID