CREATE PROC CX_SP_U_ACCOUNT_BANK
@P_BANK_ID VARCHAR(2),
@P_ACCOUNT_BANK_ID VARCHAR(20),
@P_ACCOUNT_BANK_DES VARCHAR(100),
@P_NUMBER_ACCOUNT VARCHAR(18),
@P_CURRENCY_ID VARCHAR(2),
@P_TYPE_DOC VARCHAR(2)
AS

UPDATE ACCOUNT_BANK SET
ACCOUNT_BANK_ID = @P_ACCOUNT_BANK_ID,
ACCOUNT_BANK_DES = @P_ACCOUNT_BANK_DES,
NUMBER_ACCOUNT = @P_NUMBER_ACCOUNT,
CURRENCY_ID = @P_CURRENCY_ID,
TYPE_DOC = @P_TYPE_DOC
WHERE   BANK_ID = @P_BANK_ID
AND ACCOUNT_BANK_ID = @P_ACCOUNT_BANK_ID