CREATE PROC CX_SP_I_LOT
@P_WHO_ID VARCHAR(2),
@P_PART_ID VARCHAR(20),
@P_LOT_ID VARCHAR(20),
@P_QTY_ON_HAND FLOAT,
@P_MANUFACT_DATE DATETIME,
@P_CADUCATE_DATE DATETIME,
@P_COMMENT VARCHAR(255)
AS

INSERT INTO LOT(WHO_ID,PART_ID,LOT_ID,QTY_ON_HAND,MANUFACT_DATE,CADUCATE_DATE,COMMENT)
VALUES(@P_WHO_ID, @P_PART_ID ,@P_LOT_ID ,@P_QTY_ON_HAND ,@P_MANUFACT_DATE ,@P_CADUCATE_DATE ,@P_COMMENT)