CREATE PROC CX_SP_U_NUMBER_DOCUMENT   
@P_TYPE_DOC VARCHAR(2)='NC',  
@P_NUMBER_SERIE VARCHAR(3) = '001'  ,
@P_LAST_NUMBER FLOAT
AS
UPDATE NUMBER_DOCUMENT SET LAST_NUMBER = @P_LAST_NUMBER
WHERE TYPE_DOC = @P_TYPE_DOC AND NUMBER_SERIE = @P_NUMBER_SERIE