CREATE PROC CX_SP_S_SALDO_ALL
AS
SELECT CUSTOMER_ID ,NAME, DOCUMENT_ID,SERIE_AUX,NUM_DOC_AUX,DOC_DATE,CADUCATE_DATE,DOCUMENT_REF,NUMBER_REF,
AMOUNT,AMOUNT_BALANCE_INI,CURRENCY_ID,SELL_RATE
FROM CUSTOMER_BALANCE A INNER JOIN CUSTOMER B ON A.CUSTOMER_ID = B.ID
WHERE AMOUNT <> 0
ORDER BY CUSTOMER_ID,DOC_DATE