CREATE PROC CX_SP_I_SALES_REP
@P_ID	VARCHAR	(2),
@P_NAME	VARCHAR	(30),
@P_ADDR	VARCHAR	(100),
@P_PHONE	VARCHAR	(8),
@P_EMAIL	VARCHAR	(30),
@P_VAT_REGISTRATION	VARCHAR	(11)
AS

INSERT INTO SALES_REP(ID,NAME,ADDR,PHONE,EMAIL,VAT_REGISTRATION)
VALUES(@P_ID,@P_NAME,@P_ADDR,@P_PHONE,@P_EMAIL,@P_VAT_REGISTRATION)