CREATE PROC CX_SP_U_CUSTOMER_BALANCE
@P_CUSTOMER_ID VARCHAR(11),
@P_DOCUMENT_ID VARCHAR(2),
@P_SERIE_AUX VARCHAR(50),
@P_NUM_DOC_AUX VARCHAR(50),
@P_AMOUNT FLOAT
AS
UPDATE CUSTOMER_BALANCE SET AMOUNT = AMOUNT - @P_AMOUNT 
WHERE CUSTOMER_ID = @P_CUSTOMER_ID 
AND DOCUMENT_ID = @P_DOCUMENT_ID 
AND SERIE_AUX = @P_SERIE_AUX 
AND NUM_DOC_AUX = @P_NUM_DOC_AUX