CREATE PROC CX_SP_S_RECEIVABLE_XDATE  
@P_FECHA1 DATE,  
@P_FECHA2 DATE  
AS  
SELECT ID as 'PC_ID',DATE as 'PC_FECHA',AMOUNT as 'PC_MONTO',VOUCHER_ID  as 'PC_VOUCHER'
FROM  RECEIVABLE_LIST   
WHERE DATE BETWEEN @P_FECHA1 AND @P_FECHA2  
ORDER BY ID