CREATE PROC CX_SP_I_VENDOR
@P_ID VARCHAR(11),	
@P_NAME VARCHAR(100),	
@P_VAT_REGISTRATION VARCHAR(11)	,
@P_ADDR VARCHAR(100),
@P_PHONE VARCHAR(30),
@P_EMAIL VARCHAR(50),	
@P_WEBSITE VARCHAR(50),
@P_CONTACT VARCHAR(70),
@P_DOCUMENT_TYPE_PERSON_ID	VARCHAR(2),
@P_TYPE_COMPANY	VARCHAR(2),
@P_ACCOUNT_LOCAL	VARCHAR(50),
@P_ACCOUNT_EXTERNAL VARCHAR(50)
AS
INSERT INTO VENDOR(ID,NAME,VAT_REGISTRATION,ADDR,PHONE,EMAIL,WEBSITE,CONTACT,DOCUMENT_TYPE_PERSON_ID,TYPE_COMPANY,ACCOUNT_LOCAL,ACCOUNT_EXTERNAL)
VALUES(@P_ID,	
@P_NAME,	
@P_VAT_REGISTRATION	,
@P_ADDR,
@P_PHONE,
@P_EMAIL,	
@P_WEBSITE,
@P_CONTACT,
@P_DOCUMENT_TYPE_PERSON_ID	,
@P_TYPE_COMPANY	,
@P_ACCOUNT_LOCAL	,
@P_ACCOUNT_EXTERNAL)