CREATE PROC CX_SP_S_TRANSACTION_TYPE
AS
SELECT  
TYPE_ID,MOV_ID,NAME,IS_VALUED,IS_VENDOR,IS_DOC_REF,IS_AUTHORIZED,IS_CCOST,
IS_ORDER_PURCHASE,IS_COMMENT,IS_WHO,IS_CUSTOMER,IS_ORDER_MANUFACT 
FROM TRANSACTION_TYPE 
ORDER BY TYPE_ID