
CREATE PROC CX_SP_S_CURRENCY_EXCHANGE_XFEC
@P_CURRENCY_DATE DATETIME = '20/01/2014',
@P_CURRENCY_ID VARCHAR(2) = 'ME'
AS
SELECT ISNULL(SELL_RATE,0) AS 'TC'
FROM CURRENCY_EXCHANGE
WHERE CURRENCY_ID = @P_CURRENCY_ID
AND YEAR(CURRENCY_DATE) = YEAR(@P_CURRENCY_DATE)
AND MONTH(CURRENCY_DATE) = MONTH(@P_CURRENCY_DATE)
AND DAY(CURRENCY_DATE) = DAY(@P_CURRENCY_DATE)