CREATE PROC CX_SP_S_DOCUMENT_PLACE_SALES_XSER
@P_PLACE_SALES_ID VARCHAR(2)='00'
AS
SELECT NUMBER_SERIE ,NUMBER_SERIE as 'OTRO' 
FROM DOCUMENT_PLACE_SALES WHERE  PLACE_SALES_ID = @P_PLACE_SALES_ID 
AND DOCUMENT_TYPE='NC'