
CREATE PROC CX_SP_S_SALDO_X_CLIENTE
@P_CUSTOMER_ID VARCHAR(11)='20419016242'
AS

SELECT DOCUMENT_ID,
SERIE_AUX,NUM_DOC_AUX,AMOUNT AS 'MONTO',CURRENCY_ID as 'COD_MON',SELL_RATE as 'TC',DOC_DATE,CADUCATE_DATE,SALES_ID,IS_DR_CR,
DOCUMENT_REF,NUMBER_REF,AMOUNT_BALANCE_INI
FROM CUSTOMER_BALANCE WHERE CUSTOMER_ID = @P_CUSTOMER_ID AND AMOUNT <> 0