  
CREATE PROC CX_SP_S_CARRIER_XID  
@P_ID VARCHAR(11)  
AS  
SELECT ID,
NAME_CARRIER,
ADDR,
PHONE,
VAT_REGISTRATION,
STATUS,
CREATE_DATE,
NAME,
VAT_REGISTRATION_COMP,
ADDR_COMP,
PHONE_COMP,
NUMBER_REGISTRATION,
NUMBER_LICENSE,
MODEL_VEH,
NUMBER_INSCRIP,
NUMBER_DOCUMENT
FROM CARRIER WHERE ID = @P_ID  
ORDER BY NAME