
CREATE PROC CX_SP_S_PART  
AS    
SELECT ID ,DESCRIPTION  
,ID_FAB ,FAMILY ,UNIT_OF_MEASUREMENT ,SERIES ,IS_STOCKED ,IS_LOT ,VAT_POR ,  
IS_VAT ,ACCOUNT_INTERNAL_ID ,ACCOUNT_INV ,ACCOUNT_PAY ,ISCPOR,TIPOISC,MODEL  
FROM PART ORDER BY 2