CREATE PROC CX_SP_S_I_TYPE_RECEIVE
@P_TYPE VARCHAR(1),
@P_RECEIVE_ID VARCHAR(2),
@P_DESCRIPTION VARCHAR(50),
@P_CURRENCY_ID VARCHAR(2),
@P_ACCOUNT VARCHAR(18),
@P_VENDOR_ID INT,
@P_BANK_ID INT,
@P_USER_ID varchar(8),
@P_DATE SMALLDATETIME,
@P_EFFECTIVE_DATE smalldatetime,
@P_IS_CHECK_DIF INT,
@P_IS_APPL INT,
@P_TRANS_TYPE INT,
@P_IS_CREDIT_CARD INT
AS
INSERT INTO TYPE_RECEIVE(TYPE,RECEIVE_ID,DESCRIPTION,CURRENCY_ID,ACCOUNT,VENDOR_ID,BANK_ID,USER_ID,
DATE,EFFECTIVE_DATE,IS_CHECK_DIF,IS_APPL,TRANS_TYPE,IS_CREDIT_CARD)
VALUES(@P_TYPE,@P_RECEIVE_ID,@P_DESCRIPTION,@P_CURRENCY_ID,@P_ACCOUNT,@P_VENDOR_ID,@P_BANK_ID,@P_USER_ID,@P_DATE,
@P_EFFECTIVE_DATE,@P_IS_CHECK_DIF,@P_IS_APPL,@P_TRANS_TYPE,@P_IS_CREDIT_CARD)