CREATE PROC CX_SP_U_LOT
@P_WHO_ID VARCHAR(2),
@P_PART_ID VARCHAR(20),
@P_LOT_ID VARCHAR(20),
@P_QTY_ON_HAND FLOAT,
@P_MANUFACT_DATE DATETIME,
@P_CADUCATE_DATE DATETIME,
@P_COMMENT VARCHAR(255)
AS

UPDATE LOT SET  
WHO_ID = @P_WHO_ID,
QTY_ON_HAND = @P_QTY_ON_HAND,
MANUFACT_DATE = @P_MANUFACT_DATE,
CADUCATE_DATE = @P_CADUCATE_DATE,
COMMENT = @P_COMMENT
WHERE 
PART_ID = @P_PART_ID AND LOT_ID = @P_LOT_ID