  
  
CREATE PROC CX_SP_I_WAREHOUSE_TRANS_LINE  
@P_WAREHOUSE_ID VARCHAR(2),  
@P_DOCUMENT_ID VARCHAR(2),  
@P_NUMBER_DOCUMENT VARCHAR(10),  
@P_ITEM INT,  
@P_PART_ID VARCHAR(20),  
@P_QTY FLOAT,  
@P_QTY_DLV  FLOAT,  
@P_QTY_REF FLOAT,  
@P_QTY_INVOICED FLOAT,  
@P_AMOUNT_SALES FLOAT,  
@P_PART_DESCRIPTION VARCHAR(64),  
@P_UNIT_PART VARCHAR(6)  ,
@P_NUMBER_LOT varchar(20)
AS  
  
INSERT INTO WAREHOUSE_TRANS_LINE(WAREHOUSE_ID,   
DOCUMENT_ID ,  
NUMBER_DOCUMENT ,  
ITEM ,  
PART_ID,  
QTY,  
QTY_DLV ,  
QTY_REF ,  
QTY_INVOICED,  
AMOUNT_SALES,  
PART_DESCRIPTION,  
UNIT_PART,
NUMBER_LOT)  
VALUES(  
@P_WAREHOUSE_ID ,  
@P_DOCUMENT_ID,  
@P_NUMBER_DOCUMENT,  
@P_ITEM ,  
@P_PART_ID ,  
@P_QTY ,  
@P_QTY_DLV  ,  
@P_QTY_REF ,  
@P_QTY_INVOICED ,  
@P_AMOUNT_SALES ,  
@P_PART_DESCRIPTION ,  
@P_UNIT_PART  ,
@P_NUMBER_LOT
)