
CREATE PROC CX_SP_I_LETTER_EXCHANGE_LINE
@P_ID VARCHAR(6),
@P_ITEM VARCHAR(3),
@P_TYPE_DOC VARCHAR(2),
@P_NUMBER_DOC VARCHAR(10),
@P_AMOUNT FLOAT,
@P_CADUCATE_DATE SMALLDATETIME,
@P_IS_ORIG VARCHAR(1)
AS
INSERT INTO LETTER_EXCHANGE_LINE(ID,ITEM,TYPE_DOC,NUMBER_DOC,AMOUNT,CADUCATE_DATE,IS_ORIG)
VALUES(@P_ID,@P_ITEM,@P_TYPE_DOC,@P_NUMBER_DOC,@P_AMOUNT,@P_CADUCATE_DATE,@P_IS_ORIG)