CREATE PROC CX_SP_S_TYPE_RECEIVE
AS
SELECT 
RECEIVE_ID,
DESCRIPTION,
CURRENCY_ID,
ACCOUNT,
CAST( BANK_ID AS INT) AS 'BANK_ID',
CAST(IS_CHECK_DIF AS INT) AS 'IS_CHECK_DIF',
CAST(IS_APPL AS INT) AS 'IS_APPL',
TRANS_TYPE,
cast(ISNULL(IS_CREDIT_CARD,0)as int) AS 'IS_CREDIT_CARD'
FROM 
TYPE_RECEIVE