CREATE PROC CX_SP_U_VENDOR
@P_ID VARCHAR(11),	
@P_NAME VARCHAR(100),	
@P_VAT_REGISTRATION VARCHAR(11)	,
@P_ADDR VARCHAR(100),
@P_PHONE VARCHAR(30),
@P_EMAIL VARCHAR(50),	
@P_WEBSITE VARCHAR(50),
@P_CONTACT VARCHAR(70),
@P_DOCUMENT_TYPE_PERSON_ID	VARCHAR(2),
@P_TYPE_COMPANY	VARCHAR(2),
@P_ACCOUNT_LOCAL	VARCHAR(50),
@P_ACCOUNT_EXTERNAL VARCHAR(50)
AS
UPDATE VENDOR SET NAME =@P_NAME ,
VAT_REGISTRATION =@P_VAT_REGISTRATION ,
ADDR = @P_ADDR ,
PHONE = @P_PHONE ,
EMAIL = @P_EMAIL,
WEBSITE = @P_WEBSITE,
CONTACT = @P_CONTACT,
DOCUMENT_TYPE_PERSON_ID = @P_DOCUMENT_TYPE_PERSON_ID,
TYPE_COMPANY =@P_TYPE_COMPANY ,
ACCOUNT_LOCAL = @P_ACCOUNT_LOCAL,
ACCOUNT_EXTERNAL = @P_ACCOUNT_EXTERNAL
WHERE ID = @P_ID