CREATE PROC CX_SP_S_RECEIVABLE_DET_XITEM
@P_ID VARCHAR(6)='000113',
@P_ITEM  VARCHAR(3)='001'
AS
SELECT 
TYPE_DOC,NUMBER_DOC,TYPE_OPERATION,REC_ID,DATE,AMOUNT,CURRENCY_ID,SELL_RATE,COMMENT,SALES_ID,BANK_ID,BANK_DESCRIPTION,DOC_REF,
NUM_REF,LIST_ID,IS_CASH_BANK,AMOUNT_PER,BANK_BUSSINESS_ID,ACCOUNT_BANK_CHECK,PAY_AUTO,ANNEX_ID_AUX,DOCUMET_ID,NUMBER_SERIE,
NUMBER_DOCUMENT,MEDIOS_PAGO
FROM RECEIVABLE_LIST_LINE
WHERE ID = @P_ID AND ITEM = @P_ITEM