CREATE PROC CX_SP_I_LETTER_EXCHANGE
@P_ID VARCHAR(6),
@P_DATE_EXCHANGE SMALLDATETIME,
@P_VOUCHER_ID VARCHAR(6),
@P_CREATE_DATE SMALLDATETIME,
@P_USER_ID VARCHAR(8),
@P_STATUS VARCHAR(1),
@P_ACCEPT_DATE SMALLDATETIME,
@P_SELL_RATE FLOAT,
@P_CURRENCY_ID VARCHAR(2),
@P_CUSTOMER_ID VARCHAR(11)
AS

INSERT INTO LETTER_EXCHANGE(ID,DATE_EXCHANGE,VOUCHER_ID,CREATE_DATE,USER_ID,STATUS,ACCEPT_DATE,SELL_RATE,CURRENCY_ID,CUSTOMER_ID)
VALUES(@P_ID ,
@P_DATE_EXCHANGE ,
@P_VOUCHER_ID ,
@P_CREATE_DATE ,
@P_USER_ID ,
@P_STATUS ,
@P_ACCEPT_DATE ,
@P_SELL_RATE ,
@P_CURRENCY_ID ,
@P_CUSTOMER_ID)