CREATE PROC CX_SP_S_PLANILLA_X_FEC
@P_FEC_INI DATETIME = '01/01/2014',
@P_FEC_FIN DATETIME = '28/02/2014'
AS

SELECT A.ID,A.DATE AS 'FECHA_PLA',B.ITEM,B.TYPE_DOC,B.NUMBER_DOC,B.REC_ID,B.DATE AS 'FECHA_DOC',B.AMOUNT,
B.CURRENCY_ID,B.SELL_RATE,B.BANK_ID,B.BANK_DESCRIPTION,B.DOC_REF,B.NUM_REF,B.ANNEX_ID_AUX
FROM RECEIVABLE_LIST A INNER JOIN RECEIVABLE_LIST_LINE B ON A.ID = B.ID
WHERE A.DATE BETWEEN @P_FEC_INI AND @P_FEC_FIN
ORDER BY A.ID,B.ITEM