CREATE PROC CX_SP_S_NUMBER_DOCUMENT_XCORRE 
@P_TYPE_DOC VARCHAR(2)='NC',
@P_NUMBER_SERIE VARCHAR(3) = '001'
AS

SELECT ISNULL(LAST_NUMBER,0) + 1 AS 'ULTIMO'
FROM NUMBER_DOCUMENT 
WHERE TYPE_DOC = @P_TYPE_DOC AND NUMBER_SERIE = @P_NUMBER_SERIE