CREATE PROC CX_SP_U_TRANSACTION_TYPE
@P_TYPE_ID VARCHAR(1),
@P_MOV_ID VARCHAR(2),
@P_NAME VARCHAR(40),
@P_IS_VALUED VARCHAR(1),
@P_IS_VENDOR VARCHAR(1),
@P_IS_DOC_REF VARCHAR(1),
@P_IS_AUTHORIZED VARCHAR(1),
@P_IS_CCOST VARCHAR(1),
@P_IS_ORDER_PURCHASE VARCHAR(1),
@P_IS_COMMENT VARCHAR(1),
@P_IS_WHO VARCHAR(1),
@P_IS_CUSTOMER VARCHAR(1),
@P_IS_ORDER_MANUFACT VARCHAR(1)
AS
UPDATE TRANSACTION_TYPE SET 
NAME = @P_NAME ,IS_VALUED = @P_IS_VALUED ,IS_VENDOR = @P_IS_VENDOR,IS_DOC_REF = @P_IS_DOC_REF,
IS_AUTHORIZED = @P_IS_AUTHORIZED,IS_CCOST = @P_IS_CCOST,
IS_ORDER_PURCHASE = @P_IS_ORDER_PURCHASE,IS_COMMENT = @P_IS_COMMENT,IS_WHO = @P_IS_WHO,
IS_CUSTOMER = @P_IS_CUSTOMER,IS_ORDER_MANUFACT = @P_IS_ORDER_MANUFACT
WHERE TYPE_ID =@P_TYPE_ID AND MOV_ID = @P_MOV_ID