CREATE PROC CX_SP_D_LOT
@P_WHO_ID VARCHAR(2),
@P_PART_ID VARCHAR(20),
@P_LOT_ID VARCHAR(20),
@P_QTY_ON_HAND FLOAT,
@P_MANUFACT_DATE DATETIME,
@P_CADUCATE_DATE DATETIME,
@P_COMMENT VARCHAR(255)
AS

DELETE FROM  LOT WHERE PART_ID = @P_PART_ID AND LOT_ID = @P_LOT_ID