CREATE PROC CX_SP_S_SALDO_X_CLI
@P_PC VARCHAR(100)='DEVELOPERYX'
AS
SELECT CUSTOMER_ID ,NAME, DOCUMENT_ID,SERIE_AUX,NUM_DOC_AUX,DOC_DATE,CADUCATE_DATE,DOCUMENT_REF,NUMBER_REF,
AMOUNT,AMOUNT_BALANCE_INI,CURRENCY_ID,SELL_RATE
FROM CUSTOMER_BALANCE A INNER JOIN CUSTOMER B ON A.CUSTOMER_ID = B.ID
WHERE CUSTOMER_ID IN (SELECT CODIGO FROM CX_TB_COD_TMP WHERE PC = @P_PC AND AUX = 'R')
AND AMOUNT <> 0
ORDER BY DOC_DATE