CREATE PROC CX_SP_S_LETTER_EXCHANGE_ID
AS
DECLARE @P_ULTIMO VARCHAR(6)
SET @P_ULTIMO = (SELECT ISNULL(MAX(ID),0) FROM LETTER_EXCHANGE)
SET @P_ULTIMO = RIGHT('000000' + cast((CAST(@P_ULTIMO AS INT) + 1)as varchar(6)),6)
SELECT @P_ULTIMO