
  
CREATE PROC CX_SP_S_GRD_X_ID    
@P_WAREHOUSE_ID VARCHAR(2),    
@P_DOCUMENT_ID VARCHAR(2),    
@P_NUMBER_DOCUMENT VARCHAR(10)    
AS    
SELECT ITEM,    
PART_ID,    
PART_DESCRIPTION as 'DES_PART',  
UNIT_PART,
QTY,    
UNIT_PRICE,    
AMOUNT_SALES,    
TEXT_COMMENT,    
CURRENCY_ID    
FROM WAREHOUSE_TRANS_LINE  
WHERE WAREHOUSE_ID = @P_WAREHOUSE_ID AND    
DOCUMENT_ID = @P_DOCUMENT_ID AND    
NUMBER_DOCUMENT = @P_NUMBER_DOCUMENT    
order by ITEM