CREATE PROC CX_SP_I_ACCOUNT_BANK
@P_BANK_ID VARCHAR(2),
@P_ACCOUNT_BANK_ID VARCHAR(20),
@P_ACCOUNT_BANK_DES VARCHAR(100),
@P_NUMBER_ACCOUNT VARCHAR(18),
@P_CURRENCY_ID VARCHAR(2),
@P_TYPE_DOC VARCHAR(2)
AS

INSERT INTO ACCOUNT_BANK(BANK_ID,ACCOUNT_BANK_ID,ACCOUNT_BANK_DES,NUMBER_ACCOUNT,CURRENCY_ID,TYPE_DOC)
VALUES(@P_BANK_ID,@P_ACCOUNT_BANK_ID,@P_ACCOUNT_BANK_DES,@P_NUMBER_ACCOUNT,@P_CURRENCY_ID,@P_TYPE_DOC)