
CREATE PROCEDURE DOC_PENDIENTES_X_CLIENTES
@CUSTOMER_ID VARCHAR(15)
 AS

DELETE FROM DOC_PENDIENTES

DECLARE @DOCUMENT_ID VARCHAR(2)
DECLARE @NUMBER_DOC VARCHAR(15)
DECLARE @NUM VARCHAR(10)

DECLARE CURSOR1 CURSOR FOR
Select DOCUMENT_ID,NUMBER_DOC From  CUSTOMER_BALANCE Where CUSTOMER_ID = @CUSTOMER_ID And Not(AMOUNT_BALANCE = 0)
OPEN CURSOR1
FETCH NEXT FROM CURSOR1
INTO @DOCUMENT_ID,@NUMBER_DOC
WHILE @@FETCH_STATUS=0
BEGIN
	SET @NUM=RIGHT(@NUMBER_DOC,7)
	INSERT INTO DOC_PENDIENTES
	SELECT (R.DOCUMENT_ID+' '+R.NUMBER_SERIE+'-'+R.NUMBER_DOCUMENT)AS NUM_DOC,CONVERT(VARCHAR,R.DOCUMENT_DATE,103),
	R.CUSTOMER_NAME,RL.PART_DESCRIPTION,RL.QTY,RL.PRICE_SALES,RL.AMOUNT
	FROM RECEIVABLE R INNER JOIN RECEIVABLE_LINE RL ON R.DOCUMENT_ID=RL.DOCUMENT_ID AND
	R.NUMBER_SERIE=RL.NUMBER_SERIE AND R.NUMBER_DOCUMENT=RL.NUMBER_DOCUMENT
	WHERE R.DOCUMENT_ID=@DOCUMENT_ID AND R.NUMBER_DOCUMENT=@NUM	

FETCH NEXT FROM CURSOR1
INTO @DOCUMENT_ID,@NUMBER_DOC
END
CLOSE CURSOR1
DEALLOCATE CURSOR1

SELECT * FROM DOC_PENDIENTES
