CREATE PROCEDURE ELIMINA_II
@ALMACEN VARCHAR(2)
 AS
DECLARE @NUMBER_DOCUMENT VARCHAR(30)

DECLARE ACTU CURSOR FOR
select NUMBER_DOCUMENT from warehouse_trans where year(date_document)='2010' and warehouse_id=@ALMACEN and trans_id='II'

OPEN ACTU
FETCH NEXT FROM ACTU
INTO @NUMBER_DOCUMENT

WHILE @@FETCH_STATUS=0
BEGIN
	DELETE FROM warehouse_trans_LINE WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@ALMACEN
	DELETE FROM warehouse_trans WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT AND WAREHOUSE_ID=@ALMACEN
FETCH NEXT FROM ACTU
INTO @NUMBER_DOCUMENT
END
CLOSE ACTU
DEALLOCATE ACTU