CREATE PROC [dbo].[EXCHANGE_COLLATION]
--DECLARE
@BD VARCHAR(50),@TABLE VARCHAR(50),@COLLATION VARCHAR(80)
/*SET @BD='001BDCOMUN'
SET @TABLE='MAEART'
SET @COLLATION='Modern_Spanish_CI_AS'*/
AS
SET NOCOUNT ON
SET QUOTED_IDENTIFIER off

DECLARE @NameTable as varchar(50)DECLARE @NameColum as varchar(50)
DECLARE @NameType as varchar(30)DECLARE @LengthType as varchar(30)

EXEC('SET QUOTED_IDENTIFIER off DECLARE CAMBIA_COLLATION CURSOR FOR

SELECT O.NAME,C.NAME,T.NAME,C.LENGTH FROM ['+@BD+'].DBO.SYSOBJECTS O 
INNER JOIN ['+@BD+'].DBO.SYSCOLUMNS C ON O.ID=C.ID 
INNER JOIN ['+@BD+'].DBO.SYSTYPES T ON C.XTYPE=T.XTYPE
WHERE O.XTYPE="U" AND O.NAME="'+@TABLE+'" AND C.COLLATION<>"'+@COLLATION+'"
and not T.NAME IN("TEXT","SYSNAME","NTEXT","IMAGE")')

OPEN CAMBIA_COLLATION
FETCH NEXT FROM CAMBIA_COLLATION INTO @NameTable,@NameColum,@NameType,@LengthType
	
WHILE @@FETCH_STATUS =0
BEGIN	
EXEC('SET QUOTED_IDENTIFIER off alter table '+@NameTable+' alter column '+@NameColum+' '+@NameType+'('+@LengthType+') COLLATE '+@COLLATION+'')
FETCH NEXT FROM CAMBIA_COLLATION INTO @NameTable,@NameColum,@NameType,@LengthType
END 
CLOSE CAMBIA_COLLATION
DEALLOCATE CAMBIA_COLLATION
