CREATE PROCEDURE GENERA_BK_DROG_DANY
 AS

DECLARE @A VARCHAR(50)
DECLARE @B VARCHAR(50)
DECLARE @C VARCHAR(50)
DECLARE @D VARCHAR(50)
SET @B=DAY(GETDATE())
SET @C=YEAR(GETDATE())
SET @D=MONTH(GETDATE())
SET @A='DROG_DANY_'+(@B)+'_'+@D+'_'+@C

BACKUP DATABASE DROG_DANY TO  
DISK =  N'D:\Novaq\BK\BK_DROG_DANY_NUEVO\' WITH INIT ,  
NOUNLOAD ,  NAME = @A,  NOSKIP ,  
STATS = 10,  NOFORMAT