  CREATE PROCEDURE [dbo].[HSP_COPIA_ALMACEN]  
 --DECLARE  
 @EMP VARCHAR(3)  
 --SET @EMP='002'  
 AS  
 EXEC('  
 INSERT INTO ALMACEN(CODALMACEN,DESALMACEN)  
 SELECT T.ID,T.NAME FROM WAREHOUSE T  
 WHERE T.ID NOT IN (SELECT CODALMACEN FROM ALMACEN)  
 ')  
 EXEC('  
 UPDATE A SET A.DESALMACEN = T.NAME  FROM ALMACEN A INNER JOIN     
        FROM WAREHOUSE T ON A.CODALMACEN=T.ID  
 ')  