 --Unidades de transporte atendidas DMTA  
create procedure [dbo].[HSP_UNI_TRANS_ATENDIDA]  
 --declare  
 @EMP varchar(3),  
 @COD_DMAY varchar(10),  
 @FEC_INICIO varchar(10),  
 @FEC_FINAL varchar(10)  
/*set @EMP='002'  
set @COD_DMAY='58137'  
set @FEC_INICIO='01/11/2007'  
set @FEC_FINAL='30/11/2007'  
--*/as  
 exec('set QUOTED_IDENTIFIER ON SELECT AO.COD_OPER,' + @COD_DMAY + ' as COD_MAYOR,PO.COD_OSINERG,M.NUMBER_REGISTRATION AS PLACA_TRACTO,TDG.PLACA,'''' AS OTRO_TRANS,  
   TDG.DGH AS REG_DGH,B.QTY/PO.FACTOR AS VOLUMEN,'''' AS TEMPERATURA,'''' AS API,A.DATE_DOCUMENT,A.VAT_REGISTRATION,A.CUSTOMER_NAME,A.NUMBER_DOCUMENT AS NUMFACTURA,A.WAREHOUSE_ID,B.PART_ID,PO.FACTOR,  
   M.ID  
   FROM WAREHOUSE_TRANS A  
   INNER JOIN WAREHOUSE_TRANS_LINE B ON A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT  
   INNER JOIN ALMACEN_OSINERG AO ON AO.COD_DMAY=' + @COD_DMAY  + ' AND AO.COD_ALMACEN=A.WAREHOUSE_ID and AO.TIPO_ALMACEN=''C''  
   LEFT JOIN CARRIER M ON M.ID=A.CARRIER_ID     
   INNER JOIN PRODUCTOS_OSINERG PO ON PO.COD_PRODUCTO=B.PART_ID  
   LEFT JOIN TRANS_DGH TDG on TDG.CODIGO=M.ID      
   WHERE A.DATE_DOCUMENT BETWEEN '''+ @FEC_INICIO + ''' AND ''' + @FEC_FINAL +  
   ''' AND A.DOCUMENT_ID=''GS'' AND A.TRANS_ID=''GF'' AND B.PART_ID<>''TEXTO''  
   GROUP BY AO.COD_OPER,PO.COD_OSINERG,M.NUMBER_REGISTRATION,TDG.PLACA,TDG.DGH,B.QTY,A.DATE_DOCUMENT,PO.FACTOR,A.VAT_REGISTRATION,A.CUSTOMER_NAME,A.NUMBER_DOCUMENT,  
   A.WAREHOUSE_ID,B.PART_ID,M.ID  
   ORDER BY A.DATE_DOCUMENT')  