CREATE PROC [dbo].[HSP_LIST_FACTURAS]          
--DECLARE          
  @EMP AS VARCHAR(50),          
  @OPCION AS VARCHAR(1),          
  @FECHAINI  VARCHAR(10),          
  @FECHAFIN VARCHAR(10),         
  @CFTD VARCHAR(2),      
  @CFNUMSER VARCHAR(3),      
  @CFNUMDOC VARCHAR(7)      
      
/*         
  SET @OPCION='1'          
  SET @EMP='001'          
  SET @FECHAINI='2007'          
  SET @FECHAFIN='01'          
*/        
 AS          
  DECLARE @STRcadena NVARCHAR(800)          
          
--  SET @STRcadena='SELECT CFPUNVEN,(CFTD + '' '' + CFNUMSER + ''-'' + CFNUMDOC) AS COL1,CFFECDOC,        
--      CFNOMBRE,CFFORVEN,CFCODMON,(CASE WHEN CFTIPFAC = ''FO'' THEN CFIGV ELSE CFIMPORTE END)         
--      AS COL2,CFESTADO,CFCODCLI,CFRUC,CFVENDE,CFTIPCAM,CFNUMSER,CFNUMDOC,CFTD,CFIMPFAC,CFIGV,CFTIPFAC,  
--      CFRFTD,CFRFNUMSER,CFRFNUMDOC,CFNROPED  FROM [' + @EMP + 'BDCOMUN].DBO.FACCAB WHERE (CFTD=''FT'' OR CFTD=''BV'')'          
          
  SET @STRcadena='SELECT PLACE_SALES,(DOCUMENT_ID + '' '' + NUMBER_SERIE + ''-'' + NUMBER_DOCUMENT) AS COL1,DOCUMENT_DATE,        
      CUSTOMER_NAME,TERMS_ID,CURRENCY_ID,(CASE WHEN RECEIVABLE_TYPE = ''FO'' THEN AMOUNT_TAX ELSE AMOUNT END)         
      AS COL2,STATUS,CUSTOMER_ID,VAT_REGISTRATION,SALES_REP_ID,SELL_RATE,NUMBER_SERIE,NUMBER_DOCUMENT,DOCUMENT_ID,IS_PRINT,AMOUNT_TAX,RECEIVABLE_TYPE,  
      DOCUMENT_REF,SERIE_REF,NUMBER_REF,NUMBER_ORDER  FROM ' + @EMP + '.DBO.RECEIVABLE WHERE (DOCUMENT_ID=''FT'' OR DOCUMENT_ID=''BV'')'          


 IF @OPCION='1'           
    SET @STRcadena=@strcadena + ' AND YEAR(DOCUMENT_DATE) ='+(@FECHAINI)+' AND MONTH(DOCUMENT_DATE)='+@FECHAFIN+''          
          
 IF @OPCION='2'          
     SET @STRcadena=@strcadena + ' AND DOCUMENT_DATE BETWEEN @FECHAINI AND @FECHAFIN'          
          
 IF @OPCION='3'          
     SET @STRcadena=@strcadena          
         
 SET @STRcadena=@strcadena+ ' ORDER BY COL1 '          
    
 IF @OPCION='4'        
    SET @STRcadena='SELECT * FROM ' + @EMP + '.DBO.RECEIVABLE WHERE DOCUMENT_ID=  '''+@CFTD+'''  AND NUMBER_SERIE ='''+@CFNUMSER+''' AND NUMBER_DOCUMENT='''+@CFNUMDOC+''''        
          
EXEC SP_EXECUTESQL @STRcadena,N'@EMP VARCHAR(3),@OPCION VARCHAR(1),@FECHAINI VARCHAR(10),@FECHAFIN VARCHAR(10),@CFTD VARCHAR(2),@CFNUMSER VARCHAR(3), @CFNUMDOC VARCHAR(7) '          
                  ,@EMP,@OPCION,@FECHAINI,@FECHAFIN, @CFTD, @CFNUMSER,@CFNUMDOC  