


CREATE   PROCEDURE [dbo].[HSP_REPCOSTO_AGRUPACION]  
--DECLARE  
 @EMP VARCHAR(3),  
 @FECHAINI VARCHAR(10),@FECHAFIN VARCHAR(10),  
 --@ARTINI VARCHAR(20),@ARTFIN VARCHAR(20),  
 --@INI VARCHAR(2), @FIN VARCHAR(2),  
 --@CLIINI VARCHAR(11),@CLIFIN VARCHAR(11),  
 @PC VARCHAR(60),@OPC VARCHAR(1)  
  
/*SET @EMP='002'  
SET @FECHAINI='01/04/2006'  
SET @FECHAFIN='11/04/2006'  
--SET @ARTINI='001'  
--SET @ARTFIN='XILCPR'  
--SET @INI='00'  
--SET @FIN='08'  
--SET @CLIINI='00'  
--SET @CLIFIN='TRANSP'  
SET @PC='SOVERO'  
SET @OPC='1'  
  
--*/AS   
  
IF EXISTS(SELECT * FROM tempdb.dbo.sysobjects WHERE NAME='COSTOSAGRUP'+@PC)  
  EXEC('DROP TABLE [tempdb].dbo.COSTOSAGRUP'+@PC+'')  
  
IF @OPC='0'  
 EXEC ('SELECT FD.PART_ID,FD.PART_DESCRIPTION,FC.DOCUMENT_ID ,FC.NUMBER_SERIE ,FC.NUMBER_DOCUMENT,FC.CUSTOMER_ID,FC.CUSTOMER_NAME,  
 FC.DOCUMENT_DATE,FD.QTY,FD.UNIT,FC.CURRENCY_ID,FD.PRICE_ORI,  
 FD.PART_TAX,FC.SELL_RATE,FD.DISCOUNT,FD.DISCOUNT_CUSTOMER,FD.DISCOUNT_SP,  
 FC.IS_GUIA_REC,V.ID,V.NAME  
 INTO [tempdb].dbo.COSTOSAGRUP'+@PC+'  
 FROM RECEIVABLE FC  
 INNER JOIN SALES_REP V ON FC.SALES_REP_ID=V.ID  
 INNER JOIN RECEIVABLE_LINE FD ON FC.DOCUMENT_ID=FD.DOCUMENT_ID  
 INNER JOIN PART MA ON MA.ID=FD.PART_ID  
 AND FC.NUMBER_SERIE=FD.NUMBER_SERIE AND FC.NUMBER_DOCUMENT=FD.NUMBER_DOCUMENT  
 WHERE FC.DOCUMENT_DATE>=''' + @FECHAINI + ''' AND FC.DOCUMENT_DATE<=''' + @FECHAFIN + '''   
 AND NOT(MA.IS_STOCKED=''N'' AND MA.SERIES=''N'' AND MA.IS_LOT=''N'')  
 AND FC.STATUS<>''A''  
 AND FD.PART_ID<>''CILIN ''  
 ORDER BY FD.PART_ID ')  
  
IF @OPC='1'  
EXEC ('SELECT FD.PART_ID,FD.PART_DESCRIPTION,FC.DOCUMENT_ID ,FC.NUMBER_SERIE ,FC.NUMBER_DOCUMENT,FC.CUSTOMER_ID,FC.CUSTOMER_NAME,  
 FC.DOCUMENT_DATE,FD.QTY,FD.UNIT,FC.CURRENCY_ID,FD.PRICE_ORI,  
 FD.PART_TAX,TC.SELL_RATE,FD.DISCOUNT,FD.DISCOUNT_CUSTOMER,FD.DISCOUNT_SP,  
 FC.IS_GUIA_REC,V.ID,V.NAME  
 INTO [tempdb].dbo.COSTOSAGRUP'+@PC+'  
 FROM RECEIVABLE FC  
 INNER JOIN SALES_REP V ON FC.SALES_REP_ID=V.ID  
 INNER JOIN RECEIVABLE_LINE FD ON FC.DOCUMENT_ID=FD.DOCUMENT_ID  
 INNER JOIN CURRENCY_EXCHANGE TC ON TC.CURRENCY_DATE=FC.DOCUMENT_DATE  
 INNER JOIN PART MA ON MA.ID=FD.PART_ID  
 AND FC.NUMBER_SERIE=FD.NUMBER_SERIE AND FC.NUMBER_DOCUMENT=FD.NUMBER_DOCUMENT  
 WHERE FC.DOCUMENT_DATE>=''' + @FECHAINI + ''' AND FC.DOCUMENT_DATE<=''' + @FECHAFIN + '''   
 AND NOT(MA.IS_STOCKED=''N'' AND MA.SERIES=''N'' AND MA.IS_LOT=''N'')  
 AND FC.STATUS<>''A''  
 AND FD.PART_ID<>''CILIN ''  
 ORDER BY FD.PART_ID ') 


  
--Quite para que saque todo!!!  
--WHERE FD.DFCODIGO>=''' + @ARTINI + ''' AND FD.DFCODIGO<=''' + @ARTFIN + '''  
--AND (FC.CFCODCLI>=''' + @CLIINI + ''' AND FC.CFCODCLI<=''' + @CLIFIN + ''')  
--AND V.COD_VEN>=''' + @INI + ''' AND V.COD_VEN<=''' + @FIN + '''  
  
  
EXEC ('ALTER TABLE [tempdb].dbo.COSTOSAGRUP'+@PC+' ADD COSTOMN numeric(15,9)')  
EXEC ('ALTER TABLE [tempdb].dbo.COSTOSAGRUP'+@PC+' ADD COSTOME numeric(15,9)')  
EXEC ('ALTER TABLE [tempdb].dbo.COSTOSAGRUP'+@PC+' ADD COSTOMN_REAL numeric(15,9)')  
  
EXEC ('UPDATE C SET C.COSTOMN = (CASE WHEN C.CURRENCY_ID=''MN'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST * SELL_RATE END),  
      C.COSTOME = (CASE WHEN C.CURRENCY_ID=''ME'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST / SELL_RATE END)  
FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' C INNER JOIN WAREHOUSE_TRANS_LINE MD  
ON C.PART_ID=MD.PART_ID AND C.DOCUMENT_ID=MD.DOCUMENT_ID  
AND C.NUMBER_SERIE=LEFT(MD.NUMBER_DOCUMENT,3) AND C.NUMBER_DOCUMENT=RIGHT(MD.NUMBER_DOCUMENT,7)  
WHERE C.IS_GUIA_REC IS NULL OR C.IS_GUIA_REC<>''S'' OR C.IS_GUIA_REC='''' OR C.IS_GUIA_REC='' ''')  
  
  
EXEC ('UPDATE C SET C.COSTOMN = (CASE WHEN C.CURRENCY_ID=''MN'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST * SELL_RATE END),  
      C.COSTOME = (CASE WHEN C.CURRENCY_ID=''ME'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST / SELL_RATE END)  
FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' C INNER JOIN WAREHOUSE_TRANS MC  
INNER JOIN WAREHOUSE_TRANS_LINE MD ON MC.DOCUMENT_ID=MD.DOCUMENT_ID  
AND MC.WAREHOUSE_ID=MD.WAREHOUSE_ID AND MC.NUMBER_DOCUMENT=MD.NUMBER_DOCUMENT  
ON C.DOCUMENT_ID=MC.DOC_ID_REF   
AND C.NUMBER_SERIE=LEFT(MC.NUM_ID_REF,3) AND C.NUMBER_DOCUMENT=RIGHT(MC.NUM_ID_REF,7)  
WHERE C.PART_ID=MD.PART_ID AND C.IS_GUIA_REC=''S''')  
  

EXEC ('UPDATE [tempdb].dbo.COSTOSAGRUP'+@PC+' SET QTY=(CASE WHEN QTY IS NULL THEN 0 ELSE QTY END),  
   PRICE_ORI=(CASE WHEN PRICE_ORI IS NULL THEN 0 ELSE PRICE_ORI END),  
   PART_TAX=(CASE WHEN PART_TAX IS NULL THEN 0 ELSE PART_TAX END),  
   SELL_RATE=(CASE WHEN SELL_RATE IS NULL THEN 0 ELSE SELL_RATE END),  
   DISCOUNT=(CASE WHEN DISCOUNT IS NULL THEN 0 ELSE DISCOUNT END),  
   DISCOUNT_CUSTOMER=(CASE WHEN DISCOUNT_CUSTOMER IS NULL THEN 0 ELSE DISCOUNT_CUSTOMER END),  
   DISCOUNT_SP=(CASE WHEN DISCOUNT_SP IS NULL THEN 0 ELSE DISCOUNT_SP END),  
   IS_GUIA_REC=(CASE WHEN IS_GUIA_REC IS NULL THEN '''' ELSE IS_GUIA_REC END),  
   COSTOMN=(CASE WHEN COSTOMN IS NULL THEN 0 ELSE COSTOMN END),  
   COSTOME=(CASE WHEN COSTOME IS NULL THEN 0 ELSE COSTOME END)')  
  
  
--ACTUALIZO EL COSTO REAL EN SOLES  
EXEC('UPDATE C SET COSTOMN_REAL=AVERAGE_COST  
      FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' C  
      LEFT JOIN INVENTORY I   
      ON C.DOCUMENT_ID=I.TYPE_DOC AND C.NUMBER_SERIE+C.NUMBER_DOCUMENT=I.NUMBER_DOC  
      AND C.PART_ID=I.PART_ID')  
  
--CREO MI TABLA TEMPORAL  
 IF EXISTS(SELECT * FROM tempdb.dbo.sysobjects WHERE NAME='COSTITO'+@PC)  
  EXEC('DROP TABLE [tempdb].dbo.COSTITO'+@PC+'')  
 EXEC('CREATE TABLE [tempdb].dbo.COSTITO' + @PC + '   
 (CODIGO VARCHAR(20) ,DESCRIPCION VARCHAR(64),COSTOME NUMERIC(15,6),COSTOMN NUMERIC(15,6),  
  PRECIOME NUMERIC(15,6),PRECIOMN NUMERIC(15,6),CANTIDAD NUMERIC(15,6))')  
  
 EXEC('  
 INSERT INTO [tempdb].dbo.COSTITO'+@PC+'   
 select CODIGO_PRO,DESCRIPCION,0,0,0,0,0 from ['+@EMP+'].dbo.ESTADO_PRODUCTO  
 WHERE CODIGO_PRO NOT IN (SELECT DFCODIGO FROM [tempdb].dbo.COSTOSAGRUP'+@PC+')  
 AND ESTADO=''1''  
 ORDER BY CODIGO_PRO   
 ')  
  
--AHORA CRUZO MI TEMPORAL CONTRA LA BD HAKAN PARA HACER LAS AGRUPACIONES  
   
 --DECLARE @SUMACOSTOMN NUMERIC(15,6),@SUMACOSTOME NUMERIC(15,6)  
 DECLARE @SUMACOSTOMN varchar(50),@SUMACOSTOME varchar(1000)  
 DECLARE @SUMACANT varchar(50)  
 DECLARE @INSERTA VARCHAR(1000)  
 DECLARE @COD VARCHAR(20)  
 DECLARE @DESCRI VARCHAR(64)  
     
  
 DECLARE AGRUPA CURSOR FOR  
    SELECT CODIGO_PRO,DESCRIPCION FROM ESTADO_PRODUCTO E WHERE E.ESTADO=1   
    GROUP BY CODIGO_PRO,DESCRIPCION ORDER BY E.CODIGO_PRO  
    
    OPEN AGRUPA  
 FETCH NEXT FROM AGRUPA INTO @COD,@DESCRI  
  
  
  
 WHILE @@FETCH_STATUS=0  
   BEGIN      
     SET @INSERTA='INSERT INTO [tempdb].dbo.COSTITO'+@PC+'(CODIGO,DESCRIPCION,COSTOME,COSTOMN,PRECIOME,PRECIOMN,CANTIDAD) SELECT DFCODIGO,DFDESCRI,SUM(COSTOME*DFCANTID) AS COSTOME,SUM(COSTOMN_REAL*DFCANTID) AS COSTOMN,'  
     SET @INSERTA=@INSERTA + '(CASE WHEN CFCODMON=''ME'' THEN SUM(DFPREC_ORI*DFCANTID) ELSE SUM((DFPREC_ORI/CFTIPCAM)*DFCANTID) END) AS PRECIOME,'  
     SET @INSERTA=@INSERTA + '(CASE WHEN CFCODMON=''MN'' THEN SUM(DFPREC_ORI*DFCANTID) ELSE SUM((DFPREC_ORI*CFTIPCAM)*DFCANTID) END) AS PRECIOMN,'  
     SET @INSERTA=@INSERTA + 'SUM(DFCANTID) AS CANTIDAD'   
     SET @INSERTA=@INSERTA+' FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' WHERE DFCODIGO='''+@COD+''''  
     SET @INSERTA=@INSERTA+' GROUP BY DFCODIGO,DFDESCRI,CFCODMON'  
     EXEC(@INSERTA)  
      
         
  
  DECLARE @CODIGODET VARCHAR(20)  
  DECLARE @ACTUALIZA VARCHAR(1000)  
    
  DECLARE SUMADETALLE CURSOR FOR  
  SELECT COD_PRO_SEC FROM [HAKAN].dbo.DETALLE_PRODUCTO WHERE COD_PRO_PRIN=@COD  
  
  OPEN SUMADETALLE  
  FETCH NEXT FROM SUMADETALLE INTO @CODIGODET  
  
  WHILE @@FETCH_STATUS=0  
    BEGIN  
   SET @ACTUALIZA='UPDATE [tempdb].dbo.COSTITO'+@PC+' SET COSTOME=COSTOME+ISNULL((SELECT SUM(COSTOME*QTY)'  
   SET @ACTUALIZA=@ACTUALIZA + ' FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' WHERE PART_ID='''+@CODIGODET+'''),0),'  
   SET @ACTUALIZA=@ACTUALIZA + ' COSTOMN=COSTOMN+ISNULL((SELECT ROUND(SUM(COSTOMN_REAL*QTY),2)'  
   SET @ACTUALIZA=@ACTUALIZA + ' FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' WHERE PART_ID='''+@CODIGODET+'''),0),'  
   SET @ACTUALIZA=@ACTUALIZA + ' PRECIOME=PRECIOME+ISNULL((SELECT (CASE WHEN CURRENCY_ID=''ME'' THEN SUM(PRICE_ORI*QTY) ELSE SUM((PRICE_ORI/SELL_RATE)*QTY) END)AS PRECIOME'  
   SET @ACTUALIZA=@ACTUALIZA + ' FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' WHERE PART_ID='''+@CODIGODET+''' GROUP BY CURRENCY_ID),0),'  
   SET @ACTUALIZA=@ACTUALIZA + ' PRECIOMN=PRECIOMN+ISNULL((SELECT (CASE WHEN CURRENCY_ID=''MN'' THEN SUM(PRICE_ORI*QTY) ELSE SUM((PRICE_ORI*SELL_RATE)*QTY) END)AS PRECIOMN'  
   SET @ACTUALIZA=@ACTUALIZA + ' FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' WHERE PART_ID='''+@CODIGODET+''' GROUP BY CURRENCY_ID),0),'  
   SET @ACTUALIZA=@ACTUALIZA + ' CANTIDAD=CANTIDAD + ISNULL((SELECT SUM(QTY) FROM [tempdb].dbo.COSTOSAGRUP'+@PC+' WHERE PART_ID='''+@CODIGODET+'''),0)'  
   SET @ACTUALIZA=@ACTUALIZA + ' WHERE CODIGO='''+@COD+''''  
  
   EXEC(@ACTUALIZA)  
  
   FETCH NEXT FROM SUMADETALLE INTO @CODIGODET  
    END   
    CLOSE SUMADETALLE  
    DEALLOCATE SUMADETALLE   
   
     FETCH NEXT FROM AGRUPA INTO @COD,@DESCRI  
    
   END  
 CLOSE AGRUPA  
        DEALLOCATE AGRUPA  
  
   
--ELIMINO DONDE TODO SEA CERO  
EXEC('DELETE FROM [tempdb].dbo.COSTITO'+@PC+'  
      WHERE COSTOME=0 AND COSTOMN=0 AND PRECIOME=0 AND PRECIOMN=0    
   
')  
  
--HAGO SELECT A TEMPORAL  
EXEC('SELECT CODIGO,DESCRIPCION,SUM(COSTOME) AS COSTOME,SUM(COSTOMN) AS COSTOMN,SUM(PRECIOME) AS PRECIOME,SUM(PRECIOMN) AS PRECIOMN,SUM(CANTIDAD) AS CANTIDAD   
 FROM [tempdb].dbo.COSTITO'+@PC+' GROUP BY CODIGO,DESCRIPCION')  
  
  
  
  
  

  