--HSP_MUESTRA_DETALLE

  CREATE PROCEDURE [dbo].[HSP_MUESTRA_DETALLE]  
  @EMP VARCHAR(3),@CODPRO VARCHAR(20)  
 AS  
 exec('  
 SELECT M.ID,M.DESCRIPTION FROM PART M  
 INNER JOIN DETALLE_PRODUCTO D  
 ON M.ID=D.COD_PRO_SEC  
 AND D.COD_PRO_PRIN='''+@CODPRO+'''  
 ')  
  
