  CREATE  PROCEDURE [dbo].[HSP_REPCOSTO_AGRUPADO_CLIPRO]  
--DECLARE  
 
 @FECHAINI VARCHAR(10),
 @FECHAFIN VARCHAR(10),  
 @INI VARCHAR(20), 
 @FIN VARCHAR(20),  
 @PC VARCHAR(60),  
 @OPCION VARCHAR(1),  
 @OPT VARCHAR(1)  
  
--HSP_REPCOSTO_AGRUPADO_CLIPRO '01/04/2008','30/04/2008','10001','20533984992','DEVELOPER02','1','0'
/*
SET @FECHAINI='01/04/2008'  
SET @FECHAFIN='30/04/2008'  
SET @INI='10001'  
SET @FIN='20533984992'  
SET @PC='DEVELOPER02'  
SET @OPCION='1'  
SET @OPT='0'  
  
--*/AS   
  
IF EXISTS(SELECT * FROM tempdb.dbo.sysobjects WHERE NAME='COSTOS'+@PC)  
  EXEC('DROP TABLE [tempdb].dbo.COSTOS'+@PC+'')  
  
 DECLARE @CADENA VARCHAR(100)  
 IF @OPCION='1'  
  SET @CADENA='AND FC.CUSTOMER_ID>=''' + @INI + ''' AND FC.CUSTOMER_ID<=''' + @FIN + ''''  
  
 IF @OPCION='2'   
  SET @CADENA='WHERE FD.PART_ID>=''' + @INI + ''' AND FD.PART_ID<=''' + @FIN + ''''  
  
IF @OPT='0'  
 EXEC ('SELECT FD.PART_ID,FD.PART_DESCRIPTION,FC.DOCUMENT_ID ,FC.NUMBER_SERIE ,FC.NUMBER_DOCUMENT,FC.CUSTOMER_ID,FC.CUSTOMER_NAME,  
 FC.DOCUMENT_DATE,FD.QTY,FD.UNIT,FC.CURRENCY_ID,FD.PRICE_ORI,  
 FD.PART_TAX,FC.SELL_RATE,FD.DISCOUNT,FD.DISCOUNT_CUSTOMER,FD.DISCOUNT_SP,  
 FC.IS_GUIA_REC,V.ID,V.NAME  
 INTO [tempdb].dbo.COSTOS'+@PC+'  
 FROM RECEIVABLE FC  
 INNER JOIN SALES_REP V ON FC.SALES_REP_ID=V.ID  
 INNER JOIN RECEIVABLE_LINE FD ON FC.DOCUMENT_ID=FD.DOCUMENT_ID  
 INNER JOIN PART MA ON MA.ID=FD.PART_ID  
 AND FC.NUMBER_SERIE=FD.NUMBER_SERIE AND FC.NUMBER_DOCUMENT=FD.NUMBER_DOCUMENT ' + @CADENA + '  
 AND FC.DOCUMENT_DATE>=''' + @FECHAINI + ''' AND FC.DOCUMENT_DATE<=''' + @FECHAFIN + '''  
 AND NOT(MA.IS_STOCKED=''N'' AND MA.SERIES=''N'' AND MA.IS_LOT=''N'')  
 AND FC.STATUS<>''A''  
 AND FD.PART_ID<>''CILIN ''  
 ORDER BY FD.PART_ID ')  
  

IF @OPT='1'  

EXEC ('SELECT FD.PART_ID,FD.PART_DESCRIPTION,FC.DOCUMENT_ID ,FC.NUMBER_SERIE ,FC.NUMBER_DOCUMENT,FC.CUSTOMER_ID,FC.CUSTOMER_NAME,  
 FC.DOCUMENT_DATE,FD.QTY,FD.UNIT,FC.CURRENCY_ID,FD.PRICE_ORI,  
 FD.PART_TAX,TC.SELL_RATE,FD.DISCOUNT,FD.DISCOUNT_CUSTOMER,FD.DISCOUNT_SP,  
 FC.IS_GUIA_REC,V.ID,V.NAME  
 INTO [tempdb].dbo.COSTOS'+@PC+'  
 FROM RECEIVABLE FC  
 INNER JOIN SALES_REP V ON FC.SALES_REP_ID=V.ID  
 INNER JOIN RECEIVABLE_LINE FD ON FC.DOCUMENT_ID=FD.DOCUMENT_ID  
 INNER JOIN CURRENCY_EXCHANGE TC ON TC.CURRENCY_DATE=FC.DOCUMENT_DATE  
 INNER JOIN PART MA ON MA.ID=FD.PART_ID  
 AND FC.NUMBER_SERIE=FD.NUMBER_SERIE AND FC.NUMBER_DOCUMENT=FD.NUMBER_DOCUMENT ' + @CADENA + '  
 AND FC.DOCUMENT_DATE>=''' + @FECHAINI + ''' AND FC.DOCUMENT_DATE<=''' + @FECHAFIN + '''  
 AND NOT(MA.IS_STOCKED=''N'' AND MA.SERIES=''N'' AND MA.IS_LOT=''N'')  
 AND FC.STATUS<>''A''  
 AND FD.PART_ID<>''CILIN ''  
 ORDER BY FD.PART_ID ')  

  
  
  
 --WHERE FD.DFCODIGO>=''' + @ARTINI + ''' AND FD.DFCODIGO<=''' + @ARTFIN + '''   
 --AND (FC.CFCODCLI>=''' + @CLIINI + ''' AND FC.CFCODCLI<=''' + @CLIFIN + ''')  
 --AND V.COD_VEN>=''' + @INI + ''' AND V.COD_VEN<=''' + @FIN + '''  
  
  
  
EXEC ('ALTER TABLE [tempdb].dbo.COSTOS'+@PC+' ADD COSTOMN numeric(15,9)')  
EXEC ('ALTER TABLE [tempdb].dbo.COSTOS'+@PC+' ADD COSTOME numeric(15,9)')  
EXEC ('ALTER TABLE [tempdb].dbo.COSTOS'+@PC+' ADD COSTOMN_REAL numeric(15,9)')  
  
EXEC ('UPDATE C SET C.COSTOMN = (CASE WHEN C.CURRENCY_ID=''MN'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST * SELL_RATE END),  
      C.COSTOME = (CASE WHEN C.CURRENCY_ID=''ME'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST / SELL_RATE END)  
FROM [tempdb].dbo.COSTOS'+@PC+' C INNER JOIN WAREHOUSE_TRANS_LINE MD  
ON C.PART_ID=MD.PART_ID AND C.DOCUMENT_ID=MD.DOCUMENT_ID  
AND C.NUMBER_SERIE=LEFT(MD.NUMBER_DOCUMENT,3) AND C.NUMBER_DOCUMENT=RIGHT(MD.NUMBER_DOCUMENT,7)  
WHERE C.IS_GUIA_REC IS NULL OR C.IS_GUIA_REC<>''S'' OR C.IS_GUIA_REC='''' OR C.IS_GUIA_REC='' ''')  
  
  
EXEC ('UPDATE C SET C.COSTOMN = (CASE WHEN C.CURRENCY_ID=''MN'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST * SELL_RATE END),  
      C.COSTOME = (CASE WHEN C.CURRENCY_ID=''ME'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST / SELL_RATE END)  
FROM [tempdb].dbo.COSTOS'+@PC+' C INNER JOIN WAREHOUSE_TRANS MC  
INNER JOIN WAREHOUSE_TRANS_LINE MD ON MC.DOCUMENT_ID=MD.DOCUMENT_ID  
AND MC.WAREHOUSE_ID=MD.WAREHOUSE_ID AND MC.NUMBER_DOCUMENT=MD.NUMBER_DOCUMENT  
ON C.DOCUMENT_ID=MC.DOC_ID_REF   
AND C.NUMBER_SERIE=LEFT(MC.NUM_ID_REF,3) AND C.NUMBER_DOCUMENT=RIGHT(MC.NUM_ID_REF,7)  
WHERE C.PART_ID=MD.ITEM AND C.IS_GUIA_REC=''S''')  
  
EXEC ('UPDATE [tempdb].dbo.COSTOS'+@PC+' SET QTY=(CASE WHEN QTY IS NULL THEN 0 ELSE QTY END),  
   PRICE_ORI=(CASE WHEN PRICE_ORI IS NULL THEN 0 ELSE PRICE_ORI END),  
   PART_TAX=(CASE WHEN PART_TAX IS NULL THEN 0 ELSE PART_TAX END),  
   SELL_RATE=(CASE WHEN SELL_RATE IS NULL THEN 0 ELSE SELL_RATE END),  
   DISCOUNT=(CASE WHEN DISCOUNT IS NULL THEN 0 ELSE DISCOUNT END),  
   DISCOUNT_CUSTOMER=(CASE WHEN DISCOUNT_CUSTOMER IS NULL THEN 0 ELSE DISCOUNT_CUSTOMER END),  
   DISCOUNT_SP=(CASE WHEN DISCOUNT_SP IS NULL THEN 0 ELSE DISCOUNT_SP END),  
   IS_GUIA_REC=(CASE WHEN IS_GUIA_REC IS NULL THEN '''' ELSE IS_GUIA_REC END),  
   COSTOMN=(CASE WHEN COSTOMN IS NULL THEN 0 ELSE COSTOMN END),  
   COSTOME=(CASE WHEN COSTOME IS NULL THEN 0 ELSE COSTOME END)')  
  
  
--ACTUALIZO CAMPO COSTOMN_REAL  
EXEC('UPDATE C SET COSTOMN_REAL=I.AVERAGE_COST  
      FROM [tempdb].dbo.COSTOS'+@PC+' C  
      LEFT JOIN INVENTORY I  
      ON C.DOCUMENT_ID=I.TYPE_DOC AND C.NUMBER_SERIE+C.NUMBER_DOCUMENT=I.NUMBER_DOC  
      AND C.PART_ID=I.PART_ID')  
  
--HAGO SELECT A TEMPORAL  
  
IF @OPCION='1'  
--Agrupado por clientes  
 EXEC('  
 SELECT CUSTOMER_ID,CUSTOMER_NAME,  
 SUM((CASE WHEN CURRENCY_ID=''ME'' THEN PRICE_ORI*QTY ELSE (PRICE_ORI/SELL_RATE)*QTY END)) AS TOTALME,  
 SUM(COSTOME*QTY) AS COSTO_ME,  
 SUM((CASE WHEN CURRENCY_ID=''ME'' THEN (PRICE_ORI*SELL_RATE)*QTY ELSE PRICE_ORI*QTY  END)) AS TOTALMN,  
 SUM(COSTOMN_REAL*QTY) AS COSTO_MN  
 FROM [tempdb].dbo.COSTOS'+@PC+'   
 GROUP BY CUSTOMER_ID,CUSTOMER_NAME')  
  
IF @OPCION='2'  
--Agrupado por producto  
 EXEC('  
 SELECT PART_ID,PART_DESCRIPTION,  
 SUM((CASE WHEN CURRENCY_ID=''ME'' THEN PRICE_ORI*QTY ELSE (PRICE_ORI/SELL_RATE)*QTY END)) AS TOTALME,  
 SUM(COSTOME*QTY) AS COSTO_ME,  
 SUM((CASE WHEN CURRENCY_ID=''ME'' THEN (PRICE_ORI*SELL_RATE)*QTY ELSE PRICE_ORI*QTY  END)) AS TOTALMN,  
 SUM(COSTOMN_REAL*QTY) AS COSTO_MN,  
 SUM(QTY) AS CANTIDAD  
 FROM [tempdb].dbo.COSTOS'+@PC+'   
 GROUP BY PART_ID,PART_DESCRIPTION')  


