 /*CREADO POR EVG - 20/03/2007*/        
CREATE PROC [dbo].[HSP_LIST_FACTURAS_DET]        
--DECLARE        
  @EMP AS VARCHAR(50),        
  @OPCION AS VARCHAR(1),  
  @DFTD AS VARCHAR(2),  
  @DFNUMSER AS VARCHAR(3),  
  @DFNUMDOC AS VARCHAR(7)        
/*        
  SET @OPCION='1'        
  SET @EMP='001'          
  SET @NUMPED='0000009'        
 */       
AS        
  DECLARE @STRcadena NVARCHAR(1000)        
        
 IF @OPCION='1'         
    SET @STRcadena='SELECT D.WAREHOUSE_ID,D.PART_ID,(CASE WHEN D.PART_ID<>''TEXTO'' THEN D.PART_DESCRIPTION ELSE D.TEXT_DESCRIPTION END)  AS COL1,D.UNIT,         
    (CASE WHEN D.PART_SERIE <> '''' THEN D.PART_SERIE ELSE (CASE WHEN D.PART_LOT <> '''' THEN D.PART_LOT ELSE D.PART_LOT END)END)AS COL2,        
     D.QTY,D.PRICE_SALES,(CASE WHEN C.CURRENCY_ID=''ME'' THEN D.AMOUNT_US ELSE D.AMOUNT END) AS COL3,D.PRICE_ORI,  
     D.QTY_REF,D.DISCOUNT_CUSTOMER,D.DISCOUNT_SP,D.DISCOUNT_PERCENT,D.DISCOUNT,D.TAX_PERCENT     
     FROM ' + @EMP + '.dbo.RECEIVABLE_LINE D INNER JOIN ' + @EMP + '.dbo.RECEIVABLE C ON D.DOCUMENT_ID=C.DOCUMENT_ID AND  
     D.NUMBER_SERIE =C.NUMBER_SERIE AND D.DFNUMDOC=C.NUMBER_DOCUMENT
     WHERE DOCUMENT_ID='''+@DFTD+''' AND NUMBER_SERIE='''+@DFNUMSER+''' AND NUMBER_DOCUMENT='''+@DFNUMDOC+''''     
                                         
 IF @OPCION='2'         
    SET @STRcadena='SELECT * FROM ' + @EMP + '.DBO.RECEIVABLE_LINE WHERE DOCUMENT_ID='''+@DFTD+''' AND   
                    NUMBER_SERIE='''+@DFNUMSER+''' AND NUMBER_DOCUMENT='''+@DFNUMDOC+''''        
       
        
 SET @STRcadena=@strcadena+' ORDER BY ITEM'        
        
EXEC SP_EXECUTESQL @STRcadena,N'@EMP VARCHAR(3),@OPCION VARCHAR(1),@DFTD VARCHAR(2),@DFNUMSER VARCHAR(3), @DFNUMDOC VARCHAR(7)'        
                  ,@EMP,@OPCION,@DFTD,@DFNUMSER,@DFNUMDOC        
      
    
  
  
  