  /*CREADO POR KBH - 07/03/2007*/  
CREATE PROC [dbo].[HSP_LIST_CLIENTES_1]  
--DECLARE  
  @EMP AS VARCHAR(3),  
  @OPCION AS CHAR(1)  
/*  
  SET @EMP='001'  
  SET @OPCION='1'  
*/  
AS  
  DECLARE @STRcadena NVARCHAR(400)  
  
 IF @OPCION='1'   /*MUESTRA SOLOS LOS ARTICULOS CON CONTROL DE STOCK Y VIGENTES*/  
    SET @STRcadena='SELECT ID, NAME, VAT_REGISTRATION,ADDR, OBSERV FROM    
                   CUSTOMER ORDER BY ID'  
  
  
EXEC SP_EXECUTESQL @STRcadena,N'@EMP VARCHAR(3),@OPCION CHAR(1)',@EMP,@OPCION  
  