 create procedure [dbo].[HSP_RECIBOS_DEP_TEMPORAL_PROV_EX]  
 --declare  
 @EMP varchar(3),  
 @COD_DMAY varchar(10),  
 @FEC_INICIO varchar(10),  
 @FEC_FINAL varchar(10)  
/*set @EMP='002'  
set @COD_DMAY='58113'  
set @FEC_INICIO='01/06/2007'  
set @FEC_FINAL='30/11/2007'  
--*/as  
 exec('set QUOTED_IDENTIFIER ON SELECT AO.COD_OPER,' + @COD_DMAY + ' as COD_MAYOR,PO.COD_OSINERG,  
   B.QTY/PO.FACTOR AS VOLUMEN,  
   A.DATE_DOCUMENT,PS.CODIGO_SPIC as COD_PROVE_SPIC,  
   M.NUMBER_REGISTRATION AS PLACA_TRACTO,TDG.PLACA,'''' AS OTRO_TRANS,  
   TDG.DGH AS REG_DGH,A.WAREHOUSE_ID,B.PART_ID,PO.FACTOR,M.ID,A.VENDOR_ID  
   FROM WAREHOUSE_TRANS A  
   INNER JOIN WAREHOUSE_TRANS_LINE B ON A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT 
   INNER JOIN ALMACEN_OSINERG AO ON AO.COD_DMAY=' + @COD_DMAY  + ' AND AO.COD_ALMACEN=A.WAREHOUSE_ID and AO.TIPO_ALMACEN=''F''  
   LEFT JOIN CARRIER M ON M.ID=A.CARRIER_ID     
   INNER JOIN PRODUCTOS_OSINERG PO ON PO.COD_PRODUCTO=B.PART_ID 
   LEFT JOIN TRANS_DGH TDG on TDG.CODIGO=M.ID 
   LEFT JOIN PROVSPIC PS ON A.VENDOR_ID=PS.CODPRO  
   WHERE A.DATE_DOCUMENT BETWEEN '''+ @FEC_INICIO + ''' AND ''' + @FEC_FINAL +  
   ''' AND A.TYPE_TRANS=''I'' AND (A.TRANS_ID=''CI'') AND B.PART_ID<>''TEXTO''  
   GROUP BY AO.COD_OPER,PO.COD_OSINERG,B.QTY,PO.FACTOR,A.DATE_DOCUMENT,PS.CODIGO_SPIC,M.NUMBER_REGISTRATION,  
   TDG.PLACA,TDG.DGH,A.WAREHOUSE_ID,B.PART_ID,M.ID,A.VENDOR_ID
   ORDER BY A.DATE_DOCUMENT')  