
  CREATE PROCEDURE [dbo].[HSP_COPIA_ART]  
 --DECLARE  
 @EMP VARCHAR(3)  
 --SET @EMP='002'  
 AS  
 EXEC('  
 INSERT INTO ESTADO_PRODUCTO(CODIGO_PRO,DESCRIPCION,ESTADO)  
 SELECT M.ID,M.DESCRIPTION,1 AS ESTADO FROM PART M  
 WHERE M.ID NOT IN (SELECT CODIGO_PRO FROM ESTADO_PRODUCTO)  
 ')  
  
  