CREATE PROCEDURE [dbo].[HSP_CARTERA_TIPO]    
-- DECLARE    
 @EMP varchar(50),    
 @CLI_INI varchar(11),    
 @CLI_FIN varchar(11),    
 @VEN_INI varchar(2),    
 @VEN_FIN varchar(2),    
 @OPT VARCHAR(1)     
  /*  
 SET @EMP='COMERCIAL'    
 SET @CLI_INI='01'    
 SET @CLI_FIN='20533984992'    
 SET @VEN_INI='01'    
 SET @VEN_FIN='08'    
 SET @OPT='D'    
--*/AS    
 DECLARE @CADENA VARCHAR(50)    
 IF @OPT='D'     
  SET @CADENA='AND C.IS_DR_CR=''D'' AND C.AMOUNT_BALANCE>0'    
 IF @OPT='H'     
     SET @CADENA='AND C.IS_DR_CR=''H'' AND C.AMOUNT_BALANCE<0'    
    
    
 exec('SELECT C.CUSTOMER_ID,M.NAME,C.DOCUMENT_ID,C.NUMBER_DOC,C.DOC_DATE,C.CADUCATE_DATE,C.AMOUNT_BALANCE AS SALDO,    
 (CASE WHEN c.CURRENCY_ID=''ME'' THEN C.AMOUNT_BALANCE ELSE C.AMOUNT_BALANCE/C.SELL_RATE END) AS SALDOME,    
 (CASE WHEN c.CURRENCY_ID=''MN'' THEN C.AMOUNT_BALANCE ELSE C.AMOUNT_BALANCE*C.SELL_RATE END) AS SALDOMN,    
 C.CURRENCY_ID,C.SELL_RATE,V.ID,V.NAME  AS NAME_V  
 FROM ['+ @EMP+ '].DBO.CUSTOMER_BALANCE C    
 INNER JOIN ['+ @EMP + '].DBO.CUSTOMER M ON C.CUSTOMER_ID=M.ID    
 INNER JOIN ['+ @EMP + '].DBO.SALES_REP V ON C.SALES_ID=V.ID    
 WHERE C.CUSTOMER_ID>='''+@CLI_INI +''' AND C.CUSTOMER_ID<='''+@CLI_FIN+'''    
 AND C.SALES_ID>='''+@VEN_INI +''' AND C.SALES_ID<='''+@VEN_FIN+'''    
 AND C.STATUS<>''A''' + @CADENA +'    
 ')    
    
    
    
    
    
    
    