   /*CREADO POR EVG - 07/03/2007*/  
CREATE PROC [dbo].[HSP_LIST_ARTICULOS]  
--DECLARE  
  @EMP AS VARCHAR(3),  
  @OPCION AS CHAR(1)  
  
/*  
  SET @EMP='001'  
  SET @OPCION='1'  
*/  
AS  
  DECLARE @STRcadena NVARCHAR(400)  
  
 IF @OPCION='1'   /*MUESTRA SOLOS LOS ARTICULOS CON CONTROL DE STOCK Y VIGENTES*/  
    SET @STRcadena='SELECT ID, DESCRIPTION, UNIT_OF_MEASUREMENT,STATUS, ACCOUNT FROM  PART WHERE  
                   STATUS=''V'' AND NOT(IS_LOT=''N'' AND IS_STOCKED=''N'' AND SERIES=''N'') ORDER BY ID'  
  
ELSE  /*MUESTRA TODOS*/  
    SET @STRcadena='SELECT ID, DESCRIPTION, UNIT_OF_MEASUREMENT,STATUS,ACCOUNT FROM  PART   
                                    ORDER BY ID'  
  
  
EXEC SP_EXECUTESQL @STRcadena,N'@EMP VARCHAR(3),@OPCION CHAR(1)',@EMP,@OPCION  