create procedure [dbo].[HSP_REMARCACIONES_VARIACION_MERMAS]  
 --declare  
 @EMP varchar(3),  
 @COD_DMAY varchar(10),  
 @FEC_INICIO varchar(10),  
 @FEC_FINAL varchar(10)  
/*set @EMP='002'  
set @COD_DMAY='58137'  
set @FEC_INICIO='01/11/2007'  
set @FEC_FINAL='30/11/2007'  
--*/as  
  
exec('set QUOTED_IDENTIFIER ON  
 SELECT T.COD_OPER,T.COD_OSINERG,'+@COD_DMAY + ' AS COD_MAYOR,  
   SUM(T.VOLUMEN_I) AS INGRESO,SUM(T.VOLUMEN_S) AS SALIDA,  
   SUM(T.VOLUMEN_I - T.VOLUMEN_S) AS SALDO,'''+ @FEC_FINAL +''' AS FECHA  
 FROM  
  (  
   (SELECT AO.COD_OPER,PO.COD_OSINERG,  
   SUM(B.QTY/PO.FACTOR) AS VOLUMEN_I,0 AS VOLUMEN_S  
   FROM WAREHOUSE_TRANS A  
   INNER JOIN WAREHOUSE_TRANS_LINE B ON A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT  
   INNER JOIN ALMACEN_OSINERG AO ON AO.COD_DMAY='+ @COD_DMAY +' AND AO.COD_ALMACEN=A.WAREHOUSE_ID and AO.TIPO_ALMACEN=''C''  
   INNER JOIN PRODUCTOS_OSINERG PO ON PO.COD_PRODUCTO=B.PART_ID   
   WHERE A.DATE_DOCUMENT BETWEEN '''+@FEC_INICIO + '''  AND ''' + @FEC_FINAL + ''' AND A.DOCUMENT_ID=''NI''  
   AND (A.TRANS_ID=''AJ'' OR A.TRANS_ID=''IL'' OR A.TRANS_ID=''EI'' OR A.TRANS_ID=''IA'' OR A.TRANS_ID=''IM'')  
   AND B.PART_ID<>''TEXTO''  
   GROUP BY AO.COD_OPER,PO.COD_OSINERG)  
     
   UNION  
  
   (SELECT AO.COD_OPER,PO.COD_OSINERG,  
   0 AS VOLUMEN_S,SUM(B.QTY/PO.FACTOR) AS VOLUMEN  
   FROM WAREHOUSE_TRANS A  
   INNER JOIN WAREHOUSE_TRANS_LINE B ON A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT 
   INNER JOIN ALMACEN_OSINERG AO ON AO.COD_DMAY='+@COD_DMAY+ ' AND AO.COD_ALMACEN=A.WAREHOUSE_ID and AO.TIPO_ALMACEN=''C''  
   INNER JOIN PRODUCTOS_OSINERG PO ON PO.COD_PRODUCTO=B.PART_ID   
   WHERE A.DATE_DOCUMENT BETWEEN ''' + @FEC_INICIO + ''' AND '''+ @FEC_FINAL + ''' AND A.DOCUMENT_ID=''NS''  
   AND (A.TRANS_ID=''AJ'' OR A.TRANS_ID=''SL'' OR A.TRANS_ID=''SA'' OR A.TRANS_ID=''SF'' OR A.TRANS_ID=''SM'')  
   AND B.PART_ID<>''TEXTO''  
   GROUP BY AO.COD_OPER,PO.COD_OSINERG)  
  )   
   AS T  
 GROUP BY T.COD_OPER,T.COD_OSINERG')  
  
  
  