--HSP_LIST_CLIENTES_GENERAL
CREATE PROCEDURE [dbo].[HSP_LIST_CLIENTES_GENERAL]  
@CLIINI AS VARCHAR(20),  
@CLIFIN AS VARCHAR(20)  
AS  
  DECLARE @STRcadena NVARCHAR(1000)  
  DECLARE @TDIS NVARCHAR(2)  
  set @TDIS='13'  
  set @STRcadena='SELECT M.ID,M.NAME,M.ADDR,M.PHONE,M.VAT_REGISTRATION,M.NUMBER_DOC,M.DISCOUNT_PERCENT,
		M.TERMS_TYPE,M.STATUS,M.OPEN_DATE,  
 M.CONTACT,M.STATE_ID,T.DESCRIPTION,M.TYPE_PRICE,M.SALES_ID,V.NAME,M.SELL_ZONE,M.COUNTRY,M.DEPARTMENT,M.PROVINCE,M.ADDR_DLV,  
    M.CURRENCY_CREDIT_LIMIT,M.CREDIT_LIMIT_US,M.CREDIT_LIMIT,  
    M.BALANCE,M.BALANCE_US,M.FAX_NUMBER,M.EMAIL,M.COMMENT,  
    M.IS_PRIMARY,M.RETENTION  
 FROM CUSTOMER M  
 LEFT JOIN MASTER_HELP T ON M.STATE_ID=T.ID AND T.TYPE_ID=@TDIS  
 LEFT JOIN SALES_REP V ON M.SALES_ID=V.ID   
 WHERE M.ID BETWEEN @CLIINI AND @CLIFIN  
 order by M.ID'  
  
 EXEC sp_executesql @STRcadena,N'@TDIS NVARCHAR(2),@CLIINI AS VARCHAR(20),@CLIFIN AS VARCHAR(20)',  
     @TDIS,@CLIINI,@CLIFIN  

