--HSP_PED_FAC_GUIA
CREATE procedure [dbo].[HSP_PED_FAC_GUIA]  
 --DECLARE  
 @FECHAINI as VARCHAR(10),  
 @FECHAFIN as VARCHAR(10)  
as  
 
 --SET @FECHAINI='01/01/2007'  
 --SET @FECHAFIN='01/01/2007'  
  
 DECLARE @STRcadena NVARCHAR(2000)  
 declare @STRG nvarchar(2)  
 declare @STRGF nvarchar(2)  
 set @STRG='GS'  
 set @STRGF='GF'  
  
 set @STRcadena='SELECT FC.DOCUMENT_ID,FC.NUMBER_SERIE,FC.NUMBER_DOCUMENT,FC.DOCUMENT_DATE AS FECHAFAC,FC.NUMBER_ORDER,  
   FC.DOCUMENT_REF,FC.SERIE_REF,FC.NUMBER_REF,PC.ID,PC.ORDER_DATE AS FECHAPED,  
   T.DATE_DOCUMENT AS FECHAGUIA,MD.PART_ID,MD.PART_DESCRIPTION,MD.QTY,MD.AMOUNT_SALES,PC.CUSTOMER_NAME,PC.CUSTOMER_ID,PC.USER_ID,  
            PC.CADUCATE_DATE AS FECHAENT, DATEDIFF(dd, (PC.CADUCATE_DATE), (FC.DOCUMENT_DATE)) AS FECHADIF  
   FROM RECEIVABLE FC  
   INNER JOIN ORDERS PC ON FC.NUMBER_ORDER=PC.ID  
   INNER JOIN WAREHOUSE_TRANS MC ON   
   FC.DOCUMENT_ID=MC.DOCUMENT_ID AND FC.NUMBER_SERIE=LEFT(MC.NUMBER_DOCUMENT,3)  
   AND FC.NUMBER_DOCUMENT=SUBSTRING(MC.NUMBER_DOCUMENT,4,LEN(MC.NUMBER_DOCUMENT))  
   INNER JOIN WAREHOUSE_TRANS_LINE MD ON MC.WAREHOUSE_ID=MD.WAREHOUSE_ID AND MC.DOCUMENT_ID=MD.DOCUMENT_ID AND MC.NUMBER_DOCUMENT=MD.NUMBER_DOCUMENT 
   INNER JOIN   
     (SELECT M.* FROM RECEIVABLE F   
      INNER JOIN WAREHOUSE_TRANS M ON   
      F.DOCUMENT_REF=M.DOCUMENT_ID AND F.SERIE_REF=LEFT(M.NUMBER_DOCUMENT,3)  
      AND F.NUMBER_REF=SUBSTRING(M.NUMBER_DOCUMENT,4,LEN(M.NUMBER_DOCUMENT))  
      WHERE M.DOCUMENT_ID=@STRG AND M.TRANS_ID=@STRGF) AS T  
   ON FC.DOCUMENT_REF=T.DOCUMENT_ID AND FC.SERIE_REF=LEFT(T.NUMBER_DOCUMENT,3)  
   AND FC.NUMBER_REF=SUBSTRING(T.NUMBER_DOCUMENT,4,LEN(T.NUMBER_DOCUMENT))  
   WHERE PC.ORDER_DATE >=@FECHAINI AND PC.ORDER_DATE<=@FECHAFIN AND MD.PART_ID<>''TEXTO'''  
    
  
   
 execute sp_executesql @STRcadena,N'@FECHAINI as VARCHAR(10),@FECHAFIN as VARCHAR(10),  
     @STRG as nvarchar(2),@STRGF as nvarchar(2)',@FECHAINI,@FECHAFIN,@STRG,@STRGF  
  
  