CREATE PROC [dbo].[insert_tmp_user]  
@PUSUARIO VARCHAR(50),  
@PNOMPC VARCHAR(50),  
@PUSER_SQL VARCHAR(50),  
@PPASS_SQL VARCHAR(50),  
@PCOMPANY VARCHAR(150),  
@PCODEMPRESA VARCHAR(50),  
@PNOMEMP_PANTALLA VARCHAR(50),  
@PNOMEMP_REPORTES VARCHAR(50),  
@PWORKDATE datetime
AS  
  
DECLARE @COD_ALM VARCHAR(2)
DECLARE @DES_ALM VARCHAR(25)
SELECT @COD_ALM=id,@DES_ALM=name FROM WAREHOUSE WHERE IS_DEFAULT ='1'

exec('SET QUOTED_IDENTIFIER OFF
INSERT INTO tempdb.dbo.'+@PNOMPC+'  
(USUARIO  
,NOMPC  
,USER_SQL  
,PASS_SQL  
,COMPANY  
,CODEMPRESA  
,NOMEMP_PANTALLA  
,NOMEMP_REPORTES  
,CODALMACEN  
,NOMALMACEN  
,WORKDATE)  
VALUES  
("'+@PUSUARIO+'","'+@PNOMPC+'","'+@PUSER_SQL+'","'+@PPASS_SQL+'","'+@PCOMPANY+'","'+@PCODEMPRESA+'","
'+@PNOMEMP_PANTALLA+'","'+@PNOMEMP_REPORTES+'","'+@COD_ALM+'","'+@DES_ALM+'","'+@PWORKDATE+'")') 
