CREATE procedure [dbo].[INV_RPT_LIST_WAREHOUSE]
as
	declare @STRquery nvarchar(1000)
	set @STRquery='SELECT W.ID,W.NAME,STATE_ID, DESCRIPTION AS NAMEDIST, PHONE,LAST_NUM_IN,LAST_NUM_OUT,		
		ADDR_WHO,TYPE_PART
		FROM WAREHOUSE W LEFT JOIN MASTER_HELP M ON W.STATE_ID=M.ID AND TYPE_ID=''13'' ORDER BY M.ID'
	set @STRquery=@STRquery
	exec sp_executesql @STRquery