CREATE  procedure [dbo].[INV_RECALCULO_STOCK]
--DECLARE
@IDE AS VARCHAR(80), @alma AS VARCHAR(250),@mesAnt AS VARCHAR(2),@anoAnt AS VARCHAR(4),
@mesActual AS VARCHAR(2),@anoActual AS VARCHAR(4),@ART1 AS VARCHAR(20),
@ART2 AS VARCHAR(20),@TODOS AS VARCHAR(1)
--SET @BASE='008BDCOMUN'
--SET @IDE='PC_D05'
--SET @alma='"01"'
--SET @mesAnt='08'
--SET @anoAnt='2004'
--SET @mesActual='09'
--SET @anoActual='2004'
--SET @ART1=''
--SET @ART2=''
--SET @TODOS='0'
---WITH ENCRYPTION
AS
SET NOCOUNT ON
DECLARE @Arti AS VARCHAR(20)
DECLARE @Ing As numeric(15,6)
DECLARE @Sal AS numeric(15,6)
DECLARE @Ingchar as VARCHAR(30)
DECLARE @Salchar as VARCHAR(30)
DECLARE @IngRef AS numeric(15,6)
DECLARE @SalRef AS numeric(15,6)
DECLARE @TotalMes as VARCHAR(30)
DECLARE @ARTICULOS AS VARCHAR(70)
DECLARE @ARTICULOS2 AS VARCHAR(70)
DECLARE @MORES AS VARCHAR(6)
DECLARE @TEXTO AS VARCHAR(1000)
declare @estilo as int
declare @saldomoresme as varchar(30)
DECLARE @ALMACEN AS VARCHAR(20)
DECLARE @ALMA2 AS VARCHAR(2)
DECLARE @mesSiguiente as varchar(2)
DECLARE @ALMAMOR AS VARCHAR(2)
DECLARE @CODIGOMORES AS int

SET @ARTICULOS=CASE WHEN @TODOS=1 THEN
	'AND B.PART_ID>="'+@ART1+'" AND B.PART_ID<="'+@ART2+'" '
WHEN @TODOS=0 THEN
	' '
END
SET @ARTICULOS2=CASE WHEN @TODOS=1 THEN
	'AND S.PART_ID>="'+@ART1+'" AND S.PART_ID<="'+@ART2+'" '
WHEN @TODOS=0 THEN
	' '
END

	IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'TMPMORESMES')

	BEGIN   
   		EXEC('DROP TABLE TEMPDB.DBO.'+@IDE+'TMPMORESMES')
	END   

	/*	EXEC('set quoted_identifier off DECLARE RECALC_MORESMES1 CURSOR FOR
		SELECT YEAR_MONTH FROM MONTHLY_SUMMARIZE where YEAR_MONTH="'+@anoActual+@mesActual+'"')
	*/
		set quoted_identifier off 
		DECLARE RECALC_MORESMES1 CURSOR FOR
		SELECT YEAR_MONTH FROM MONTHLY_SUMMARIZE 
		where YEAR_MONTH=''+@anoActual+@mesActual+''
	
		set @estilo=0

		OPEN RECALC_MORESMES1
		FETCH NEXT FROM RECALC_MORESMES1 INTO @MORES

	    	WHILE @@FETCH_STATUS=0
			BEGIN
				set @estilo=1
				FETCH NEXT FROM RECALC_MORESMES1 INTO @MORES
         		END
		CLOSE RECALC_MORESMES1
		DEALLOCATE RECALC_MORESMES1
		if @estilo=0
			begin
				EXEC('set quoted_identifier off select * into tempdb.dbo.'+@IDE+'TMPMORESMES from MONTHLY_SUMMARIZE where YEAR_MONTH="'+@anoAnt+@mesAnt+'" and WAREHOUSE_ID in('+@alma+')')
				EXEC('set quoted_identifier off update tempdb.dbo.'+@IDE+'tmpmoresmes set YEAR_MONTH="'+@anoActual+@mesActual+'",
	      			QTY_INITIAL=(QTY_INITIAL+QTY_ENTER)-QTY_OUT,QTY_ENTER=0.000000,QTY_OUT=0.000000 WHERE  YEAR_MONTH="'+@anoAnt+@mesAnt+'"')
				EXEC('set quoted_identifier off insert into MONTHLY_SUMMARIZE select * from tempdb.dbo.'+@IDE+'TMPMORESMES')
			
				EXEC('set quoted_identifier off update S set QTY_ON_HAND=ISNULL((QTY_INITIAL+QTY_ENTER)-QTY_OUT,0.000000)
				from PART_QTY s inner join MONTHLY_SUMMARIZE m on s.PART_ID=m.PART_ID and s.WAREHOUSE_ID=m.WAREHOUSE_ID
				inner join PART a on s.PART_ID=a.ID
				WHERE M.YEAR_MONTH="'+@anoAnt+@mesAnt+'" '+@ARTICULOS2+' and A.IS_STOCKED="S" and M.WAREHOUSE_ID in('+@alma+')')
   			end
		ELSE
			BEGIN	
				exec('set quoted_identifier off update S set QTY_ON_HAND=0 FROM PART_QTY S INNER JOIN PART M ON
				S.PART_ID=M.ID WHERE M.IS_STOCKED="S" '+@ARTICULOS2+' and S.WAREHOUSE_ID in ('+@alma+')') 
				
				IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'TMPNOSALDO')

				BEGIN   
   					EXEC('DROP TABLE tempdb.dbo.'+@IDE+'TMPNOSALDO')
				END 
				EXEC('CREATE TABLE tempdb.dbo.'+@IDE+'TMPNOSALDO (DECODIGO VARCHAR(20),ALMACEN VARCHAR(2),
				INGRESO NUMERIC(15,6),SALIDA NUMERIC(15,6))')

				EXEC('set quoted_identifier off INSERT INTO tempdb.dbo.'+@IDE+'TMPNOSALDO 
				SELECT B.PART_ID,B.WAREHOUSE_ID,SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)AS INGRESO,
				SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END)as SALIDA from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON 
				A.WAREHOUSE_ID = B.WAREHOUSE_ID AND A.DOCUMENT_ID = B.DOCUMENT_ID AND A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID = C.ID
				WHERE C.IS_STOCKED="S" and B.WAREHOUSE_ID in('+@alma+') AND A.STATUS_GUIA<>"A" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F") 
				AND NOT (C.IS_STOCKED="N" AND C.IS_STOCKED="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")
				AND (cast(MONTH(A.DATE_DOCUMENT)as varchar(2))+cast(year(A.DATE_DOCUMENT)as varchar(4)))<'+@mesActual+@anoAnt+' GROUP BY B.PART_ID,B.WAREHOUSE_ID ORDER BY B.PART_ID ASC')
				
				EXEC('set quoted_identifier off update s set QTY_ON_HAND=ISNULL(INGRESO-SALIDA,0)
				from PART_QTY s inner join tempdb.dbo.'+@IDE+'TMPNOSALDO t on s.PART_ID=t.DECODIGO and s.WAREHOUSE_ID=t.ALMACEN')
			
			END

	IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'RECALCULO_STOCK')

	BEGIN   
   		EXEC('DROP TABLE tempdb.dbo.'+@IDE+'RECALCULO_STOCK')
	END 
	EXEC('CREATE TABLE tempdb.dbo.'+@IDE+'RECALCULO_STOCK (DECODIGO VARCHAR(20),ALMACEN VARCHAR(2),
	Ingresos NUMERIC(15,6),Salida NUMERIC(15,6),IngresosRef NUMERIC(15,6),SalidasRef NUMERIC(15,6))')

	EXEC('set quoted_identifier off INSERT INTO TEMPDB.DBO.'+@IDE+'RECALCULO_STOCK
	select B.PART_ID,B.WAREHOUSE_ID,
	SUM((CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)) AS Ingresos,
	SUM((CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END)) AS Salida,
	SUM((CASE WHEN A.TYPE_TRANS="I" THEN B.QTY_REFERENCE ELSE 0 END))IngresosRef,
	SUM((CASE WHEN A.TYPE_TRANS="S" THEN B.QTY_REFERENCE ELSE 0 END))SalidasRef
	FROM  (WAREHOUSE_TRANS  A INNER JOIN WAREHOUSE_TRANS_LINE B ON (A.WAREHOUSE_ID = B.WAREHOUSE_ID) AND (A.DOCUMENT_ID = B.DOCUMENT_ID) AND 
	(A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT)) INNER JOIN PART C ON B.PART_ID = C.ID
	WHERE C.IS_STOCKED="S" and B.WAREHOUSE_ID IN('+@alma+') AND A.STATUS_GUIA<>"A" '+@ARTICULOS+'
	AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F") 
	AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")
	AND REPLICATE("0",2-LEN(MONTH(A.DATE_DOCUMENT)))+MONTH(A.DATE_DOCUMENT)='+@mesActual+' and year(A.DATE_DOCUMENT)='+@anoActual+' 
	GROUP BY B.PART_ID,B.WAREHOUSE_ID')
	

		EXEC('set quoted_identifier off UPDATE S set QTY_ON_HAND=ISNULL((QTY_ON_HAND+Ingresos)-Salida,0.000000)
		FROM PART_QTY s inner join tempdb.dbo.'+@IDE+'RECALCULO_STOCK T ON
		S.PART_ID=T.DECODIGO AND S.WAREHOUSE_ID=T.ALMACEN')
		
		if @estilo=0
			begin
				EXEC('set quoted_identifier off update m set QTY_INITIAL=(QTY_INITIAL+QTY_ENTER)-QTY_OUT FROM MONTHLY_SUMMARIZE M INNER JOIN
				tempdb.dbo.'+@IDE+'RECALCULO_STOCK T ON M.WAREHOUSE_ID=T.ALMACEN AND M.PART_ID=T.DECODIGO WHERE 
				YEAR_MONTH="'+@anoActual+@mesActual+'"')
   			end

		/*EXEC('set quoted_identifier off DECLARE RECALC_MORESMES2 CURSOR FOR
		SELECT YEAR_MONTH FROM MONTHLY_SUMMARIZE where YEAR_MONTH="'+@anoAnt+@mesAnt+'"')*/
		set quoted_identifier off 
		DECLARE RECALC_MORESMES2 CURSOR FOR
		SELECT YEAR_MONTH FROM MONTHLY_SUMMARIZE where YEAR_MONTH=''+@anoAnt+@mesAnt+''
		
		set @CODIGOMORES=0

		OPEN RECALC_MORESMES2
		FETCH NEXT FROM RECALC_MORESMES2 INTO @MORES

	    	WHILE @@FETCH_STATUS=0
		BEGIN 
			set @CODIGOMORES=1
			FETCH NEXT FROM RECALC_MORESMES2 INTO @MORES
         		END
		CLOSE RECALC_MORESMES2
		DEALLOCATE RECALC_MORESMES2

	if @CODIGOMORES=0
		begin
			EXEC('set quoted_identifier off UPDATE M SET QTY_ENTER=Ingresos,QTY_OUT=Salida FROM MONTHLY_SUMMARIZE M INNER JOIN
			tempdb.dbo.'+@IDE+'RECALCULO_STOCK T ON M.WAREHOUSE_ID=T.ALMACEN AND M.PART_ID=T.DECODIGO WHERE 
			YEAR_MONTH="'+@anoActual+@mesActual+'"')
		end
	else
		begin
			IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'saldo')

			BEGIN   
   				EXEC('DROP TABLE TEMPDB.DBO.'+@IDE+'saldo')
			END   
			EXEC('create TABLE tempdb.dbo.'+@IDE+'saldo (SALDO NUMERIC(15,6),ALMACEN varchar(2),DECODIGO varchar(20))')
			EXEC ('set quoted_identifier off INSERT INTO tempdb.dbo.'+@IDE+'saldo SELECT (QTY_INITIAL+QTY_ENTER)-QTY_OUT,WAREHOUSE_ID,PART_ID FROM MONTHLY_SUMMARIZE M INNER JOIN
			tempdb.dbo.'+@IDE+'RECALCULO_STOCK T ON M.WAREHOUSE_ID=T.ALMACEN AND M.PART_ID=T.DECODIGO WHERE 
			YEAR_MONTH="'+@anoAnt+@mesAnt+'"')

			EXEC('set quoted_identifier off UPDATE M SET QTY_ENTER=Ingresos,QTY_OUT=Salida FROM MONTHLY_SUMMARIZE M INNER JOIN
			tempdb.dbo.'+@IDE+'RECALCULO_STOCK T ON M.WAREHOUSE_ID=T.ALMACEN AND M.PART_ID=T.DECODIGO WHERE 
			YEAR_MONTH="'+@anoActual+@mesActual+'"')
			
			EXEC('set quoted_identifier off UPDATE M SET QTY_INITIAL=SALDO FROM MONTHLY_SUMMARIZE M INNER JOIN
			tempdb.dbo.'+@IDE+'saldo s ON M.WAREHOUSE_ID=s.ALMACEN AND M.PART_ID=s.DECODIGO inner join tempdb.dbo.'+@IDE+'RECALCULO_STOCK T
			ON M.WAREHOUSE_ID=T.ALMACEN AND M.PART_ID=T.DECODIGO where YEAR_MONTH="'+@anoActual+@mesActual+'"')

		end





