CREATE procedure [dbo].[INV_RECALCULO_STOCK_LOTE]  
--DECLARE  
@alma AS VARCHAR(500),@mesPOST AS VARCHAR(2),@anoPOST AS VARCHAR(4)  
  
/*SET @alma='"01","02"'  
SET @mesPOST='05'  
SET @anoPOST='2007'  
--*/AS  
  
SET NOCOUNT ON  
DECLARE @Arti AS VARCHAR(20)  
DECLARE @Ing AS numeric(15,6)  
DECLARE @Sal AS numeric(15,6)  
DECLARE @LOT AS VARCHAR(20)  
DECLARE @TOTSTK AS VARCHAR(30)  
DECLARE @ALMACEN AS VARCHAR(500)  

EXEC('set quoted_identifier off update S set S.QTY_ON_HAND=0 from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON   
 A.WAREHOUSE_ID = B.WAREHOUSE_ID AND A.DOCUMENT_ID = B.DOCUMENT_ID AND A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID = C.ID 
 inner join PART_QTY S ON S.PART_ID=B.PART_ID AND S.WAREHOUSE_ID=B.WAREHOUSE_ID
where B.WAREHOUSE_ID in('+@alma+') AND A.STATUS_GUIA<>"A" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")   
 AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")AND C.IS_LOT="S"  
 and A.DATE_DOCUMENT<"01/"+"'+@mesPOST+'"+"/"+"'+@anoPOST+'"')  

exec('set quoted_identifier off update S set S.QTY_ON_HAND=0 from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON   
 A.WAREHOUSE_ID = B.WAREHOUSE_ID AND A.DOCUMENT_ID = B.DOCUMENT_ID AND A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID = C.ID 
 inner join PART_QTY S ON S.PART_ID=B.PART_ID AND S.WAREHOUSE_ID=B.WAREHOUSE_ID
where B.WAREHOUSE_ID in('+@alma+') AND A.STATUS_GUIA<>"A" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")   
 AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")AND C.IS_LOT="S"  
 and A.DATE_DOCUMENT<"01/"+"'+@mesPOST+'"+"/"+"'+@anoPOST+'"')  


 /*exec('set quoted_identifier off DECLARE RECALC_STOCK_L CURSOR FOR  
 SELECT B.PART_ID,B.WAREHOUSE_ID,B.NUMBER_LOT,SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)AS INGRESO,  
 SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END)as SALIDA  
 from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON   
 A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID=C.ID  
 WHERE B.WAREHOUSE_ID in('+@alma+') AND A.STATUS_GUIA<>"A" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")   
 AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")AND C.IS_LOT="S"  
 and A.DATE_DOCUMENT<"01/"+"'+@mesPOST+'"+"/"+"'+@anoPOST+'" GROUP BY B.PART_ID,B.WAREHOUSE_ID,B.NUMBER_LOT ORDER BY B.PART_ID ASC')  
  */
 set quoted_identifier off
 DECLARE RECALC_STOCK_L CURSOR FOR  
 SELECT B.PART_ID,B.WAREHOUSE_ID,B.NUMBER_LOT,SUM(CASE WHEN A.TYPE_TRANS='I' THEN B.QTY ELSE 0 END)AS INGRESO,  
 SUM(CASE WHEN A.TYPE_TRANS='S' THEN B.QTY ELSE 0 END)as SALIDA  
 from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON   
 A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT 
 INNER JOIN PART C ON B.PART_ID=C.ID  
 WHERE --B.WAREHOUSE_ID in(''+ @alma +'') AND 
 A.STATUS_GUIA<>'A' AND NOT (A.DOCUMENT_ID='GS' AND A.TRANS_ID='GF'
  AND A.STATUS_GUIA='F')   
 AND NOT (C.IS_STOCKED='N' AND C.SERIES='N' AND C.IS_LOT='N')AND (B.PART_ID<>'TEXTO')AND C.IS_LOT='S'  
 and A.DATE_DOCUMENT<'01/'+@mesPOST+'/'+@anoPOST+'' 
 GROUP BY B.PART_ID,B.WAREHOUSE_ID,B.NUMBER_LOT ORDER BY B.PART_ID ASC  
 
   

 OPEN RECALC_STOCK_L  
 FETCH NEXT FROM RECALC_STOCK_L INTO @Arti,@ALMACEN,@LOT,@Ing,@Sal  
  
WHILE @@FETCH_STATUS =0  
BEGIN  

  SET @TOTSTK=@Ing-@Sal  
  declare @cuenta int   
  declare @cuenta2 int   

  exec INV_STKLOTE @ALMACEN,@Arti,@LOT,@cuenta output  
  if @cuenta=0   
   begin  
      exec('set quoted_identifier off insert into LOT(WHO_ID,PART_ID,LOT_ID,QTY_ON_HAND)values("'+@ALMACEN+'","'+@Arti+'","'+@LOT+'","'+@TOTSTK+'")')  
   end  
  else  
   begin  
   exec('set quoted_identifier off UPDATE LOT SET QTY_ON_HAND=QTY_ON_HAND+'+@TOTSTK+'   
   where WHO_ID="'+@ALMACEN+'" and PART_ID="'+@Arti+'" and LOT_ID="'+@LOT+'"')  
   end  
    
  exec INV_STKART @ALMACEN,@Arti,@cuenta2 output  
  if @cuenta2=0   
   begin  
      exec('set quoted_identifier off insert into PART_QTY(WAREHOUSE_ID,PART_ID,QTY_ON_HAND)values("'+@ALMACEN+'","'+@Arti+'","'+@TOTSTK+'")')  
   end  
  else  
   begin  
   exec('set quoted_identifier off UPDATE PART_QTY SET QTY_ON_HAND=QTY_ON_HAND+'+@TOTSTK+'  
   where PART_ID="'+@Arti+'" and WAREHOUSE_ID="'+@ALMACEN+'"')  
   end  
  
  
 FETCH NEXT FROM RECALC_STOCK_L INTO @Arti,@ALMACEN,@LOT,@Ing,@Sal  
END   
  
CLOSE RECALC_STOCK_L  
DEALLOCATE RECALC_STOCK_L 
