CREATE procedure [dbo].[INV_MORESMESLOT]  
--DECLARE  
@ide as varchar(50), @alma as varchar(500),
@mesAnt as varchar(2),@anoAnt as varchar(4),  
@mesActual as varchar(2),@anoActual as varchar(4)  
/*SET @IDE='developer03'  
SET @alma='"01","02"'  
SET @mesAnt='06'  
SET @anoAnt='2000'  
SET @mesActual='07'  
SET @anoActual='2000'  
--*/AS  
SET NOCOUNT ON  
DECLARE @MORESMES VARCHAR(6)  
SET @MORESMES=@anoActual+@mesActual  
  
 IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'TMPNOSALDOLOTE')  
  BEGIN     
      EXEC('DROP TABLE TEMPDB.DBO.'+@IDE+'TMPNOSALDOLOTE')  
  END   
 EXEC ('CREATE TABLE TEMPDB.DBO.'+@IDE+'TMPNOSALDOLOTE (ALMACEN VARCHAR(2),DECODIGO VARCHAR(20),  
 SMMESPRO VARCHAR(6),LOTE VARCHAR(20),INGRESO NUMERIC(15,6),SALIDA NUMERIC(15,6),SALDO NUMERIC(15,6))')  
  
 exec ('set quoted_identifier off INSERT INTO TEMPDB.DBO.'+@IDE+'TMPNOSALDOLOTE  
 SELECT B.WAREHOUSE_ID,B.PART_ID,"'+@MORESMES+'",B.NUMBER_LOT,SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)AS INGRESO,  
 SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END)as SALIDA,  
 SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)-SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END) AS SALDO  
 from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON   
 A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID = B.DOCUMENT_ID AND A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID=C.ID  
 WHERE B.WAREHOUSE_ID in('+@alma+') AND A.STATUS_GUIA<>"A" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")   
 AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")AND C.IS_LOT="S"  
 and A.DATE_DOCUMENT<"01/"+"'+@mesActual+'"+"/"+"'+@anoActual+'" GROUP BY B.PART_ID,B.WAREHOUSE_ID,B.NUMBER_LOT ORDER BY B.PART_ID ASC')  
  
 declare @@cuenta2 int   
 SET @@cuenta2=0  
 exec INV_EXISTEMORESMESLOT @MORESMES,@@cuenta2 output  
 if @@cuenta2=0   
     BEGIN  
  EXEC ('set quoted_identifier off insert into MONTHLY_SUMMARIZE_LOT(WAREHOUSE_ID,PART_ID,YEAR_MONTH,LOT_ID,QTY_ENTER,QTY_OUT,QTY_INITIAL,  
  AMOUNT_US,AMOUNT,AMOUNT_PREVIOUS_US,AMOUNT_PREVIOUS,LAST_MOVE,QTY_ACT,GROUP_PART_ID,FAMILY_PART_ID,LINE_PART_ID,TYPE)  
  select ALMACEN,DECODIGO,SMMESPRO,LOTE,0.000000,0.000000,SALDO,0.000000,0.000000,0.000000,0.000000,0.000000,  
  0.000000,"","","","" from TEMPDB.DBO.'+@IDE+'TMPNOSALDOLOTE')  
     END   
 ELSE  
     BEGIN  
  
  exec ('set quoted_identifier off  DELETE FROM MONTHLY_SUMMARIZE_LOT WHERE YEAR_MONTH="'+@MORESMES+'"')  
  exec('set quoted_identifier off  insert into MONTHLY_SUMMARIZE_LOT(WAREHOUSE_ID,PART_ID,YEAR_MONTH,LOT_ID,QTY_ENTER,QTY_OUT,QTY_INITIAL,  
  AMOUNT_US,AMOUNT,AMOUNT_PREVIOUS_US,AMOUNT_PREVIOUS,LAST_MOVE,QTY_ACT,GROUP_PART_ID,FAMILY_PART_ID,LINE_PART_ID,TYPE)  
  select ALMACEN,DECODIGO,SMMESPRO,LOTE,0.000000,0.000000,SALDO,0.000000,0.000000,0.000000,0.000000,0.000000,  
  0.000000,"","","","" from TEMPDB.DBO.'+@IDE+'TMPNOSALDOLOTE')  
     END  
  
  
 IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'RECALCULO_STOCK_LOTE')  
  
 BEGIN     
     EXEC('set quoted_identifier off DROP TABLE tempdb.dbo.'+@IDE+'RECALCULO_STOCK_LOTE')  
 END   
 EXEC ('set quoted_identifier off CREATE TABLE tempdb.dbo.'+@IDE+'RECALCULO_STOCK_LOTE (ALMACEN VARCHAR(2),DECODIGO VARCHAR(20),  
 SMMESPRO VARCHAR(6),LOTE VARCHAR(20),Ingresos NUMERIC(15,6),Salida NUMERIC(15,6),SALDO NUMERIC(15,6))')  
  
 EXEC ('set quoted_identifier off INSERT INTO tempdb.dbo.'+@IDE+'RECALCULO_STOCK_LOTE  
 select B.WAREHOUSE_ID,B.PART_ID,"'+@MORESMES+'",B.NUMBER_LOT,  
 SUM((CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)) AS Ingresos,  
 SUM((CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END)) AS Salida,  
 SUM((CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END))-SUM((CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END))AS SALDO  
 FROM  (WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON (A.WAREHOUSE_ID = B.WAREHOUSE_ID) AND (A.DOCUMENT_ID = B.DOCUMENT_ID) AND   
 (A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT)) INNER JOIN PART C ON B.PART_ID = C.ID  
 WHERE B.WAREHOUSE_ID IN('+@alma+') AND A.STATUS_GUIA<>"A" AND C.IS_LOT="S"  
 AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")   
 AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")  
 AND REPLICATE("0",2-LEN(MONTH(A.DATE_DOCUMENT)))+cast(MONTH(A.DATE_DOCUMENT) as varchar(2))='+@mesActual+' and year(A.DATE_DOCUMENT)='+@anoActual+'   
 GROUP BY B.PART_ID,B.WAREHOUSE_ID,B.NUMBER_LOT')  
   
 IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'XXX')  
 BEGIN     
     EXEC('set quoted_identifier off DROP TABLE TEMPDB.DBO.'+@IDE+'XXX')  
 END   
 EXEC ('set quoted_identifier off SELECT L.ALMACEN,L.DECODIGO,L.SMMESPRO,L.LOTE,L.Ingresos,L.Salida INTO TEMPDB.DBO.'+@IDE+'XXX   
 FROM TEMPDB.DBO.'+@IDE+'RECALCULO_STOCK_LOTE L LEFT JOIN  
 MONTHLY_SUMMARIZE_LOT M ON L.ALMACEN=M.WAREHOUSE_ID AND DECODIGO=M.PART_ID AND   
 L.SMMESPRO=M.YEAR_MONTH AND LOTE=M.LOT_ID WHERE M.LOT_ID IS NULL')  
   
 EXEC ('set quoted_identifier off update M set M.QTY_ENTER=ISNULL(Ingresos,0.000000),M.QTY_OUT=ISNULL(Salida,0.000000)   
 FROM MONTHLY_SUMMARIZE_LOT M INNER JOIN TEMPDB.DBO.'+@IDE+'RECALCULO_STOCK_LOTE t   
 ON M.WAREHOUSE_ID=T.ALMACEN AND M.PART_ID=T.DECODIGO AND M.LOT_ID=T.LOTE WHERE M.YEAR_MONTH="'+@MORESMES+'"')  
   
 EXEC ('set quoted_identifier off INSERT INTO MONTHLY_SUMMARIZE_LOT SELECT ALMACEN,DECODIGO,SMMESPRO,LOTE,0.000000,  
 0.000000,0.000000,0.000000,0.000000,INGRESOs,SALIDA,0.000000,0.000000,"","","","",0.000000 from TEMPDB.DBO.'+@IDE+'XXX')  
  