CREATE procedure [dbo].[INV_RPT_TRANSACTIONS]
as
	declare @STRquery nvarchar(1000)
	set @STRquery='SELECT TYPE_ID,MOV_ID,NAME,IS_VALUED,
		IS_VENDOR,IS_DOC_REF,IS_AUTHORIZED,IS_CCOST,IS_ORDER_PURCHASE,IS_COMMENT,
		IS_WHO,IS_CUSTOMER,IS_ORDER_MANUFACT,IS_POST,IS_ACCOUNT
		FROM TRANSACTION_TYPE'
	set @STRquery=@STRquery
	exec sp_executesql @STRquery
