CREATE procedure [dbo].[INV_RECALCULO_STOCK_SERIE]
--DECLARE  
@alma AS VARCHAR(100),@tipo as varchar(1),@IDE AS VARCHAR(50)  

/*SET @alma='"01","02"'  
set @tipo='0'  
SET @IDE='developer03'  
--WITH ENCRYPTION  
--*/AS  
  
SET NOCOUNT ON  
DECLARE @Arti AS VARCHAR(20)  
DECLARE @Ing AS numeric(15,6)  
DECLARE @Sal AS numeric(15,6)  
DECLARE @IngRef AS numeric(15,6)  
DECLARE @SalRef AS numeric(15,6)  
DECLARE @TotalMes as VARCHAR(20)  
DECLARE @ARTICULOS AS VARCHAR(100)  
DECLARE @SER AS VARCHAR(20)  
DECLARE @CODSER AS VARCHAR(20)  
DECLARE @TOTSTK AS VARCHAR(30)  
DECLARE @ALMACEN AS VARCHAR(2)  
declare @STRquery nvarchar(2300)
declare @table_variable_name  varchar(200)

 IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'RECALCULO_SERIE')  
 BEGIN  
     EXEC('set quoted_identifier off DROP TABLE tempdb.dbo.'+@IDE+'RECALCULO_SERIE')  
 END  
 EXEC('set quoted_identifier off CREATE TABLE tempdb.dbo.'+@IDE+'RECALCULO_SERIE(DECODIGO VARCHAR(20),DELOTE VARCHAR(20),  
 DESERIE VARCHAR(20),DEALMA VARCHAR(2),Ingresos NUMERIC(15,6),IngresosRef NUMERIC(15,6))')   
  
 EXEC('set quoted_identifier off INSERT INTO tempdb.dbo.'+@IDE+'RECALCULO_SERIE select B.PART_ID,B.NUMBER_LOT,B.NUMBER_SERIE,B.WAREHOUSE_ID,  
 SUM((CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END))-SUM((CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END)) AS Ingresos,  
 SUM((CASE WHEN A.TYPE_TRANS="I" THEN B.QTY_REFERENCE ELSE 0 END))-SUM((CASE WHEN A.TYPE_TRANS="S" THEN B.QTY_REFERENCE ELSE 0 END))AS IngresosRef  
 FROM  (WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON (A.WAREHOUSE_ID=B.WAREHOUSE_ID) AND (A.DOCUMENT_ID=B.DOCUMENT_ID) AND   
 (A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT)) INNER JOIN PART C ON B.PART_ID=C.ID  
 WHERE B.WAREHOUSE_ID IN ('+@alma+') AND A.STATUS_GUIA<>"A" AND C.SERIES="S"  
 AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")   
 AND B.PART_ID<>"TEXTO" GROUP BY B.PART_ID,B.NUMBER_LOT,B.NUMBER_SERIE,B.WAREHOUSE_ID ORDER BY B.PART_ID ASC')  
 
 set @table_variable_name='tempdb.dbo.'+@IDE+'RECALCULO_SERIE'


 exec ('set quoted_identifier off 
 DECLARE @Arti AS VARCHAR(20)  
DECLARE @Ing AS numeric(15,6)  
DECLARE @TOTSTK AS VARCHAR(30)  
DECLARE @ALMACEN AS VARCHAR(2)  
 DECLARE RECALC_STOCK_S CURSOR FOR  
 SELECT DECODIGO,DEALMA,SUM(Ingresos)AS INGRESO  
 FROM '+@table_variable_name+' WHERE Ingresos=1   GROUP BY DECODIGO,DEALMA
  
   
   
 OPEN RECALC_STOCK_S  
 FETCH NEXT FROM RECALC_STOCK_S INTO @Arti,@ALMACEN,@ing
   
   
WHILE @@FETCH_STATUS =0  
BEGIN
 exec(''set quoted_identifier off update PART_QTY set QTY_ON_HAND=0 where PART_ID="'+@Arti+'" and WAREHOUSE_ID="'+@ALMACEN+'"'')
 exec(''set quoted_identifier off update STOCK_SERIE SET QTY_ON_HAND=0 WHERE PART_ID="'+@Arti+'" AND WAREHOUSE_ID="'+@ALMACEN+'"'')   

 set @TOTSTK=@ing  
 exec(''set quoted_identifier off UPDATE PART_QTY SET QTY_ON_HAND='+@TOTSTK+'  
 where PART_ID="'+@Arti+'" and WAREHOUSE_ID="'+@ALMACEN+'"'')  
  
 exec(''set quoted_identifier off UPDATE STOCK_SERIE SET QTY_ON_HAND=1   
 WHERE SERIE IN(SELECT DESERIE FROM tempdb.dbo.'+@IDE+'RECALCULO_SERIE WHERE Ingresos=1)'')  
  
 FETCH NEXT FROM RECALC_STOCK_S INTO @Arti,@ALMACEN,@ing  
END   
  
CLOSE RECALC_STOCK_S  
DEALLOCATE RECALC_STOCK_S ')
  

