CREATE procedure [dbo].[INV_RECALCULO_STOCK_ARTICULOS]
--DECLARE  
@alma AS VARCHAR(500),@mesPOST AS VARCHAR(10),@anoPOST AS VARCHAR(10)  
/*  
SET @alma='"01","02","03"'  
SET @mesPOST='07'  
SET @anoPOST='2005'*/  
AS  
SET NOCOUNT ON  
SET QUOTED_IDENTIFIER off  
  
DECLARE @Arti AS VARCHAR(20)  
DECLARE @Ing AS numeric(15,6)  
DECLARE @Sal AS numeric(15,6)  
DECLARE @LOT AS VARCHAR(20)  
DECLARE @TOTSTK AS VARCHAR(30)  
DECLARE @ALMACEN AS VARCHAR(500)  
DECLARE @IngRef AS numeric(15,6)  
DECLARE @SalRef AS numeric(15,6)  
DECLARE @TOTSTKREF AS VARCHAR(30)  
  
  
  
 EXEC ('set quoted_identifier off update PART_QTY set QTY_ON_HAND=0,QTY_REFERENCE=0 where WAREHOUSE_ID in ('+@alma+')')  
  /*
 EXEC ('set quoted_identifier off DECLARE RECALC_STOCK_STKART CURSOR FOR  
 SELECT B.PART_ID,B.WAREHOUSE_ID,SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)AS INGRESO,  
 SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END)as SALIDA,  
 SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY_REFERENCE ELSE 0 END)AS INGRESOREF,  
 SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY_REFERENCE ELSE 0 END)AS SALIDAREF  
   
 from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON   
 A.WAREHOUSE_ID = B.WAREHOUSE_ID AND A.DOCUMENT_ID = B.DOCUMENT_ID AND A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID= C.ID  
 WHERE A.WAREHOUSE_ID in('+@alma+') AND A.STATUS_GUIA<>"A" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")   
 AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")  
 and A.DATE_DOCUMENT<"01/"+"'+@mesPOST+'"+"/"+"'+@anoPOST+'" GROUP BY B.PART_ID,B.WAREHOUSE_ID ORDER BY B.PART_ID ASC')  
   */
   set quoted_identifier off 
 DECLARE RECALC_STOCK_STKART CURSOR FOR  
 SELECT B.PART_ID,B.WAREHOUSE_ID,SUM(CASE WHEN A.TYPE_TRANS='I' THEN B.QTY ELSE 0 END)AS INGRESO,  
 SUM(CASE WHEN A.TYPE_TRANS='S' THEN B.QTY ELSE 0 END)as SALIDA,  
 SUM(CASE WHEN A.TYPE_TRANS='I' THEN B.QTY_REFERENCE ELSE 0 END)AS INGRESOREF,  
 SUM(CASE WHEN A.TYPE_TRANS='S' THEN B.QTY_REFERENCE ELSE 0 END)AS SALIDAREF  
   
 from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON   
 A.WAREHOUSE_ID = B.WAREHOUSE_ID AND A.DOCUMENT_ID = B.DOCUMENT_ID AND A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID= C.ID  
 WHERE --A.WAREHOUSE_ID in(''+@alma+'') AND 
 A.STATUS_GUIA<>'A' AND NOT (A.DOCUMENT_ID='GS' AND A.TRANS_ID='GF' AND A.STATUS_GUIA='F')   
 AND NOT (C.IS_STOCKED='N' AND C.SERIES='N' AND C.IS_LOT='N')AND (B.PART_ID<>'TEXTO')  
 and A.DATE_DOCUMENT<'01/'+''+@mesPOST+''+'/'+''+@anoPOST+'' GROUP BY B.PART_ID,B.WAREHOUSE_ID ORDER BY B.PART_ID ASC  
  
  
  
 OPEN RECALC_STOCK_STKART  
 FETCH NEXT FROM RECALC_STOCK_STKART INTO @Arti,@ALMACEN,@Ing,@Sal,@IngRef,@SalRef  
  
WHILE @@FETCH_STATUS =0  
BEGIN  
  
  SET @TOTSTK= @Ing - @Sal  
  SET @TOTSTKREF=@IngRef - @SalRef  
  
  declare @cuenta int   
  declare @cuenta2 int  
    
  exec INV_STKART @ALMACEN,@Arti,@cuenta2 output  
  if @cuenta2=0   
   begin  
      EXEC ('set quoted_identifier off insert into PART_QTY(WAREHOUSE_ID,PART_ID,QTY_ON_HAND,QTY_REFERENCE)values("'+@ALMACEN+'","'+@Arti+'",'+@TOTSTK+','+@TOTSTKREF+')')  
   end  
  else  
   begin  
   EXEC ('set quoted_identifier off UPDATE PART_QTY SET QTY_ON_HAND=QTY_ON_HAND+'+@TOTSTK+',QTY_REFERENCE=QTY_REFERENCE+'+@TOTSTKREF+'  
   where PART_ID="'+@Arti+'" and WAREHOUSE_ID="'+@ALMACEN+'"')  
   end  
  
 FETCH NEXT FROM RECALC_STOCK_STKART INTO @Arti,@ALMACEN,@Ing,@Sal,@IngRef,@SalRef  
END   
  
CLOSE RECALC_STOCK_STKART  
DEALLOCATE RECALC_STOCK_STKART  
  

