CREATE procedure INV_RPT_KARDEX_CON_LOTES    
--DECLARE    
@IDE AS VARCHAR(80), @alma AS VARCHAR(10),@fechaINI int,    
@fechaFIN int,@ART1 AS VARCHAR(70),@ART2 AS VARCHAR(70),  
@TODOSMOV AS VARCHAR(1),@TODOS AS VARCHAR(1),    
@mesAnt AS VARCHAR(2),@anoAnt AS VARCHAR(4),@mesActual AS VARCHAR(2),  
@anoAct AS VARCHAR(4),@LOTE  VARCHAR(10)
/*
SET @IDE='ACONTABLE02'    
SET @alma='01'    
SET @fechaINI=39917    
SET @fechaFIN=39978    
SET @ART1='A0001'    
SET @ART2='V0002'    
SET @TODOSMOV='0'    
set @TODOS='0'    
SET @mesAnt='03'    
SET @anoAnt='2009'    
SET @mesActual='04'    
set @anoAct='2009'    
    
--*/as    
SET NOCOUNT ON    
SET  QUOTED_IDENTIFIER off    
    
DECLARE @ARTICULOS AS VARCHAR(70)    
DECLARE @ARTICULOS2 AS VARCHAR(70)    
DECLARE @anomesAnt AS VARCHAR(6)    
DECLARE @Arti AS VARCHAR(20)    
DECLARE @Arti2 AS VARCHAR(20)    
DECLARE @DESCRI AS VARCHAR(64)    
DECLARE @ALMACEN AS VARCHAR(2)    
DECLARE @ing AS NUMERIC(15,6)    
DECLARE @SAL AS NUMERIC(15,6)    
DECLARE @INGREF AS NUMERIC(15,6)    
DECLARE @SALREF AS NUMERIC(15,6)    
DECLARE @SALDO AS varchar(30)    
DECLARE @SALDOREF AS varchar(30)    
declare @fecha1 AS varchar(10)    
declare @fecha2 AS varchar(10)    
DECLARE @UF VARCHAR(5) 
 declare @STRquery nvarchar(1500)  
 declare @tabla nvarchar(80)  
   
set @fecha1=str(@fechaINI)    
set @fecha2=str(@fechaFIN)    
    

    
SET @ARTICULOS=CASE WHEN @TODOS=1 THEN    
 ' AND B.PART_ID>="'+@ART1+'" AND B.PART_ID<="'+@ART2+'" '    
WHEN @TODOS=0 THEN    
 ' '    
END    
SET @ARTICULOS2=CASE WHEN @TODOS=1 THEN    
 'AND SMCODIGO>="'+@ART1+'" AND SMCODIGO<="'+@ART2+'" '    
WHEN @TODOS=0 THEN    
 ' '    
END    


SET @ALMA=SUBSTRING(@ALMA,1,2)
 IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'KARDEXSQL')    
 BEGIN       
     EXEC('DROP TABLE TEMPDB.DBO.'+@IDE+'KARDEXSQL')    
 END    
    
 EXEC ('CREATE TABLE TEMPDB.DBO.'+@IDE+'KARDEXSQL(CODIGO VARCHAR(20),DESCRIPCION VARCHAR(64)NULL,    
 UNIDAD VARCHAR(6)NULL,UMREFERENCIA VARCHAR(6)NULL,CAFECDOC datetime,CAALMA VARCHAR(2)NULL,CATD VARCHAR(2)NULL,CANUMDOC VARCHAR(10)NULL,    
 CATIPMOV VARCHAR(1)NULL,CACODMOV VARCHAR(2)NULL,CARFTDOC VARCHAR(2)NULL,CARFNDOC VARCHAR(10)NULL,CANOMPRO VARCHAR(100)NULL,    
 CANOMCLI VARCHAR(100)NULL,CACODCLI VARCHAR(11)NULL,DECENCOS VARCHAR(10)NULL,DEORDFAB VARCHAR(10)NULL,    
 DELOTE VARCHAR(20)NULL,DESERIE VARCHAR(20)NULL,SALDO NUMERIC(15,6)DEFAULT(0),ENTRADA NUMERIC(15,6)DEFAULT(0),    
 SALIDA NUMERIC(15,6)DEFAULT(0),SALDOREF NUMERIC(15,6)DEFAULT(0),ENTRADAREF NUMERIC(15,6)DEFAULT(0),SALIDAREF NUMERIC(15,6)DEFAULT(0),TYPE_PART VARCHAR(2)NULL)')    
    
 IF EXISTS(SELECT * FROM tempdb.dbo.sysobjects WHERE XTYPE='U' AND NAME=''+@IDE+'saldo')    
 BEGIN       
     EXEC('DROP TABLE TEMPDB.DBO.'+@IDE+'saldo')    
 END    
 EXEC ('    
 SELECT B.PART_ID,C.DESCRIPTION,B.WAREHOUSE_ID,SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)AS INGRESO,    
 SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END)as SALIDA,    
 SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY_REFERENCE ELSE 0 END)AS INGRESOREF,    
 SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY_REFERENCE ELSE 0 END)AS SALIDAREF,    
 SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END)-SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END) AS SALDOMOV,    
 SUM(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY_REFERENCE ELSE 0 END)-SUM(CASE WHEN A.TYPE_TRANS="S" THEN B.QTY_REFERENCE ELSE 0 END) AS SALDOREF,C.TYPE_PART   
 into tempdb.dbo.'+@ide+'saldo from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON     
 A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID=C.ID    
 WHERE A.WAREHOUSE_ID in("'+@alma+'") AND A.STATUS_GUIA<>"A" AND B.NUMBER_LOT="'+@LOTE+'" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF"  AND  A.STATUS_GUIA="F")     
 AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")'+@ARTICULOS+'    
 and A.DATE_DOCUMENT<'+@fecha1+' GROUP BY B.PART_ID,C.DESCRIPTION,B.WAREHOUSE_ID,C.TYPE_PART ORDER BY B.PART_ID ASC')    
     
 EXEC ('DECLARE RECORRE_CODIGOS CURSOR FOR    
 select B.PART_ID from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON     
 A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID=C.ID    
 WHERE A.WAREHOUSE_ID in("'+@alma+'") AND B.NUMBER_LOT="'+@LOTE+'" AND  A.STATUS_GUIA<>"A" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")     
 AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO")'+@ARTICULOS+'    
 GROUP BY B.PART_ID,C.DESCRIPTION,B.WAREHOUSE_ID ORDER BY B.PART_ID ASC')    
    
 OPEN RECORRE_CODIGOS    
 FETCH NEXT FROM RECORRE_CODIGOS INTO @Arti  
     
 WHILE @@FETCH_STATUS =0    
 BEGIN     
  EXEC ('INSERT INTO tempdb.dbo.'+@IDE+'KARDEXSQL (CODIGO,DESCRIPCION,SALDO,SALDOREF,TYPE_PART)    
  select PART_ID,DESCRIPTION,SALDOMOV,SALDOREF,TYPE_PART from tempdb.dbo.'+@ide+'saldo    
  where PART_ID="'+@Arti+'" AND(saldomov<>0)')    
    
  EXEC ('INSERT INTO tempdb.dbo.'+@IDE+'KARDEXSQL     
  (CODIGO,DESCRIPCION,UNIDAD,UMREFERENCIA,CAFECDOC,CAALMA,CATD,CANUMDOC,CATIPMOV,    
  CACODMOV,CARFTDOC,CARFNDOC,CANOMPRO,CANOMCLI,CACODCLI,DECENCOS,DEORDFAB,DELOTE,DESERIE,SALDO,    
  ENTRADA,SALIDA,SALDOREF,ENTRADAREF,SALIDAREF,TYPE_PART)    
    
  SELECT B.PART_ID,C.DESCRIPTION,C.UNIT_OF_MEASUREMENT,C.REFERENCE,A.DATE_DOCUMENT,A.WAREHOUSE_ID,A.DOCUMENT_ID,A.NUMBER_DOCUMENT,A.TYPE_TRANS,    
  A.TRANS_ID,A.DOC_ID_REF,A.NUM_ID_REF,(CASE WHEN A.DOCUMENT_ID="TD" THEN "ALMACEN"+" "+A.WAREHOUSE_ID ELSE     
  (CASE WHEN B.CCOST_ID<>"" THEN "C.C. "+B.CCOST_ID ELSE     
  (CASE WHEN B.ORDER_MANUFACT_ID<>"" THEN "O.F. "+B.ORDER_MANUFACT_ID ELSE (SELECT NAME FROM VENDOR P WHERE A.VENDOR_ID=P.ID) END)    
  END)    
  END)AS CANOMPROV,M.NAME,A.CUSTOMER_ID,B.CCOST_ID,B.ORDER_MANUFACT_ID,B.NUMBER_LOT,B.NUMBER_SERIE,0,    
  (CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END),    
  (CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END),0,    
  (CASE WHEN A.TYPE_TRANS="I" THEN B.QTY_REFERENCE ELSE 0 END),    
  (CASE WHEN A.TYPE_TRANS="S" THEN B.QTY_REFERENCE ELSE 0 END),C.TYPE_PART    
  from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON     
  A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT INNER JOIN PART C ON B.PART_ID=C.ID    
  LEFT JOIN CUSTOMER M ON A.CUSTOMER_ID=M.ID WHERE A.WAREHOUSE_ID in("'+@alma+'") AND B.NUMBER_LOT="'+@LOTE+'" AND  A.STATUS_GUIA<>"A" AND NOT (A.DOCUMENT_ID="GS" AND A.TRANS_ID="GF" AND A.STATUS_GUIA="F")     
  AND NOT (C.IS_STOCKED="N" AND C.SERIES="N" AND C.IS_LOT="N")AND (B.PART_ID<>"TEXTO") and B.PART_ID="'+@Arti+'"    
  and A.DATE_DOCUMENT>='+@fecha1+' AND A.DATE_DOCUMENT<='+@fecha2+' AND (B.QTY>0)ORDER BY B.PART_ID,A.DATE_DOCUMENT,A.TYPE_TRANS,A.DOCUMENT_ID,A.NUMBER_DOCUMENT ASC')    
    
    
  FETCH NEXT FROM RECORRE_CODIGOS INTO @Arti  
 END     
    
 CLOSE RECORRE_CODIGOS    
 DEALLOCATE RECORRE_CODIGOS    
    
IF @TODOSMOV=1     
 BEGIN    
  EXEC ('INSERT INTO tempdb.dbo.'+@IDE+'KARDEXSQL (CODIGO,DESCRIPCION,UNIDAD,ENTRADA,SALIDA,ENTRADAREF,SALIDAREF,TYPE_PART)    
  SELECT B.PART_ID,B.PART_DESCRIPTION,B.UNIT_PART,(CASE WHEN A.TYPE_TRANS="I" THEN B.QTY ELSE 0 END),    
  (CASE WHEN A.TYPE_TRANS="S" THEN B.QTY ELSE 0 END),    
  (CASE WHEN A.TYPE_TRANS="I" THEN B.QTY_REFERENCE ELSE 0 END),    
  (CASE WHEN A.TYPE_TRANS="S" THEN B.QTY_REFERENCE ELSE 0 END) ,D.TYPE_PART   
  from WAREHOUSE_TRANS A INNER JOIN WAREHOUSE_TRANS_LINE B ON     
  A.WAREHOUSE_ID=B.WAREHOUSE_ID AND A.DOCUMENT_ID=B.DOCUMENT_ID AND A.NUMBER_DOCUMENT=B.NUMBER_DOCUMENT INNER JOIN PART_QTY C ON B.PART_ID=C.PART_ID  INNER JOIN PART D C.PART_ID=D.ID  
  WHERE A.WAREHOUSE_ID in("'+@alma+'") AND B.NUMBER_LOT="'+@LOTE+'"  AND  A.STATUS_GUIA<>"A"     
  and B.PART_ID NOT IN (SELECT DISTINCT CODIGO FROM tempdb.dbo.'+@IDE+'KARDEXSQL)    
  and A.DATE_DOCUMENT>="01/"+"'+@mesActual+'"+"/"+"'+@anoAct+'" AND A.DATE_DOCUMENT<='+@fecha1+' ORDER BY B.PART_ID,A.DATE_DOCUMENT,A.TYPE_TRANS,A.DOCUMENT_ID,A.NUMBER_DOCUMENT ASC')    
 END    
    

 set @tabla=N'[tempdb].dbo.'+@IDE+'KARDEXSQL'  
 SET @STRquery='select CODIGO,DESCRIPCION,UNIDAD,UMREFERENCIA,convert(varchar(10),CAFECDOC,103) as CAFECDOC,  
  CAALMA,CATD,CANUMDOC,CATIPMOV,CACODMOV,CARFTDOC,  
  CARFNDOC,CANOMPRO,CANOMCLI,CACODCLI,DECENCOS,  
  DEORDFAB,DELOTE,DESERIE,SALDO,ENTRADA,SALIDA,  
  SALDOREF,ENTRADAREF,SALIDAREF,TYPE_PART
  from '+@tabla  
 exec sp_executesql @STRquery,N'@IDE AS varchar(80)',@IDE


--***************************************************************************************************************************************