CREATE PROCEDURE LISTAR_NUMEROS_NO_INGRESADOS
@FECHA1 VARCHAR(10),
@FECHA2 VARCHAR(10)
 AS

DECLARE @DOCUMENT_ID VARCHAR(2)
DECLARE @NUMBER_DOCUMENT VARCHAR(15)
DECLARE @N INT
DECLARE @NUMERO INT
DECLARE @NUMERO_A_COMPARAR INT
DECLARE @NUMERO_FALTA VARCHAR(15)
DECLARE @A INT
DECLARE @DIFERENCIA INT
DECLARE @NUMERO_DOS INT
DECLARE @DIFERENCIA_DOS INT

DECLARE CURSOR1 CURSOR FOR
SELECT DISTINCT DOCUMENT_ID FROM RECEIVABLE
OPEN CURSOR1
FETCH NEXT FROM CURSOR1
INTO @DOCUMENT_ID
WHILE @@FETCH_STATUS=0
BEGIN
	SET @N=1	
	SET @A=1
	DECLARE CURSOR2 CURSOR FOR
	SELECT  NUMBER_DOCUMENT from RECEIVABLE where DOCUMENT_ID=@document_id AND DOCUMENT_DATE BETWEEN @FECHA1 AND @FECHA2 order by number_document
	OPEN CURSOR2
	FETCH NEXT FROM CURSOR2
	INTO @NUMBER_DOCUMENT
	WHILE @@FETCH_STATUS=0
	BEGIN
		IF @N=1
		BEGIN
			SET @NUMERO=CONVERT(INT,@NUMBER_DOCUMENT)
			SET @N=0
		END
		ELSE	IF @N=0
		BEGIN
			SET @NUMERO=@NUMERO+1
			SET @NUMERO_A_COMPARAR=CONVERT(INT,@NUMBER_DOCUMENT)
			IF @NUMERO<>@NUMERO_A_COMPARAR
			BEGIN
				SET @DIFERENCIA=@NUMERO_A_COMPARAR-@NUMERO
				SET @DIFERENCIA_DOS=@DIFERENCIA
				IF @NUMERO >0 AND @NUMERO<=9
				BEGIN
					SET @NUMERO_FALTA='000000'+CONVERT(VARCHAR,@NUMERO)
				END
				ELSE IF @NUMERO>=10 AND @NUMERO<=99
				BEGIN
					SET @NUMERO_FALTA='00000'+CONVERT(VARCHAR,@NUMERO)				
				END
				ELSE IF @NUMERO>=100 AND @NUMERO<=999
				BEGIN
					SET @NUMERO_FALTA='0000'+CONVERT(VARCHAR,@NUMERO)				
				END
				ELSE IF @NUMERO>=1000 AND @NUMERO<=9999
				BEGIN
					SET @NUMERO_FALTA='000'+CONVERT(VARCHAR,@NUMERO)				
				END
				ELSE IF @NUMERO>=10000 AND @NUMERO<=99999
				BEGIN
					SET @NUMERO_FALTA='00'+CONVERT(VARCHAR,@NUMERO)				
				END
				ELSE IF @NUMERO>=100000 AND @NUMERO<=999999
				BEGIN
					SET @NUMERO_FALTA='0'+CONVERT(VARCHAR,@NUMERO)				
				END
				ELSE IF @NUMERO>=1000000 AND @NUMERO<=9999999
				BEGIN
					SET @NUMERO_FALTA=CONVERT(VARCHAR,@NUMERO)				
				END
				
				WHILE @DIFERENCIA>0
				BEGIN
					IF @A=1
					BEGIN
						INSERT INTO NUMEROS_DOCUMENTOS_FALTANTES VALUES(@DOCUMENT_ID,@NUMERO_FALTA)					
						SET @DIFERENCIA=@DIFERENCIA-1
						SET @A=2
						SET @NUMERO_DOS=@NUMERO
					END
					ELSE
					BEGIN
						SET @NUMERO_DOS=@NUMERO_DOS+1
						IF @NUMERO_DOS >0 AND @NUMERO_DOS<=9
						BEGIN
							SET @NUMERO_FALTA='000000'+CONVERT(VARCHAR,@NUMERO_DOS)
						END
						ELSE IF @NUMERO_DOS>=10 AND @NUMERO_DOS<=99
						BEGIN
							SET @NUMERO_FALTA='00000'+CONVERT(VARCHAR,@NUMERO_DOS)				
						END
						ELSE IF @NUMERO_DOS>=100 AND @NUMERO_DOS<=999
						BEGIN
							SET @NUMERO_FALTA='0000'+CONVERT(VARCHAR,@NUMERO_DOS)				
						END
						ELSE IF @NUMERO_DOS>=1000 AND @NUMERO_DOS<=9999
						BEGIN
							SET @NUMERO_FALTA='000'+CONVERT(VARCHAR,@NUMERO_DOS)				
						END
						ELSE IF @NUMERO_DOS>=10000 AND @NUMERO_DOS<=99999
						BEGIN
							SET @NUMERO_FALTA='00'+CONVERT(VARCHAR,@NUMERO_DOS)				
						END
						ELSE IF @NUMERO_DOS>=100000 AND @NUMERO_DOS<=999999
						BEGIN
							SET @NUMERO_FALTA='0'+CONVERT(VARCHAR,@NUMERO_DOS)				
						END
						ELSE IF @NUMERO_DOS>=1000000 AND @NUMERO_DOS<=9999999
						BEGIN
							SET @NUMERO_FALTA=CONVERT(VARCHAR,@NUMERO_DOS)				
						END
						INSERT INTO NUMEROS_DOCUMENTOS_FALTANTES VALUES(@DOCUMENT_ID,@NUMERO_FALTA)	
						SET @DIFERENCIA=@DIFERENCIA-1		

					END
				END
				SET @NUMERO=@NUMERO+@DIFERENCIA_DOS
				SET @A=1			
			END

		END


			
	FETCH NEXT FROM CURSOR2
	INTO @NUMBER_DOCUMENT
	END
	CLOSE CURSOR2
	DEALLOCATE CURSOR2
	
FETCH NEXT FROM CURSOR1
INTO @DOCUMENT_ID
END
CLOSE CURSOR1
DEALLOCATE CURSOR1

SELECT * FROM NUMEROS_DOCUMENTOS_FALTANTES ORDER BY DOCUMENT_ID,NUMBER_DOCUMENT