CREATE PROCEDURE MOD_CREATE_DATE
(
@NUM VARCHAR(10)
)
 AS
DECLARE @DOCUMENT_ID VARCHAR(2)
DECLARE @NUMBER_SERIE VARCHAR(3)
DECLARE @NUMBER_DOCUMENT VARCHAR(10)
DECLARE @DOCUMENT_REF VARCHAR(2)
DECLARE @SERIE_REF VARCHAR(3)
DECLARE @NUMBER_REF VARCHAR(10)
DECLARE @FECHA DATETIME
DECLARE @A VARCHAR(1)

DECLARE CURSOR1 CURSOR FOR
SELECT DOCUMENT_ID,NUMBER_SERIE,NUMBER_DOCUMENT,DOCUMENT_REF,SERIE_REF,NUMBER_REF 
FROM RECEIVABLE WHERE NUMBER_DOCUMENT=@NUM
OPEN CURSOR1
FETCH NEXT FROM CURSOR1
INTO @DOCUMENT_ID,@NUMBER_SERIE,@NUMBER_DOCUMENT,@DOCUMENT_REF,@SERIE_REF,@NUMBER_REF
WHILE @@FETCH_STATUS=0
BEGIN
	SELECT @FECHA=DOCUMENT_DATE,@A=1 FROM RECEIVABLE WHERE DOCUMENT_ID=@DOCUMENT_REF AND NUMBER_SERIE=@SERIE_REF AND NUMBER_DOCUMENT=@NUMBER_REF
	IF @A<>'1'
	BEGIN
		SET @FECHA='01/01/2009'
		UPDATE RECEIVABLE SET CREATE_DATE=@FECHA WHERE DOCUMENT_ID=@DOCUMENT_ID AND NUMBER_SERIE=@NUMBER_SERIE AND NUMBER_DOCUMENT=@NUMBER_DOCUMENT
	END
	ELSE
	BEGIN
		UPDATE RECEIVABLE SET CREATE_DATE=@FECHA WHERE DOCUMENT_ID=@DOCUMENT_ID AND NUMBER_SERIE=@NUMBER_SERIE AND NUMBER_DOCUMENT=@NUMBER_DOCUMENT
	END



FETCH NEXT FROM CURSOR1
INTO @DOCUMENT_ID,@NUMBER_SERIE,@NUMBER_DOCUMENT,@DOCUMENT_REF,@SERIE_REF,@NUMBER_REF
END
CLOSE CURSOR1
DEALLOCATE CURSOR1