CREATE PROC [dbo].[NQ_insertDocCompras]
@PID VARCHAR(2),
@PDESCRIPTION VARCHAR(70),
@PNUMBER_INI FLOAT,
@PNUMBER_FIN FLOAT,
@PNUMBER FLOAT,
@PUSER_ID VARCHAR(5),
@PNAME_FORMAT VARCHAR(20)
AS
--SELECT * FROM DBO.NUMBER_DOCUMENT_PURCHASE

INSERT INTO NUMBER_DOCUMENT_PURCHASE
([ID],[DESCRIPTION],[NUMBER_INI],[NUMBER_FIN]
,[NUMBER],[USER_ID],[NAME_FORMAT])VALUES(@PID ,
@PDESCRIPTION ,@PNUMBER_INI ,@PNUMBER_FIN ,
@PNUMBER ,@PUSER_ID ,@PNAME_FORMAT)