CREATE PROC [dbo].[NQ_INSERT_PARAMETROS]
@SERVIDOR_COME VARCHAR(200),
@SERVIDOR_CONTA VARCHAR(200),
@BASE_COME VARCHAR(200),
@BASE_CONTA VARCHAR(200),
@CUENTA1 VARCHAR(100),
@CUENTA2 VARCHAR(100),
@CUENTA3 VARCHAR(100),
@CUENTA4 VARCHAR(100),
@CUENTA5 VARCHAR(100),
@CUENTA6 VARCHAR(100)
AS
delete from TRANSFER_PARAMETERS;
INSERT INTO TRANSFER_PARAMETERS
VALUES(@BASE_COME,@BASE_CONTA,@CUENTA1,
@CUENTA2,@CUENTA3,@CUENTA4,@CUENTA5,@CUENTA6,@SERVIDOR_COME,@SERVIDOR_CONTA)