CREATE PROC [dbo].[NQ_REQUISICIONES_PENDIENTES]
AS
SELECT C.ID AS NUM_REQUISI,MH.DESCRIPTION AS SOLICITANTE,C.REQUIRED_DATE AS FECHA_REQUI,C.AREA_ID AS COD_AREA,
A.DESCRIPTION AS NOMBRE_AREA,D.PART_ID AS COD_ARTI,
P.DESCRIPTION AS DESCRIPCION_ARTICULO,D.QTY AS CANTIDAD_SOLIC,D.AMOUNT_BALANCE AS SALDO,
D.AMOUNT_BALANCE as CANT_INCLUIR,
D.PROJECT_ID AS PROYECTO,D.CCOST_ID AS CC,P.UNIT_OF_MEASUREMENT AS UNIT
FROM DBO.REQUIREMENT C INNER JOIN REQUIREMENT_LINE D 
ON C.ID=D.ID INNER JOIN PART P ON D.PART_ID=P.ID INNER JOIN AREA A ON C.AREA_ID=A.ID
INNER JOIN MASTER_HELP MH ON C.REQUIRED_USER=MH.ID
WHERE D.STATUS<>'A' OR D.STATUS IS NULL AND MH.TYPE_ID='12'
ORDER BY NUM_REQUISI