CREATE PROC [dbo].[NQ_Updatedoccompras]
@PID VARCHAR(2),
@PDESCRIPTION VARCHAR(70),
@PNUMBER_INI FLOAT,
@PNUMBER_FIN FLOAT,
@PNUMBER FLOAT,
@PUSER_ID VARCHAR(5),
@PNAME_FORMAT VARCHAR(20)
AS
UPDATE [NUMBER_DOCUMENT_PURCHASE]
   SET 
      [DESCRIPTION] = @PDESCRIPTION
      ,[NUMBER_INI] = @PNUMBER_INI
      ,[NUMBER_FIN] = @PNUMBER_FIN
      ,[NUMBER] = @PNUMBER
      ,[USER_ID] =@PUSER_ID
      ,[NAME_FORMAT] = @PNAME_FORMAT
 WHERE [ID] = @PID