CREATE PROCEDURE [dbo].[PUR_RPT_ORDENIMPORTACIONPROVART]  
--DECLARE
@PROV1 	CHAR(11),  
@PROV2 CHAR(11),  
@ART1 CHAR(20),  
@ART2 CHAR(20),  
@ESTADO1 CHAR(2),  
@ESTADO2 CHAR(2),
@FEC1 NUMERIC(15,6),
@FEC2 NUMERIC(15,6)
/*
SET @PROV1='001'
SET @PROV2='001'
SET @ART1='001'
SET @ART2='002'
SET @ESTADO1='01'
SET @ESTADO2='02'
SET @FEC1=32920
SET @FEC2=32970
*/
AS  
DECLARE @STRQUERY NVarchar(4000)
DECLARE @criterio NVarchar(2000)

IF LEN(@PROV1)<>0 AND LEN(@PROV2)<>0 
   SET  @criterio=' AND C.VENDOR_ID BETWEEN @PROV1 AND @PROV2 order by V.NAME '

IF LEN(@ART1)<>0 AND LEN(@ART2)<>0 
   SET  @criterio=' AND D.PART_ID BETWEEN @ART1 AND @ART2 ORDER BY D.PART_DESCRIPTION'

  SET @STRQUERY='SELECT C.ID AS C_ID,C.STATUS_ID AS C_STATUS_ID,C.VENDOR_ID AS C_VENDOR_ID, C.DOCUMENT_DATE AS C_DOCUMENT_DATE,C.PROMISE_DATE AS C_PROMISE_DATE, 
				C.AMOUNT AS C_AMOUNT,C.CURRENCY_ID_IMP AS C_CURRENCY_ID_IMP, C.EQUIVALENCE_US AS C_EQUIVALENCE_US, 
			    C.CURRENCY_EXCHANGE AS C_CURRENCY_EXCHANGE,C.COMMENT AS C_COMMENT,C.NUMBER_IMPORT_INT AS C_NUMBER_IMPORT_INT,
				D.PART_ID AS D_PART_ID,D.PART_DESCRIPTION AS D_PART_DESCRIPTION,D.ITEM AS D_ITEM, D.UNIT AS D_UNIT, D.QTY AS D_QTY, 
                D.PRICE AS D_PRICE, D.PRICE_NET AS D_PRICE_NET, D.PRICE_REF AS D_PRICE_REF,D.TOTAL_SALES AS D_TOTAL_SALES,
				D.COMMENT AS D_COMMENT, V.NAME AS V_NAME, V.VAT_REGISTRATION AS V_VAT_REGISTRATION, 
                V.ADDR AS V_ADDR, T.DESCRIPTION AS T_DESCRIPTION FROM IMPORT_ORDER C INNER JOIN
                IMPORT_ORDER_LINE D ON C.ID = D.ID INNER JOIN
                TYPE_IMPORT T ON C.TYPE_ORDER = T.ID INNER JOIN
                VENDOR V ON C.VENDOR_ID = V.ID
		  	    Where C.STATUS_ID BETWEEN @ESTADO1 AND @ESTADO2  AND C.DOCUMENT_DATE BETWEEN @FEC1 AND @FEC2 ' 
  
  set @STRQUERY=@STRQUERY + @criterio

  exec sp_executesql @STRQUERY,N'@PROV1 CHAR(11),@PROV2 CHAR(11),
                @ART1 CHAR(20),@ART2 CHAR(20),@ESTADO1 CHAR(2),@ESTADO2 CHAR(2),
                @FEC1 NUMERIC(15,6),@FEC2 NUMERIC(15,6)',@PROV1,@PROV2,@ART1,@ART2,@ESTADO1,@ESTADO2,@FEC1,@FEC2
