CREATE PROC [dbo].[PUR_DELETE_REQUIREMENT]
--DECLARE
@NUMERO VARCHAR(10),
@TIPO VARCHAR(2)
AS
SET NOCOUNT ON
/*
SET @NUMERO='000000015'
SET @TIPO='RQ'
--SET @IDE='DEVELOPER6'*/
declare @TRAN1 int
declare @TRAN2 int

BEGIN TRAN DELETE_REQUIREMENT
EXEC('set quoted_identifier off DELETE FROM REQUIREMENT WHERE ID="'+@NUMERO+'" AND TYPE= "'+@TIPO+'"')
SET @TRAN1 =@@ERROR

EXEC('set quoted_identifier off DELETE FROM REQUIREMENT_LINE WHERE ID="'+@NUMERO+'" AND TYPE= "'+@TIPO+'"')
SET @TRAN2 =@@ERROR

IF (@TRAN1<>0 OR @TRAN2<>0) 
	BEGIN
		ROLLBACK TRAN DELETE_REQUIREMENT
	END
ELSE
	BEGIN
		COMMIT TRAN DELETE_REQUIREMENT
	END