
CREATE PROC [dbo].[PUR_INSERT_REQUIREMENT_LINE]  
@NUMERO VARCHAR(10),  
@TIPO VARCHAR(2),  
@IDE VARCHAR(50),  
@CANT_ERROR INT OUTPUT  
AS  
  
declare @TABLA varchar(50)  
SET NOCOUNT ON  
  
SET @TABLA='tempdb.dbo.'+@IDE+'REQUIREMENT_LINE'  
  
SET @CANT_ERROR=0  
EXEC('set quoted_identifier off Insert Into REQUIREMENT_LINE (ID,TYPE,ITEM,PART_ID,PART_DESCRIPTION,UNIT,QTY,  
           STATUS,DOCUMENT_DATE,AMOUNT_BALANCE,CCOST_ID,COMMENT,PROJECT_ID)   
           SELECT "'+@NUMERO+'","'+@TIPO+'",ITEM,PART_ID,PART_DESCRIPTION,UNIT,QTY,  
           STATUS,DOCUMENT_DATE,AMOUNT_BALANCE,CCOST_ID,COMMENT,PROJECT FROM '+@TABLA+'')  
  
     IF @@error<>0  
         SET @CANT_ERROR=1