
CREATE procedure [dbo].[PUR_RPT_IMPORCOSTCERTIFICATE]
--DECLARE
@NUMIMPOR AS VARCHAR(13), @NUMLIQ AS VARCHAR(20)
/*
SET @NUMIMPOR='IMP123'
SET @NUMLIQ='POLIZA001'
*/
AS
	declare @STRquery nvarchar(4000)

	set @STRquery='SELECT V.NAME AS V_NAME,V.VAT_REGISTRATION AS V_VATREGISTRATION,
	V.ADDR AS V_ADDR,I.VENDOR_ID AS I_VENDOR_ID,I.DOCUMENT_DATE AS I_DOCUMENTDATE,
	I.PROMISE_DATE AS I_PROMISEDATE,I.AMOUNT AS I_AMOUNT, I.CURRENCY_ID_IMP AS I_CURRENCYIDIMP,
	I.EQUIVALENCE_US AS I_EQUIVALENCE_US,I.CURRENCY_EXCHANGE AS I_CURRENCY_EXCHANGE,
	I.SOLIINSP AS I_SOLIINSP,I.GUIATRAN AS I_GUIATRAN,I.AMOUNT_LIQ AS I_AMOUNT_LIQ,
	I.LLIQREAL AS I_LLIQREAL,I.AMOUNT_BALANCE AS I_AMOUNT_BALANCE,I.AMOUNT_BALANCE_LIQ AS I_AMOUNT_BALANCE_LIQ,
	I.COMMENT AS I_COMMENT,I.TYPE_ORDER AS I_TYPE_ORDER,I.NUMBER_LIQ AS I_NUMBER_LIQ, 
	I.NADVALOR AS I_NADVALOR,I.ITINERANT AS I_ITINERANT, I.CPACKING AS I_CPACKING,
	I.CURR_EXCHANGE_TYPE AS I_CURR_EXCHANGE_TYPE,I.TIPPREIMP AS I_TIPPREIMP,I.STATUS_ID AS I_STATUS_ID, 
	I.AMOUNT_FLETE AS I_AMOUNT_FLETE,I.NUMBER_IMPORT_INT AS I_NUMBER_IMPORT_INT,I.SECURE AS I_SECURE,
	C.ID AS C_ID, C.NUMBER_LIQ AS C_NUMBER_LIQ,C.DOCUMENT_DATE AS C_DOCUMENT_DATE,
	C.PERCENT_FOB AS C_PERCENT_FOB,C.AMOUNT_FOB AS C_AMOUNT_FOB,C.AMOUNT_TOTAL AS C_AMOUNT_TOTAL,
	C.NUMBER_PARTE AS C_NUMBER_PARTE,C.WAREHOUSE_ID AS C_WAREHOUSE_ID,D.COST_ID AS D_COST_ID,
	D.COMMENT_COST AS D_COMMENT_COST,D.AMOUNT AS D_AMOUNT, D.TYPE AS D_TYPE,D.CURRENCY_EXCHANGE AS D_CURRENCY_EXCHANGE,
	D.EXCHANGE_TYPE AS D_EXCHANGE_TYPE,D.CURRENCY_ID AS D_CURRENCY_ID,D.NUMBER_IMPORT_INT AS D_NUMBER_IMPORT_INT, 
	D.AMOUNT_COST_ORIG AS D_AMOUNT_COST_ORIG,T.DESCRIPTION AS T_DESCRIPTION,T.SUM_COST AS T_SUM_COST,T.ID AS T_ID 
	FROM IMPORT_COST_CERTIFICATE C INNER JOIN
	IMPORT_COST_CERTIFICATE_LINE D ON C.ID = D.ID AND C.NUMBER_LIQ = D.NUMBER_LIQ INNER JOIN
	IMPORT_ORDER I ON C.ID = I.ID INNER JOIN TYPE_COST T ON D.COST_ID = T.ID INNER JOIN
	VENDOR V ON I.VENDOR_ID = V.ID 
    WHERE C.ID=@NUMIMPOR AND C.NUMBER_LIQ=@NUMLIQ ' 

    exec sp_executesql @STRquery,N'@NUMIMPOR varchar(13),@NUMLIQ varchar(20)',@NUMIMPOR,@NUMLIQ



