CREATE PROC [dbo].[PUR_INSERT_PURCHASE_QUOTE]    
--DECLARE    
@NUMERO VARCHAR(10),    
@COD_PROVEE VARCHAR(11),    
@FECHAEMI NUMERIC(15,6),    
@COMENTARIO VARCHAR(250),    
@FECHA_CREACION NUMERIC(15,6),    
@COD_USUARIO VARCHAR(8),    
@IDE VARCHAR(50),  
@PROJECT_ID VARCHAR(20)    
AS    
SET NOCOUNT ON    
/*    
SET @NUMERO='000000015'    
SET @COD_PROVEE='01'    
SET @FECHAEMI='01/07/2007'    
SET @COMENTARIO='SDFSDFDSFDS'    
SET @FECHA_CREACION='01/06/2007'    
SET @COD_USUARIO='ERIKA'    
--SET @IDE='DEVELOPER6'*/    
--declare @TABLA varchar(50)    
declare @TRAN1 int    
declare @TRAN2 int    
--set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'    
    --SELECT  * FROM PURCHASE_QUOTE
BEGIN TRAN INSERT_PURCHASE_QUOTE    
EXEC('set quoted_identifier off INSERT INTO PURCHASE_QUOTE (ID,VENDOR_ID,DOCUMENT_DATE,COMMENT,    
            CREATE_DATE,USER_ID,PROJECT_ID,QUOTE_DATE) VALUES ("'+@NUMERO+'","'+@COD_PROVEE+'", '+@FECHAEMI+',    
           "'+@COMENTARIO+'",'+@FECHA_CREACION+',"'+@COD_USUARIO+'","'+@PROJECT_ID+'",'+@FECHAEMI+')')    
    
SET @TRAN1 =@@ERROR    
    
EXEC PUR_INSERT_PURCHASE_QUOTE_LINE  @NUMERO,@IDE,@TRAN2 OUTPUT    
    
IF (@TRAN1<>0 OR @TRAN2<>0)     
 BEGIN    
  ROLLBACK TRAN INSERT_PURCHASE_QUOTE    
 END    
ELSE    
 BEGIN    
  COMMIT TRAN INSERT_PURCHASE_QUOTE    
 END
