CREATE PROC [dbo].[PUR_UPDATE_PURCHASE_QUOTE]  
--DECLARE  
@NUMERO VARCHAR(10),  
@COD_PROVEE VARCHAR(11),  
@FECHAEMI NUMERIC(15,6),  
@COMENTARIO VARCHAR(250),  
@FECHA_CREACION NUMERIC(15,6),  
@NROCOTIZACION VARCHAR(12),  
@FECHACOTIZA NUMERIC(15,6),  
@MONEDA VARCHAR(2),  
@FORMAPAGO VARCHAR(80),  
@TIEMPOENT VARCHAR(80),  
@VALIDEZ VARCHAR(80),  
@COMENTARIOCOT VARCHAR(250),  
@IDE VARCHAR(50),
@PROJECT_ID VARCHAR(20)    
AS  
SET NOCOUNT ON  
/*  
SET @NUMERO='000000015'  
SET @COD_PROVEE='01'  
SET @FECHAEMI='01/07/2007'  
SET @COMENTARIO='SDFSDFDSFDS'  
SET @FECHA_CREACION='01/06/2007'  
SET @COD_USUARIO='ERIKA'  
--SET @IDE='DEVELOPER6'*/  
--declare @TABLA varchar(50)  
declare @TRAN1 int  
declare @TRAN2 int  
--set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'  
  
BEGIN TRAN UPDATE_PURCHASE_QUOTE  
EXEC('set quoted_identifier off UPDATE PURCHASE_QUOTE SET VENDOR_ID="'+@COD_PROVEE+'",DOCUMENT_DATE='+@FECHAEMI+',  
            COMMENT="'+@COMENTARIO+'",UPDATE_DATE='+@FECHA_CREACION+', SCNCOTIZ = "'+@NROCOTIZACION+'", QUOTE_DATE='+@FECHACOTIZA+',  
           CURRENCY_ID="'+@MONEDA+'" , SCFORPAG="'+@FORMAPAGO+'",SCTIEMENT="'+@TIEMPOENT+'",SCVALIDEZ="'+@VALIDEZ+'", COMMENT_COT="'+@COMENTARIOCOT+'",PROJECT_ID="'+@PROJECT_ID+'"   
            WHERE ID="'+@NUMERO+'"')  
  
SET @TRAN1 =@@ERROR  
  
EXEC PUR_UPDATE_PURCHASE_QUOTE_LINE @NUMERO,@IDE,@TRAN2 OUTPUT  
  
IF (@TRAN1<>0 AND @TRAN2<>0)   
 BEGIN  
  ROLLBACK TRAN UPDATE_PURCHASE_QUOTE  
 END  
ELSE  
 BEGIN  
  COMMIT TRAN UPDATE_PURCHASE_QUOTE  
 END
