CREATE PROCEDURE [dbo].[PUR_LIQUIDATEIMPORT]
 /*
Liquidacion por Poliza de Importaciones*/ 
--DECLARE      
 @emp as varchar(50),      
 @ide varchar(30),      
 @congen2 varchar(1000),      
 @congen3 varchar(1000),      
 @congen4 varchar(1000),      
 @congen5 varchar(1000),      
 @congen6 varchar(1000),      
 @congen7 varchar(1000),      
 @congen8 varchar(1000),      
 @congen9 varchar(1000),      
 @impini varchar(20),      
 @impfin varchar(20),    
 @polimp varchar(20)    
-- @fechaini as varchar(10),      
-- @fechafin as varchar(10)      
/*exec sp_LiqPolImp '400','ERIKA','"01"','""','"02"','""','""','"03"','""','""','IMP003','IMP003','POL123'*/      
/*  
set @emp='DEMO'      
set @ide='ERIKA'      
set @congen2='"01"'      
set @congen3='""'      
set @congen4='"02"'      
set @congen5='""'      
set @congen6='""'      
set @congen7='"03"'      
set @congen8='""'      
set @congen9='""'      
set @impini='IMP1'      
set @impfin='IMP1'      
SET @polimp='POLIZA1'  
--set @fechaini='37620'      
--set @fechafin='38286'         
*/
AS             
 set quoted_identifier off      
 set nocount on      
      
 /* VERIFICO SI EXISTE LA TABLA*/      
 DECLARE @EXISTE INT      
 DECLARE @TEMPO VARCHAR(50)      
       
 SET @TEMPO='##'+@ide+'COS_IMP'    
 EXEC PUR_MANTTEMP @TEMPO,1,'1','',@VALOR=@EXISTE OUTPUT    
 IF @EXISTE=1 EXEC('DROP TABLE [##'+ @ide+'COS_IMP]')    
     
 SET @TEMPO='##'+@ide+'COS_IMP_TOTAL'    
 EXEC PUR_MANTTEMP @TEMPO,1,'1','',@VALOR=@EXISTE OUTPUT    
 IF @EXISTE=1 EXEC('DROP TABLE [##'+ @ide+'COS_IMP_TOTAL]')    
 /* FIN */    
       
exec('delete from ['+@emp+'].dbo.HOJA_COSTOS ')      
exec('set quoted_identifier off      
 SELECT VENDOR_ID AS CDESPROVE,AI.CUSTOMS_ID AS COD_ADU,A.NAME AS NOM_ADU,B.NAME AS NOM_BAN,BI.NUM_FAC NRO_FAC,
        BI.COB_EXT,DATE_FAC AS FECHA_FAC,BI.DATE_CADUCATE AS FECHA_VTO,
        G.NUMBER_LIQ AS CNUMLIQUI,IC.ID AS CNUMERO,IC.NUMBER_IMPORT_INT AS CNUMIMP,
        CURRENCY_ID_IMP AS CCODMONIM,IC.DOCUMENT_DATE AS FEMISION,QTY AS NCANTIDAD,
        REFERENCE AS UMREFERENCIA,ID.PART_ID AS CCODARTIC,M.DESCRIPTION AS CDESARTIC,       
       (0.00) AS VALOR_FOB,      
       (0.00) AS FLETE,      
       (0.00) AS CCSEGURO,      
       (0.00) AS TOTAL_VALOR_CFR,      
       (CASE WHEN G.COST_ID IN ('+@congen3+') THEN (CASE WHEN TG.SUM_COST=1 THEN G.AMOUNT*-1 ELSE G.AMOUNT END) ELSE 0 END) AS GASTOS_VPE,      
       (0.00) AS AD_VAL,      
       (CASE WHEN G.COST_ID IN ('+@congen5+') THEN (CASE WHEN TG.SUM_COST=1 THEN G.AMOUNT*-1 ELSE G.AMOUNT END) ELSE 0 END) AS GASTOS_AGE,      
       (CASE WHEN G.COST_ID IN ('+@congen6+') THEN (CASE WHEN TG.SUM_COST=1 THEN G.AMOUNT*-1 ELSE G.AMOUNT END) ELSE 0 END) AS INTS_ADU,      
       (CASE WHEN G.COST_ID IN ('+@congen2+') THEN (CASE WHEN TG.SUM_COST=1 THEN G.AMOUNT*-1 ELSE G.AMOUNT END) ELSE 0 END) AS FLETE_CON,      
       (CASE WHEN G.COST_ID IN ('+@congen7+') THEN (CASE WHEN TG.SUM_COST=1 THEN G.AMOUNT*-1 ELSE G.AMOUNT END) ELSE 0 END) AS SEGURO,      
       (CASE WHEN G.COST_ID IN ('+@congen8+') THEN (CASE WHEN TG.SUM_COST=1 THEN G.AMOUNT*-1 ELSE G.AMOUNT END) ELSE 0 END) AS GASTOS_BAN,      
       (CASE WHEN G.COST_ID IN ('+@congen9+') THEN (CASE WHEN TG.SUM_COST=1 THEN G.AMOUNT*-1 ELSE G.AMOUNT END) ELSE 0 END) AS TRANS_DESC,      
       (0.00) AS COSTO_TOTAL,      
       (0.000000) AS COSTO_UNIT    
       INTO ##'+@ide+'COS_IMP      
       FROM ((((['+@emp+']..IMPORT_ORDER IC INNER JOIN (['+@emp+']..COST_IMP_PART ID       
       INNER JOIN ['+@EMP+']..PART M       
       ON PART_ID=M.ID) ON IC.ID=ID.ID AND ID.NUMBER_LIQ="'+@POLIMP+'" AND ID.PART_ID=M.ID) left JOIN (['+@emp+'].dbo.CUSTOMS_IMPORT AI       
       INNER JOIN ['+@emp+'].dbo.CUSTOMS A ON AI.CUSTOMS_ID=A.CUSTOMS_ID)      
       ON IC.ID=AI.NUMBER_IMPORT) LEFT JOIN (['+@emp+']..BANK_IMPORT BI       
       INNER JOIN ['+@emp+']..BANK B ON BI.BANK_ID=B.ID) ON IC.ID=BI.NUMBER_IMPORT)      
       LEFT JOIN ['+@emp+'].dbo.IMPORT_COST_CERTIFICATE_LINE G ON IC.ID=G.ID AND G.NUMBER_LIQ="'+@POLIMP+'") inner join       
       ['+@EMP+']..TYPE_COST TG ON G.COST_ID=TG.ID      
       WHERE IC.ID>="'+@impini+'" AND IC.ID<="'+@impfin+'"        
      ')      
/* ACTULIZO PARA QUE NO HAIGA DUPLICADO*/      
exec('set quoted_identifier off      
 SELECT       
 CNUMERO,CDESPROVE,COD_ADU,NOM_ADU,NOM_BAN,NRO_FAC,COB_EXT,FECHA_FAC,FECHA_VTO,CNUMLIQUI,      
 CNUMIMP,CCODMONIM,FEMISION,NCANTIDAD,UMREFERENCIA,CCODARTIC,CDESARTIC,      
 SUM(VALOR_FOB) AS VALOR_FOB,SUM(FLETE) AS FLETE,SUM(CCSEGURO) AS CCSEGURO,SUM(TOTAL_VALOR_CFR) AS TOTAL_VALOR_CFR,SUM(GASTOS_VPE) AS GASTOS_VPE,      
 SUM(AD_VAL) AS AD_VAL,SUM(GASTOS_AGE) AS GASTOS_AGE,SUM(INTS_ADU) AS INTS_ADU,SUM(FLETE_CON) AS FLETE_CON,SUM(SEGURO) AS SEGURO,SUM(GASTOS_BAN) AS GASTOS_BAN,      
 SUM(TRANS_DESC) AS TRANS_DESC,SUM(COSTO_TOTAL) AS COSTO_TOTAL,SUM(COSTO_UNIT) AS COSTO_UNIT      
 INTO ##'+@ide+'COS_IMP_TOTAL      
  FROM ##'+@ide+'COS_IMP      
 GROUP BY CNUMERO,CDESPROVE,COD_ADU,NOM_ADU,NOM_BAN,NRO_FAC,COB_EXT,FECHA_FAC,FECHA_VTO,CNUMLIQUI,      
 CNUMIMP,CCODMONIM,FEMISION,NCANTIDAD,UMREFERENCIA,CCODARTIC,CDESARTIC      
')      
/* Actualizo la tasa de aranceles*/        
exec('set quoted_identifier off      
 UPDATE  T SET AD_VAL=CUSTOMS_MEASURE from      
 (##'+@ide+'COS_IMP_TOTAL T inner join       
 ['+@emp+'].dbo.PART M      
 ON CCODARTIC=M.ID) INNER JOIN       
 ['+@emp+'].dbo.CUSTOMS_TARIFF A ON M.CUSTOMS_TARIFF_ID=A.CUSTOMSTARIFF_ID      
')      
  
exec('set quoted_identifier off      
 DROP TABLE ##'+@ide+'COS_IMP      
')      
/*ACTUALIZO VALOR FOB EN COS_IMP_TOTAL */      
exec('set quoted_identifier off      
 UPDATE C SET       
 VALOR_FOB=AMOUNT_FOB FROM ##'+@ide+'COS_IMP_TOTAL C INNER JOIN ['+@EMP+']..IMPORT_COST_CERTIFICATE I    
 ON C.CNUMERO=I.ID AND C.CNUMLIQUI=I.NUMBER_LIQ      
')       
exec('set quoted_identifier off      
 SELECT       
 T.CNUMERO,T.CDESPROVE,COD_ADU,NOM_ADU,NOM_BAN,NRO_FAC,      
 COB_EXT,FECHA_FAC,FECHA_VTO,T.CNUMLIQUI,T.CNUMIMP,T.CCODMONIM,T.FEMISION,T.NCANTIDAD,      
 UMREFERENCIA,T.CCODARTIC,T.CDESARTIC,      
 CAST(IDE.AMOUNT AS NUMERIC(23,2))-      
 CAST(((T.NCANTIDAD/(SELECT SUM(IDD.QTY) AS CANT_TOT FROM ['+@EMP+']..COST_IMP_PART IDD WHERE IDD.ID=I.ID AND IDD.NUMBER_LIQ="'+@POLIMP+'"))*AMOUNT_FLETE)*(T.VALOR_FOB/I.AMOUNT) AS NUMERIC(23,2))      
 -CAST(((T.NCANTIDAD/(SELECT SUM(IDD.QTY) AS CANT_TOT FROM ['+@emp+']..COST_IMP_PART IDD WHERE IDD.ID=I.ID AND IDD.NUMBER_LIQ="'+@POLIMP+'"))*ISNULL(I.SECURE,0))*(T.VALOR_FOB/I.AMOUNT) AS NUMERIC(23,2)) AS VALOR_FOB,      
 CAST(((T.NCANTIDAD/(SELECT SUM(IDD.QTY) AS CANT_TOT FROM ['+@emp+']..COST_IMP_PART IDD WHERE IDD.ID=I.ID AND IDD.NUMBER_LIQ="'+@POLIMP+'"))*AMOUNT_FLETE)*(T.VALOR_FOB/I.AMOUNT) AS NUMERIC(23,2)) AS FLETE,      
 CAST(((T.NCANTIDAD/(SELECT SUM(IDD.QTY) AS CANT_TOT FROM ['+@emp+']..COST_IMP_PART IDD WHERE IDD.ID=I.ID AND IDD.NUMBER_LIQ="'+@POLIMP+'"))*ISNULL(I.SECURE,0))*(T.VALOR_FOB/I.AMOUNT) AS NUMERIC(23,2))  AS CCSEGURO,      
 CAST(IDE.AMOUNT AS NUMERIC(23,2)) AS TOTAL_VALOR_CFR,      
 GASTOS_VPE,AD_VAL,GASTOS_AGE,      
 INTS_ADU,FLETE_CON,SEGURO,GASTOS_BAN,TRANS_DESC,COSTO_TOTAL,COSTO_UNIT       
 INTO ##'+@ide+'COS_IMP      
  FROM ##'+@ide+'COS_IMP_TOTAL T INNER JOIN (['+@emp+']..IMPORT_ORDER I INNER JOIN       
 ['+@emp+']..COST_IMP_PART IDE ON  I.ID=IDE.ID)       
 ON T.CNUMERO=I.ID AND T.CCODARTIC=IDE.PART_ID AND T.CNUMLIQUI=IDE.NUMBER_LIQ    
')      
exec('set quoted_identifier off      
 DROP TABLE ##'+@ide+'COS_IMP_TOTAL      
')      
  
exec('set quoted_identifier off      
 SELECT       
 T.CNUMERO,T.CDESPROVE,COD_ADU,NOM_ADU,NOM_BAN,NRO_FAC,      
 COB_EXT,FECHA_FAC,FECHA_VTO,T.CNUMLIQUI,T.CNUMIMP,T.CCODMONIM,T.FEMISION,NCANTIDAD,      
 UMREFERENCIA,CCODARTIC,CDESARTIC,VALOR_FOB,FLETE,CCSEGURO,TOTAL_VALOR_CFR,      
 CAST(((VALOR_FOB/(SELECT SUM(VALOR_FOB) AS CANT_TOT   
 FROM ##'+@ide+'COS_IMP TT   
WHERE TT.CNUMERO=T.CNUMERO))*GASTOS_VPE) AS NUMERIC(23,2)) AS GASTOS_VPE,      
    
 ((TOTAL_VALOR_CFR+CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*FLETE_CON) AS NUMERIC(23,2))+CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*SEGURO) AS NUMERIC(23,2)))*(AD_VAL/100)) AS AD_VAL,      
    
 CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*GASTOS_AGE) AS NUMERIC(23,2)) AS GASTOS_AGE,      
 CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*INTS_ADU) AS NUMERIC(23,2)) AS INTS_ADU,      
 CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*FLETE_CON) AS NUMERIC(23,2)) AS FLETE_CON,      
 CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*SEGURO) AS NUMERIC(23,2)) AS SEGURO,      
 CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*GASTOS_BAN) AS NUMERIC(23,2)) AS GASTOS_BAN,      
 CAST(((NCANTIDAD/(SELECT SUM(NCANTIDAD) AS CANT_TOT FROM ##'+@ide+'COS_IMP TT WHERE TT.CNUMERO=T.CNUMERO))*TRANS_DESC) AS NUMERIC(23,2)) AS TRANS_DESC,      
 COSTO_TOTAL,COSTO_UNIT,  
 ((TOTAL_VALOR_CFR+CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*FLETE_CON) AS NUMERIC(23,2))+CAST(((TOTAL_VALOR_CFR/AMOUNT_FOB)*SEGURO) AS NUMERIC(23,2)))*(AD_VAL/100)) AS xAD_VAL,      
 CONVERT(NUMERIC(18,8),0.000000) AS SUM_ADVALOREM,  
 CONVERT(NUMERIC(18,5),0.00000) AS TAZA_F    
  
 INTO ##'+@ide+'COS_IMP_TOTAL      
 FROM ##'+@ide+'COS_IMP T INNER JOIN ['+@emp+']..IMPORT_COST_CERTIFICATE I ON T.CNUMERO=I.ID AND I.NUMBER_LIQ="'+@POLIMP+'"    
')          
/*  
LE AGREAGO LOS CAMPOS PARA VOLVER A CALCULAR LO QUE GUARDA LA SUMA DEL ADVALOREM DE CAMPO AD_VAL   
*/  
exec('set quoted_identifier off      
UPDATE ##'+@ide+'COS_IMP_TOTAL SET SUM_ADVALOREM=(SELECT SUM(AD_VAL) FROM ##'+@ide+'COS_IMP_TOTAL)  
') 
/*  
LUEGO ACTUALIZO EL CAMPO AD_VAL CON LA NUEVA FORMUAL  
*/  
exec('set quoted_identifier off    
 UPDATE ##'+@ide+'COS_IMP_TOTAL SET TAZA_F=xAD_VAL/SUM_ADVALOREM  
')     
/*  
LUEGO ACTUALIZO EL CAMPO AD_VAL CON LA NUEVA FORMUAL  
*/  
/* FALTA BD */  
exec('set quoted_identifier off      
UPDATE C SET AD_VAL=(IMPGS.AMOUNT)*C.TAZA_F FROM ##'+@ide+'COS_IMP_TOTAL C INNER JOIN   
['+@emp+'].DBO.IMPORT_COST_CERTIFICATE_LINE IMPGS ON C.CNUMERO=IMPGS.ID AND C.CNUMLIQUI=IMPGS.NUMBER_LIQ  
WHERE  IMPGS.ID="'+@IMPINI+'" and IMPGS.NUMBER_LIQ="'+@polimp+'" AND IMPGS.COST_ID='+@congen4+'  
')
  
/* PARA EL COSTO TOTAL*/      
--COSTO_TOTAL=(TOTAL_VALOR_CFR+GASTOS_VPE+AD_VAL+GASTOS_AGE+INTS_ADU+SEGURO+GASTOS_BAN+TRANS_DESC)      
exec('set quoted_identifier off      
 UPDATE ##'+@ide+'COS_IMP_TOTAL SET       
 COSTO_TOTAL=TOTAL_VALOR_CFR+GASTOS_VPE+AD_VAL+GASTOS_AGE+INTS_ADU+FLETE_CON+SEGURO+GASTOS_BAN+TRANS_DESC      
')       
/* FIN*/      
/* PARA EL COSTO UNITARIO*/      
exec('set quoted_identifier off      
 UPDATE ##'+@ide+'COS_IMP_TOTAL SET       
COSTO_UNIT=(COSTO_TOTAL/NCANTIDAD)       
')       
/* FIN*/      
/* Inserto en la tabla HOJA_COSTOS */      
exec('set quoted_identifier off      
 insert into ['+@emp+'].dbo.HOJA_COSTOS       
 (HCNUMIMPOR,HCNUMLIQUI,HCTIPO,HCITEM,HCCODARTIC,HCDESARTIC,HCCANTIDAD,      
 HCVALORFOB,HCFLETE,HCCSEGURO,HCTOTALCFR,HCGASTOSVPE,HCADVAL,HCGASAGEN,HCAGADUANA,      
 HFLETECON,HCSEGURO,HCGASBAN,HCTRANSPORTE,HCCOSTOTOT,HCCOSTOUNI)      
 select       
 T.CNUMERO AS CNUMIMPOR,T.CNUMLIQUI,1 as TIPO,ITEM,T.CCODARTIC,T.CDESARTIC,T.NCANTIDAD,      
 VALOR_FOB,FLETE,CCSEGURO,TOTAL_VALOR_CFR,GASTOS_VPE,AD_VAL,GASTOS_AGE,INTS_ADU,      
 FLETE_CON,SEGURO,GASTOS_BAN,TRANS_DESC,COSTO_TOTAL,COSTO_UNIT      
 from ##'+@ide+'COS_IMP_TOTAL T inner join ['+@emp+']..COST_IMP_PART D      
 on T.CNUMERO=D.ID AND T.CCODARTIC=D.PART_ID AND D.NUMBER_LIQ="'+@POLIMP+'"     
')      
/* Fin */      
exec('set quoted_identifier off      
 select       
 HCNUMIMPOR,HCNUMLIQUI,HCTIPO,HCITEM,HCCODARTIC,HCDESARTIC,HCCANTIDAD,      
 HCVALORFOB,HCFLETE,HCCSEGURO,HCTOTALCFR,HCGASTOSVPE,HCADVAL,HCGASAGEN,HCAGADUANA,      
 HFLETECON,HCSEGURO,HCGASBAN,HCTRANSPORTE,HCCOSTOTOT,HCCOSTOUNI      
 from ['+@emp+'].dbo.HOJA_COSTOS order by HCITEM      
')      
  
  
