CREATE PROC [dbo].[PUR_INSERT_IMPORT_ORDER_LINE]
@NUMERO VARCHAR(13),
@IDE VARCHAR(50),
@CANT_ERROR INT OUTPUT
AS
declare @TABLA varchar(50)

SET NOCOUNT ON
set @TABLA='tempdb.dbo.'+@IDE+'IMPORT_ORDER_LINE'
SET @CANT_ERROR=0

EXEC('set quoted_identifier off Insert Into IMPORT_ORDER_LINE (ID,ITEM,PART_ID,PART_DESCRIPTION,UNIT,UNIT_REF,FACTOR,
	QTY,PRICE,PRICE_NET,PRICE_REF,TOTAL_SALES,QTY_IN,QTY_BALANCE,
	RECEIVE,VALUE_CIF,PERCEN_CIF,VALUE_AMOUNT,COMMENT,COMMENT1,FACTOR1,QTY_NAC) 
	SELECT "'+@NUMERO+'",ITEM,PART_ID,PART_DESCRIPTION,UNIT,UNIT_REF,FACTOR,
	QTY,PRICE,PRICE_NET,PRICE_REF,TOTAL_SALES,QTY_IN,QTY_BALANCE,
	RECEIVE,VALUE_CIF,PERCEN_CIF,VALUE_AMOUNT,COMMENT,COMMENT1,FACTOR1,QTY_NAC  FROM '+@TABLA+'')
	
   IF @@ERROR<>0 
       SET @CANT_ERROR=1