CREATE PROC [dbo].[PUR_UPDATE_PURCHASE_ORDER_LINE]  
@NUMERO VARCHAR(13),  
@TIPO VARCHAR(2),  
@IDE VARCHAR(50),  
@CANT_ERROR INT OUTPUT  
AS  
declare @TABLA varchar(50)  
DECLARE @ERROR1 INT  
DECLARE @ERROR2 INT  
  
SET NOCOUNT ON  
set @TABLA='tempdb.dbo.'+@IDE+'PURCHASE_ORDER_LINE'  
  
SET @ERROR1=0  
--Elimina los detalles para volver a insertarlos  
EXEC('set quoted_identifier off DELETE FROM PURCHASE_ORDER_LINE WHERE ID= "'+@NUMERO+'" AND TYPE="'+@TIPO+'"')  
SET @ERROR1=@@ERROR  
  
SET @ERROR2=0  
EXEC('set quoted_identifier off Insert Into PURCHASE_ORDER_LINE (ID,TYPE,ITEM,PART_ID,PART_DESCRIPTION,UNIT,UNIT_REFERENCE,  
           FACTOR_REFERENCE,QTY,PRICE,DISCOUNT_PER,DISCOUNT,AMOUNT_TAX,PERCENT_TAX,PRICE_NET,AMOUNT_TOTAL,  
          AMOUNT_TOTAL_NET,QTY_ENTER,QTY_OUT,STATUS_ID,COMMENT1,TEXT_COMMENT,IS_VAT,  
          PRICE_UNIT,CCOST_ID,PROJECT_ID,AREA_ID,COTI_ID,REQUI_ID)   
          SELECT "'+@NUMERO+'","'+@TIPO+'",ITEM,PART_ID,PART_DESCRIPTION,UNIT,UNIT_REFERENCE,FACTOR_REFERENCE,  
          QTY,PRICE,DISCOUNT_PER,DISCOUNT,AMOUNT_TAX,PERCENT_TAX,PRICE_NET,AMOUNT_TOTAL,  
          AMOUNT_TOTAL_NET,QTY_ENTER,QTY_OUT,STATUS_ID,COMMENT1,TEXT_COMMENT,IS_VAT,  
          PRICE_UNIT,CCOST_ID,PROJECT_ID,AREA_ID,COTI_ID,REQUI_ID FROM '+@TABLA+'')  
SET @ERROR2=@@ERROR  
   IF @ERROR1<>0 AND @ERROR2<>0   
       SET @CANT_ERROR=1  