CREATE PROCEDURE [dbo].[PUR_MANTTEMP]
@NOMTABLA VARCHAR(100),
@OP INT,
@EMP VARCHAR(100)='', 
@USU VARCHAR(15)='',
@VALOR INT =0  OUTPUT
AS
set quoted_identifier  off
set nocount on

DECLARE @CONT INT
SET @EMP=LTRIM(RTRIM(@EMP))
SET @USU=LTRIM(RTRIM(@USU))

IF @OP=1 --EXISTE TEMPORAL
BEGIN
     SELECT @CONT=COUNT(name) FROM tempdb.dbo.sysobjects WHERE name =LTRIM(RTRIM(@NOMTABLA))
     IF @CONT=0  
     BEGIN 	
             IF @EMP='' SELECT 0 AS EXISTE
             ELSE SET @VALOR=0
     END	
     ELSE 
     BEGIN
             IF @EMP='' SELECT 1 AS EXISTE      
	ELSE  SET @VALOR=1
     END  
END
IF @OP=2 --ELIMINAR DATOS DEL TEMPORAL CORRESPONDIENTE AL USUARIO Y A LA EMPRESA
BEGIN
    SELECT @CONT=COUNT(name)  FROM tempdb.dbo.sysobjects WHERE name =LTRIM(RTRIM(@NOMTABLA))
    IF @CONT >0  EXEC('SET QUOTED_IDENTIFIER OFF DELETE FROM   ' + @NOMTABLA + ' WHERE EMP="' + @EMP + '" AND USU="' + @USU + '"'  ) 
END
