CREATE PROCEDURE [dbo].[PUR_RPT_REQUISPENDIENTES]  
--DECLARE
@MARCA1 CHAR(20),  
@MARCA2 CHAR(20),  
@TIPOREQ CHAR(2), 
@TIPOQUIEBRE  CHAR(1)
/*
SET @MARCA1='000111'
SET @MARCA2='SER'
SET @TIPOREQ='RQ'
SET @TIPOQUIEBRE='1'
*/
AS  
  declare @STRquery nvarchar(1500)
  declare @criterio nvarchar(1500)
  if @TIPOQUIEBRE='1' 
     SET @CRITERIO='AND D.PART_ID BETWEEN @MARCA1 AND @MARCA2' 
  ELSE
     SET @CRITERIO=' AND C.REQUIRED_USER BETWEEN @MARCA1 AND @MARCA2' 

set @STRquery='  
    SELECT C.*,D.*, S.DESCRIPTION as PersonalSolicitante, M.DESCRIPTION, M.UNIT_OF_MEASUREMENT
    FROM  REQUIREMENT  C INNER JOIN  REQUIREMENT_LINE  D ON C.ID=D.ID INNER JOIN   
    PART M ON D.PART_ID=M.ID INNER JOIN MASTER_HELP S ON S.ID=C.REQUIRED_USER AND S.TYPE_ID=''12''  
    WHERE C.TYPE=@TIPOREQ AND D.TYPE=@TIPOREQ  AND C.STATUS=''P'' '

set @STRquery=@STRquery + @criterio

  exec sp_executesql @STRquery,N'@MARCA1 char(20), @MARCA2 CHAR(20),@TIPOREQ CHAR(2),@TIPOQUIEBRE CHAR(1)' 
                 ,@MARCA1, @MARCA2,@TIPOREQ,@TIPOQUIEBRE  
  
  
SELECT * FROM MASTER_HELP
