/*CREADO  28/06/2007 - 
   INSERTA DATOS DE ORDEN DE IMPORTACION*/
CREATE PROC [dbo].[PUR_UPDATE_IMPORT_ORDER] 
--DECLARE
@NUMERO VARCHAR(13),
@NUMINT VARCHAR(13),
@FECHAEMI NUMERIC(15,6),
@FECHAENT NUMERIC(15,6),
@COD_PROVEE VARCHAR(11),
@MONEDA VARCHAR(3),
@TIPOCONV VARCHAR(3),
@TIPOCAMBIO NUMERIC(15,6),
@EQUIVUS NUMERIC(15,6),
@TIPOORDEN VARCHAR(2),
@SOLINSPECCION VARCHAR(16),
@NROPOLIZA VARCHAR(16),
@IMPORTE NUMERIC(15,6),
@SALLIQ NUMERIC(15,6),
@OBSERVACION VARCHAR(100),
@ESTADO VARCHAR(2),
@FECHA_CREACION NUMERIC(15,6),
@COD_USUARIO VARCHAR(8),
@IDE VARCHAR(50),
@EMBARQUE VARCHAR(100),
@FORMAPAGO VARCHAR(100),
@FACT VARCHAR(250),
@ADJUNTAR VARCHAR(250),
@IMPORTANTE VARCHAR(250),
@DOCUMENTOS VARCHAR(100),
@COMENTARIO VARCHAR(250),
@FICHATECNICA VARCHAR(4000)
AS
SET NOCOUNT ON
/*
SET @NUMERO='000000015'
SET @COD_PROVEE='01'
SET @FECHAEMI='01/07/2007'
SET @COMENTARIO='SDFSDFDSFDS'
SET @FECHA_CREACION='01/06/2007'
SET @COD_USUARIO='ERIKA'
--SET @IDE='DEVELOPER6'*/
--declare @TABLA varchar(50)

declare @TRAN1 int
declare @TRAN2 int
declare @TRAN3 int
--set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'

BEGIN TRAN UPDATE_IMPORT_ORDER
EXEC('set quoted_identifier off UPDATE IMPORT_ORDER SET  VENDOR_ID ="'+@COD_PROVEE+'",DOCUMENT_DATE='+@FECHAEMI+',PROMISE_DATE='+@FECHAENT+',
                    AMOUNT='+@IMPORTE+' ,CURRENCY_ID_IMP="'+@MONEDA+'", EQUIVALENCE_US='+@EQUIVUS+',CURRENCY_EXCHANGE='+@TIPOCAMBIO+',SOLIINSP= "'+@SOLINSPECCION+'",
	      AMOUNT_BALANCE_LIQ = '+@SALLIQ+',COMMENT="'+@OBSERVACION+'",TYPE_ORDER="'+@TIPOORDEN+'",NUMBER_LIQ="'+@NROPOLIZA+'",
                   CURR_EXCHANGE_TYPE="'+@TIPOCONV+'",STATUS_ID="'+@ESTADO+'",NUMBER_IMPORT_INT="'+@NUMINT+'", UPDATE_DATE='+@FECHA_CREACION+'  WHERE ID="'+@NUMERO+'"')

SET @TRAN1 =@@ERROR

EXEC PUR_UPDATE_IMPORT_ORDER_LINE  @NUMERO,@IDE,@TRAN2 OUTPUT

EXEC PUR_UPDATE_DATA_IMPORT @NUMERO,@EMBARQUE,@FORMAPAGO,@FACT, @IMPORTANTE,@DOCUMENTOS,@ADJUNTAR,@COMENTARIO,@FICHATECNICA,@TRAN3 OUTPUT

IF (@TRAN1<>0  AND @TRAN2<>0 AND @TRAN3<>0) 
	BEGIN
		ROLLBACK TRAN UPDATE_IMPORT_ORDER
	END
ELSE
	BEGIN
		COMMIT TRAN UPDATE_IMPORT_ORDER
	END