CREATE PROC [dbo].[PUR_UPDATE_DATA_IMPORT]
--DECLARE
@NUMERO VARCHAR(13),
@EMBARQUE VARCHAR(100),
@FORMAPAGO VARCHAR(100),
@FACT VARCHAR(250),
@ADJUNTAR VARCHAR(250),
@IMPORTANTE VARCHAR(250),
@DOCUMENTOS VARCHAR(100),
@COMENTARIO VARCHAR(250),
@FICHATECNICA VARCHAR(4000),
@CANT_ERROR INT OUTPUT
/*
SET @NUMERO ='123'
SET @EMBARQUE ='DFGDFG'
SET @FORMAPAGO='DFGDFG'
SET @FACT ='DFGDFG'
SET @ADJUNTAR ='DFGDFG'
SET @IMPORTANTE ='DFGDFG'
SET @DOCUMENTOS='DFGDFG'
SET @COMENTARIO='DFGDFG'
SET @FICHATECNICA ='DFGDFG'
*/
AS
SET NOCOUNT ON

SET @CANT_ERROR=0
EXEC('set quoted_identifier off UPDATE DATA_IMPORT  SET  EMBARQUE= "'+@EMBARQUE+'",TERMS_TYPE="'+@FORMAPAGO+'" ,NAME_FACT="'+@FACT+'",
          ADJUNTAR="'+@ADJUNTAR+'",IMPORTANT="'+@IMPORTANTE+'",DOCUMENTS="'+@DOCUMENTOS+'",COMMENT="'+@COMENTARIO+'",
          COMMENT_TECNIC = "'+@FICHATECNICA+'"  WHERE ID="'+@NUMERO+'"')

  IF @@ERROR<>0 
    SET @CANT_ERROR =1