CREATE PROC [dbo].[PUR_UPDATE_PURCHASE_ORDER]  
--DECLARE  
@NUMERO VARCHAR(13),  
@TIPO VARCHAR(2),  
@FECHAEMI NUMERIC(15,6),  
@COD_PROVEE VARCHAR(11),  
@NROCOTIZA VARCHAR(15),  
@MONEDA VARCHAR(2),  
@FORMAPAGO VARCHAR(40),  
@TIPOCAMBIO NUMERIC(15,6),  
@FECHAENT NUMERIC(15,6),  
@COMENTARIO VARCHAR(250),  
@PERSOL VARCHAR(3),  
@RESPCOM VARCHAR(2),  
@DIRENT VARCHAR(60),  
@ESTADO VARCHAR(2),  
@MONTOBRUTO NUMERIC(15,6),  
@MONTODSCTO NUMERIC(15,6),  
@MONTOIGV NUMERIC(15,6),  
@MONTOTOTAL NUMERIC(15,6),  
@FECHA_CREACION NUMERIC(15,6),  
@COD_USUARIO VARCHAR(8),  
@TIPCONV VARCHAR(8),  
@FACTNOMBRE VARCHAR(70),  
@FACTRUC VARCHAR(11),  
@FACTDIREC VARCHAR(70),  
@TIPDOCREF VARCHAR(2),  
@NRODOCREF VARCHAR(13),  
@IDE VARCHAR(50) ,
@PROJECT_ID VARCHAR(20)    
AS  
SET NOCOUNT ON  
/*  
SET @NUMERO='000000015'  
SET @COD_PROVEE='01'  
SET @FECHAEMI='01/07/2007'  
SET @COMENTARIO='SDFSDFDSFDS'  
SET @FECHA_CREACION='01/06/2007'  
SET @COD_USUARIO='ERIKA'  
--SET @IDE='DEVELOPER6'*/  
--declare @TABLA varchar(50)  
declare @TRAN1 int  
declare @TRAN2 int  
--set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'  
  
BEGIN TRAN INSERT_PURCHASE_ORDER  
EXEC('set quoted_identifier off UPDATE PURCHASE_ORDER SET DOCUMENT_DATE= '+@FECHAEMI+', VENDOR_ID= "'+@COD_PROVEE+'",   
                  NUMBER_ESTIMATING = "'+@NROCOTIZA+'",CURRENCY_TYPE="'+@MONEDA+'",TERMS_NAME = "'+@FORMAPAGO+'",   
                  SELL_RATE='+@TIPOCAMBIO+', PROMISE_DATE = '+@FECHAENT+', COMMENT = "'+@COMENTARIO+'", AUTORIZED_ID="'+@PERSOL+'",  
                  BUYER_PURCHASE_ID="'+@RESPCOM+'", ADDR_DLV= "'+@DIRENT+'", STATUS_ID= "'+@ESTADO+'", AMOUNT= '+@MONTOBRUTO+',  
                  DISCOUNT='+@MONTODSCTO+' , AMOUNT_TAX = '+@MONTOIGV+' , AMOUNT_SALES='+@MONTOTOTAL+', UPDATE_DATE='+@FECHA_CREACION+' ,   
                  USER_ID="'+@COD_USUARIO+'", CURR_EXCHANGE_TYPE="'+@TIPCONV+'", NAME_FACT="'+@FACTNOMBRE+'",   
                  VAT_REGISTRATION_FACT= "'+@FACTRUC+'", ADDR_FACT = "'+@FACTDIREC+'",REFER_DOCUMENT_TYPE= "'+@TIPDOCREF+'",  
                  REFER_DOCUMENT_NUMBER="'+@NRODOCREF+'",PROJECT_ID="'+@PROJECT_ID+'"  
                   WHERE ID="'+@NUMERO+'" AND TYPE="'+@TIPO+'"')  
  
SET @TRAN1 =@@ERROR  
  
EXEC PUR_UPDATE_PURCHASE_ORDER_LINE  @NUMERO,@TIPO,@IDE,@TRAN2 OUTPUT  
  
IF (@TRAN1<>0 AND @TRAN2<>0)   
 BEGIN  
  ROLLBACK TRAN UPDATE_PURCHASE_ORDER  
 END  
ELSE  
 BEGIN  
  COMMIT TRAN UPDATE_PURCHASE_ORDER  
 END