CREATE procedure [dbo].[PUR_RPT_PURCHASE_QUOTE]  
@NUMERO AS VARCHAR(10),  
@TIPO AS VARCHAR(2)  
as  
 declare @STRquery nvarchar(1500)  
IF @TIPO='SC'   
 set @STRquery='Select C.ID,C.DOCUMENT_DATE,V.NAME,V.VAT_REGISTRATION,V.ADDR,V.CONTACT, V.REPRESENT,  
     C.COMMENT,PART_ID,PART_DESCRIPTION,UNIT,QTY,D.COMMENT AS GLOSADET,   
				P.ID AS PRO_ID,P.DESCRIPTION AS PRO_DES,D.PROJECT_ID
                 FROM PURCHASE_QUOTE C INNER JOIN PURCHASE_QUOTE_LINE D ON C.ID=D.ID   
     INNER JOIN VENDOR  V ON C.VENDOR_ID=V.ID LEFT JOIN PROYECT P ON C.PROJECT_ID=P.ID
                  WHERE C.ID=@NUMERO ORDER BY ITEM'   
IF @TIPO='CT'    
 set @STRquery='Select C.ID,C.DOCUMENT_DATE,V.NAME,V.VAT_REGISTRATION,V.ADDR,V.CONTACT, V.REPRESENT,  
     C.COMMENT,C.CURRENCY_ID,COMMENT_COT,QUOTE_DATE,SCTIPCAM,SCVALIDEZ,SCTIEMENT,  
    SCFORPAG,SCNCOTIZ, PART_ID,PART_DESCRIPTION,UNIT,QTY,D.COMMENT AS GLOSADET, D.PRICE, AMOUNT_TAX,  
                 GUARANTEE, MARK, DISCOUNT, DLV_DATE, IS_VAT    
                 FROM PURCHASE_QUOTE C INNER JOIN PURCHASE_QUOTE_LINE D ON C.ID=D.ID   
     INNER JOIN VENDOR  V ON C.VENDOR_ID=V.ID    
                  WHERE C.ID=@NUMERO ORDER BY ITEM'    
  
  
             exec sp_executesql @STRquery,N'@NUMERO varchar(10)',@NUMERO