CREATE PROC [dbo].[PUR_UPDATE_PURCHASE_QUOTE_LINE]  
--DECLARE  
@NUMERO VARCHAR(10),  
@IDE VARCHAR(50),  
@CANT_ERROR INT OUTPUT  
/*  
SET @NUMERO='0000000001'  
SET @IDE='DEVELOPER04'  
SET @CANT_ERROR=0  
*/  
AS  
declare @TABLA varchar(50)  
DECLARE @ERROR1 INT  
DECLARE @ERROR2 INT  
  
SET NOCOUNT ON  
set @TABLA='tempdb.dbo.'+@IDE+'PURCHASE_QUOTE_LINE'  
  
SET @ERROR1=0  
--Elimina los detalles para volver a insertarlos  
EXEC('set quoted_identifier off DELETE FROM PURCHASE_QUOTE_LINE WHERE ID= "'+@NUMERO+'"')  
SET @ERROR1=@@ERROR  
--Inserta los detalles  
SET @ERROR2=0  
EXEC('set quoted_identifier off Insert Into PURCHASE_QUOTE_LINE (ID,ITEM,PART_ID,PART_DESCRIPTION,UNIT,QTY,COMMENT,  
           PRICE,AMOUNT_TAX,DISCOUNT,GUARANTEE,QUALITY,MARK,DLV_DATE,IS_VAT,PROJECT_ID,CC_ID,AREA_ID,REQUI_ID)  
           SELECT "'+@NUMERO+'",ITEM,PART_ID,PART_DESCRIPTION,UNIT,QTY,COMMENT,PRICE,AMOUNT_TAX,  
           DISCOUNT,GUARANTEE,QUALITY,MARK,DLV_DATE,IS_VAT,PROJECT_ID,CC_ID,AREA_ID,REQUI_ID FROM '+@TABLA+'')  
SET @ERROR2=@@ERROR  
  
           IF @ERROR1<>0  AND @ERROR2<>0  
               SET @CANT_ERROR=1

