
CREATE PROC [dbo].[PUR_DELETE_IMPORT_ORDER]
--DECLARE
@NUMERO VARCHAR(13)
AS
SET NOCOUNT ON
/*
SET @NUMERO='000000015'
--SET @IDE='DEVELOPER6'*/
declare @TRAN1 int
declare @TRAN2 int
declare @TRAN3 int

BEGIN TRAN DELETE_IMPORT_ORDER
EXEC('set quoted_identifier off DELETE FROM IMPORT_ORDER WHERE ID="'+@NUMERO+'" ')
SET @TRAN1 =@@ERROR

EXEC('set quoted_identifier off DELETE FROM IMPORT_ORDER_LINE WHERE ID="'+@NUMERO+'"')
SET @TRAN2 =@@ERROR

EXEC('set quoted_identifier off DELETE FROM DATA_IMPORT WHERE ID="'+@NUMERO+'"')
SET @TRAN3 =@@ERROR

IF (@TRAN1<>0 OR @TRAN2<>0 OR @TRAN3<>0) 
	BEGIN
		ROLLBACK TRAN DELETE_IMPORT_ORDER
	END
ELSE
	BEGIN
		COMMIT TRAN DELETE_IMPORT_ORDER
	END
