CREATE PROC [dbo].[PUR_DELETE_PURCHASE_ORDER]
--DECLARE
@NUMERO VARCHAR(13),
@TIPO VARCHAR(2)
AS
SET NOCOUNT ON
/*
SET @NUMERO='000000015'
--SET @IDE='DEVELOPER6'*/
declare @TRAN1 int
declare @TRAN2 int

BEGIN TRAN DELETE_PURCHASE_ORDER
EXEC('set quoted_identifier off DELETE FROM PURCHASE_ORDER WHERE ID="'+@NUMERO+'" AND TYPE="'+@TIPO+'"')
SET @TRAN1 =@@ERROR

EXEC('set quoted_identifier off DELETE FROM PURCHASE_ORDER_LINE WHERE ID="'+@NUMERO+'" AND TYPE="'+@TIPO+'"')
SET @TRAN2 =@@ERROR

IF (@TRAN1<>0 OR @TRAN2<>0) 
	BEGIN
		ROLLBACK TRAN DELETE_PURCHASE_QUOTE
	END
ELSE
	BEGIN
		COMMIT TRAN DELETE_PURCHASE_QUOTE
	END