CREATE PROC [dbo].[PUR_UPDATE_IMPORT_ORDER_LINE]
@NUMERO VARCHAR(13),
@IDE VARCHAR(50),
@CANT_ERROR INT OUTPUT
AS
declare @TABLA varchar(50)
DECLARE @ERROR1 INT
DECLARE @ERROR2 INT

SET NOCOUNT ON
set @TABLA='tempdb.dbo.'+@IDE+'IMPORT_ORDER_LINE'

SET @ERROR1=0
--Elimina los detalles para volver a insertarlos
EXEC('set quoted_identifier off DELETE FROM IMPORT_ORDER_LINE WHERE ID= "'+@NUMERO+'"')
SET @ERROR1=@@ERROR

SET @ERROR2=0
EXEC('set quoted_identifier off Insert Into IMPORT_ORDER_LINE (ID,ITEM,PART_ID,PART_DESCRIPTION,UNIT,UNIT_REF,FACTOR,
             QTY,PRICE,PRICE_NET,PRICE_REF,TOTAL_SALES,QTY_IN,QTY_BALANCE, RECEIVE,VALUE_CIF,PERCEN_CIF,VALUE_AMOUNT,COMMENT,
             COMMENT1,FACTOR1,QTY_NAC)
             SELECT "'+@NUMERO+'",ITEM,PART_ID,PART_DESCRIPTION,UNIT,UNIT_REF,FACTOR,
	QTY,PRICE,PRICE_NET,PRICE_REF,TOTAL_SALES,QTY_IN,QTY_BALANCE,
	RECEIVE,VALUE_CIF,PERCEN_CIF,VALUE_AMOUNT,COMMENT,COMMENT1,FACTOR1,QTY_NAC FROM '+@TABLA+'')
	SET @ERROR2=@@ERROR

   IF @ERROR1<>0 AND @ERROR2<>0 
       SET @CANT_ERROR=1