CREATE  PROCEDURE [dbo].[PUR_RPT_FACTURACOMPRAS]
--DECLARE
@PROV1 	CHAR(11),  
@PROV2 CHAR(11),  
@ART1 CHAR(20),  
@ART2 CHAR(20),  
@FEC1 NUMERIC(15,6),
@FEC2 NUMERIC(15,6)
/*
SET @PROV1='001'
SET @PROV2='001'
SET @ART1='001'
SET @ART2='002'
SET @FEC1=32210
SET @FEC2=32457
*/
AS  
DECLARE @STRQUERY NVarchar(4000)

  SET @STRQUERY='select C.*,D.*,V.*  From  PURCHASE_CAB  C INNER JOIN PURCHASE_LINE D ON C.ID=D.PURCHASE_ID_CAB 
                                    INNER JOIN VENDOR V ON C.VENDOR_ID=V.ID
                                    Where  DOCUMENT_DATE BETWEEN @FEC1 AND @FEC2  AND VENDOR_ID BETWEEN @PROV1 AND @PROV2 
                                    AND PART_ID BETWEEN @ART1 AND @ART2  ' 

  exec sp_executesql @STRQUERY,N'@PROV1 CHAR(11),@PROV2 CHAR(11),
                @ART1 CHAR(20),@ART2 CHAR(20), @FEC1 NUMERIC(15,6),@FEC2 NUMERIC(15,6)',@PROV1,@PROV2,@ART1,@ART2,@FEC1,@FEC2