CREATE PROC [dbo].[PUR_UPDATE_REQUIREMENT]  
--DECLARE  
@NUMERO VARCHAR(10),  
@TIPO VARCHAR(2),  
@COD_PERSOL VARCHAR(8),  
@FECHAEMI NUMERIC(15,6),  
@COMENTARIO VARCHAR(250),  
@COD_AREA VARCHAR(6),  
@ESTADO VARCHAR(1),  
@FECHA_CREACION NUMERIC(15,6),  
@IDE VARCHAR(50),
@PROJECT_ID VARCHAR(50)  
AS  
SET NOCOUNT ON  
/*  
SET @NUMERO='000000015'  
SET @TIPO='RQ'  
SET @COD_PERSOL='01'  
SET @FECHAEMI='01/07/2007'  
SET @COMENTARIO='SDFSDFDSFDS'  
SET @COD_AREA='01'  
SET @ESTADO='P'  
SET @FECHA_CREACION='01/06/2007'  
SET @COD_USUARIO='ERIKA'  
--SET @IDE='DEVELOPER6'*/  
--declare @TABLA varchar(50)  
declare @TRAN1 int  
declare @TRAN2 int  
declare @TRAN3 int  
  
--set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'  
  
BEGIN TRAN UPDATE_REQUIREMENT  
EXEC('set quoted_identifier off UPDATE REQUIREMENT SET REQUIRED_USER="'+@COD_PERSOL+'",REQUIRED_DATE='+@FECHAEMI+',  
            COMMENT="'+@COMENTARIO+'", AREA_ID="'+@COD_AREA+'",UPDATE_DATE='+@FECHA_CREACION+',PROJECT_ID="'+@PROJECT_ID+'"    
            WHERE ID="'+@NUMERO+'" AND TYPE= "'+@TIPO+'"')  
  
SET @TRAN1 =@@ERROR  
  
EXEC PUR_UPDATE_REQUIREMENT_LINE @NUMERO,@TIPO,@IDE,@TRAN2 OUTPUT  
  
IF (@TRAN1<>0 AND @TRAN2<>0)   
 BEGIN  
  ROLLBACK TRAN UPDATE_REQUIREMENT  
 END  
ELSE  
 BEGIN  
  COMMIT TRAN UPDATE_REQUIREMENT  
 END