CREATE procedure [dbo].[PUR_RPT_PURCHASE_ORDER_ORI]  
--DECLARE  
@NUMERO AS VARCHAR(13),  
@TIPO AS VARCHAR(2)  
/*  
SET @NUMERO='0000000000003'  
SET @TIPO='OC'  
*/  
AS  
 declare @STRquery nvarchar(4000)  
  
 set @STRquery='Select C.ID,C.TYPE,DOCUMENT_DATE, VENDOR_ID,V.NAME,V.VAT_REGISTRATION,V.ADDR,V.CONTACT, V.REPRESENT,   
                   PHONE,FAX_NUMBER,NUMBER_ESTIMATING,CURRENCY_TYPE, TERMS_NAME, SELL_RATE, PROMISE_DATE, C.COMMENT,   
                   AUTORIZED_ID, BUYER_PURCHASE_ID, ADDR_DLV, C.STATUS_ID,   
                  AMOUNT,C.DISCOUNT, C.AMOUNT_TAX, AMOUNT_SALES, UPDATE_DATE, USER_ID, CURR_EXCHANGE_TYPE, NAME_FACT,   
                  VAT_REGISTRATION_FACT, ADDR_FACT,REFER_DOCUMENT_TYPE,REFER_DOCUMENT_NUMBER,ITEM,PART_ID,  
                  PART_DESCRIPTION,UNIT,UNIT_REFERENCE,FACTOR_REFERENCE, QTY,PRICE,DISCOUNT_PER,D.DISCOUNT, D.AMOUNT_TAX,   
                  PERCENT_TAX, PRICE_NET, AMOUNT_TOTAL, AMOUNT_TOTAL_NET,QTY_ENTER, QTY_OUT,D.STATUS_ID,COMMENT1,  
                 TEXT_COMMENT,IS_VAT,PRICE_UNIT,CCOST_ID   
                 FROM PURCHASE_ORDER C INNER JOIN PURCHASE_ORDER_LINE D ON C.ID=D.ID  AND C.TYPE=D.TYPE  
     INNER JOIN VENDOR  V ON C.VENDOR_ID=V.ID    
                  WHERE C.ID=@NUMERO AND C.TYPE=@TIPO ORDER BY ITEM'   
/*IF @TIPO='CT'    
 set @STRquery='Select C.ID,C.DOCUMENT_DATE,V.NAME,V.VAT_REGISTRATION,V.ADDR,V.CONTACT, V.REPRESENT,  
     C.COMMENT,C.CURRENCY_ID,COMMENT_COT,QUOTE_DATE,SCTIPCAM,SCVALIDEZ,SCTIEMENT,  
    SCFORPAG,SCNCOTIZ, PART_ID,PART_DESCRIPTION,UNIT,QTY,D.COMMENT AS GLOSADET, D.PRICE, AMOUNT_TAX,  
                 GUARANTEE, MARK, DISCOUNT, DLV_DATE, IS_VAT    
                 FROM PURCHASE_QUOTE C INNER JOIN PURCHASE_QUOTE_LINE D ON C.ID=D.ID   
     INNER JOIN VENDOR  V ON C.VENDOR_ID=V.ID    
                  WHERE C.ID=@NUMERO ORDER BY ITEM'  */  
  
             exec sp_executesql @STRquery,N'@NUMERO varchar(13),@TIPO varchar(2)',@NUMERO,@TIPO