CREATE PROC [dbo].[PUR_DELETE_PURCHASE_QUOTE]
--DECLARE
@NUMERO VARCHAR(10)
AS
SET NOCOUNT ON
/*
SET @NUMERO='000000015'
--SET @IDE='DEVELOPER6'*/
declare @TRAN1 int
declare @TRAN2 int

BEGIN TRAN DELETE_PURCHASE_QUOTE
EXEC('set quoted_identifier off DELETE FROM PURCHASE_QUOTE WHERE ID="'+@NUMERO+'"')
SET @TRAN1 =@@ERROR

EXEC('set quoted_identifier off DELETE FROM PURCHASE_QUOTE_LINE WHERE ID="'+@NUMERO+'"')
SET @TRAN2 =@@ERROR

IF (@TRAN1<>0 OR @TRAN2<>0) 
	BEGIN
		ROLLBACK TRAN DELETE_PURCHASE_QUOTE
	END
ELSE
	BEGIN
		COMMIT TRAN DELETE_PURCHASE_QUOTE
	END