/*CREADO  28/06/2007 - 
   INSERTA OTROS DATOS DE ORDEN DE IMPORTACION*/
CREATE PROC [dbo].[PUR_INSERT_DATA_IMPORT]
--DECLARE
@NUMERO VARCHAR(13),
@EMBARQUE VARCHAR(100),
@FORMAPAGO VARCHAR(100),
@FACT VARCHAR(250),
@ADJUNTAR VARCHAR(250),
@IMPORTANTE VARCHAR(250),
@DOCUMENTOS VARCHAR(100),
@COMENTARIO VARCHAR(250),
@FICHATECNICA VARCHAR(4000),
@CANT_ERROR INT OUTPUT

AS
SET NOCOUNT ON

SET @CANT_ERROR=0
EXEC('set quoted_identifier off INSERT INTO DATA_IMPORT  (ID,EMBARQUE,TERMS_TYPE,NAME_FACT,ADJUNTAR,IMPORTANT,DOCUMENTS,COMMENT,COMMENT_TECNIC )
 VALUES ("'+@NUMERO+'","'+@EMBARQUE+'","'+@FORMAPAGO+'","'+@FACT+'","'+@ADJUNTAR+'","'+@IMPORTANTE+'",
                 "'+@DOCUMENTOS+'" ,"'+@COMENTARIO+'","'+@FICHATECNICA+'")')

             IF @@ERROR<>0 
	    SET @CANT_ERROR =1