/*CREADO  27/06/2007 - 
   INSERTA DATOS DE ORDEN DE IMPORTACION*/
CREATE PROC [dbo].[PUR_INSERT_IMPORT_ORDER] 
--DECLARE
@NUMERO VARCHAR(13),
@NUMINT VARCHAR(13),
@FECHAEMI NUMERIC(15,6),
@FECHAENT NUMERIC(15,6),
@COD_PROVEE VARCHAR(11),
@MONEDA VARCHAR(3),
@TIPOCONV VARCHAR(3),
@TIPOCAMBIO NUMERIC(15,6),
@EQUIVUS NUMERIC(15,6),
@TIPOORDEN VARCHAR(2),
@SOLINSPECCION VARCHAR(16),
@NROPOLIZA VARCHAR(16),
@IMPORTE NUMERIC(15,6),
@SALLIQ NUMERIC(15,6),
@OBSERVACION VARCHAR(100),
@ESTADO VARCHAR(2),
@FECHA_CREACION NUMERIC(15,6),
@COD_USUARIO VARCHAR(8),
@IDE VARCHAR(50),
@EMBARQUE VARCHAR(100),
@FORMAPAGO VARCHAR(100),
@FACT VARCHAR(250),
@ADJUNTAR VARCHAR(250),
@IMPORTANTE VARCHAR(250),
@DOCUMENTOS VARCHAR(100),
@COMENTARIO VARCHAR(250),
@FICHATECNICA VARCHAR(4000)
--
AS
SET NOCOUNT ON
/*
SET @NUMERO='000000015'
SET @COD_PROVEE='01'
SET @FECHAEMI='01/07/2007'
SET @COMENTARIO='SDFSDFDSFDS'
SET @FECHA_CREACION='01/06/2007'
SET @COD_USUARIO='ERIKA'
--SET @IDE='DEVELOPER6'*/
--declare @TABLA varchar(50)

declare @TRAN1 int
declare @TRAN2 int
declare @TRAN3 int
--set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'

BEGIN TRAN INSERT_IMPORT_ORDER
EXEC('set quoted_identifier off INSERT INTO IMPORT_ORDER  (ID,VENDOR_ID,DOCUMENT_DATE,PROMISE_DATE,AMOUNT,CURRENCY_ID_IMP,
	EQUIVALENCE_US,CURRENCY_EXCHANGE,SOLIINSP,AMOUNT_BALANCE_LIQ,COMMENT,TYPE_ORDER,NUMBER_LIQ,CURR_EXCHANGE_TYPE,STATUS_ID,
	NUMBER_IMPORT_INT,USER_ID, CREATE_DATE)
 VALUES ("'+@NUMERO+'","'+@COD_PROVEE+'",'+@FECHAEMI+','+@FECHAENT+','+@IMPORTE+',"'+@MONEDA+'",'+@EQUIVUS+','+@TIPOCAMBIO+',
                 "'+@SOLINSPECCION+'" ,'+@SALLIQ+',"'+@OBSERVACION+'","'+@TIPOORDEN+'","'+@NROPOLIZA+'","'+@TIPOCONV+'", "'+@ESTADO+'","'+@NUMINT+'",
                 "'+@COD_USUARIO+'",'+@FECHA_CREACION+')')

SET @TRAN1 =@@ERROR

EXEC PUR_INSERT_IMPORT_ORDER_LINE @NUMERO,@IDE,@TRAN2 OUTPUT

EXEC PUR_INSERT_DATA_IMPORT @NUMERO,@EMBARQUE,@FORMAPAGO,@FACT, @IMPORTANTE,@DOCUMENTOS,@ADJUNTAR,@COMENTARIO,@FICHATECNICA,@TRAN3 OUTPUT


IF (@TRAN1<>0 AND @TRAN2<>0 AND @TRAN3<>0)   
	BEGIN
		ROLLBACK TRAN INSERT_IMPORT_ORDER
	END
ELSE
	BEGIN
		COMMIT TRAN INSERT_IMPORT_ORDER
	END