CREATE procedure [dbo].[PUR_RPT_CUADROCOMPARATIVO]
--DECLARE
@NUMINI AS VARCHAR(10),
@NUMFIN AS VARCHAR(10),
@FECINI AS NUMERIC(15,6),
@FECFIN AS NUMERIC(15,6)
/*
SET @NUMINI='0000000101'
SET @NUMFIN='0000000106'  
SET @FECINI=32120
SET @FECFIN=32120
*/
as
  declare @STRquery nvarchar(1500)

	set @STRquery='Select C.ID,C.DOCUMENT_DATE,C.VENDOR_ID,V.NAME,V.VAT_REGISTRATION,V.ADDR,V.CONTACT, V.REPRESENT,
	    C.COMMENT,C.CURRENCY_ID,COMMENT_COT,QUOTE_DATE,SCTIPCAM,SCVALIDEZ,SCTIEMENT,
	   SCFORPAG,SCNCOTIZ, PART_ID,PART_DESCRIPTION,UNIT,QTY,D.COMMENT AS GLOSADET, D.PRICE, AMOUNT_TAX,
                 GUARANTEE, MARK, DISCOUNT, DLV_DATE, IS_VAT  
                 FROM PURCHASE_QUOTE C INNER JOIN PURCHASE_QUOTE_LINE D ON C.ID=D.ID 
	    INNER JOIN VENDOR  V ON C.VENDOR_ID=V.ID  
                  WHERE (C.ID BETWEEN @NUMINI  AND @NUMFIN) AND (C.DOCUMENT_DATE BETWEEN @FECINI AND @FECFIN )  ORDER BY ITEM'  

             exec sp_executesql @STRquery,N'@NUMINI varchar(10), @NUMFIN VARCHAR(10),@FECINI NUMERIC(15,6), 
                  @FECFIN NUMERIC(15,6)',@NUMINI, @NUMFIN,@FECINI,@FECFIN