CREATE procedure [dbo].[PUR_RPT_REQUIREMENT]      
@NUMERO AS VARCHAR(10),      
@TIPO AS VARCHAR(2),
@BDCONTA VARCHAR(50)      
as      
 declare @STRquery nvarchar(1500)      
 set @STRquery='Select R.ID,REQUIRED_DATE,M.DESCRIPTION AS PERSOL,A.DESCRIPTION AS AREA,      
     R.STATUS,R.COMMENT,PART_ID,PART_DESCRIPTION,UNIT,QTY,AMOUNT_BALANCE,CC.COST_CENTER_DESCRIPTION AS CCOST_ID,D.COMMENT AS GLOSADET,    
  R.PROJECT_ID AS PRO_ID,P.DESCRIPTION AS PRO_DES,D.PROJECT_ID AS PRO_DET    
                 FROM REQUIREMENT R INNER JOIN REQUIREMENT_LINE D ON R.ID=D.ID AND R.TYPE=D.TYPE      
     INNER JOIN MASTER_HELP  M ON R.REQUIRED_USER=M.ID        
     AND M.TYPE_ID=''12'' INNER JOIN AREA A ON R.AREA_ID=A.ID      
   LEFT JOIN PROYECT P ON R.PROJECT_ID=P.ID LEFT JOIN CENTER_COST CC ON D.CCOST_ID=CC.COST_CENTER_ID    
                  WHERE R.ID=@NUMERO AND R.TYPE=@TIPO'      
             exec sp_executesql @STRquery,N'@NUMERO varchar(10), @TIPO varchar(2),@BDCONTA VARCHAR(50)',      
                  @NUMERO, @TIPO ,@BDCONTA 

