CREATE procedure [dbo].[PUR_RPT_IMPORT_ORDER]
--DECLARE
@NUMERO AS VARCHAR(13)
/*
SET @NUMERO='IMP123'
*/
AS
declare @STRquery nvarchar(4000)
set @STRquery='SELECT  I.ID AS I_ID, I.VENDOR_ID AS I_VENDOR_ID, I.DOCUMENT_DATE AS I_DOCUMENT_DATE, 
I.PROMISE_DATE AS I_PROMISE_DATE,I.AMOUNT AS I_AMOUNT, I.CURRENCY_ID_IMP AS CURRENCY_ID_IMP, 
I.EQUIVALENCE_US AS I_EQUIVALENCE_US,I.CURRENCY_EXCHANGE AS I_CURRENCY_EXCHANGE,I.SOLIINSP AS I_SOLIINSP,
I.GUIATRAN AS I_GUIATRAN, I.AMOUNT_LIQ AS I_AMOUNT_LIQ,I.LLIQREAL AS I_LLIQREAL, I.AMOUNT_BALANCE AS I_AMOUNT_BALANCE,
I.AMOUNT_BALANCE_LIQ AS I_AMOUNT_BALANCE_LIQ,I.COMMENT AS I_COMMENT, I.LREAL AS I_LREAL,I.TYPE_ORDER AS I_TYPE_ORDER,
I.NUMBER_LIQ AS I_NUMBER_LIQ,I.NADVALOR AS I_NADVALOR, I.ITINERANT AS I_ITINERANT, I.CPACKING AS I_CPACKING,
I.CURR_EXCHANGE_TYPE AS I_CURR_EXCHANGE_TYPE,I.TIPPREIMP AS I_TIPPREIMP, I.STATUS_ID AS I_STATUS_ID, I.AMOUNT_FLETE AS I_AMOUNT_FLETE, 
I.NUMBER_IMPORT_INT AS I_NUMBER_IMPORT_INT, I.SECURE AS I_SECURE,T.BILL_NAME_COMPANY AS T_BILL_NAME_COMPANY, 
T.BILL_ADDRESS_COMPANY AS T_BILL_ADDRESS_COMPANY, T.BILL_TELFAX AS T_BILL_TELFAX, T.BILL_CONTAC AS T_BILL_CONTAC, 
T.BILL_FAX AS T_BILL_FAX,T.EMBARQUE AS T_EMBARQUE,T.TERMS_TYPE AS T_TERMS_TYPE, T.NAME_FACT AS NAME_FACT, T.ADJUNTAR AS T_ADJUNTAR, 
T.IMPORTANT AS T_IMPORTANT,T.DOCUMENTS AS T_DOCUMENTS,T.COMMENT AS T_COMMENT, T.COMMENT_TECNIC AS T_COMMENT_TECNIC, 
V.NAME AS V_NAME, V.VAT_REGISTRATION AS V_VAT_REGISTRATION, V.ADDR AS V_ADDR, V.STATE_ID AS V_STATE_ID,  
V.PHONE AS V_PHONE,V.FAX_NUMBER AS V_FAX_NUMBER,V.EMAIL AS V_EMAIL, V.WEBSITE AS V_WEBSITE,V.CONTACT V_CONTACT, 
V.CONTACT_POSITION AS V_CONTACT_POSITION, V.CONTACT_PHONE AS V_CONTACT_PHONE, V.CONTACT_EMAIL AS V_CONTACT_EMAIL,V.REPRESENT AS V_REPRESENT, 
V.REPRESENT_POSITION AS V_REPRESENT_POSITION, V.REPRESENT_PHONE AS V_REPRESENT_PHONE,V.REPRESENT_EMAIL AS V_REPRESENT_EMAIL,V.COMMENT AS V_COMMENT, 
D.ITEM AS D_ITEM, D.PART_ID AS D_PART_ID,D.PART_DESCRIPTION AS D_PART_DESCRIPTION, D.UNIT AS D_UNIT, D.UNIT_REF AS D_UNIT_REF,D.FACTOR AS D_FACTOR, 
D.QTY AS D_QTY, D.PRICE_NET AS D_PRICE_NET,D.PRICE AS D_PRICE, D.PRICE_REF AS D_PRICE_REF,D.TOTAL_SALES AS D_TOTAL_SALES, D.QTY_IN AS D_QTY_IN,
D.QTY_BALANCE AS D_QTY_BALANCE,D.RECEIVE AS D_RECEIVE,D.VALUE_CIF AS D_VALUE_CIF,D.PERCEN_CIF AS D_PERCEN_CIF, D.VALUE_AMOUNT AS D_VALUE_AMOUNT, 
D.COMMENT AS D_COMMENT,D.COMMENT1 AS D_COMMENT1, D.FACTOR1 AS D_FACTOR1,D.QTY_NAC AS D_QTY_NAC,D.NUMBER_IMPOR_INT AS D_NUMBER_IMPOR_INT, 
P.ID_FAB AS P_ID_FAB, P.DESCRIPTION AS P_DESCRIPTION,P.DESCRIPTION_OPT AS P_DESCRIPTION_OPT,P.UNIT_OF_MEASUREMENT AS P_UNIT, 
P.CUSTOMS_TARIFF_ID AS P_CUSTOMS_TARIFF_ID FROM IMPORT_ORDER I INNER JOIN IMPORT_ORDER_LINE D ON 
I.ID = D.ID INNER JOIN PART P ON D.PART_ID = P.ID INNER JOIN VENDOR V 
ON I.VENDOR_ID = V.ID INNER JOIN DATA_IMPORT T ON 
I.ID = T.ID  WHERE I.ID=@NUMERO  ORDER BY D.ITEM' 
exec sp_executesql @STRquery,N'@NUMERO varchar(13)',@NUMERO
