CREATE PROC [dbo].[PUR_INSERT_FACTPROVE_L]    
@NUMERO VARCHAR(13),    
@TIPO VARCHAR(2),    
@IDE VARCHAR(50),    
@CANT_ERROR INT OUTPUT    
AS    
declare @TABLA varchar(50)    
    
SET NOCOUNT ON    
set @TABLA='tempdb.dbo.'+@IDE+'PURCHASE_FACT_SUPPLIER_L'    
SET @CANT_ERROR=0    
    
EXEC('set quoted_identifier off Insert Into PURCHASE_FACT_SUPPLIER_L (ID,TYPE,ITEM,PART_ID,PART_DESCRIPTION,UNIT,UNIT_REFERENCE,    
           FACTOR_REFERENCE,QTY,PRICE,DISCOUNT_PER,DISCOUNT,AMOUNT_TAX,PERCENT_TAX,PRICE_NET,AMOUNT_TOTAL,    
          AMOUNT_TOTAL_NET,QTY_ENTER,QTY_OUT,STATUS_ID,COMMENT1,TEXT_COMMENT,IS_VAT,    
          PRICE_UNIT,CCOST_ID,OPT_AFECTO)     
SELECT "'+@NUMERO+'","'+@TIPO+'",ITEM,PART_ID,PART_DESCRIPTION,UNIT,UNIT_REFERENCE,FACTOR_REFERENCE,    
 QTY,PRICE,DISCOUNT_PER,DISCOUNT,AMOUNT_TAX,PERCENT_TAX,PRICE_NET,AMOUNT_TOTAL,    
 AMOUNT_TOTAL_NET,QTY_ENTER,QTY_OUT,STATUS_ID,COMMENT1,TEXT_COMMENT,IS_VAT,    
 PRICE_UNIT,CCOST_ID,OPT_AFECTO FROM '+@TABLA+'')    
     
   IF @@ERROR<>0     
       SET @CANT_ERROR=1