CREATE PROC [dbo].[PUR_INSERT_FACTPROVE]       
--DECLARE      
@NUMERO VARCHAR(13),      
@TIPO VARCHAR(2),      
@FECHAEMI NUMERIC(15,6),            
@COD_PROVEE VARCHAR(11),      
@NROCOTIZA VARCHAR(15),      
@MONEDA VARCHAR(2),      
@FORMAPAGO VARCHAR(40),      
@TIPOCAMBIO NUMERIC(15,6),      
@FECHAENT NUMERIC(15,6),      
@COMENTARIO VARCHAR(250),      
@PERSOL VARCHAR(3),      
@RESPCOM VARCHAR(2),      
@DIRENT VARCHAR(60),      
@ESTADO VARCHAR(2),      
@MONTOBRUTO NUMERIC(15,6),      
@MONTODSCTO NUMERIC(15,6),      
@MONTOIGV NUMERIC(15,6),      
@MONTOTOTAL NUMERIC(15,6),      
@FECHA_CREACION NUMERIC(15,6),      
@COD_USUARIO VARCHAR(8),      
@TIPCONV VARCHAR(8),      
@FACTNOMBRE VARCHAR(70),      
@FACTRUC VARCHAR(11),      
@FACTDIREC VARCHAR(70),      
@TIPDOCREF VARCHAR(2),      
@NRODOCREF VARCHAR(13),      
@IDE VARCHAR(50),    
@PSERIE  VARCHAR(50),    
@PEXPIRATION_DATE  NUMERIC(15,6),      
@PBUDGET_ID VARCHAR(50),    
@PORDER_BUY VARCHAR(50),    
@PNOTE_IN_ID VARCHAR(50),    
@ALMA VARCHAR(50),
@SERVICIO VARCHAR(20)
AS      
SET NOCOUNT ON      
/*      
SET @NUMERO='000000015'      
SET @COD_PROVEE='01'      
SET @FECHAEMI='01/07/2007'      
SET @COMENTARIO='SDFSDFDSFDS'      
SET @FECHA_CREACION='01/06/2007'      
SET @COD_USUARIO='ERIKA'      
--SET @IDE='DEVELOPER6'*/      
--DECLARE @TABLA VARCHAR(50)      
DECLARE @TRAN1 INT      
DECLARE @TRAN2 INT      
--SET @TABLA='TEMPDB.DBO.'+@IDE+'FACWORCAB'      
      
BEGIN TRAN INSERT_PURCHASE_ORDER      
EXEC('SET QUOTED_IDENTIFIER OFF INSERT INTO PURCHASE_FACT_SUPPLIER  (ID,TYPE,DOCUMENT_DATE, VENDOR_ID, NUMBER_ESTIMATING,CURRENCY_TYPE,      
                  TERMS_NAME, SELL_RATE, PROMISE_DATE, COMMENT, AUTORIZED_ID,BUYER_PURCHASE_ID, ADDR_DLV, STATUS_ID, AMOUNT,DISCOUNT,      
                  AMOUNT_TAX, AMOUNT_SALES, UPDATE_DATE, USER_ID, CURR_EXCHANGE_TYPE, NAME_FACT, VAT_REGISTRATION_FACT,      
                 ADDR_FACT,REFER_DOCUMENT_TYPE,REFER_DOCUMENT_NUMBER,SERIE,EXPIRATION_DATE,BUDGET_ID,ORDER_BUY_ID,NOTE_IN_ID,WAREHOUSE_ID,TIME_DLV)      
 VALUES ("'+@NUMERO+'","'+@TIPO+'", '+@FECHAEMI+',"'+@COD_PROVEE+'","'+@NROCOTIZA+'","'+@MONEDA+'","'+@FORMAPAGO+'",'+@TIPOCAMBIO+',      
                 '+@FECHAENT+',"'+@COMENTARIO+'","'+@PERSOL+'","'+@RESPCOM+'","'+@DIRENT+'", "'+@ESTADO+'",'+@MONTOBRUTO+','+@MONTODSCTO+', '+@MONTOIGV+',      
     '+@MONTOTOTAL+', '+@FECHA_CREACION+',"'+@COD_USUARIO+'","'+@TIPCONV+'","'+@FACTNOMBRE+'","'+@FACTRUC+'","'+@FACTDIREC+'",      
                  "'+@TIPDOCREF+'","'+@NRODOCREF+'","'+@PSERIE+'",'+@PEXPIRATION_DATE+',"'+@PBUDGET_ID+'","'+@PORDER_BUY+'","'+@PNOTE_IN_ID+'","'+@ALMA+'","'+@SERVICIO+'")')      
      
SET @TRAN1 =@@ERROR      
      
EXEC PUR_INSERT_FACTPROVE_L  @NUMERO,@TIPO,@IDE,@TRAN2 OUTPUT      
      
IF (@TRAN1<>0 OR @TRAN2<>0)       
 BEGIN      
  ROLLBACK TRAN INSERT_PURCHASE_ORDER      
 END      
ELSE      
 BEGIN      
  COMMIT TRAN INSERT_PURCHASE_ORDER      
 END
