CREATE PROC [dbo].[PUR_INSERT_PURCHASE_QUOTE_LINE]    
@NUMERO VARCHAR(10),    
@IDE VARCHAR(50),    
@CANT_ERROR INT OUTPUT    
AS    
declare @TABLA varchar(50)    
    
SET NOCOUNT ON    
set @TABLA='tempdb.dbo.'+@IDE+'PURCHASE_QUOTE_LINE'    
    
SET @CANT_ERROR=0    
EXEC('set quoted_identifier off Insert Into PURCHASE_QUOTE_LINE (ID,ITEM,PART_ID,PART_DESCRIPTION,UNIT,QTY,COMMENT,PROJECT_ID,CC_ID,AREA_ID,REQUI_ID)     
SELECT "'+@NUMERO+'",ITEM,PART_ID,PART_DESCRIPTION,UNIT,QTY,COMMENT,PROJECT_ID,CC_ID,AREA_ID,REQUI_ID FROM '+@TABLA+'')    
    
IF @@ERROR<>0     
    SET @CANT_ERROR=1 


