CREATE PROC [dbo].[PUR_INSERT_REQUIREMENT]  
--DECLARE  
@NUMERO VARCHAR(10),  
@TIPO VARCHAR(2),  
@COD_PERSOL VARCHAR(8),  
@FECHAEMI NUMERIC(15,6),  
@COMENTARIO VARCHAR(250),  
@COD_AREA VARCHAR(6),  
@ESTADO VARCHAR(1),  
@FECHA_CREACION NUMERIC(15,6),  
@COD_USUARIO VARCHAR(8),  
@IDE VARCHAR(50),  
@PROJECT_ID VARCHAR(50)  
AS  
SET NOCOUNT ON  
/*  
SET @NUMERO='000000015'  
SET @TIPO='RQ'  
SET @COD_PERSOL='01'  
SET @FECHAEMI='01/07/2007'  
SET @COMENTARIO='SDFSDFDSFDS'  
SET @COD_AREA='01'  
SET @ESTADO='P'  
SET @FECHA_CREACION='01/06/2007'  
SET @COD_USUARIO='ERIKA'  
--SET @IDE='DEVELOPER6'*/  
--declare @TABLA varchar(50)  
declare @TRAN1 int  
declare @TRAN2 int  
--set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'  
  
BEGIN TRAN INSERT_REQUIREMENT  
EXEC('set quoted_identifier off INSERT INTO REQUIREMENT (ID,TYPE,REQUIRED_USER,REQUIRED_DATE,COMMENT,  
            AREA_ID,STATUS,CREATE_DATE,USER_ID,PROJECT_ID) VALUES ("'+@NUMERO+'","'+@TIPO+'","'+@COD_PERSOL+'", '+@FECHAEMI+',  
           "'+@COMENTARIO+'","'+@COD_AREA+'","'+@ESTADO+'",'+@FECHA_CREACION+',"'+@COD_USUARIO+'","'+@PROJECT_ID+'")')  
  
SET @TRAN1 =@@ERROR  
  
EXEC PUR_INSERT_REQUIREMENT_LINE @NUMERO,@TIPO,@IDE,@TRAN2 OUTPUT  
  
IF (@TRAN1<>0 OR @TRAN2<>0)   
 BEGIN  
  ROLLBACK TRAN INSERT_REQUIREMENT  
 END  
ELSE  
 BEGIN  
  COMMIT TRAN INSERT_REQUIREMENT  
 END