CREATE procedure [dbo].[PUR_RPT_TRANS_IN_SERVICE]
--DECLARE
@TIPODOC AS VARCHAR(2),
@NUMERO AS VARCHAR(10)
/*
SET @TIPODOC='NI'
SET @NUMERO='0000000019'
*/
AS
	declare @STRquery nvarchar(4000)

	set @STRquery='Select C.TYPE_ID,C.NUMBER_DOC,DOCUMENT_DATE,C.VENDOR_ID,V.NAME,V.VAT_REGISTRATION,
                      TRANS_TYPE_ID,TRANS_ID, C.STATUS,DOCUMENT_REF,NUMBER_REF,VENDOR_ID,UPDATE_DATE,
                      USER_ID,CURRENCY_ID, NUMBER_ORDER_MANUFAC,STATUS_GUIA,C.CCOST,C.COMMENT,CURRENCY_EXCHANGE,
                      D.TYPE_ID,D.NUMBER_DOC,ITEM,PART_ID,QTY,PRICE_UNIT,AMOUNT_TOTAL,PART_DESCRIPTION,QTY_IN,QTY_REF 
                      FROM TRANS_IN_SERVICE C INNER JOIN   TRANS_IN_SERVICE_LINE D ON C.TYPE_ID=D.TYPE_ID AND 
                      C.NUMBER_DOC=D.NUMBER_DOC INNER JOIN VENDOR V ON C.VENDOR_ID=V.ID
                      WHERE C.TYPE_ID=@TIPODOC AND C.NUMBER_DOC=@NUMERO ' 

             exec sp_executesql @STRquery,N'@TIPODOC varchar(2),@NUMERO varchar(10)',@TIPODOC,@NUMERO