CREATE PROCEDURE [dbo].[PUR_RPT_ORDENCOMPRAPROVART]  
--DECLARE
@PROV1 	CHAR(11),  
@PROV2 CHAR(11),  
@ART1 CHAR(20),  
@ART2 CHAR(20),  
@ESTADO1 CHAR(2),  
@ESTADO2 CHAR(2),
@TIPO CHAR(2), 
@FEC1 NUMERIC(15,6),
@FEC2 NUMERIC(15,6)

/*
SET @PROV1='001'
SET @PROV2='001'
SET @ART1='001'
SET @ART2='002'
SET @ESTADO1='01'
SET @ESTADO2='02'
SET @TIPO='OC'
*/
AS  
DECLARE @STRQUERY NVarchar(4000)
DECLARE @criterio NVarchar(2000)

IF LEN(@PROV1)<>0 AND LEN(@PROV2)<>0 
   SET  @criterio=' AND A.VENDOR_ID BETWEEN @PROV1 AND @PROV2 order by V.NAME,c.PART_DESCRIPTION, a.ID '

IF LEN(@ART1)<>0 AND LEN(@ART2)<>0 
   SET  @criterio=' AND C.PART_ID BETWEEN @ART1 AND @ART2 ORDER BY c.PART_DESCRIPTION, V.NAME, a.ID '

  SET @STRQUERY='select a.ID,a.STATUS_ID,d.DESCRIPTION, a.DOCUMENT_DATE,a.PROMISE_DATE,a.VENDOR_ID,   
	       V.NAME,a.CURRENCY_TYPE,a.NUMBER_ESTIMATING, c.ITEM,c.PART_ID,c.PART_DESCRIPTION,   
               c.UNIT,C.PRICE, C.DISCOUNT_PER, C.DISCOUNT,  C.AMOUNT_TAX, C.PERCENT_TAX,   
               C.PRICE_NET, C.AMOUNT_TOTAL, C.AMOUNT_TOTAL_NET, C.PRICE_UNIT, c.QTY, c.QTY_ENTER,  
               (c.QTY- c.QTY_ENTER) AS SALDO  From  PURCHASE_ORDER a INNER JOIN   
		PURCHASE_ORDER_LINE C ON a.ID=c.ID AND C.TYPE=@TIPO INNER JOIN   
		PURCHASE_STATUS d ON a.STATUS_ID=d.ID INNER JOIN VENDOR V ON A.VENDOR_ID=V.ID
                Where a.STATUS_ID BETWEEN @ESTADO1 AND @ESTADO2  AND DOCUMENT_DATE BETWEEN @FEC1 AND @FEC2 ' 
  
  set @STRQUERY=@STRQUERY + @criterio
  exec sp_executesql @STRQUERY,N'@PROV1 CHAR(11),@PROV2 CHAR(11),
                @ART1 CHAR(20),@ART2 CHAR(20),@ESTADO1 CHAR(2),@ESTADO2 CHAR(2),
                @TIPO CHAR(2),@FEC1 NUMERIC(15,6),@FEC2 NUMERIC(15,6)',@PROV1,@PROV2,@ART1,@ART2,@ESTADO1,
                @ESTADO2,@TIPO,@FEC1,@FEC2