CREATE PROCEDURE RANKING_VENTAS_MENSUALES_ANUAL
@fecha1 varchar(10),
@fecha2 varchar(10)
 AS

DECLARE @CUSTOMER_ID VARCHAR(15)
DECLARE @DOCUMENT_DATE VARCHAR(10)
DECLARE @CUSTOMER_ID_DOS VARCHAR(15)
DECLARE @QTY FLOAT
DECLARE @AMOUNT FLOAT
DECLARE @SUMA_QTY_ENERO FLOAT
DECLARE @SUMA_AMOUNT_ENERO FLOAT
DECLARE @SUMA_QTY_FEBRERO FLOAT
DECLARE @SUMA_AMOUNT_FEBRERO FLOAT
DECLARE @SUMA_QTY_MARZO FLOAT
DECLARE @SUMA_AMOUNT_MARZO FLOAT
DECLARE @SUMA_QTY_ABRIL FLOAT
DECLARE @SUMA_AMOUNT_ABRIL FLOAT
DECLARE @SUMA_QTY_MAYO FLOAT
DECLARE @SUMA_AMOUNT_MAYO FLOAT
DECLARE @SUMA_QTY_JUNIO FLOAT
DECLARE @SUMA_AMOUNT_JUNIO FLOAT
DECLARE @SUMA_QTY_JULIO FLOAT
DECLARE @SUMA_AMOUNT_JULIO FLOAT
DECLARE @SUMA_QTY_AGOSTO FLOAT
DECLARE @SUMA_AMOUNT_AGOSTO FLOAT
DECLARE @SUMA_QTY_SETIEMBRE FLOAT
DECLARE @SUMA_AMOUNT_SETIEMBRE FLOAT
DECLARE @SUMA_QTY_OCTUBRE FLOAT
DECLARE @SUMA_AMOUNT_OCTUBRE FLOAT
DECLARE @SUMA_QTY_NOVIEMBRE FLOAT
DECLARE @SUMA_AMOUNT_NOVIEMBRE FLOAT
DECLARE @SUMA_QTY_DICIEMBRE FLOAT
DECLARE @SUMA_AMOUNT_DICIEMBRE FLOAT
DECLARE @MES VARCHAR(2)



DROP TABLE TABLADECLIENTES

--Select B.DOCUMENT_DATE,B.CUSTOMER_ID,B.CUSTOMER_NAME,A.AMOUNT,A.QTY,A.NUMBER_DOCUMENT,A.DOCUMENT_ID
--into TABLADECLIENTES
--From ([DROG_DANY].dbo.RECEIVABLE_LINE A Inner Join [DROG_DANY].dbo.RECEIVABLE B on  A.DOCUMENT_ID = B.DOCUMENT_ID and   
--A.NUMBER_SERIE = B.NUMBER_SERIE and  A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT)   INNER JOIN [DROG_DANY].DBO.PART C   ON A.PART_ID=C.ID   
--Where  A.STATUS <> 'A' AND NOT (IS_STOCKED='N' AND SERIES='N' AND IS_LOT='N')  AND DOCUMENT_DATE>=@FECHA1 and   DOCUMENT_DATE<= @FECHA2   
--ORDER BY DOCUMENT_DATE ,A.NUMBER_DOCUMENT 

Select DOCUMENT_DATE,CUSTOMER_ID,VAT_REGISTRATION,CUSTOMER_NAME,SUM(QTY)AS QTY,SUM(A.AMOUNT-A.AMOUNT_TAX)AS AMOUNT,
SUM(A.AMOUNT_US)AS AMOUNT_US,B.CURRENCY_ID,SUM(A.AMOUNT_TAX)AS AMOUNT_TAX,B.NUMBER_DOCUMENT,B.DOCUMENT_ID
into TABLADECLIENTES
From ([DROG_DANY].dbo.RECEIVABLE_LINE A Inner Join [DROG_DANY].dbo.RECEIVABLE B on  A.DOCUMENT_ID = B.DOCUMENT_ID and 
A.NUMBER_SERIE = B.NUMBER_SERIE and  A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT)   INNER JOIN [DROG_DANY].DBO.PART C 
ON A.PART_ID=C.ID 
Where  B.STATUS <> 'A'  AND  DOCUMENT_DATE>=@FECHA1 and 
DOCUMENT_DATE<= @FECHA2  
GROUP BY B.DOCUMENT_DATE,B.CUSTOMER_ID,B.VAT_REGISTRATION,B.CUSTOMER_NAME,B.CURRENCY_ID,B.NUMBER_DOCUMENT,B.DOCUMENT_ID
ORDER BY DOCUMENT_DATE--A.NUMBER_SERIE,A.NUMBER_DOCUMENT

DELETE FROM TABLAFINALDECLIENTES

INSERT INTO TABLAFINALDECLIENTES(CUSTOMER_ID,CUSTOMER_NAME,VAT_REGISTRATION)
SELECT DISTINCT CUSTOMER_ID,CUSTOMER_NAME,VAT_REGISTRATION 
FROM TABLADECLIENTES ORDER BY CUSTOMER_NAME,CUSTOMER_ID



DECLARE CURSOR1 CURSOR FOR
SELECT  CUSTOMER_ID FROM TABLAFINALDECLIENTES ORDER BY CUSTOMER_ID
OPEN CURSOR1
FETCH NEXT FROM CURSOR1
INTO @CUSTOMER_ID
WHILE @@FETCH_STATUS=0
BEGIN
	SET @SUMA_QTY_ENERO=0
SET @SUMA_AMOUNT_ENERO=0
SET @SUMA_QTY_FEBRERO=0
SET @SUMA_AMOUNT_FEBRERO=0
SET @SUMA_QTY_MARZO=0
SET @SUMA_AMOUNT_MARZO=0
SET @SUMA_QTY_ABRIL=0
SET @SUMA_AMOUNT_ABRIL=0
SET @SUMA_QTY_MAYO=0
SET @SUMA_AMOUNT_MAYO=0
SET @SUMA_QTY_JUNIO=0
SET @SUMA_AMOUNT_JUNIO=0
SET @SUMA_QTY_JULIO=0
SET @SUMA_AMOUNT_JULIO=0
SET @SUMA_QTY_AGOSTO=0
SET @SUMA_AMOUNT_AGOSTO=0
SET @SUMA_QTY_SETIEMBRE=0
SET @SUMA_AMOUNT_SETIEMBRE=0
SET @SUMA_QTY_OCTUBRE=0
SET @SUMA_AMOUNT_OCTUBRE=0
SET @SUMA_QTY_NOVIEMBRE=0
SET @SUMA_AMOUNT_NOVIEMBRE=0
SET @SUMA_QTY_DICIEMBRE=0
SET @SUMA_AMOUNT_DICIEMBRE=0
	DECLARE CURSOR2 CURSOR FOR
	SELECT CONVERT(VARCHAR,DOCUMENT_DATE,103)AS DOCUMENT_DATE,CUSTOMER_ID,QTY,AMOUNT FROM TABLADECLIENTES WHERE CUSTOMER_ID=@CUSTOMER_ID
	OPEN CURSOR2
	FETCH NEXT FROM CURSOR2
	INTO @DOCUMENT_DATE,@CUSTOMER_ID_DOS,@QTY,@AMOUNT
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @MES=SUBSTRING(@DOCUMENT_DATE,4,2)
		IF @MES='01'
		BEGIN
			SET @SUMA_QTY_ENERO=@SUMA_QTY_ENERO+@QTY
			SET @SUMA_AMOUNT_ENERO=@SUMA_AMOUNT_ENERO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET ENERO=@SUMA_AMOUNT_ENERO,ENERO_QTY=@SUMA_QTY_ENERO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='02'
		BEGIN
			SET @SUMA_QTY_FEBRERO=@SUMA_QTY_FEBRERO+@QTY
			SET @SUMA_AMOUNT_FEBRERO=@SUMA_AMOUNT_FEBRERO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET FEBRERO=@SUMA_AMOUNT_FEBRERO,FEBRERO_QTY=@SUMA_QTY_FEBRERO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='03'
		BEGIN
			SET @SUMA_QTY_MARZO=@SUMA_QTY_MARZO+@QTY
			SET @SUMA_AMOUNT_MARZO=@SUMA_AMOUNT_MARZO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET MARZO=@SUMA_AMOUNT_MARZO,MARZO_QTY=@SUMA_QTY_MARZO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='04'
		BEGIN
			SET @SUMA_QTY_ABRIL=@SUMA_QTY_ABRIL+@QTY
			SET @SUMA_AMOUNT_ABRIL=@SUMA_AMOUNT_ABRIL+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET ABRIL=@SUMA_AMOUNT_ABRIL,ABRIL_QTY=@SUMA_QTY_ABRIL WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='05'
		BEGIN
			SET @SUMA_QTY_MAYO=@SUMA_QTY_MAYO+@QTY
			SET @SUMA_AMOUNT_MAYO=@SUMA_AMOUNT_MAYO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET MAYO=@SUMA_AMOUNT_MAYO,MAYO_QTY=@SUMA_QTY_MAYO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='06'
		BEGIN
			SET @SUMA_QTY_JUNIO=@SUMA_QTY_JUNIO+@QTY
			SET @SUMA_AMOUNT_JUNIO=@SUMA_AMOUNT_JUNIO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET JUNIO=@SUMA_AMOUNT_JUNIO,JUNIO_QTY=@SUMA_QTY_JUNIO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='07'
		BEGIN
			SET @SUMA_QTY_JULIO=@SUMA_QTY_JULIO+@QTY
			SET @SUMA_AMOUNT_JULIO=@SUMA_AMOUNT_JULIO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET JULIO=@SUMA_AMOUNT_JULIO,JULIO_QTY=@SUMA_QTY_JULIO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='08'
		BEGIN
			SET @SUMA_QTY_AGOSTO=@SUMA_QTY_AGOSTO+@QTY
			SET @SUMA_AMOUNT_AGOSTO=@SUMA_AMOUNT_AGOSTO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET AGOSTO=@SUMA_AMOUNT_AGOSTO,AGOSTO_QTY=@SUMA_QTY_AGOSTO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='09'
		BEGIN
			SET @SUMA_QTY_SETIEMBRE=@SUMA_QTY_SETIEMBRE+@QTY
			SET @SUMA_AMOUNT_SETIEMBRE=@SUMA_AMOUNT_SETIEMBRE+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET SETIEMBRE=@SUMA_AMOUNT_SETIEMBRE,SETIEMBRE_QTY=@SUMA_QTY_SETIEMBRE WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='10'
		BEGIN
			SET @SUMA_QTY_OCTUBRE=@SUMA_QTY_OCTUBRE+@QTY
			SET @SUMA_AMOUNT_OCTUBRE=@SUMA_AMOUNT_OCTUBRE+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET OCTUBRE=@SUMA_AMOUNT_OCTUBRE,OCTUBRE_QTY=@SUMA_QTY_OCTUBRE WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='11'
		BEGIN
			SET @SUMA_QTY_NOVIEMBRE=@SUMA_QTY_NOVIEMBRE+@QTY
			SET @SUMA_AMOUNT_NOVIEMBRE=@SUMA_AMOUNT_NOVIEMBRE+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET NOVIEMBRE=@SUMA_AMOUNT_NOVIEMBRE,NOVIEMBRE_QTY=@SUMA_QTY_NOVIEMBRE WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='12'
		BEGIN
			SET @SUMA_QTY_DICIEMBRE=@SUMA_QTY_DICIEMBRE+@QTY
			SET @SUMA_AMOUNT_DICIEMBRE=@SUMA_AMOUNT_DICIEMBRE+@AMOUNT
			UPDATE TABLAFINALDECLIENTES SET DICIEMBRE=@SUMA_AMOUNT_DICIEMBRE,DICIEMBRE_QTY=@SUMA_QTY_DICIEMBRE WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
	

	FETCH NEXT FROM CURSOR2
	INTO @DOCUMENT_DATE,@CUSTOMER_ID_DOS,@QTY,@AMOUNT
	END
	
	CLOSE CURSOR2
	DEALLOCATE CURSOR2
FETCH NEXT FROM CURSOR1
INTO @CUSTOMER_ID
END
CLOSE CURSOR1
DEALLOCATE CURSOR1




UPDATE TABLAFINALDECLIENTES SET
ENERO=(CASE WHEN ENERO IS NULL THEN 0 ELSE ENERO END),ENERO_QTY=(CASE WHEN ENERO_QTY IS NULL THEN 0 ELSE ENERO_QTY END),
FEBRERO=(CASE WHEN FEBRERO IS NULL THEN 0 ELSE FEBRERO END),FEBRERO_QTY=(CASE WHEN FEBRERO_QTY IS NULL THEN 0 ELSE FEBRERO_QTY END),
MARZO=(CASE WHEN MARZO IS NULL THEN 0 ELSE MARZO END),MARZO_QTY=(CASE WHEN MARZO_QTY IS NULL THEN 0 ELSE MARZO_QTY END),
ABRIL=(CASE WHEN ABRIL IS NULL THEN 0 ELSE ABRIL END),ABRIL_QTY=(CASE WHEN ABRIL_QTY IS NULL THEN 0 ELSE ABRIL_QTY END),
MAYO=(CASE WHEN MAYO IS NULL THEN 0 ELSE MAYO END),MAYO_QTY=(CASE WHEN MAYO_QTY IS NULL THEN 0 ELSE MAYO_QTY END),
JUNIO=(CASE WHEN JUNIO IS NULL THEN 0 ELSE JUNIO END),JUNIO_QTY=(CASE WHEN JUNIO_QTY IS NULL THEN 0 ELSE JUNIO_QTY END),
JULIO=(CASE WHEN JULIO IS NULL THEN 0 ELSE JULIO END),JULIO_QTY=(CASE WHEN JULIO_QTY IS NULL THEN 0 ELSE JULIO_QTY END),
AGOSTO=(CASE WHEN AGOSTO IS NULL THEN 0 ELSE AGOSTO END),AGOSTO_QTY=(CASE WHEN AGOSTO_QTY IS NULL THEN 0 ELSE AGOSTO_QTY END),
SETIEMBRE=(CASE WHEN SETIEMBRE IS NULL THEN 0 ELSE SETIEMBRE END),SETIEMBRE_QTY=(CASE WHEN SETIEMBRE_QTY IS NULL THEN 0 ELSE SETIEMBRE_QTY END),
OCTUBRE=(CASE WHEN OCTUBRE IS NULL THEN 0 ELSE OCTUBRE END),OCTUBRE_QTY=(CASE WHEN OCTUBRE_QTY IS NULL THEN 0 ELSE OCTUBRE_QTY END),
NOVIEMBRE=(CASE WHEN NOVIEMBRE IS NULL THEN 0 ELSE NOVIEMBRE END),NOVIEMBRE_QTY=(CASE WHEN NOVIEMBRE_QTY IS NULL THEN 0 ELSE NOVIEMBRE_QTY END),
DICIEMBRE=(CASE WHEN DICIEMBRE IS NULL THEN 0 ELSE DICIEMBRE END),DICIEMBRE_QTY=(CASE WHEN DICIEMBRE_QTY IS NULL THEN 0 ELSE DICIEMBRE_QTY END)