CREATE PROCEDURE RANKING_VENTAS_MENSUALES_ANUAL_VAT_REGISTRATION
@fecha1 varchar(10),
@fecha2 varchar(10)
 AS

DECLARE @CUSTOMER_ID VARCHAR(15)
DECLARE @DOCUMENT_DATE VARCHAR(10)
DECLARE @CUSTOMER_ID_DOS VARCHAR(15)
DECLARE @QTY NUMERIC(38,12)
DECLARE @AMOUNT NUMERIC(38,12)
DECLARE @SUMA_QTY_ENERO NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_ENERO NUMERIC(38,12)
DECLARE @SUMA_QTY_FEBRERO NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_FEBRERO NUMERIC(38,12)
DECLARE @SUMA_QTY_MARZO NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_MARZO NUMERIC(38,12)
DECLARE @SUMA_QTY_ABRIL NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_ABRIL NUMERIC(38,12)
DECLARE @SUMA_QTY_MAYO NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_MAYO NUMERIC(38,12)
DECLARE @SUMA_QTY_JUNIO NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_JUNIO NUMERIC(38,12)
DECLARE @SUMA_QTY_JULIO NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_JULIO NUMERIC(38,12)
DECLARE @SUMA_QTY_AGOSTO NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_AGOSTO NUMERIC(38,12)
DECLARE @SUMA_QTY_SETIEMBRE NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_SETIEMBRE NUMERIC(38,12)
DECLARE @SUMA_QTY_OCTUBRE NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_OCTUBRE NUMERIC(38,12)
DECLARE @SUMA_QTY_NOVIEMBRE NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_NOVIEMBRE NUMERIC(38,12)
DECLARE @SUMA_QTY_DICIEMBRE NUMERIC(38,12)
DECLARE @SUMA_AMOUNT_DICIEMBRE NUMERIC(38,12)
DECLARE @MES VARCHAR(2)



DROP TABLE TABLADECLIENTES_VAT_REGISTRATION

--Select B.DOCUMENT_DATE,B.CUSTOMER_ID,B.CUSTOMER_NAME,A.AMOUNT,A.QTY,A.NUMBER_DOCUMENT,A.DOCUMENT_ID
--into TABLADECLIENTES
--From ([DROG_DANY].dbo.RECEIVABLE_LINE A Inner Join [DROG_DANY].dbo.RECEIVABLE B on  A.DOCUMENT_ID = B.DOCUMENT_ID and   
--A.NUMBER_SERIE = B.NUMBER_SERIE and  A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT)   INNER JOIN [DROG_DANY].DBO.PART C   ON A.PART_ID=C.ID   
--Where  A.STATUS <> 'A' AND NOT (IS_STOCKED='N' AND SERIES='N' AND IS_LOT='N')  AND DOCUMENT_DATE>=@FECHA1 and   DOCUMENT_DATE<= @FECHA2   
--ORDER BY DOCUMENT_DATE ,A.NUMBER_DOCUMENT 

Select DOCUMENT_DATE,VAT_REGISTRATION,CUSTOMER_NAME,SUM(QTY)AS QTY,SUM(A.AMOUNT)AS AMOUNT,
SUM(A.AMOUNT_US)AS AMOUNT_US,B.CURRENCY_ID,SUM(A.AMOUNT_TAX)AS AMOUNT_TAX,B.NUMBER_DOCUMENT,B.DOCUMENT_ID
into TABLADECLIENTES_VAT_REGISTRATION
From ([DROG_DANY].dbo.RECEIVABLE_LINE A Inner Join [DROG_DANY].dbo.RECEIVABLE B on  A.DOCUMENT_ID = B.DOCUMENT_ID and 
A.NUMBER_SERIE = B.NUMBER_SERIE and  A.NUMBER_DOCUMENT = B.NUMBER_DOCUMENT)   INNER JOIN [DROG_DANY].DBO.PART C 
ON A.PART_ID=C.ID 
Where  B.STATUS <> 'A'  AND NOT (IS_STOCKED='N' AND SERIES='N' AND IS_LOT='N') AND DOCUMENT_DATE>=@FECHA1 and 
DOCUMENT_DATE<= @FECHA2  
GROUP BY B.DOCUMENT_DATE,B.VAT_REGISTRATION,B.CUSTOMER_NAME,B.CURRENCY_ID,B.NUMBER_DOCUMENT,B.DOCUMENT_ID
ORDER BY DOCUMENT_DATE--A.NUMBER_SERIE,A.NUMBER_DOCUMENT

DELETE FROM TABLAFINALDECLIENTES_VAT_REGISTRATION

INSERT INTO TABLAFINALDECLIENTES_VAT_REGISTRATION(CUSTOMER_ID,CUSTOMER_NAME)
SELECT DISTINCT VAT_REGISTRATION,CUSTOMER_NAME 
FROM TABLADECLIENTES_VAT_REGISTRATION ORDER BY CUSTOMER_NAME,VAT_REGISTRATION



DECLARE CURSOR1 CURSOR FOR
SELECT  CUSTOMER_ID FROM TABLAFINALDECLIENTES_VAT_REGISTRATION ORDER BY CUSTOMER_ID
OPEN CURSOR1
FETCH NEXT FROM CURSOR1
INTO @CUSTOMER_ID
WHILE @@FETCH_STATUS=0
BEGIN
	SET @SUMA_QTY_ENERO=0
SET @SUMA_AMOUNT_ENERO=0
SET @SUMA_QTY_FEBRERO=0
SET @SUMA_AMOUNT_FEBRERO=0
SET @SUMA_QTY_MARZO=0
SET @SUMA_AMOUNT_MARZO=0
SET @SUMA_QTY_ABRIL=0
SET @SUMA_AMOUNT_ABRIL=0
SET @SUMA_QTY_MAYO=0
SET @SUMA_AMOUNT_MAYO=0
SET @SUMA_QTY_JUNIO=0
SET @SUMA_AMOUNT_JUNIO=0
SET @SUMA_QTY_JULIO=0
SET @SUMA_AMOUNT_JULIO=0
SET @SUMA_QTY_AGOSTO=0
SET @SUMA_AMOUNT_AGOSTO=0
SET @SUMA_QTY_SETIEMBRE=0
SET @SUMA_AMOUNT_SETIEMBRE=0
SET @SUMA_QTY_OCTUBRE=0
SET @SUMA_AMOUNT_OCTUBRE=0
SET @SUMA_QTY_NOVIEMBRE=0
SET @SUMA_AMOUNT_NOVIEMBRE=0
SET @SUMA_QTY_DICIEMBRE=0
SET @SUMA_AMOUNT_DICIEMBRE=0
	DECLARE CURSOR2 CURSOR FOR
	SELECT CONVERT(VARCHAR,DOCUMENT_DATE,103)AS DOCUMENT_DATE,VAT_REGISTRATION,QTY,AMOUNT FROM TABLADECLIENTES_VAT_REGISTRATION WHERE VAT_REGISTRATION=@CUSTOMER_ID
	OPEN CURSOR2
	FETCH NEXT FROM CURSOR2
	INTO @DOCUMENT_DATE,@CUSTOMER_ID_DOS,@QTY,@AMOUNT
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @MES=SUBSTRING(@DOCUMENT_DATE,4,2)
		IF @MES='01'
		BEGIN
			
			SET @SUMA_QTY_ENERO=@SUMA_QTY_ENERO+@QTY
			SET @SUMA_AMOUNT_ENERO=@SUMA_AMOUNT_ENERO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET ENERO=@SUMA_AMOUNT_ENERO,ENERO_QTY=@SUMA_QTY_ENERO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='02'
		BEGIN
			SET @SUMA_QTY_FEBRERO=@SUMA_QTY_FEBRERO+@QTY
			SET @SUMA_AMOUNT_FEBRERO=@SUMA_AMOUNT_FEBRERO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET FEBRERO=@SUMA_AMOUNT_FEBRERO,FEBRERO_QTY=@SUMA_QTY_FEBRERO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='03'
		BEGIN
			SET @SUMA_QTY_MARZO=@SUMA_QTY_MARZO+@QTY
			SET @SUMA_AMOUNT_MARZO=@SUMA_AMOUNT_MARZO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET MARZO=@SUMA_AMOUNT_MARZO,MARZO_QTY=@SUMA_QTY_MARZO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='04'
		BEGIN
			SET @SUMA_QTY_ABRIL=@SUMA_QTY_ABRIL+@QTY
			SET @SUMA_AMOUNT_ABRIL=@SUMA_AMOUNT_ABRIL+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET ABRIL=@SUMA_AMOUNT_ABRIL,ABRIL_QTY=@SUMA_QTY_ABRIL WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='05'
		BEGIN
			SET @SUMA_QTY_MAYO=@SUMA_QTY_MAYO+@QTY
			SET @SUMA_AMOUNT_MAYO=@SUMA_AMOUNT_MAYO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET MAYO=@SUMA_AMOUNT_MAYO,MAYO_QTY=@SUMA_QTY_MAYO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='06'
		BEGIN
			SET @SUMA_QTY_JUNIO=@SUMA_QTY_JUNIO+@QTY
			SET @SUMA_AMOUNT_JUNIO=@SUMA_AMOUNT_JUNIO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET JUNIO=@SUMA_AMOUNT_JUNIO,JUNIO_QTY=@SUMA_QTY_JUNIO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='07'
		BEGIN
			SET @SUMA_QTY_JULIO=@SUMA_QTY_JULIO+@QTY
			SET @SUMA_AMOUNT_JULIO=@SUMA_AMOUNT_JULIO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET JULIO=@SUMA_AMOUNT_JULIO,JULIO_QTY=@SUMA_QTY_JULIO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='08'
		BEGIN
			SET @SUMA_QTY_AGOSTO=@SUMA_QTY_AGOSTO+@QTY
			SET @SUMA_AMOUNT_AGOSTO=@SUMA_AMOUNT_AGOSTO+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET AGOSTO=@SUMA_AMOUNT_AGOSTO,AGOSTO_QTY=@SUMA_QTY_AGOSTO WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='09'
		BEGIN
			SET @SUMA_QTY_SETIEMBRE=@SUMA_QTY_SETIEMBRE+@QTY
			SET @SUMA_AMOUNT_SETIEMBRE=@SUMA_AMOUNT_SETIEMBRE+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET SETIEMBRE=@SUMA_AMOUNT_SETIEMBRE,SETIEMBRE_QTY=@SUMA_QTY_SETIEMBRE WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='10'
		BEGIN
			SET @SUMA_QTY_OCTUBRE=@SUMA_QTY_OCTUBRE+@QTY
			SET @SUMA_AMOUNT_OCTUBRE=@SUMA_AMOUNT_OCTUBRE+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET OCTUBRE=@SUMA_AMOUNT_OCTUBRE,OCTUBRE_QTY=@SUMA_QTY_OCTUBRE WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='11'
		BEGIN
			SET @SUMA_QTY_NOVIEMBRE=@SUMA_QTY_NOVIEMBRE+@QTY
			SET @SUMA_AMOUNT_NOVIEMBRE=@SUMA_AMOUNT_NOVIEMBRE+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET NOVIEMBRE=@SUMA_AMOUNT_NOVIEMBRE,NOVIEMBRE_QTY=@SUMA_QTY_NOVIEMBRE WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
		ELSE IF @MES='12'
		BEGIN
			SET @SUMA_QTY_DICIEMBRE=@SUMA_QTY_DICIEMBRE+@QTY
			SET @SUMA_AMOUNT_DICIEMBRE=@SUMA_AMOUNT_DICIEMBRE+@AMOUNT
			UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET DICIEMBRE=@SUMA_AMOUNT_DICIEMBRE,DICIEMBRE_QTY=@SUMA_QTY_DICIEMBRE WHERE CUSTOMER_ID=@CUSTOMER_ID
		END
	

	FETCH NEXT FROM CURSOR2
	INTO @DOCUMENT_DATE,@CUSTOMER_ID_DOS,@QTY,@AMOUNT
	END
	
	CLOSE CURSOR2
	DEALLOCATE CURSOR2
FETCH NEXT FROM CURSOR1
INTO @CUSTOMER_ID
END
CLOSE CURSOR1
DEALLOCATE CURSOR1




UPDATE TABLAFINALDECLIENTES_VAT_REGISTRATION SET
ENERO=(CASE WHEN ENERO IS NULL THEN 0 ELSE ENERO END),ENERO_QTY=(CASE WHEN ENERO_QTY IS NULL THEN 0 ELSE ENERO_QTY END),
FEBRERO=(CASE WHEN FEBRERO IS NULL THEN 0 ELSE FEBRERO END),FEBRERO_QTY=(CASE WHEN FEBRERO_QTY IS NULL THEN 0 ELSE FEBRERO_QTY END),
MARZO=(CASE WHEN MARZO IS NULL THEN 0 ELSE MARZO END),MARZO_QTY=(CASE WHEN MARZO_QTY IS NULL THEN 0 ELSE MARZO_QTY END),
ABRIL=(CASE WHEN ABRIL IS NULL THEN 0 ELSE ABRIL END),ABRIL_QTY=(CASE WHEN ABRIL_QTY IS NULL THEN 0 ELSE ABRIL_QTY END),
MAYO=(CASE WHEN MAYO IS NULL THEN 0 ELSE MAYO END),MAYO_QTY=(CASE WHEN MAYO_QTY IS NULL THEN 0 ELSE MAYO_QTY END),
JUNIO=(CASE WHEN JUNIO IS NULL THEN 0 ELSE JUNIO END),JUNIO_QTY=(CASE WHEN JUNIO_QTY IS NULL THEN 0 ELSE JUNIO_QTY END),
JULIO=(CASE WHEN JULIO IS NULL THEN 0 ELSE JULIO END),JULIO_QTY=(CASE WHEN JULIO_QTY IS NULL THEN 0 ELSE JULIO_QTY END),
AGOSTO=(CASE WHEN AGOSTO IS NULL THEN 0 ELSE AGOSTO END),AGOSTO_QTY=(CASE WHEN AGOSTO_QTY IS NULL THEN 0 ELSE AGOSTO_QTY END),
SETIEMBRE=(CASE WHEN SETIEMBRE IS NULL THEN 0 ELSE SETIEMBRE END),SETIEMBRE_QTY=(CASE WHEN SETIEMBRE_QTY IS NULL THEN 0 ELSE SETIEMBRE_QTY END),
OCTUBRE=(CASE WHEN OCTUBRE IS NULL THEN 0 ELSE OCTUBRE END),OCTUBRE_QTY=(CASE WHEN OCTUBRE_QTY IS NULL THEN 0 ELSE OCTUBRE_QTY END),
NOVIEMBRE=(CASE WHEN NOVIEMBRE IS NULL THEN 0 ELSE NOVIEMBRE END),NOVIEMBRE_QTY=(CASE WHEN NOVIEMBRE_QTY IS NULL THEN 0 ELSE NOVIEMBRE_QTY END),
DICIEMBRE=(CASE WHEN DICIEMBRE IS NULL THEN 0 ELSE DICIEMBRE END),DICIEMBRE_QTY=(CASE WHEN DICIEMBRE_QTY IS NULL THEN 0 ELSE DICIEMBRE_QTY END)