CREATE PROC [dbo].[REC_LIQUIDACION_COBRANZA]
	@COD NVARCHAR(10),
	@TIP INT
as
	DECLARE @STRcadena NVARCHAR(800)
	SET @STRcadena='SELECT R.TYPE_DOC AS DETTIP_DOC,R.NUMBER_DOC AS DETNUM_DOC,
			CONVERT(VARCHAR(10),C.DOC_DATE,103) AS CARDOC_DATE,R.DOC_REF AS DETDOC_REF,
			CONVERT(VARCHAR(10),C.CADUCATE_DATE,103) AS CARFECHA_VENCI,R.REC_ID AS DETREC_ID,
			R.CURRENCY_ID AS DETCURRENCY_ID,R.AMOUNT AS DETAMOUNT ,
			R.SELL_RATE AS DETSELL_RATE,R.BANK_DESCRIPTION AS DETBANK_DESCRIPT,
			CT.ID AS CUST_ID,RC.ID AS CAB_ID,CT.NAME AS CUST_NAME,
			R.NUM_REF AS DETNUM_REF,R.SALES_ID AS DET_SALES_ID,CONVERT(VARCHAR(10),RC.DATE,103) AS CAB_DATE
			FROM RECEIVABLE_LIST_LINE_PAY R, CUSTOMER_BALANCE_PAY C,VENDOR CT,RECEIVABLE_LIST_PAY RC
			WHERE 	RC.ID=R.ID AND
			R.TYPE_DOC=C.DOCUMENT_ID AND
			R.NUMBER_DOC=C.NUMBER_DOC AND
			C.CUSTOMER_ID=CT.ID'	
			
	IF(@TIP=1)
	BEGIN
	SET @STRcadena=@STRcadena + ' AND RC.ID=@COD'
	END

	exec SP_EXECUTESQL @STRcadena,N'@COD NVARCHAR(10)',@COD