CREATE PROC [dbo].[REC_LIST_CUSTOMERS]
	@ORI INT,
	@TIPO INT,
	@RANGO1 NVARCHAR(20),
	@RANGO2 NVARCHAR(20) 
AS
	DECLARE @STRcadena NVARCHAR(400)

IF(@ORI=1)
BEGIN
	SET @STRcadena='SELECT * FROM CUSTOMER  '
	IF(@TIPO=1)
	BEGIN
	SET @STRcadena=@STRcadena + 'WHERE ID BETWEEN @RANGO1 AND @RANGO2 ORDER BY ID'
	END
	IF(@TIPO=2)
	BEGIN
	SET @STRcadena=@STRcadena + 'WHERE VAT_REGISTRATION BETWEEN @RANGO1 AND @RANGO2 ORDER BY VAT_REGISTRATION'
	END
	IF(@TIPO=0)  
	 BEGIN  
	 SET @STRcadena=@STRcadena + ' order by id'  
	 END 


END

IF(@ORI=2)--REC_LIST_GROUP_CUST
BEGIN
	SET @STRcadena='SELECT R.GROUP_ID,C.ADDR,C.VAT_REGISTRATION,C.PHONE,C.NAME,C.ID,CG.ID,CG.NAME
			FROM RELATION_CUST_GROUP R,CUSTOMER C,CUSTOMER_GROUP CG
			WHERE R.CUST_ID =C.ID AND
			R.GROUP_ID=CG.ID '
	
	IF(@TIPO=1)  
	 BEGIN  
	 SET @STRcadena=@STRcadena + '  AND C.ID BETWEEN @RANGO1 AND @RANGO2 ORDER BY R.GROUP_ID'  
	 END  
	IF(@TIPO=0)  
	 BEGIN  
	 SET @STRcadena=@STRcadena + '  ORDER BY R.GROUP_ID'  
	 END
END

	

IF(@ORI=3)--REC_LIST_ZONE_CUST
BEGIN
	SET @STRcadena='SELECT M.*, T.description 
			FROM DROG_PRUEBA.dbo.CUSTOMER M 
			LEFT JOIN DROG_PRUEBA.dbo.MASTER_HELP T 
			ON M.SELL_ZONE = T.ID 
			WHERE T.TYPE_ID=28'

	 IF(@TIPO=1)  
	 BEGIN  
	 SET @STRcadena=@STRcadena + ' AND M.SELL_ZONE BETWEEN @RANGO1 AND @RANGO2 ORDER BY NAME'  
	 END  
	 IF(@TIPO=0)  
	 BEGIN  
	 SET @STRcadena=@STRcadena + ' ORDER BY NAME'  
	 END 
END

IF(@ORI=4)--REC_LIST_SALES_REP_CUST
BEGIN
	SET @STRcadena='SELECT CUSTOMER_ID AS CUSTID,CUSTOMER_ADDR AS addr,R.VAT_REGISTRATION,CUSTOMER_NAME AS CUSTNAME,
SALES_REP_ID AS SALES_ID,S.NAME
 FROM RECEIVABLE R INNER JOIN SALES_REP S ON R.SALES_REP_ID=S.ID 
WHERE  DOCUMENT_ID=''FT'' '
		
	IF(@TIPO=1)
	BEGIN
	SET @STRcadena=@STRcadena + ' AND S.ID BETWEEN @RANGO1 AND @RANGO2 GROUP BY S.NAME,R.CUSTOMER_ID,R.CUSTOMER_ADDR,R.VAT_REGISTRATION,R.CUSTOMER_NAME,R.SALES_REP_ID,S.ID
						ORDER BY S.ID'
	END  
	IF(@TIPO=0)
	BEGIN
	SET @STRcadena=@STRcadena + '  GROUP BY S.NAME,R.CUSTOMER_ID,R.CUSTOMER_ADDR,R.VAT_REGISTRATION,R.CUSTOMER_NAME,R.SALES_REP_ID,S.ID
						ORDER BY S.ID'
	END  
END

IF(@ORI=5)  
BEGIN  
 SET @STRcadena='SELECT * FROM CUSTOMER ORDER BY NAME'  
 IF(@TIPO=1)  
 BEGIN  
 SET @STRcadena=@STRcadena + 'WHERE ID BETWEEN @RANGO1 AND @RANGO2'  
 END  
 IF(@TIPO=2)  
 BEGIN  
 SET @STRcadena=@STRcadena + 'WHERE VAT_REGISTRATION BETWEEN @RANGO1 AND @RANGO2'  
 END  
END  

IF(@ORI=6)  
BEGIN  
 SET @STRcadena='SELECT * FROM CUSTOMER ORDER BY VAT_REGISTRATION'  
 IF(@TIPO=1)  
 BEGIN  
 SET @STRcadena=@STRcadena + 'WHERE ID BETWEEN @RANGO1 AND @RANGO2'  
 END  
 IF(@TIPO=2)  
 BEGIN  
 SET @STRcadena=@STRcadena + 'WHERE VAT_REGISTRATION BETWEEN @RANGO1 AND @RANGO2'  
 END  
END  

EXEC SP_EXECUTESQL @STRcadena,N'@RANGO1 NVARCHAR(20),@RANGO2 NVARCHAR(20)', @RANGO1,@RANGO2