CREATE PROC [dbo].[REC_REGLET]  --VAMOS  A  VER SI ESTO FUNCA PERO LO VEO MAS YUCA A APRENDER PUNTEROS EN C JAJAA  
--DECLARE    
@IDE AS VARCHAR(15),@BASE AS VARCHAR(10),@fecha1 AS CHAR(10),@fecha2 AS VARCHAR(10)    
--SET @IDE='PC_D05'    
--SET @BASE='006BDCOMUN'    
--SET @fecha1='01/02/2004'    
--SET @fecha2='25/02/2004'    
AS    
IF EXISTS(SELECT * FROM tempdb.dbo.SYSOBJECTS WHERE XTYPE='U' AND NAME=''+@IDE+'REGLET')    
    
BEGIN       
   EXEC('DROP TABLE TEMPDB.DBO.'+@IDE+'REGLET')    
END     
EXEC('CREATE TABLE TEMPDB.DBO.'+@IDE+'REGLET (PCCNROCANJE VARCHAR(10),PCCFECCAN SMALLDATETIME,CNUMRUC VARCHAR(11),    
CNOMCLI VARCHAR(70),PCDNUMDOC VARCHAR(10),PCDFECVEN SMALLDATETIME,NUMDOC VARCHAR(10),    
CDOIMPORTE_MN NUMERIC(15,6) NULL DEFAULT (0),IMPORTE_ME NUMERIC(15,6) NULL DEFAULT (0),    
CDOTIPCAM FLOAT NULL DEFAULT (0),ALCAMBIO NUMERIC(15,6) NULL DEFAULT(0))')    
    
DECLARE @CANJE AS VARCHAR(6)    
DECLARE @NUMDOC AS VARCHAR(10)    
    
--declare @fecha1 as varchar(10)  
--declare @fecha2 as varchar(10)  
--declare @BASE as varchar(10)  
--SET @fecha1='01/02/2007'  
--SET @fecha2='01/02/2007'  
--set @BASE='demo'  
  
EXEC('DECLARE INSERTA_LETRAS CURSOR FOR    
SELECT C.ID AS CAID,D.ID AS DEID FROM ['+@BASE+'].dbo.LETTER_EXCHANGE_LINE D INNER JOIN ['+@BASE+'].dbo.LETTER_EXCHANGE C ON    
D.ID = C.ID WHERE C.DATE_EXCHANGE>='+@fecha1+' AND     
C.DATE_EXCHANGE<='+@fecha2+'AND D.TYPE_DOC <> ''LT'' order by D.ID')    
    
OPEN INSERTA_LETRAS    
    
FETCH NEXT FROM INSERTA_LETRAS INTO @CANJE,@NUMDOC    
    
WHILE  @@FETCH_STATUS=0    
BEGIN    
    
 EXEC('INSERT INTO TEMPDB.DBO.'+@IDE+'REGLET (PCCNROCANJE,PCCFECCAN,CNUMRUC,CNOMCLI,PCDNUMDOC,PCDFECVEN,    
 NUMDOC,CDOIMPORTE_MN,IMPORTE_ME,CDOTIPCAM,ALCAMBIO)     
 SELECT PC.ID AS PCID,PC.DATE_EXCHANGE,M.VAT_REGISTRATION,M.NAME AS CNAME, PD.NUMBER_DOC, PD.CADUCATE_DATE,"'+@NUMDOC+'",    
 (case when PC.CURRENCY_ID="MN" then PD.AMOUNT else 0.00 end)AS MN,(case when PC.CURRENCY_ID="ME" THEN PD.AMOUNT ELSE 0.00 END)as ME,PC.SELL_RATE,(case when PC.CURRENCY_ID="MN" then PD.AMOUNT else PD.AMOUNT * PC.SELL_RATE end)    
 FROM ['+@BASE+'].DBO.LETTER_EXCHANGE PC INNER JOIN ['+@BASE+'].DBO.LETTER_EXCHANGE_LINE PD     
 ON PC.ID=PD.ID left JOIN ['+@BASE+'].DBO.CUSTOMER M     
 ON PC.CUSTOMER_ID=M.ID WHERE PC.ID="'+@CANJE+'" AND PD.TYPE_DOC="LT"')  
  
 FETCH NEXT FROM INSERTA_LETRAS INTO @CANJE,@NUMDOC    
END     
    
CLOSE INSERTA_LETRAS    
DEALLOCATE INSERTA_LETRAS    
