CREATE PROC [dbo].[REC_PROYCOBRVENXCLI]
	@PC_MAS_MAQUINAS NVARCHAR(200)  
AS  
	DECLARE @STRcadena NVARCHAR(100)
	SET @STRcadena = 'SELECT * FROM '+ @PC_MAS_MAQUINAS
	EXEC SP_EXECUTESQL @STRcadena,N'@PC_MAS_MAQUINAS NVARCHAR(200)',@PC_MAS_MAQUINAS
