CREATE PROC [dbo].[REC_ESTCTACLI] 
	@TABLA NVARCHAR(200),
	@BASE NVARCHAR(100)  
AS  
	DECLARE @STRcadena NVARCHAR(300)
	
	SET @STRcadena='SELECT T.CODCLI,T.FECHAMOV,T.TIPDOC,T.NUMDOC,T.CARGOMN,T.CARGOME,T.ABONOME,T.ABONOMN,  
        M.name,M.id,M.addr,M.vat_registration FROM ' + @TABLA +' T  INNER JOIN '+ @BASE +' M ON T.CODCLI=M.ID'

	EXEC SP_EXECUTESQL @STRcadena,N'@TABLA NVARCHAR(200),@BASE AS NVARCHAR(100)',@TABLA,@BASE

