CREATE PROC [dbo].[Rec_List_Sales_Rep]
as
	DECLARE @STRcadena NVARCHAR(200)
	SET @STRcadena='SELECT ID,NAME,ADDR,PHONE,EMAIL,VAT_REGISTRATION,TERRITORY_ID,
			SEGMENT_ID,UBICATION_ID,ZONE_ID,CREATE_DATE,
		 	USER_ID, ROUTE_ID, DOC_NUMBER FROM SALES_REP'

	exec SP_EXECUTESQL @STRcadena

