CREATE PROC [dbo].[REC_PLANIxCUST]  
	@PC_MAS_MAQUINAS NVARCHAR(200)  
--SET @PC_MAS_MAQUINAS='tempdb.dbo.DEVELOPER2DETPLANILLA'
AS  
	DECLARE @STRcadena NVARCHAR(100)
	SET @STRcadena = 'SELECT * FROM '+ @PC_MAS_MAQUINAS
		
	EXEC SP_EXECUTESQL @STRcadena,N'@PC_MAS_MAQUINAS NVARCHAR(200)',@PC_MAS_MAQUINAS
