CREATE PROCEDURE RENTABILIDAD_POR_FAMILIA_PRINCIPAL
 AS

DECLARE @FAMILY  VARCHAR(50)
DECLARE @MODEL VARCHAR(50)
DECLARE @DESCRIPTION_OPT VARCHAR(50)

DECLARE PRIMER_CURSOR CURSOR FOR
SELECT DISTINCT FAMILY,MODEL,DESCRIPTION_OPT FROM TABLA_MEDIADORA_RENTABILIDAD
OPEN PRIMER_CURSOR
FETCH NEXT FROM PRIMER_CURSOR
INTO @FAMILY,@MODEL,@DESCRIPTION_OPT
WHILE @@FETCH_STATUS=0
BEGIN
	INSERT INTO TABLA_FINAL_RENTABILIDAD(FAMILY,MODEL,DESCRIPTION_OPT)
	VALUES(@FAMILY,@MODEL,@DESCRIPTION_OPT)
FETCH NEXT FROM PRIMER_CURSOR
INTO @FAMILY,@MODEL,@DESCRIPTION_OPT
END
CLOSE PRIMER_CURSOR
DEALLOCATE PRIMER_CURSOR

DECLARE @PMODEL VARCHAR(50)

DECLARE SEGUNDO_CURSOR CURSOR FOR
SELECT DISTINCT MODEL FROM TABLA_MEDIADORA_RENTABILIDAD
OPEN SEGUNDO_CURSOR
FETCH NEXT FROM SEGUNDO_CURSOR
INTO @PMODEL
WHILE @@FETCH_STATUS=0
BEGIN
	DECLARE @VALORVENTA NUMERIC(15,9)
	DECLARE @COSTOMN NUMERIC(15,9)
	DECLARE @FECHA VARCHAR(10)
	
	DECLARE TERCER_CURSOR CURSOR FOR
	SELECT VALOR_VENTA,COSTOMN,FECHA FROM TABLA_MEDIADORA_RENTABILIDAD WHERE MODEL=@PMODEL
	OPEN TERCER_CURSOR
	FETCH NEXT FROM TERCER_CURSOR
	INTO @VALORVENTA,@COSTOMN,@FECHA
	WHILE @@FETCH_STATUS=0
	BEGIN
		IF LEN(@FECHA)=5 
		BEGIN
			IF SUBSTRING(@FECHA,5,1)=1 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL1=@VALORVENTA,COSTOMN1=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=2 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL2=@VALORVENTA,COSTOMN2=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=3 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL3=@VALORVENTA,COSTOMN3=@COSTOMN WHERE MODEL=@PMODEL
			END

			ELSE IF SUBSTRING(@FECHA,5,1)=4 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL4=@VALORVENTA,COSTOMN4=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=5 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL5=@VALORVENTA,COSTOMN5=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=6 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL6=@VALORVENTA,COSTOMN6=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=7 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL7=@VALORVENTA,COSTOMN7=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=8 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL8=@VALORVENTA,COSTOMN8=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=9 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL9=@VALORVENTA,COSTOMN9=@COSTOMN WHERE MODEL=@PMODEL
			END

		END
		ELSE IF LEN(@FECHA)=6 
		BEGIN
			 IF SUBSTRING(@FECHA,5,2)=10 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL10=@VALORVENTA,COSTOMN10=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,2)=11 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL11=@VALORVENTA,COSTOMN11=@COSTOMN WHERE MODEL=@PMODEL
			END
			ELSE IF SUBSTRING(@FECHA,5,2)=12 
			BEGIN
				UPDATE TABLA_FINAL_RENTABILIDAD SET VAL12=@VALORVENTA,COSTOMN12=@COSTOMN WHERE MODEL=@PMODEL
			END

		END
	FETCH NEXT FROM TERCER_CURSOR
	INTO @VALORVENTA,@COSTOMN,@FECHA
	END
	CLOSE TERCER_CURSOR
	DEALLOCATE TERCER_CURSOR

FETCH NEXT FROM SEGUNDO_CURSOR
INTO @PMODEL
END
CLOSE SEGUNDO_CURSOR
DEALLOCATE SEGUNDO_CURSOR



UPDATE TABLA_FINAL_RENTABILIDAD SET
COSTOMN1=(CASE WHEN COSTOMN1 IS NULL THEN 0 ELSE COSTOMN1 END),VAL1=(CASE WHEN VAL1 IS NULL THEN 0 ELSE VAL1 END),
COSTOMN2=(CASE WHEN COSTOMN2 IS NULL THEN 0 ELSE COSTOMN2 END),VAL2=(CASE WHEN VAL2 IS NULL THEN 0 ELSE VAL2 END),
COSTOMN3=(CASE WHEN COSTOMN3 IS NULL THEN 0 ELSE COSTOMN3 END),VAL3=(CASE WHEN VAL3 IS NULL THEN 0 ELSE VAL3 END),
COSTOMN4=(CASE WHEN COSTOMN4 IS NULL THEN 0 ELSE COSTOMN4 END),VAL4=(CASE WHEN VAL4 IS NULL THEN 0 ELSE VAL4 END),
COSTOMN5=(CASE WHEN COSTOMN5 IS NULL THEN 0 ELSE COSTOMN5 END),VAL5=(CASE WHEN VAL5 IS NULL THEN 0 ELSE VAL5 END),
COSTOMN6=(CASE WHEN COSTOMN6 IS NULL THEN 0 ELSE COSTOMN6 END),VAL6=(CASE WHEN VAL6 IS NULL THEN 0 ELSE VAL6 END),
COSTOMN7=(CASE WHEN COSTOMN7 IS NULL THEN 0 ELSE COSTOMN7 END),VAL7=(CASE WHEN VAL7 IS NULL THEN 0 ELSE VAL7 END),
COSTOMN8=(CASE WHEN COSTOMN8 IS NULL THEN 0 ELSE COSTOMN8 END),VAL8=(CASE WHEN VAL8 IS NULL THEN 0 ELSE VAL8 END),
COSTOMN9=(CASE WHEN COSTOMN9 IS NULL THEN 0 ELSE COSTOMN9 END),VAL9=(CASE WHEN VAL9 IS NULL THEN 0 ELSE VAL9 END),
COSTOMN10=(CASE WHEN COSTOMN10 IS NULL THEN 0 ELSE COSTOMN10 END),VAL10=(CASE WHEN VAL10 IS NULL THEN 0 ELSE VAL10 END),
COSTOMN11=(CASE WHEN COSTOMN11 IS NULL THEN 0 ELSE COSTOMN11 END),VAL11=(CASE WHEN VAL11 IS NULL THEN 0 ELSE VAL11 END),
COSTOMN12=(CASE WHEN COSTOMN12 IS NULL THEN 0 ELSE COSTOMN12 END),VAL12=(CASE WHEN VAL12 IS NULL THEN 0 ELSE VAL12 END)
