CREATE PROCEDURE REP_VENDEDOR_DETALLADO
@FECHA_INICIAL VARCHAR(10),
@FECHA_FINAL VARCHAR(10),
@VEN_UNO VARCHAR(2),
@VEN_DOS VARCHAR(2),
@PV_UNO VARCHAR(2),
@PV_DOS VARCHAR(2)
 AS

Select PLACE_SALES AS VENCODAGE,FC.DOCUMENT_ID AS VENTD,(FC.NUMBER_SERIE+FC.NUMBER_DOCUMENT) AS VENSERDOC,
FC.DOCUMENT_DATE AS VENFECDOC,SALES_REP_ID AS VENVENDE,V.NAME AS NAME_VEN,
CUSTOMER_ID AS VENCODCLI,C.NAME AS NAME_CUSTOMER  
,FD.PART_ID,FD.ITEM,FD.QTY,FD.PRICE_SALES,FD.AMOUNT,FD.UNIT,FD.PART_DESCRIPTION,FC.CURRENCY_ID,FC.SELL_RATE,
(FD.AMOUNT_TAX+FD.ISC) AS AMOUNT_TAX,FD.AMOUNT_US
From DBO.RECEIVABLE_LINE FD,DBO.RECEIVABLE FC,[IVM].DBO.SALES_REP V,
DBO.CUSTOMER C,DBO.PART P  
Where  FD.DOCUMENT_ID = FC.DOCUMENT_ID And FD.NUMBER_SERIE = FC.NUMBER_SERIE And FD.NUMBER_DOCUMENT = FC.NUMBER_DOCUMENT
 AND FC.SALES_REP_ID=V.ID AND FC.CUSTOMER_ID=C.ID AND  FD.PART_ID=P.ID AND DOCUMENT_DATE >= @FECHA_INICIAL and 
DOCUMENT_DATE <= @FECHA_FINAL and  SALES_REP_ID >=@VEN_UNO  and SALES_REP_ID <=@VEN_DOS and FC.STATUS = 'V' AND 
PLACE_SALES >=@PV_UNO AND PLACE_SALES <=@PV_DOS 
 GROUP BY FD.ITEM,FC.PLACE_SALES,FC.DOCUMENT_ID,FC.NUMBER_SERIE,FC.NUMBER_DOCUMENT,FC.DOCUMENT_DATE,FC.SALES_REP_ID,
V.NAME,FC.CUSTOMER_ID,C.NAME,FD.PART_ID,FD.QTY,FD.PRICE_SALES,FD.AMOUNT,FD.UNIT,FD.PART_DESCRIPTION,FC.CURRENCY_ID,
FC.SELL_RATE,FD.AMOUNT_TAX,FD.AMOUNT_US,FD.ISC
 ORDER BY VENSERDOC