CREATE procedure rep_inventory    
AS    
select DISTINCT PART_ID AS ALM,P.DESCRIPTION,P.UNIT_OF_MEASUREMENT AS UNIDAD,  
ISNULL(sum(QTY_INITIAL),0) AS [CANTIDAD INICIAL],  
ISNULL(SUM(QTY_IN),0)AS ENTRADAS,  
ISNULL(SUM(QTY_OUT),0)AS SALIDAS,  
ISNULL(SUM(INIT_VALUE),0)[SALDO_INICIAL],  
ISNULL(SUM(IN_VALUE),0)AS ENTRADAS_VAL,  
ISNULL(SUM(OUT_VALUE),0)AS SALIDAS_VAL,  
ISNULL(SUM(AVERAGE_COST),0)AS PROMEDIO  
from inventory AS I INNER JOIN PART AS P  
ON I.PART_ID=P.ID  
GROUP BY PART_ID,P.DESCRIPTION,P.UNIT_OF_MEASUREMENT 
