CREATE proc [dbo].[REP_FACTPROVE01]
@FECHA1 DATETIME,
@FECHA2 DATETIME,
@PROVE1 VARCHAR(50),
@PROVE2 VARCHAR(50),
@MONEDA VARCHAR(5)
AS
--SELECT * FROM PURCHASE_FACT_SUPPLIER
--SELECT * from PURCHASE_FACT_SUPPLIER_L
--SELECT * FROM VENDOR
--SELECT * FROM WAREHOUSE_TRANS

SELECT  p.id as num_fac,convert(varchar(20),P.DOCUMENT_DATE) AS FECHA_DOC,P.VENDOR_ID AS COD_PROVE,V.NAME AS NOM_PROVE,
		P.NOTE_IN_ID AS NOTA_ING,P.CURRENCY_TYPE AS MONEDA, P.AMOUNT_SALES AS MONTO,
		P.WAREHOUSE_ID AS ALMACEN,convert(varchar(20),W.DATE_DOCUMENT) AS FECHA_ING,P.SELL_RATE AS TC
FROM	PURCHASE_FACT_SUPPLIER P,VENDOR V,WAREHOUSE_TRANS W
WHERE	P.VENDOR_ID=V.ID AND W.NUMBER_DOCUMENT=P.NOTE_IN_ID AND DOCUMENT_ID='NI'
		AND P.DOCUMENT_DATE BETWEEN @FECHA1 AND @FECHA2 AND 
		P.VENDOR_ID BETWEEN @PROVE1 AND @PROVE2 and p.currency_type=@MONEDA

		
--EXEC REP_FACTPROVE01 '01-05-2008','30-05-2008','2024004553','43619045','MN'