CREATE proc [dbo].[REP_FACTPROVE02]
@FECHA1 DATETIME,
@FECHA2 DATETIME,
@PROVE1 VARCHAR(50),
@PROVE2 VARCHAR(50),
@MONEDA VARCHAR(5),
@ART1 VARCHAR(50),
@ART2 VARCHAR(50)
AS
--SELECT * FROM PURCHASE_FACT_SUPPLIER
--SELECT * from PURCHASE_FACT_SUPPLIER_L
--SELECT * FROM VENDOR
--SELECT * FROM WAREHOUSE_TRANS
--SELECT * FROM PART
SELECT  P.WAREHOUSE_ID AS ALMACEN,P.NOTE_IN_ID AS NOTA_ING,P.ID AS NUM_FAC,CONVERT(VARCHAR(20),P.DOCUMENT_DATE) AS FECHA_DOC,
		P.VENDOR_ID AS COD_PROVE,V.NAME AS NOM_PROVE,
		P.CURRENCY_TYPE AS MONEDA, DP.AMOUNT_TOTAL AS MONTO,
		P.SELL_RATE AS TC,DP.PART_ID AS COD_ART,DP.PART_DESCRIPTION AS DES_ART,
		DP.PRICE AS PU,DP.QTY AS CANTIDAD,P.AMOUNT_SALES		
FROM	PURCHASE_FACT_SUPPLIER P,PURCHASE_FACT_SUPPLIER_L DP, VENDOR V,WAREHOUSE_TRANS W
WHERE	P.ID=DP.ID AND
		P.VENDOR_ID=V.ID AND W.NUMBER_DOCUMENT=P.NOTE_IN_ID AND DOCUMENT_ID='NI' AND 
		P.DOCUMENT_DATE BETWEEN @FECHA1 AND @FECHA2 AND 
		P.VENDOR_ID BETWEEN @PROVE1 AND @PROVE2 AND 
		P.CURRENCY_TYPE=@MONEDA AND DP.PART_ID BETWEEN @ART1 AND @ART2
	
--EXEC REP_FACTPROVE02 '01-05-2008','30-05-2008','2024004553','43619045','MN','ACET','TOL'