CREATE PROCEDURE reporte_por_agrupaciones_por_vendedor
@part1 varchar(10),
@part2 varchar(10),
@vendedor1 varchar(2),
@vendedor2 varchar(2),
@fecha1 int,
@fecha2 int,
@punto_de_venta1 varchar(2),
@punto_de_venta2 varchar(2)
AS
Select PART_ID AS VENCODIGO,DESCRIPTION,UNIT_OF_MEASUREMENT,PLACE_SALES AS VENCODAGE,B.DOCUMENT_ID AS VENTD,
(B.NUMBER_SERIE+B.NUMBER_DOCUMENT) AS VENSERDOC,DOCUMENT_DATE AS VENFECDOC,SALES_REP_ID AS VENVENDE,
V.NAME,(CASE WHEN B.CURRENCY_ID='MN' THEN B.AMOUNT_TAX ELSE Round(B.AMOUNT_TAX * SELL_RATE, 2) END) AS VENIGV,
(CASE WHEN TYPE_PART= '' THEN '' ELSE TYPE_PART END) AS VENTIPO,
(CASE  WHEN PART_SERIE Is Not Null And PART_SERIE<>'' THEN  PART_SERIE ELSE  '' END) AS VENSERIE,
--(CASE WHEN CUSTOMER_ID= '' THEN  ' ' ELSE CUSTOMER_ID END) AS VENCODCLI,
--C.NAME AS NAME_CUSTOMER,
QTY AS VENCANTID,A.AMOUNT_US AS VENIMPUS,A.AMOUNT AS VENIMPMN,
(CASE WHEN B.CURRENCY_ID Is Not Null And B.CURRENCY_ID<> '' THEN B.CURRENCY_ID ELSE ' ' END) AS VENMONEDA,
SELL_RATE AS VENTIPCAM,(' ')AS VENCODVEN,DOCUMENT_REF AS VENRFTD,(SERIE_REF+NUMBER_REF) AS VENDOCREF,A.PRICE_ORI 
INTO T_2_VENDEDOR 
FROM ([DROG_DANY].DBO.RECEIVABLE B INNER JOIN [DROG_DANY].DBO.RECEIVABLE_LINE A 
ON B.DOCUMENT_ID = A.DOCUMENT_ID And B.NUMBER_SERIE = A.NUMBER_SERIE And 
B.NUMBER_DOCUMENT = A.NUMBER_DOCUMENT)INNER JOIN [DROG_DANY].DBO.PART M ON A.PART_ID = M.ID
 LEFT JOIN  [DROG_DANY].DBO.SALES_REP V ON B.SALES_REP_ID=V.ID 
WHERE M.ID<>'TEXTO' AND A.PART_ID >= @part1 and A.PART_ID <= @part2  AND B.STATUS <> 'A' and SALES_REP_ID >= @vendedor1 
and SALES_REP_ID  <= @vendedor2 AND DOCUMENT_DATE >= @fecha1 and DOCUMENT_DATE <= @fecha2 AND PLACE_SALES >= @punto_de_venta1 AND 
NOT (IS_STOCKED='N' AND SERIES='N' AND IS_LOT='N') AND
PLACE_SALES <= @punto_de_venta2 ORDER BY VENSERDOC