CREATE PROCEDURE REPORTE_DE_STOCK
 AS

DROP TABLE TABLA_DE_STOCK

select P.ID,P.DESCRIPTION,F.NAME,P.DESCRIPTION_OPT,N.WAREHOUSE_ID,
CONVERT(decimal(15,4),N.QTY_ON_HAND)AS STOCK,P.UNIT_OF_MEASUREMENT,
P.ID_FAB,
--CONVERT(decimal(15,4),N.COST_AVG)AS COSTO_PROMEDIO
round(CONVERT(decimal(15,4),N.COST_AVG)+(CONVERT(decimal(15,4),N.COST_AVG)*0.19),4)AS COSTO_PROMEDIO  
INTO TABLA_DE_STOCK
from PART P INNER JOIN PART_QTY N  ON P.ID =N.PART_ID INNER JOIN family f ON p.family=f.id
where   N.QTY_ON_HAND<>'0'
 ORDER BY P.ID

DELETE FROM TABLA_FINAL_DE_STOCK
INSERT INTO TABLA_FINAL_DE_STOCK(ID,DESCRIPTION,NAME,DESCRIPTION_OPT,UNIT_OF_MEASUREMENT,ID_FAB,COSTO_PROMEDIO)
SELECT DISTINCT ID,DESCRIPTION,NAME,DESCRIPTION_OPT,UNIT_OF_MEASUREMENT,ID_FAB,COSTO_PROMEDIO
 FROM TABLA_DE_STOCK

DECLARE @ID VARCHAR(15)
DECLARE @WAREHOUSE_ID VARCHAR(2)
DECLARE @STOCK FLOAT

DECLARE CURSOR1 CURSOR FOR
SELECT ID FROM TABLA_FINAL_DE_STOCK ORDER BY ID
OPEN CURSOR1
FETCH NEXT FROM CURSOR1
INTO @ID
WHILE @@FETCH_STATUS=0
BEGIN
	
	DECLARE CURSOR2 CURSOR FOR
	SELECT WAREHOUSE_ID FROM TABLA_DE_STOCK WHERE ID=@ID
	OPEN CURSOR2
	FETCH NEXT FROM CURSOR2
	INTO @WAREHOUSE_ID
	WHILE @@FETCH_STATUS=0
	BEGIN
		SELECT @STOCK=STOCK FROM TABLA_DE_STOCK WHERE ID=@ID AND WAREHOUSE_ID=@WAREHOUSE_ID
		IF @WAREHOUSE_ID='01'
		BEGIN
			UPDATE TABLA_FINAL_DE_STOCK SET ALMACEN1=@STOCK WHERE ID=@ID 
		END
		ELSE IF @WAREHOUSE_ID='02'
		BEGIN
			UPDATE TABLA_FINAL_DE_STOCK SET ALMACEN2=@STOCK WHERE ID=@ID 
		END
		ELSE IF @WAREHOUSE_ID='03'
		BEGIN
			UPDATE TABLA_FINAL_DE_STOCK SET ALMACEN3=@STOCK WHERE ID=@ID 
		END

		ELSE IF @WAREHOUSE_ID='04'
		BEGIN
			UPDATE TABLA_FINAL_DE_STOCK SET ALMACEN4=@STOCK WHERE ID=@ID 
		END

		ELSE IF @WAREHOUSE_ID='05'
		BEGIN
			UPDATE TABLA_FINAL_DE_STOCK SET ALMACEN5=@STOCK WHERE ID=@ID 
		END

	
	FETCH NEXT FROM CURSOR2
	INTO @WAREHOUSE_ID	
	END
	CLOSE CURSOR2
	DEALLOCATE CURSOR2

FETCH NEXT FROM CURSOR1
INTO @ID
END
CLOSE CURSOR1
DEALLOCATE CURSOR1


UPDATE TABLA_FINAL_DE_STOCK SET
ALMACEN1=(CASE WHEN ALMACEN1 IS NULL THEN 0 ELSE ALMACEN1 END),ALMACEN2=(CASE WHEN ALMACEN2 IS NULL THEN 0 ELSE ALMACEN2 END),
ALMACEN3=(CASE WHEN ALMACEN3 IS NULL THEN 0 ELSE ALMACEN3 END),ALMACEN4=(CASE WHEN ALMACEN4 IS NULL THEN 0 ELSE ALMACEN4 END),
ALMACEN5=(CASE WHEN ALMACEN5 IS NULL THEN 0 ELSE ALMACEN5 END)