  
  
  
  
CREATE  PROC [dbo].[REPO_INVLISTADOINVENTARIO]  
--DECLARE  
@IDE AS VARCHAR(30)    
--SET @IDE='DEVELOPER02'  
AS    
EXEC('SELECT * FROM TEMPDB.DBO.LISTAINVENTARIO'+@IDE+'   L  INNER JOIN  PART M ON L.CODART=M.ID   
          WHERE M.STATUS=''V''  ORDER BY CODART')    
EXEC('UPDATE T SET INVTRANSITO=0 , CONDICION='''' FROM TEMPDB.DBO.LISTAINVENTARIO'+@IDE+'   T WHERE TIPOALMACEN<>''01''')    
   
  
    
    
  
  
  
  
  
  
  