
 CREATE PROCEDURE [dbo].[RESTRANSXALMACEN]    
--DECLARE    
@TIPO VARCHAR(1),@DOCUS VARCHAR(100),@ALMACENES VARCHAR(1000),@OPT VARCHAR(1),@OPT1 VARCHAR(1)    
  
/*
SET @TIPO='I'    
SET @DOCUS='A1,A'  
SET @ALMACENES=''    
SET @OPT='1'    
SET @OPT1='0'    
*/
AS    
 SET NOCOUNT ON          
 SET  QUOTED_IDENTIFIER off          
 DECLARE @CADENA VARCHAR(100)    
 IF @OPT='1'    
  SET @CADENA=' AND I.TRANS_ID IN ('''+@DOCUS+''') '    
 ELSE		
  SET @CADENA=''    
    
 DECLARE @CADENAALM VARCHAR(100)    
 IF @OPT1='1'    
  SET @CADENAALM=' AND I.WAREHOUSE_ID IN ('+@ALMACENES+') '    
 ELSE    
  SET @CADENAALM=''    
  
IF @TIPO='T'    
EXEC('SELECT *,M.DESCRIPTION,MO.CURRENCY_EXCHANGE,M.UNIT_OF_MEASUREMENT, T.NAME FROM INVENTORY I     
      INNER JOIN PART M ON I.PART_ID=M.ID    
      LEFT JOIN WAREHOUSE_TRANS MO ON I.TYPE_DOC=MO.DOCUMENT_ID AND I.WAREHOUSE_ID=MO.WAREHOUSE_ID AND I.NUMBER_DOC=MO.NUMBER_DOCUMENT     
      LEFT  JOIN WAREHOUSE T ON MO.WAREHOUSE_ID=T.ID    
      WHERE  (I.QTY_IN>0 OR I.QTY_OUT>0 OR IN_VALUE>0 OR OUT_VALUE>0)'+@CADENA+''+@CADENAALM+'')    
ELSE    
EXEC('SELECT *,M.DESCRIPTION,MO.CURRENCY_EXCHANGE,M.UNIT_OF_MEASUREMENT,T.NAME FROM INVENTORY I     
      INNER JOIN PART M ON I.PART_ID=M.ID    
      LEFT JOIN WAREHOUSE_TRANS MO ON I.TYPE_DOC=MO.DOCUMENT_ID AND I.WAREHOUSE_ID=MO.WAREHOUSE_ID AND I.NUMBER_DOC=MO.NUMBER_DOCUMENT    
      LEFT  JOIN WAREHOUSE T ON MO.WAREHOUSE_ID=T.ID    
      --WHERE (ING_SAL='''+@TIPO+''' OR ING_SAL=''I'')    
      WHERE (IS_IN_OUT='''+@TIPO+''')    
      AND (I.QTY_IN>0 OR I.QTY_OUT>0 OR IN_VALUE>0 OR OUT_VALUE>0)'+@CADENA+''+@CADENAALM+'')  
  
    
  
  