

CREATE PROCEDURE [dbo].[RESTRANS]  
-- DECLARE  
@TIPO VARCHAR(1),
@DOCUS VARCHAR(100),
@OPT VARCHAR(1)  
  
/*SET @EMP='002'  
SET @TIPO='I'  
SET @DOCUS=''  
SET @OPT='0'  
--*/AS  
 DECLARE @CADENA VARCHAR(100)  
 IF @OPT='1'  
  SET @CADENA='AND TRANS_ID IN ('+@DOCUS+')'  
 ELSE  
  SET @CADENA=''  
   
EXEC('SELECT *,M.DESCRIPTION,MO.CURRENCY_EXCHANGE,M.UNIT_OF_MEASUREMENT FROM INVENTORY I   
      INNER JOIN PART M ON I.PART_ID=M.ID  
      LEFT JOIN WAREHOUSE_TRANS MO ON I.TYPE_DOC=MO.DOCUMENT_ID AND I.WAREHOUSE_ID=MO.WAREHOUSE_ID AND I.NUMBER_DOC=MO.NUMBER_DOCUMENT  
      --WHERE (IS_IN_OUT='''+@TIPO+''' OR IS_IN_OUT=''I'')  
      WHERE (IS_IN_OUT='''+@TIPO+''')  
      AND (I.QTY_IN>0 OR I.QTY_OUT>0 OR IN_VALUE>0 OR OUT_VALUE>0)'+@CADENA+'')  
  

