create procedure SAL_SERIE_DOC_PTO_VENTA
		(
		@PTO_VENTA VARCHAR(2),
		@DOCUMENT_TYPE VARCHAR(30)
		)
	as
		select NUMBER_SERIE 
		from DOCUMENT_PLACE_SALES where PLACE_SALES_ID=@PTO_VENTA
		and DOCUMENT_TYPE =@DOCUMENT_TYPE
		ORDER BY NUMBER_SERIE