CREATE PROC [dbo].[SAL_UPGRADE_QUOTE_LINE]
--DECLARE
@NUMERO VARCHAR(7),
@IDE VARCHAR(30),
@CANT_ERROR INT OUTPUT
AS
SET NOCOUNT ON
/*set @NUMERO='0000015'
set @IDE='DEVELOPER6'*/

declare @TABLA varchar(50)
set @TABLA='tempdb.dbo.'+@IDE+'FACWORDET'
SET @CANT_ERROR=0

BEGIN TRAN UPDATE_QUOTE_LINE
exec('set quoted_identifier off Insert Into QUOTE_LINE (NUMBER_DOC,ITEM,PART_ID,PART_DESCRIPTION,TEXT_COMMENT,QTY,
PRICE_SALES,PRICE_ORI,DISCOUNT,PERCENT_DISCOUNT,DISCOUNT_CUST,DISCOUNT_SP,AMOUNT_TAX,PERCENT_TAX,AMOUNT_US,AMOUNT,
NUMBER_SERIE,WAREHOUSE_ID,NUMBER_LOT,IS_TAX,PRICE_LIST,UNIT) 
select "'+@NUMERO+'",DFSECUEN,DFCODIGO,DFDESCRI,DFTEXTO,DFCANTID,DFPREC_VEN,DFPREC_ORI,DFDESCTO,DFPORDES,DFDESCLI,
DFDESESP,DFIGV,DFIGVPOR,DFIMPUS,DFIMPMN,DFSERIE,DFALMA,DFLOTE,DFARTIGV,isnull(DFCODLIS," "),DFUNIDAD FROM '+@TABLA+'')
SET @CANT_ERROR=@@ERROR
COMMIT TRAN UPDATE_QUOTE_LINE
