create procedure [dbo].[SAL_HLP_ALL_PRODUCTOS]
as
	declare @PRODUCTO_INI varchar(20)
	declare @PRODUCTO_NOM_INI varchar(100)
	declare @PRODUCTO_FIN varchar(20)
	declare @PRODUCTO_NOM_FIN varchar(100)
	
	SELECT @PRODUCTO_INI=MIN(ID),@PRODUCTO_FIN=MAX(ID)
	FROM PART
	
	select @PRODUCTO_NOM_INI=DESCRIPTION
				from PART WHERE ID=@PRODUCTO_INI
	
	select @PRODUCTO_NOM_FIN=DESCRIPTION
				from PART WHERE ID=@PRODUCTO_FIN	
	
	
				
	select @PRODUCTO_INI,@PRODUCTO_NOM_INI,@PRODUCTO_FIN,@PRODUCTO_NOM_FIN