CREATE PROC [dbo].[SAL_UPGRADE_WHO_TRANS_SALES]    
--DECLARE    
@TD VARCHAR(2),@ALMA VARCHAR(2),@NUMERO VARCHAR(10),@FECHA VARCHAR(10),@TIPO_CAMBIO VARCHAR(15),@TD_REF VARCHAR(2),    
@NUM_REF VARCHAR(10),@USER VARCHAR(10),@COD_CLI VARCHAR(11),@RUC VARCHAR(11),@NOM_CLI VARCHAR(100),@PAGO VARCHAR(2),    
@MONEDA VARCHAR(2),@MONTO VARCHAR(15),@HORA VARCHAR(20),@ORDENCOMPRA VARCHAR(20),@COTIZACION VARCHAR(7),    
@PEDIDO VARCHAR(7),@GLOSA VARCHAR(80),@IDE VARCHAR(50),@FLAG_REF VARCHAR(1),@ANOMES VARCHAR(6), @CANT_ERROR INT OUTPUT    
AS    
/*SET @TD='FT'    
SET @ALMA='01'    
SET @NUMERO='0010100100'    
SET @FECHA='39186'    
SET @TIPO_CAMBIO='3.35'    
SET @TD_REF=''    
SET @NUM_REF=''    
SET @USER='NovaQ'    
SET @COD_CLI='32165498712'    
SET @RUC='12345678912'    
SET @NOM_CLI='marco'    
SET @PAGO='00'    
SET @MONEDA='MN'    
SET @MONTO='500.25'    
SET @HORA='12:38:06'    
SET @ORDENCOMPRA='32165498732165498732'    
SET @COTIZACION='3216549877'    
SET @PEDIDO='3216547'    
SET @GLOSA='FGTHFTGHF'    
SET @IDE ='DEVELOPER6'    
SET @FLAG_REF='0'    
SET @ANOMES='200704'*/    
    
SET NOCOUNT ON    
    
DECLARE @TABLA_det AS VARCHAR(50)    
DECLARE @TRANS_CAB INT    
DECLARE @TRANS_DET INT    
DECLARE @TRANS_PEDDET INT    
DECLARE @MORES_INSERT INT    
DECLARE @MORES_UPDATE INT    
DECLARE @UPDATE_COST INT    
    
set @TABLA_det='tempdb.dbo.'+@IDE+'FACWORDET'    
SET @TRANS_CAB=0    
SET @TRANS_DET=0    
SET @TRANS_PEDDET=0    
SET @MORES_INSERT=0    
SET @MORES_UPDATE=0    
SET @UPDATE_COST=0    
SET @CANT_ERROR=0    
    
BEGIN TRAN UPGRADE_WHOTRANS_SALES    
    
IF @TD<>'NC'    
 BEGIN    
 EXEC('set quoted_identifier off INSERT INTO WAREHOUSE_TRANS (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,DATE_DOCUMENT,    
 CURRENCY_EXCHANGE,TYPE_TRANS,STATUS_GUIA,DOC_ID_REF,NUM_ID_REF,USER_ID,CUSTOMER_ID,VAT_REGISTRATION,CUSTOMER_NAME,    
 SALES_TERM,CURRENCY_TYPE,AMOUNT,TRANS_ID,HOUR,NUMBER_PURCHASE, NUMBER_ESTIMATING, NUMBER_ORDER, COMMENT)    
 VALUES("'+@ALMA+'","'+@TD+'","'+@NUMERO+'",'+@FECHA+',"'+@TIPO_CAMBIO+'","S","F","'+@TD_REF+'","'+@NUM_REF+'",    
 "'+@USER+'","'+@COD_CLI+'","'+@RUC+'","'+@NOM_CLI+'","'+@PAGO+'","'+@MONEDA+'","'+@MONTO+'","FT","'+@HORA+'",    
 "'+@ORDENCOMPRA+'","'+@COTIZACION+'","'+@PEDIDO+'","'+@GLOSA+'")')    
 SET @TRANS_CAB=@@ERROR    
 END    
ELSE    
 BEGIN    
 EXEC('set quoted_identifier off INSERT INTO WAREHOUSE_TRANS (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,DATE_DOCUMENT,    
 CURRENCY_EXCHANGE,TYPE_TRANS,STATUS_GUIA,DOC_ID_REF,NUM_ID_REF,USER_ID,CUSTOMER_ID,VAT_REGISTRATION,CUSTOMER_NAME,    
 SALES_TERM,CURRENCY_TYPE,AMOUNT,TRANS_ID,HOUR,NUMBER_ORDER)    
 VALUES("'+@ALMA+'","'+@TD+'","'+@NUMERO+'",'+@FECHA+','+@TIPO_CAMBIO+',"I","F","'+@TD_REF+'","'+@NUM_REF+'",    
 "'+@USER+'","'+@COD_CLI+'","'+@RUC+'","'+@NOM_CLI+'","'+@PAGO+'","'+@MONEDA+'","'+@MONTO+'","FT","'+@HORA+'","'+@PEDIDO+'")')    
 SET @TRANS_CAB=@@ERROR    
 END    
     
--ACTUALIZO EL ULTIMO COSTO PROMEDIO AL TEMPORAL    
 EXEC('set quoted_identifier off UPDATE T SET T.DFCOSTO=(CASE WHEN "'+@MONEDA+'"="MN" THEN S.COST_AVG ELSE S.COST_AVG_US END) FROM '+@TABLA_det+' T     
  INNER JOIN PART_QTY S ON T.dfALMA=S.WAREHOUSE_ID AND T.dfCODIGO=S.PART_ID')     
 SET @UPDATE_COST=@@ERROR     
    
IF @FLAG_REF=1    
 BEGIN    
 EXEC('set quoted_identifier off Insert Into WAREHOUSE_TRANS_LINE (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,ITEM,PART_ID,PART_DESCRIPTION,QTY,    
 AVERAGE_COST,AMOUNT_SALES,UNIT_PART,NUMBER_SERIE,NUMBER_LOT, QTY_REF,REFERENCE,UNIT_REFERENCE,QTY_REFERENCE)    
 SELECT dfALMA,"'+@TD+'","'+@NUMERO+'",DFSECUEN,dfCODIGO,DFDESCRI,abs(dfCANTID),DFCOSTO,    
 (CASE WHEN DFARTIGV=1 THEN DFPREC_ORI/1+(DFIGVPOR/100) ELSE DFPREC_ORI END),DFUNIDAD,DFSERIE,DFLOTE,abs(DFCANTID),DFPRESU,    
 UMREFERENCIA,abs(CANTREFERENCIA) FROM '+@TABLA_det+'')    
 SET @TRANS_DET=@@ERROR    
 END    
ELSE    
 BEGIN    
 EXEC('set quoted_identifier off Insert Into WAREHOUSE_TRANS_LINE (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,ITEM,PART_ID,PART_DESCRIPTION,QTY,    
 AVERAGE_COST,AMOUNT_SALES,UNIT_PART,NUMBER_SERIE,NUMBER_LOT, QTY_REF,REFERENCE)    
 SELECT dfALMA,"'+@TD+'","'+@NUMERO+'",DFSECUEN,dfCODIGO,DFDESCRI,abs(dfCANTID),DFCOSTO,    
 (CASE WHEN DFARTIGV=1 THEN DFPREC_ORI/1+(DFIGVPOR/100) ELSE DFPREC_ORI END),DFUNIDAD,DFSERIE,DFLOTE,abs(DFCANTID),DFPRESU FROM '+@TABLA_det+'')    
 SET @TRANS_DET=@@ERROR    
 END    
    
    
IF @TD_REF='PD'    
 BEGIN    
  EXEC('set quoted_identifier off UPDATE P SET WAREHOUSE_ID="'+@ALMA+'",BALANCE=BALANCE-dfCANTID FROM ORDER_LINE P INNER JOIN '+@TABLA_det+' T ON P.PART_ID=T.dfCODIGO')    
  SET @TRANS_PEDDET=@@ERROR    
 END    
    
    
--CONTROLA ENTRADA Y SALIDAS DE MORESMES    
IF @TD='NC'    
 BEGIN    
  EXEC('set quoted_identifier off Update M set QTY_OUT =QTY_OUT ,QTY_ENTER = QTY_ENTER+dfCANTID  FROM MONTHLY_SUMMARIZE M INNER JOIN '+@TABLA_det+' T ON M.PART_ID=T.dfCODIGO AND M.WAREHOUSE_ID=T.dfALMA WHERE YEAR_MONTH ="'+@ANOMES+'"')     
  SET @MORES_UPDATE=@@ERROR    
 END    
ELSE    
 BEGIN    
  EXEC('set quoted_identifier off Update M set QTY_OUT =QTY_OUT-dfCANTID ,QTY_ENTER = QTY_ENTER  FROM MONTHLY_SUMMARIZE M INNER JOIN '+@TABLA_det+' T ON M.PART_ID=T.dfCODIGO AND M.WAREHOUSE_ID=T.dfALMA WHERE YEAR_MONTH ="'+@ANOMES+'"')     
  SET @MORES_UPDATE=@@ERROR    
 END    
    
IF @TD='NC'    
 BEGIN    
  EXEC('set quoted_identifier off INSERT INTO MONTHLY_SUMMARIZE(WAREHOUSE_ID,PART_ID,YEAR_MONTH,QTY_ENTER,QTY_OUT)    
  SELECT dfALMA,dfCODIGO,"'+@ANOMES+'",dfCANTID,0 FROM '+@TABLA_det+' T LEFT JOIN MONTHLY_SUMMARIZE M ON T.dfALMA=M.WAREHOUSE_ID AND T.dfCODIGO=M.PART_ID AND "'+@ANOMES+'"=YEAR_MONTH WHERE PART_ID IS NULL')    
  SET @MORES_INSERT=@@ERROR    
 END    
ELSE    
 BEGIN    
  EXEC('set quoted_identifier off INSERT INTO MONTHLY_SUMMARIZE(WAREHOUSE_ID,PART_ID,YEAR_MONTH,QTY_ENTER,QTY_OUT)    
  SELECT dfALMA,dfCODIGO,"'+@ANOMES+'",0,-dfCANTID FROM '+@TABLA_det+' T LEFT JOIN MONTHLY_SUMMARIZE M ON T.dfALMA=M.WAREHOUSE_ID AND T.dfCODIGO=M.PART_ID AND "'+@ANOMES+'"=YEAR_MONTH WHERE PART_ID IS NULL')    
  SET @MORES_INSERT=@@ERROR    
 END    
    
    
    
    
/*CONTROLA ERROR*/    
IF (@TRANS_CAB<>0 OR @TRANS_DET<>0 OR @TRANS_PEDDET<>0 OR @UPDATE_COST<>0 OR @MORES_INSERT<>0 OR @MORES_UPDATE<>0)    
 BEGIN    
  SET @CANT_ERROR=1    
  ROLLBACK TRAN UPGRADE_WHOTRANS_SALES    
 END    
ELSE    
 BEGIN    
  COMMIT TRAN UPGRADE_WHOTRANS_SALES    
 END    
