CREATE PROC [dbo].[SAL_UPGRADE_ORDERS]  
--DECLARE  
@NUMERO VARCHAR(7),  
@PTOVTA VARCHAR(2),  
@USER VARCHAR(8),  
@MONTO VARCHAR(15),  
@MONTOIGV VARCHAR(15),  
@IDE VARCHAR(30)  
AS  
SET NOCOUNT ON  
/*SET @NUMERO='0000015'  
SET @PTOVTA='01'  
SET @USER='1'  
SET @MONTO='1000'  
SET @MONTOIGV='190'  
SET @IDE='DEVELOPER6'*/  
  
declare @TABLA varchar(50)  
declare @TRAN1 int  
declare @TRAN2 int  
set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'  

BEGIN TRAN UPDATE_ORDERS  
EXEC('set quoted_identifier off Insert Into ORDERS (ID,ORDER_DATE,CADUCATE_DATE,SALES_ID,PLACE_SALES,CUSTOMER_ID,VAT_REGISTRATION,CUSTOMER_NAME,  
CUSTOMER_ADDR,DISCOUNT_CUSTOMER,DISCOUNT_SP,TERMS,SELL_RATE,CURRENCY_ID,USER_ID,DOCUMENT_REF,SERIE_REF,NUMBER_REF,  
STATUS,AMOUNT,AMOUNT_VAT,DISCOUNT_VAL,STATUS_ORDER)  
SELECT "'+@NUMERO+'",CFFECDOC,CFFECVEN,cfVENDE,"'+@PTOVTA+'",CFCODCLI,ISNULL(CFRUC," "),CFNOMBRE,ISNULL(CFDIRECC," "),CFPORDESCL,CFPORDESES,CFFORVEN,  
CFTIPCAM,CFCODMON,"'+@USER+'",ISNULL(CFRFTD," "),ISNULL(CFRFNUMSER," "),ISNULL(CFRFNUMDOC," "),"V","'+@MONTO+'","'+@MONTOIGV+'",CFDESVAL,"AUTORIZADO" FROM '+@TABLA+'')  
SET @TRAN1 =@@ERROR  
  
EXEC SAL_UPGRADE_ORDERS_LINE @NUMERO,@IDE,@TRAN2 OUTPUT  
  
  
IF (@TRAN1<>0 OR @TRAN2<>0)   
 BEGIN  
  ROLLBACK TRAN UPDATE_ORDERS  
 END  
ELSE  
 BEGIN  
  COMMIT TRAN UPDATE_ORDERS  
 END  
  