CREATE procedure SAL_HLP_ALL_CLIENTES
as
	declare @CLIENTE_INI varchar(20)
	declare @CLIENTE_NOM_INI varchar(100)
	declare @CLIENTE_FIN varchar(20)
	declare @CLIENTE_NOM_FIN varchar(100)
	
	SELECT @CLIENTE_INI=MIN(ID),@CLIENTE_FIN=MAX(ID)
	FROM CUSTOMER
	
	select @CLIENTE_NOM_INI=NAME
				from CUSTOMER WHERE ID=@CLIENTE_INI
	
	select @CLIENTE_NOM_FIN=NAME
				from CUSTOMER WHERE ID=@CLIENTE_FIN	
	
	
				
	select @CLIENTE_INI,@CLIENTE_NOM_INI,@CLIENTE_FIN,@CLIENTE_NOM_FIN