CREATE PROC [dbo].[SAL_UPGRADE_GUIA_TRANS]
--DECLARE
@ALMA VARCHAR(2),@TIPO VARCHAR(2),@SERIE VARCHAR(3),@NUMERO VARCHAR(7),@FECHA VARCHAR(10),@VENDEDOR VARCHAR(11),@COD_CLI VARCHAR(11),
@RUC VARCHAR(11),@RAZONSOCIAL VARCHAR(100),@DIRECCION  VARCHAR(100),@FORMA_PAG  VARCHAR(2),@MONTO VARCHAR(15),
@MONEDA VARCHAR(2),@TIPO_CAMBIO VARCHAR(15),@USER VARCHAR(8),@TD_REF VARCHAR(2),@NUM_REF VARCHAR(10),
@DESC_CLI VARCHAR(15),@DESC_ESP VARCHAR(15),@HORA VARCHAR(20),@TRANS VARCHAR(11),@ORDEN_COMPRA VARCHAR(20),
@COTIZA VARCHAR(7),@PEDIDO VARCHAR(7),@GLOSA VARCHAR(80),@SER_GUIA VARCHAR(3),@NUM_GUIA VARCHAR(7),
@FLAG_REF VARCHAR(1),@IDE VARCHAR(50), @CANT_ERROR INT OUTPUT
AS

SET NOCOUNT ON
/*SET @ALMA='01'
set @TIPO='FT'
SET @SERIE='001'
SET @NUMERO='0100100'
SET @FECHA='11/12/2007'
SET @VENDEDOR='01'
SET @COD_CLI='01'
SET @RUC='12345678912'
SET @RAZONSOCIAL='MARCO ANTONIO JESUS VARGAS GALLO'
SET @DIRECCION='FTH FTGHDFGH FTGHDGF'
SET @FORMA_PAG='00'
SET @MONTO='1000'
SET @MONEDA='MN'
SET @TIPO_CAMBIO='3.265'
SET @USER='1'
SET @TD_REF=' '
SET @NUM_REF=' '
SET @DESC_CLI='10'
SET @DESC_ESP='20'
SET @HORA='03:05:15'
SET @TRANS='01'
SET @ORDEN_COMPRA='32165498732165498732'
SET @COTIZA='3216547'
SET @PEDIDO='3216547'
SET @GLOSA='KGKGKJ'
SET @SER_GUIA='001'
SET @NUM_GUIA='0100100'
SET @FLAG_REF='0'
SET @IDE='DEVELOPER6'*/

DECLARE @ERROR1 INT
DECLARE @ERROR2 INT
DECLARE @ERROR3 INT
DECLARE @TABLA_det VARCHAR(50)
SET @ERROR1=0
SET @ERROR2=0
SET @ERROR3=0
SET @CANT_ERROR=0
set @TABLA_det='tempdb.dbo.'+@IDE+'FACWORDET'

BEGIN TRAN UPDATE_GUIA_TRANS
EXEC('set quoted_identifier off Insert Into WAREHOUSE_TRANS (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,TRANS_ID,
TYPE_TRANS,TYPE_GUIA, STATUS_GUIA,DATE_DOCUMENT,SALES_ID,CUSTOMER_ID,VAT_REGISTRATION,CUSTOMER_NAME,ADDR_DLV,
SALES_TERM,AMOUNT,CURRENCY_TYPE,CURRENCY_EXCHANGE,USER_ID,DOC_ID_REF,NUM_ID_REF,DISCOUNT_PER_CUST,DISCOUNT_PER_SP,
UPDATE_DATE,HOUR,RECEIVABLE_GUIA,CARRIER_ID,NUMBER_PURCHASE,NUMBER_ESTIMATING, NUMBER_ORDER, COMMENT)
VALUES("'+@ALMA+'","GS","'+@SER_GUIA+@NUM_GUIA+'","GF","S","GF","F",'+@FECHA+',"'+@VENDEDOR+'","'+@COD_CLI+'","'+@RUC+'",
"'+@RAZONSOCIAL+'","'+@DIRECCION+'","'+@FORMA_PAG+'","'+@MONTO+'","'+@MONEDA+'","'+@TIPO_CAMBIO+'","'+@USER+'",
"'+@TD_REF+'","'+@NUM_REF+'","'+@DESC_CLI+'","'+@DESC_ESP+'",getdate(),"'+@HORA+'","N","'+@TRANS+'","'+@ORDEN_COMPRA+'",
"'+@COTIZA+'","'+@PEDIDO+'","'+@GLOSA+'")')
SET @ERROR1=@@ERROR

IF @FLAG_REF=1
	BEGIN
	EXEC('set quoted_identifier off INSERT INTO WAREHOUSE_TRANS_LINE (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,TRANS_ID,ITEM,PART_ID,
	PART_DESCRIPTION,AMOUNT_SALES,AVERAGE_COST,QTY,DISCOUNT_CUST,DISCOUNT_SP,DISCOUNT_PERCENT,DISCOUNT,STATUS,
	AMOUNT_TAX,TAX_PERCENT,AMOUNT_US,AMOUNT,NUMBER_SERIE,NUMBER_LOT,TEXT_COMMENT,CURRENCY_ID,TYPE_EXCHANGE,UNIT_PART
	QTY_REF,REFERENCE,UNIT_REFERENCE,QTY_REFERENCE)SELECT "'+@ALMA+'","GS","'+@SER_GUIA+@NUM_GUIA+'","GV",DFSECUEN,DFCODIGO,
	(CASE WHEN DFCODIGO="TEXTO" THEN DFTEXTO ELSE DFDESCRI END),DFPREC_ORI,DFPREC_VEN,DFCANTID,DFDESCLI,DFDESESP,
	DFPORDES,DFDESCTO,"S",DFIGV,DFIGVPOR,DFIMPUS,DFIMPMN,DFSERIE,DFLOTE,DFTR,"'+@MONEDA+'","'+@TIPO_CAMBIO+'",DFUNIDAD,DFCANTID,
	DFPRESU,REFERENCE,CANTREFERENCIA FROM '+@TABLA_det+'')
	SET @ERROR2=@@ERROR
	END
ELSE
	BEGIN
	EXEC('set quoted_identifier off INSERT INTO WAREHOUSE_TRANS_LINE (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,TRANS_ID,ITEM,PART_ID,
	PART_DESCRIPTION,AMOUNT_SALES,AVERAGE_COST,QTY,DISCOUNT_CUST,DISCOUNT_SP,DISCOUNT_PERCENT,DISCOUNT,STATUS,
	AMOUNT_TAX,TAX_PERCENT,AMOUNT_US,AMOUNT,NUMBER_SERIE,NUMBER_LOT,TEXT_COMMENT,CURRENCY_ID,TYPE_EXCHANGE,UNIT_PART,
	QTY_REF,REFERENCE)SELECT "'+@ALMA+'","GS","'+@SER_GUIA+@NUM_GUIA+'","GV",DFSECUEN,DFCODIGO,
	(CASE WHEN DFCODIGO="TEXTO" THEN DFTEXTO ELSE DFDESCRI END),DFPREC_ORI,DFPREC_VEN,DFCANTID,DFDESCLI,DFDESESP,
	DFPORDES,DFDESCTO,"S",DFIGV,DFIGVPOR,DFIMPUS,DFIMPMN,DFSERIE,DFLOTE,DFTR,"'+@MONEDA+'","'+@TIPO_CAMBIO+'",DFUNIDAD,DFCANTID,
	DFPRESU FROM '+@TABLA_det+'')
	SET @ERROR2=@@ERROR
	END

EXEC('set quoted_identifier off Update RECEIVABLE Set DOCUMENT_REF = "GS",SERIE_REF = "'+@SER_GUIA+'",NUMBER_REF = "'+@NUM_GUIA+'",LIST_GUIA = "'+@SER_GUIA+@NUM_GUIA+'" Where DOCUMENT_ID = "'+@TIPO+'" and NUMBER_SERIE = "'+@SERIE+'" and NUMBER_DOCUMENT = "'+@NUMERO+'"')

SET @ERROR3=@@ERROR

IF (@ERROR1<>0 OR @ERROR2<>0 OR @ERROR3<>0)
	BEGIN
		SET @CANT_ERROR=1
		ROLLBACK TRAN UPDATE_GUIA_TRANS
	END
ELSE
	BEGIN
		COMMIT TRAN UPDATE_GUIA_TRANS
	END

