CREATE PROC [dbo].[SAL_UPGRADE_ORDERS_LINE]
@NUMERO VARCHAR(7),
@IDE VARCHAR(50),
@CANT_ERROR INT OUTPUT
AS
declare @TABLA varchar(50)

SET NOCOUNT ON
set @TABLA='tempdb.dbo.'+@IDE+'FACWORDET'
SET @CANT_ERROR=0

BEGIN TRAN UPDATE_ORDERS_LINE
EXEC('set quoted_identifier off Insert Into ORDER_LINE (ID,ITEM,PART_ID,PART_DESCRIPTION,TEXT_COMMENT,QTY,PRICE_SALES,PRICE_ORI,DISCOUNT,
PERCENT_DISCOUNT,DISCOUNT_CUST,DISCOUNT_SP,AMOUNT_TAX,PERCENT_TAX,AMOUNT_US,AMOUNT,SERIE,WAREHOUSE_ID,LOT,
IS_PART_TAX,LIST_ID,UNIT,BALANCE) 
SELECT "'+@NUMERO+'",DFSECUEN,DFCODIGO,DFDESCRI,ISNULL(DFTEXTO," "),DFCANTID,DFPREC_VEN,DFPREC_ORI,DFDESCTO,
DFPORDES,DFDESCLI,DFDESESP,DFIGV,DFIGVPOR,DFIMPUS,DFIMPMN,ISNULL(DFSERIE," "),DFALMA,ISNULL(DFLOTE," "),
DFARTIGV,ISNULL(DFCODLIS," "),DFUNIDAD,DFCANTID FROM '+@TABLA+'')

SET @CANT_ERROR=@@ERROR
COMMIT TRAN UPDATE_ORDERS_LINE
