CREATE procedure SAL_HLP_ALL_VENDEDORES
as
	declare @VENDEDOR_INI varchar(20)
	declare @VENDEDOR_NOM_INI varchar(100)
	declare @VENDEDOR_FIN varchar(20)
	declare @VENDEDOR_NOM_FIN varchar(100)
	
	SELECT @VENDEDOR_INI=MIN(ID),@VENDEDOR_FIN=MAX(ID)
	FROM SALES_REP
	
	select @VENDEDOR_NOM_INI=NAME
				from SALES_REP WHERE ID=@VENDEDOR_INI
	
	select @VENDEDOR_NOM_FIN=NAME
				from SALES_REP WHERE ID=@VENDEDOR_FIN	
	
	
				
	select @VENDEDOR_INI,@VENDEDOR_NOM_INI,@VENDEDOR_FIN,@VENDEDOR_NOM_FIN