CREATE PROC [dbo].[SAL_INSERT_CARTERA]
--DECLARE
@COD_CLI VARCHAR(11),@TIPO VARCHAR(2),@NUM_DOC VARCHAR(10),@FECHA VARCHAR(10),@FECHA_VEN VARCHAR(10),
@TD_REF VARCHAR(2),@NUM_REF VARCHAR(10),@VENDEDOR VARCHAR(2),@MONTO VARCHAR(15),@SALDO VARCHAR(15),
@SALDO_INI VARCHAR(15),@MONEDA VARCHAR(2),@TIPO_CAMBIO VARCHAR(15),@DH VARCHAR(1),@USER VARCHAR(8),
@TIPO_FAC VARCHAR(2),@PAGO VARCHAR(2),@PTOVTA VARCHAR(2),@CANT_ERROR INT OUTPUT
AS
SET NOCOUNT ON

/*SET @COD_CLI='01'
SET @TIPO='FT'
SET @NUM_DOC='0010100100'
SET @FECHA='36541'
SET @FECHA_VEN='36541'
SET @TD_REF='GS'
SET @NUM_REF='0010100102'
SET @VENDEDOR='01'
SET @MONTO='100.25'
SET @SALDO='100.25'
SET @SALDO_INI='100.25'
SET @MONEDA='MN'
SET @TIPO_CAMBIO='3.2'
SET @DH='D'
SET @USER='1'
SET @TIPO_FAC='FT'
SET @PAGO='00'
SET @PTOVTA='01'*/


DECLARE @TRANSA1 INT
DECLARE @TRANSA2 INT
DECLARE @TRANSA3 INT
DECLARE @TRANSA4 INT
DECLARE @TRANSA5 INT
DECLARE @CUENTA VARCHAR(18)

SET @TRANSA1=0
SET @TRANSA2=0
SET @TRANSA3=0
SET @TRANSA4=0
SET @TRANSA5=0
SET @CANT_ERROR=0

SELECT @CUENTA=(CASE WHEN @MONEDA='MN' THEN ACOUNT ELSE ACOUNT_US END)FROM PARAMETERS_ACOUNT WHERE TYPE_DOC=@TIPO

BEGIN TRAN UPDATE_CARTERA
EXEC('set quoted_identifier off Insert Into CUSTOMER_BALANCE (CUSTOMER_ID,DOCUMENT_ID,NUMBER_DOC,DOC_DATE,CADUCATE_DATE,
DOCUMENT_REF,NUMBER_REF,SALES_ID,AMOUNT,AMOUNT_BALANCE,AMOUNT_BALANCE_INI,CURRENCY_ID,SELL_RATE,IS_DR_CR,STATUS,
CREATE_DATE,LAST_MODIFIED,USER_ID,TYPE_REC,ACCOUNT ,TERMS,PLACE_SALES)
VALUES("'+@COD_CLI+'","'+@TIPO+'","'+@NUM_DOC+'",'+@FECHA+','+@FECHA_VEN+',"'+@TD_REF+'","'+@NUM_REF+'",
"'+@VENDEDOR+'","'+@MONTO+'","'+@SALDO+'","'+@SALDO_INI+'","'+@MONEDA+'","'+@TIPO_CAMBIO+'","'+@DH+'","V",
GETDATE(),GETDATE(),"'+@USER+'","'+@TIPO_FAC+'","'+@CUENTA+'","'+@PAGO+'","'+@PTOVTA+'")')
SET @TRANSA2=@@ERROR

IF @MONEDA='MN'
	BEGIN
		EXEC('set quoted_identifier off Update CUSTOMER set BALANCE = BALANCE  + '+@MONTO+'  Where ID = "'+@COD_CLI+'" ')
		SET @TRANSA3=@@ERROR
	END
ELSE
	BEGIN
		EXEC('set quoted_identifier off Update CUSTOMER set BALANCE_US = BALANCE_US  + '+@MONTO+'  Where ID = "'+@COD_CLI+'" ')
		SET @TRANSA3=@@ERROR
	END


EXEC('set quoted_identifier off INSERT INTO INVOICE (INVOICE_ID,STATUS,LAST_STATUS) VALUES("'+@NUM_DOC+'","CR","CR")')
SET @TRANSA4=@@ERROR

EXEC ('set quoted_identifier off INSERT INTO HISTORY_RECEIVABLE (INVOICE_ID,STATUS,AMOUNT,DATE) VALUES("'+@NUM_DOC+'","CR",'+@MONTO+','+@FECHA+')')
SET @TRANSA5=@@ERROR


IF (@TRANSA1<>0 OR @TRANSA2<>0 OR @TRANSA3<>0 OR @TRANSA4<>0 OR @TRANSA5<>0)
	BEGIN
		SET @CANT_ERROR=1
		ROLLBACK TRAN UPDATE_CARTERA
	END
ELSE
	BEGIN
		COMMIT TRAN UPDATE_CARTERA
	END

