CREATE PROC [dbo].[SAL_UPGRADE_QUOTE]
--DECLARE
@NUMERO VARCHAR(7),
@USER VARCHAR(8),
@MONTO VARCHAR(15),
@MONTOIGV VARCHAR(15),
@IDE VARCHAR(30),
@EXPIRES_DATE VARCHAR(10),
@PLACE_SHIPPER VARCHAR(80),
@TIME_SHIPPER VARCHAR(80)
AS
SET NOCOUNT ON
/*SET @NUMERO='0000015'
SET @USER='1'
SET @MONTO='1000'
SET @MONTOIGV='190'
SET @IDE='DEVELOPER6'
SET @EXPIRES_DATE='rr'
SET @PLACE_SHIPPER='ereeee'
SET @TIME_SHIPPER='33'*/


declare @TABLA varchar(50)
declare @TRAN1 int
declare @TRAN2 int
set @TABLA='tempdb.dbo.'+@IDE+'FACWORCAB'

BEGIN TRAN UPDATE_QUOTE
exec('set quoted_identifier off Insert Into QUOTE (NUMBER_QUOTE,QUOTE_DATE,CADUCATE_DATE,SALES_ID,PLACE_SALES,
CUSTOMER_ID,VAT_REGISTRATION,CUSTOMER_NAME,CUSTOMER_ADDR,DISCOUNT,DISCOUNT_SP,TERMS,SELL_RATE,CURRENCY_ID,USER_ID,
REFERENCE_DOC,REFERENCE_SERIE,REFERENCE_NUMBER,STATUS,COMMENT,AMOUNT,AMOUNT_TAX,AMOUNT_DISCOUNT,EXPIRES_DATE,
PLACE_SHIPPER,TIME_SHIPPER)
SELECT "'+@NUMERO+'",CFFECDOC,CFFECVEN,cfVENDE,cfPUNVEN,CFCODCLI,ISNULL(CFRUC," "),CFNOMBRE,ISNULL(CFDIRECC," "),
CFPORDESCL,CFPORDESES,CFFORVEN,CFTIPCAM,CFCODMON,"'+@USER+'",ISNULL(CFRFTD," "),ISNULL(CFRFNUMSER," "),
ISNULL(CFRFNUMDOC," "),"V",cfglosa,"'+@MONTO+'","'+@MONTOIGV+'",CFDESVAL,
"'+@EXPIRES_DATE+'","'+@PLACE_SHIPPER+'","'+@TIME_SHIPPER+'" FROM '+@TABLA+'')
SET @TRAN1 =@@ERROR

EXEC SAL_UPGRADE_QUOTE_LINE @NUMERO,@IDE,@TRAN2 OUTPUT


IF (@TRAN1<>0 OR @TRAN2<>0) 
	BEGIN
		ROLLBACK TRAN UPDATE_QUOTE
	END
ELSE
	BEGIN
		COMMIT TRAN UPDATE_QUOTE
	END

