CREATE PROC [dbo].[SAL_UPGRADE_GUIA_LINE]
--DECLARE
@ALMA VARCHAR(2),
@NUMFACWOR VARCHAR(7),
@NUMERO VARCHAR(10),
@FLAG_REF INT,
@MONEDA VARCHAR(2),
@TIPCAM VARCHAR(15),
@IDE VARCHAR(30),
@CANT_ERROR INT --OUTPUT
AS
SET NOCOUNT ON
/*SET @ALMA='01'
SET @NUMFACWOR='0000232'
SET @NUMERO='0010100100'
SET @FLAG_REF='1'
SET @MONEDA='MN'
SET @TIPCAM='3.23'
SET @IDE='DEVELOPER6'*/

DECLARE @TABLA VARCHAR(50)
set @TABLA='tempdb.dbo.'+@IDE+'FACWORDET'
SET @CANT_ERROR=0
BEGIN TRAN UPDATE_GUIA_LINE 

IF @FLAG_REF=1
	BEGIN
	EXEC('set quoted_identifier off INSERT INTO WAREHOUSE_TRANS_LINE (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,TRANS_ID,ITEM,PART_ID,
	PART_DESCRIPTION,AMOUNT_SALES,AVERAGE_COST,QTY,DISCOUNT_CUST,DISCOUNT_SP,DISCOUNT_PERCENT,DISCOUNT,STATUS,
	AMOUNT_TAX,TAX_PERCENT,AMOUNT_US,AMOUNT,NUMBER_SERIE,NUMBER_LOT,TEXT_COMMENT,CURRENCY_ID,TYPE_EXCHANGE,UNIT_PART
	)SELECT "'+@ALMA+'","GS","'+@NUMERO+'","GV",DFSECUEN,DFCODIGO,
	(CASE WHEN DFCODIGO="TEXTO" THEN DFTEXTO ELSE DFDESCRI END),DFPREC_ORI,DFPREC_VEN,DFCANTID,DFDESCLI,DFDESESP,
	DFPORDES,DFDESCTO,"S",DFIGV,DFIGVPOR,DFIMPUS,DFIMPMN,DFSERIE,DFLOTE,DFTR,"'+@MONEDA+'","'+@TIPCAM+'",DFUNIDAD,DFCANTID,
	DFPRESU FROM '+@TABLA+' where DFSISTEM = "F" and  DFNUMPED = "'+@NUMFACWOR+'"')
	SET @CANT_ERROR=@@ERROR
	END
ELSE
	BEGIN
	EXEC('set quoted_identifier off INSERT INTO WAREHOUSE_TRANS_LINE (WAREHOUSE_ID,DOCUMENT_ID,NUMBER_DOCUMENT,TRANS_ID,ITEM,PART_ID,
	PART_DESCRIPTION,AMOUNT_SALES,AVERAGE_COST,QTY,DISCOUNT_CUST,DISCOUNT_SP,DISCOUNT_PERCENT,DISCOUNT,STATUS,
	AMOUNT_TAX,TAX_PERCENT,AMOUNT_US,AMOUNT,NUMBER_SERIE,NUMBER_LOT,TEXT_COMMENT,CURRENCY_ID,TYPE_EXCHANGE,UNIT_PART,
	QTY_REF,REFERENCE)SELECT "'+@ALMA+'","GS","'+@NUMERO+'","GV",DFSECUEN,DFCODIGO,
	(CASE WHEN DFCODIGO="TEXTO" THEN DFTEXTO ELSE DFDESCRI END),DFPREC_ORI,DFPREC_VEN,DFCANTID,DFDESCLI,DFDESESP,
	DFPORDES,DFDESCTO,"S",DFIGV,DFIGVPOR,DFIMPUS,DFIMPMN,DFSERIE,DFLOTE,DFTR,"'+@MONEDA+'","'+@TIPCAM+'",DFUNIDAD,DFCANTID,
	DFPRESU,REFERENCE,CANTREFERENCIA FROM '+@TABLA+' where DFSISTEM = "F" and  DFNUMPED = "'+@NUMFACWOR+'"')
	SET @CANT_ERROR=@@ERROR
	END

COMMIT TRAN UPDATE_GUIA_LINE
