create procedure SAL_TIPO_DOC_PTO_VENTA
		(
		@PTO_VENTA VARCHAR(2)
		)
	as
	select DOCUMENT_TYPE 
	from DOCUMENT_PLACE_SALES where PLACE_SALES_ID=@PTO_VENTA
	and DOCUMENT_TYPE in ('FT','BV','ND')
	group by DOCUMENT_TYPE
	ORDER BY DOCUMENT_TYPE
