CREATE PROCEDURE [dbo].[SALcrfact002]   
   @FECINI VARCHAR(20),  
   @FECFIN VARCHAR(20),  
   @PVTAINI VARCHAR(5),  
   @PVTAFIN VARCHAR(5),  
   @BASE VARCHAR(20)  
AS  
-- EXEC('SELECT A.*,B.NAME,B.NET_DAYS FROM RECEIVABLE A LEFT JOIN   
   EXEC('SET QUOTED_IDENTIFIER OFF SELECT A.*,B.NAME,B.NET_DAYS FROM RECEIVABLE A LEFT JOIN   
 TERMS B ON A.TERMS_ID=B.ID   
 WHERE A.DOCUMENT_DATE BETWEEN '+@FECINI+' AND '+@FECFIN+' AND  
        A.PLACE_SALES BETWEEN "'+@PVTAINI+'" AND "'+@PVTAFIN+'"')   

