CREATE PROC [dbo].[SALimprimePedidos]-- '0000007' 
--DECLARE  
@NUMERO NVARCHAR(10)  
AS  
DECLARE @STRquery nvarchar(4000)  
set @STRquery='SELECT C.ID, ORDER_DATE, CADUCATE_DATE, C.SALES_ID, C.PLACE_SALES, CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_ADDR, C.VAT_REGISTRATION, C.AMOUNT, DISCOUNT_CUSTOMER, C.DISCOUNT_SP, TERMS, SELL_RATE, CURRENCY_ID, DOCUMENT_REF, SERIE_REF, NUMBER_REF,   
C.CREATE_DATE, C.STATUS, C.USER_ID, C.COMMENT, NUMBER_GUIA, NUMBER_REC, ORDER_PURCHASE, COMMENT1, AMOUNT_VAT, C.DISCOUNT, DISCOUNT_AMOUNT, REC_TYPE, DISCOUNT_VAL, STATUS_ORDER  
  
,ITEM, PART_ID, PART_DESCRIPTION, QTY, PRICE_SALES, PRICE_ORI, D.DISCOUNT AS DISCOUNT_LINE, AMOUNT_TAX, DISCOUNT_CUST, D.DISCOUNT_SP AS DISCOUNT_SP_LINE, PERCENT_TAX, PERCENT_DISCOUNT, AMOUNT_US, D.AMOUNT AS AMOUNT_MN, D.STATUS AS STATUS_LINE,   
SERIE, WAREHOUSE_ID, TEXT_COMMENT, QTY_REF, LOT, D.BALANCE, IS_PART_TAX, LIST_ID, UNIT  
  
,T.ID AS COD_TERM, T.NAME AS NAME_TERM, NET_DAYS, REGISTER_DATE, EFFECTIVE_DATE  ,CL.CONTACT
  
FROM ORDERS C INNER JOIN ORDER_LINE D ON C.ID=D.ID LEFT JOIN TERMS T ON C.TERMS=T.ID  
LEFT JOIN CUSTOMER CL ON C.CUSTOMER_ID=CL.ID
WHERE C.ID=@NUMERO'  
--PRINT(@STRquery)  
  
exec sp_executesql @STRquery,N'@NUMERO NVARCHAR(10)',@NUMERO  