--exec SALimprimefacturas 'NC','001','0000364'
CREATE PROC [dbo].[SALimprimefacturas]          
--declare          
@TIPO NVARCHAR(2),@SERIE NVARCHAR(3),@NUMERO NVARCHAR(7)          
AS          
/*set @TIPO='FT'          
SET @SERIE='001'          
SET @NUMERO='0000016'*/          
DECLARE @STRquery nvarchar(4000)          
set @STRquery='SELECT C.DOCUMENT_ID, C.NUMBER_SERIE, C.NUMBER_DOCUMENT, DOCUMENT_DATE, C.CADUCATE_DATE, C.SALES_REP_ID, PLACE_SALES, NUMBER_QUOTE, NUMBER_ORDER_PUR,RECEIVABLE_TYPE, CUSTOMER_ID,      
CUSTOMER_NAME, CUSTOMER_ADDR, C.VAT_REGISTRATION, C.WAREHOUSE_ID, C.AMOUNT, TERMS_ID, C.BALANCE, SELL_RATE, C.CURRENCY_ID, DOCUMENT_REF, SERIE_REF, NUMBER_REF, NUMBER_ORDER, C.CREATE_DATE, LAST_MODIFIED, C.STATUS, C.USER_ID, C.COMMENT, IS_GUIA_REC,       
NUMBER_REGISTRATION, C.DISCOUNT_PERCENT, DISCOUNT_PERCENT_SP, CARD_ID, NUMBER_CARD, AMOUNT_CARD_US, AMOUNT_CARD, BANK_CHECK, NUMBER_CHECK, AMOUNT_CH_US, AMOUNT_CH, VOUCHER_ID, NUMBER_TRA, C.AMOUNT_TAX, DISCOUNTV, DISCOUNTP, LIST_GUIA, IS_PRINT,           
DISCOUNT_RECIVABLE,IS_CLOSED, SUB_ID, TOTAL_ERROR, PROMISE_DAYS, SHIPPER_TYPE, ZONE_FREIGTH, AMOUNT_FREIGTH, IS_GUIA, IS_CASH_BANK, TAX_TYPE, REC_AUTO  
,ITEM, D.PART_ID, QTY, PRICE_SALES, PRICE_ORI, D.DISCOUNT, D.AMOUNT_TAX AS AMOUNT_TAX_LINE, TAX_PERCENT, AMOUNT_US, D.AMOUNT AS AMOUNT_LINE, UNIT, D.STATUS AS STATUS_LINE, PART_SERIE, D.WAREHOUSE_ID AS WAREHOUSE_ID_LINE, TEXT_DESCRIPTION, DFTR,           
STOCK, PART_DESCRIPTION, QTY_REF, D.DISCOUNT_PERCENT AS DISCOUNT_PERCENT_LINE, BALANCE_PART, DISCOUNT_CUSTOMER, DISCOUNT_SP, PART_LOT, NUMBER_GUIA, PART_TAX, DISCOUNT1, DISCOUNT2, PERCENT1, PERCENT2, PRICE_LIST_ID, SHIPPER_QTY, BUDGET_ID, ORDER_ID,       
BRUTE_QTY, DISCOUNT_QTY_BRUTE, UM_REFERENCE, QTY_REFERENCE,M.ID AS COD_CUSTOMER, M.NAME, M.ADDR, M.PHONE, M.VAT_REGISTRATION AS VAT_REG_CUSTOMER, NUMBER_DOC, M.DISCOUNT_PERCENT AS DISCOUNT_PERCENT_CUSTOMER, TERMS_TYPE, M.STATUS AS STATUS_CUSTOMER, OPEN_DATE, CONTACT, STATE_ID, M.CREATE_USER,           
M.CREATE_DATE AS CREATE_DATE_CUSTOMER, MODIFY_DATE, TYPE_PRICE, M.SALES_ID AS SALES_ID_CUSTOMER, SELL_ZONE, COUNTRY, DEPARTMENT, PROVINCE, M.ADDR_DLV AS ADDR_DLV_CUSTOMER, CURRENCY_CREDIT_LIMIT, CREDIT_LIMIT_US, CREDIT_LIMIT,           
M.BALANCE AS BALANCE_CUSTOMER, BALANCE_US, OBSERV, TOTAL_LETTER, TOTAL_RECEIVABLE, TOTAL_CHECK, TOTAL_LETTER_PROTESTED, CUSTOMER_TYPE, BUSINESS_TYPE, TERRITORY, ROUTE, SEGMENT, SEGMENT_LOCATION, BANK_ID, ACCOUNT_NO, DATE_REVIEW, HOUR_VISIT,           
ATTENTION_TYPE, FAX_NUMBER, M.EMAIL, WEBSITE, M.COMMENT AS COMMENT_CUSTOMER, IS_PRIMARY, RETENTION,A.ID AS COD_PART, ID_FAB, DESCRIPTION, DESCRIPTION_OPT, FAMILY,L.NAME AS MODEL, UNIT_OF_MEASUREMENT, GROUP_ID, A.ACCOUNT AS ACCOUNT_PART, SERIES, A.UNIT_PRICE AS UNIT_PRICE_PART, A.DISCOUNT AS DISCOUNT_PART, PRICE_BUY, VENDOR_ID_PART,           
LOCATION, IS_STOCKED, A.CREATE_USER AS CREATE_USER_PART, A.STATUS AS STATUS_PART, A.DATE_CADUCATE AS DATE_CADUCATE_PART, A.CURRENCY_ID AS CURRENCY_PART, TYPE_PART, A.COMMENT AS COMMENT_PART, IS_LOT, WEIGHT,           
CST_POR, VAT_POR, HOUR_UPDATE, IS_FREE_PRICE, IS_PRICE_VAT, COMMISSION_SALES, IS_VAT, COLOR, MARK, PICTURE, HEIGHT, A.REFERENCE AS REFERENCE_PART, ID_AUTONUMERIC, LAST_DATE_BUY          
,S.ID AS COD_SALES, S.NAME AS NAME_SALES, S.ADDR AS ADDR_SALES, S.PHONE AS PHONE_SALES, S.EMAIL AS EMAIL_SALES, S.VAT_REGISTRATION AS VAT_REGISTRATION_SALES, TERRITORY_ID, SEGMENT_ID, UBICATION_ID, ZONE_ID, S.CREATE_DATE AS CREATE_DATE_SALES,           
S.USER_ID AS SALES, ROUTE_ID, DOC_NUMBER ,T.ID AS COD_TERM, T.NAME AS NAME_TERM, NET_DAYS, REGISTER_DATE, EFFECTIVE_DATE,LT.CADUCATE_DATE,D.COMISION,ISNULL(D.TIPOISC,0) AS TIPOISC,ISNULL(D.ISCPOR,0) AS ISCPOR, ISNULL(D.ISC,0) AS ISC      
FROM RECEIVABLE C INNER JOIN RECEIVABLE_LINE D ON C.DOCUMENT_ID=D.DOCUMENT_ID AND C.NUMBER_SERIE=D.NUMBER_SERIE AND C.NUMBER_DOCUMENT=D.NUMBER_DOCUMENT          
INNER JOIN CUSTOMER M ON C.CUSTOMER_ID=M.ID INNER JOIN PART A ON D.PART_ID = A.ID      
INNER JOIN SALES_REP S ON C.SALES_REP_ID=S.ID LEFT JOIN TERMS T ON C.TERMS_ID=T.ID  
left JOIN LINES L ON L.ID=A.MODEL AND L.FAMILY_ID=A.FAMILY   
LEFT join LOT LT ON LT.PART_ID=D.PART_ID AND LT.LOT_ID=D.PART_LOT AND LT.WHO_ID=D.WAREHOUSE_ID      
WHERE C.DOCUMENT_ID=@TIPO AND C.NUMBER_SERIE=@SERIE AND C.NUMBER_DOCUMENT=@NUMERO'          
      
--PRINT(@STRquery)          
          
EXEC sp_executesql @STRquery,N'@TIPO NVARCHAR(2),@SERIE NVARCHAR(3),@NUMERO NVARCHAR(10)',@TIPO,@SERIE,@NUMERO          
  --select * from lines  

