CREATE PROC [dbo].[SALimprimeGuias]
--DECLARE
@ALMACEN NVARCHAR(2),@NUMERO NVARCHAR(10)
AS
--SET @ALMACEN='01'
--SET @NUMERO='0010000038'

DECLARE @STRquery nvarchar(4000)
DECLARE @TIPO CHAR(2)
SET @TIPO='GS'
set @STRquery='SELECT C.WAREHOUSE_ID, C.DOCUMENT_ID, C.NUMBER_DOCUMENT, DATE_DOCUMENT, TYPE_TRANS, C.TRANS_ID, DOCUMENT_STATUS, DOC_ID_REF, NUM_ID_REF, AUTORIZED_ID, DATE_RETURN, VENDOR_ID, C.CCOST_ID, C.WAREHOUSE_REF, C.COMMENT, UPDATE_DATE, HOUR, 
C.USER_ID, CUSTOMER_ID, C.VAT_REGISTRATION, CUSTOMER_NAME, SALES_TERM, CURRENCY_TYPE, C.SALES_ID, CURRENCY_EXCHANGE, TYPE_GUIA, STATUS_GUIA, RECEIVABLE_GUIA, C.ADDR_DLV, CARRIER_ID, NUMBER_PURCHASE, IS_GUIA_RETURN, VENDOR_NAME, NUMBER_ORDER, 
NUMBER_ESTIMATING, DISCOUNT_PER_CUST, DISCOUNT_PER_SP, C.AMOUNT, CARRIER_NAME, CARRIER_ADDR, CARRIER_VAT, C.NUMBER_REGISTRATION, NUMBER_IMPORT, NUMBER_LIQ, PRINTER_STATUS, STATUS_CLOSE, TYPE_SHIPPER, ZONE_FREIGHT, IS_GUIA, IS_POST, FREIGHT, 
ORDER_REF, COST, RECEP_NAME, DOCUMENT_RECEP, NUM_ORDER_MANUFACT, INTERFACE, C.ACCOUNT 

,ITEM, PART_ID, REF_ID, QTY, QTY_DLV, QTY_REF, QTY_INVOICED, NUM_ORDER, D.UNIT_PRICE, AVERAGE_COST, AMOUNT_SALES, D.DISCOUNT, STOCK, AMOUNT_TAX, D.AMOUNT, AMOUNT_US, NUMBER_SERIE, STATUS_DOC, DATE_DOC, D.CCOST_ID, D.WAREHOUSE_REF, TEXT_COMMENT, 
D.STATUS, D.TRANS_ID, VAL_AMOUNT, NUM_VOUCHER, D.CURRENCY_ID AS CURRENCY_LINE, TYPE, TYPE_EXCHANGE, PRICE_SALES, TOTAL_SALES, D.DATE_CADUCATE AS DATE_CADUCATE_LINE, RETURN_AMOUNT, AUTHORIZED, PART_DESCRIPTION, 
D.DISCOUNT_PERCENT AS DISCOUNT_PERCENT_LINE, TAX_PERCENT, DISCOUNT_CUST, DISCOUNT_SP, NUMBER_INVOICE, NUMBER_LOT, UNIT_PART, ORDER_MANUFACT_ID, EQUIP_ID, FREIGTH, ITEMI, QTY_BRUTE, DISCOUNT_PER_QTY, STATUS_VALUE, UNIT_REFERENCE, QTY_REFERENCE, 
D.COMMENT AS COMMENT_LINE, D.REFERENCE AS REFERENCE_LINE, D.ACCOUNT AS ACCOUNT_LINE 

,M.ID AS COD_CUSTOMER, M.NAME, M.ADDR, M.PHONE, M.VAT_REGISTRATION AS VAT_REG_CUSTOMER, NUMBER_DOC, M.DISCOUNT_PERCENT AS DISCOUNT_PERCENT_CUSTOMER, TERMS_TYPE, M.STATUS AS STATUS_CUSTOMER, OPEN_DATE, CONTACT, STATE_ID, M.CREATE_USER, 
M.CREATE_DATE, MODIFY_DATE, TYPE_PRICE, M.SALES_ID AS SALES_ID_CUSTOMER, SELL_ZONE, COUNTRY, DEPARTMENT, PROVINCE, M.ADDR_DLV AS ADDR_DLV_CUSTOMER, CURRENCY_CREDIT_LIMIT, CREDIT_LIMIT_US, CREDIT_LIMIT, BALANCE, BALANCE_US, OBSERV, TOTAL_LETTER, 
TOTAL_RECEIVABLE, TOTAL_CHECK, TOTAL_LETTER_PROTESTED, CUSTOMER_TYPE, BUSINESS_TYPE, TERRITORY, ROUTE, SEGMENT, SEGMENT_LOCATION, BANK_ID, ACCOUNT_NO, DATE_REVIEW, HOUR_VISIT, ATTENTION_TYPE, FAX_NUMBER, EMAIL, WEBSITE, 
M.COMMENT AS COMMENT_CUSTOMER, IS_PRIMARY, RETENTION,

A.ID AS COD_PART, ID_FAB, DESCRIPTION, DESCRIPTION_OPT, FAMILY, MODEL, UNIT_OF_MEASUREMENT, GROUP_ID, A.ACCOUNT AS ACCOUNT_PART, SERIES, A.UNIT_PRICE AS UNIT_PRICE_PART, A.DISCOUNT AS DISCOUNT_PART, PRICE_BUY, VENDOR_ID_PART, 
A.CREATE_DATE AS CREATE_DATE_PART, LOCATION, IS_STOCKED, A.CREATE_USER AS CREATE_USER_PART, A.STATUS AS STATUS_PART, A.DATE_CADUCATE AS DATE_CADUCATE_PART, A.CURRENCY_ID AS CURRENCY_PART, TYPE_PART, A.COMMENT AS COMMENT_PART, IS_LOT, WEIGHT, 
CST_POR, VAT_POR, HOUR_UPDATE, IS_FREE_PRICE, IS_PRICE_VAT, COMMISSION_SALES, IS_VAT, COLOR, MARK, PICTURE, HEIGHT, A.REFERENCE AS REFERENCE_PART, ID_AUTONUMERIC, LAST_DATE_BUY

,R.ID AS COD_CARRIER, NAME_CARRIER, R.ADDR AS ADDR_CARRIER, R.PHONE, R.VAT_REGISTRATION AS VAT_REG_CARRIER, R.STATUS AS STATUS_CARRIER, R.CREATE_DATE AS CREATE_DATE_CARRIER, R.NAME AS NAME_CARRIER, VAT_REGISTRATION_COMP, ADDR_COMP, PHONE_COMP, 
R.NUMBER_REGISTRATION AS NUMBER_REG_CARRIER, NUMBER_LICENSE, MODEL_VEH, NUMBER_INSCRIP, R.NUMBER_DOCUMENT AS NUMBER_DOCUMENT_CARRIER

,T.ID AS COD_TERM, T.NAME AS NAME_TERM, NET_DAYS, REGISTER_DATE, EFFECTIVE_DATE

FROM WAREHOUSE_TRANS C INNER JOIN WAREHOUSE_TRANS_LINE D ON C.WAREHOUSE_ID=D.WAREHOUSE_ID AND C.DOCUMENT_ID=D.DOCUMENT_ID AND C.NUMBER_DOCUMENT=D.NUMBER_DOCUMENT 
INNER JOIN CUSTOMER M ON C.CUSTOMER_ID=M.ID INNER JOIN PART A ON D.PART_ID = A.ID LEFT JOIN CARRIER R ON C.CARRIER_ID=R.ID LEFT JOIN TERMS T ON C.SALES_TERM=T.ID 
WHERE C.WAREHOUSE_ID=@ALMACEN AND C.DOCUMENT_ID=@TIPO AND C.NUMBER_DOCUMENT=@NUMERO'
--PRINT(@STRquery)

exec sp_executesql @STRquery,N'@ALMACEN NVARCHAR(2),@NUMERO NVARCHAR(10),@TIPO CHAR(2)',@ALMACEN,@NUMERO,@TIPO





