CREATE PROC [dbo].[SALprintquote]  
--DECLARE  
@NUMERO NVARCHAR(10)  
AS 
SELECT C.ID AS NUMBER_QUOTE,C.ORDER_DATE AS QUOTE_DATE,C.AMOUNT,C.TERMS,C.CURRENCY_ID,C.USER_ID,D.AMOUNT_TAX,
		D.PART_ID,D.PART_DESCRIPTION,D.QTY,D.PRICE_ORI,D.TEXT_COMMENT,D.UNIT,P.ID_FAB,CU.ID AS COD_CUSTOMER,
		CU.NAME AS NAME_CUSTOMER,CU.ADDR AS ADDR_CUSTOMER,CU.PHONE AS PHONE_CUSTOMER,CU.FAX_NUMBER,S.NAME AS NAME_SALES
FROM QUOTE C INNER JOIN QUOTE_LINE D ON C.ID=D.ID INNER JOIN PART P ON D.PART_ID=P.ID 
	INNER JOIN CUSTOMER CU ON C.CUSTOMER_ID =CU.ID INNER JOIN SALES_REP S ON C.SALES_ID=S.ID
WHERE C.ID=@NUMERO