CREATE PROCEDURE [dbo].[SALselecrango]
@NUMOPC NUMERIC(1),@OPCION1 VARCHAR(100),@CFFLAGCIERRE char(1),@CFFECDOC1 VARCHAR(4),
@CFFECDOC2 VARCHAR(4),@CFFECDOC3 VARCHAR(4),@CFFECDOC4 VARCHAR(4),@CFESTADO varchar(1)
AS
IF @NUMOPC=1
     exec('SET QUOTED_IDENTIFIER OFF Select '+@OPCION1+' From RECEIVABLE Where IS_CLOSED = '+@CFFLAGCIERRE+' And month(DOCUMENT_DATE) >= '+@CFFECDOC1+'  and 
year(DOCUMENT_DATE) >= '+@CFFECDOC2+' And month(DOCUMENT_DATE) <= '+@CFFECDOC3+'  and year(DOCUMENT_DATE) <= '+@CFFECDOC4+'  AND 
STATUS <>"'+@CFESTADO+'"')
ELSE
     exec('SET QUOTED_IDENTIFIER OFF  Select ' + @OPCION1 +'  From RECEIVABLE Where IS_CLOSED = '+@CFFLAGCIERRE+' And month(DOCUMENT_DATE) <= '+@CFFECDOC1+'  And 
year(DOCUMENT_DATE) <= '+@CFFECDOC2+'  AND STATUS <> "'+@CFESTADO+'" ORDER BY DOCUMENT_DATE')


