create PROC SG_CO_SP_REP_EGP_COMPA    
@P_AYO INT = 2012 ,  
@P_MES INT = 1 ,  
@P_ES_MENSUAL INT = 1  
AS    

    
    
DECLARE @VENTAS_NETAS NUMERIC(20,2)    
DECLARE @COSTO_VENTAS NUMERIC(20,2)    
DECLARE @UTILIDAD_BRUTA NUMERIC(20,2)    
DECLARE @GASTOS_ADMINISTRATIVOS NUMERIC(20,2)    
DECLARE @GASTOS_VENTAS NUMERIC(20,2)    
DECLARE @UTILIDAD_OPERATIVA NUMERIC(20,2)    
DECLARE @INGRESOS_FINANCIEROS NUMERIC(20,2)    
DECLARE @GASTOS_FINANCIEROS NUMERIC(20,2)    
DECLARE @OTROS_INGRESOS NUMERIC(20,2)    
DECLARE @OTROS_GASTOS NUMERIC(20,2)    
DECLARE @INGRESOS_EXATRAORDINARIOS NUMERIC(20,2)    
DECLARE @GASTOS_EXTRAORDINARIOS NUMERIC(20,2)    
DECLARE @RESULTADO_ANTES NUMERIC(20,2)    
DECLARE @PARTICIPACIONES NUMERIC(20,2)    
DECLARE @IMPUESTO_RENTA NUMERIC(20,2)    
DECLARE @UTILIDAD_NETA NUMERIC(20,2)    
    
  
 if @P_ES_MENSUAL = 1 begin    
  SET @VENTAS_NETAS =    
   (    
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
   WHERE  AC_ANHO = @P_AYO  and ac_mes = @P_MES AND LEFT(AD_CUENTA,2) IN (    
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 1)    
   )    
 end else begin  
  SET @VENTAS_NETAS =    
   (    
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
   WHERE  AC_ANHO = @P_AYO  and ac_mes <= @P_MES AND LEFT(AD_CUENTA,2) IN (    
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 1)    
   )  
 end  
         
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @VENTAS_NETAS WHERE EGP_IDCONCEPTO_EGP = 1      
  
    
 if @P_ES_MENSUAL = 1 begin    
  SET @COSTO_VENTAS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 2)    
  )    
 end else begin  
  SET @COSTO_VENTAS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 2)    
  )  
 end  
       
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @COSTO_VENTAS WHERE EGP_IDCONCEPTO_EGP = 2      
  
    
  SET @UTILIDAD_BRUTA = ISNULL(@VENTAS_NETAS - @COSTO_VENTAS,0)    
    
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @UTILIDAD_BRUTA WHERE EGP_IDCONCEPTO_EGP = 3      
   
    
 if @P_ES_MENSUAL = 1 begin    
  SET @GASTOS_ADMINISTRATIVOS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 6)    
  )    
 end else begin  
  SET @GASTOS_ADMINISTRATIVOS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 6)    
  )  
 end  
       
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @GASTOS_ADMINISTRATIVOS WHERE EGP_IDCONCEPTO_EGP = 6 
    
  
 if @P_ES_MENSUAL = 1 begin    
  SET @GASTOS_VENTAS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 7)    
  )    
 end else begin  
  SET @GASTOS_VENTAS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 7)    
  )  
 end  
       
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @GASTOS_VENTAS WHERE EGP_IDCONCEPTO_EGP = 7 
    
  SET @UTILIDAD_OPERATIVA = ISNULL(@UTILIDAD_BRUTA - @GASTOS_ADMINISTRATIVOS - @GASTOS_VENTAS,0)    
       
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @UTILIDAD_OPERATIVA WHERE EGP_IDCONCEPTO_EGP = 8 
    
  
 if @P_ES_MENSUAL = 1 begin         
  SET @INGRESOS_FINANCIEROS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 11)    
  )    
 end else begin  
  SET @INGRESOS_FINANCIEROS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 11)    
  )  
 end  
  
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @INGRESOS_FINANCIEROS WHERE EGP_IDCONCEPTO_EGP = 11 
       
    
 if @P_ES_MENSUAL = 1 begin       
  SET @GASTOS_FINANCIEROS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 12)    
  )    
 end else begin  
  SET @GASTOS_FINANCIEROS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 12)    
  )  
 end  
  
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @GASTOS_FINANCIEROS WHERE EGP_IDCONCEPTO_EGP = 12 
    
    
   
 if @P_ES_MENSUAL = 1 begin       
  SET @OTROS_INGRESOS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 13)    
  )    
  
 end else begin  
  
  SET @OTROS_INGRESOS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 13)    
  )  
 end  
    
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @OTROS_INGRESOS WHERE EGP_IDCONCEPTO_EGP = 13 
      
  
  
  
 if @P_ES_MENSUAL = 1 begin        
  SET @OTROS_GASTOS =    
   (    
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
   WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 14)    
   )    
 end else begin  
  SET @OTROS_GASTOS =    
   (    
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
   WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 14)    
   )  
 end  
  
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @OTROS_GASTOS WHERE EGP_IDCONCEPTO_EGP = 14 
    
 if @P_ES_MENSUAL = 1 begin           
  SET @INGRESOS_EXATRAORDINARIOS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 15)    
  )    
 end else begin  
  SET @INGRESOS_EXATRAORDINARIOS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 15)    
  )  
 end  
  
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @INGRESOS_EXATRAORDINARIOS WHERE EGP_IDCONCEPTO_EGP = 15 
    
  
  
  
  
 if @P_ES_MENSUAL = 1 begin             
  SET @GASTOS_EXTRAORDINARIOS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 16)    
  )    
 end else begin  
  SET @GASTOS_EXTRAORDINARIOS =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 16)    
  )  
 end  
  
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @GASTOS_EXTRAORDINARIOS WHERE EGP_IDCONCEPTO_EGP = 16
    
       
  SET @RESULTADO_ANTES = @UTILIDAD_OPERATIVA + @INGRESOS_FINANCIEROS - @GASTOS_FINANCIEROS +     
        @OTROS_INGRESOS - @OTROS_GASTOS + @INGRESOS_EXATRAORDINARIOS -     
        @GASTOS_EXTRAORDINARIOS    
    
       
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @RESULTADO_ANTES WHERE EGP_IDCONCEPTO_EGP = 17 
    
  
 if @P_ES_MENSUAL = 1 begin   
  SET @PARTICIPACIONES =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 20)    
  )  
 end else begin  
  SET @PARTICIPACIONES =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 20)    
  )  
 end    
       
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @PARTICIPACIONES WHERE EGP_IDCONCEPTO_EGP = 20 
    
 if @P_ES_MENSUAL = 1 begin   
  SET @IMPUESTO_RENTA =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 21)    
  )    
 end else begin  
  SET @IMPUESTO_RENTA =    
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)    
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB    
  WHERE  AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (    
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 21)    
  )  
 end       
  
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @IMPUESTO_RENTA WHERE EGP_IDCONCEPTO_EGP = 21 
    
    
  SET @UTILIDAD_NETA = @RESULTADO_ANTES - @PARTICIPACIONES - @IMPUESTO_RENTA    
      
   UPDATE CO_TB_REP_EGP SET  EGP_VALOR2 = @UTILIDAD_NETA WHERE EGP_IDCONCEPTO_EGP = 22 
    
  SELECT CO_ID,CO_DESCRIPCION,CO_TITULO,ISNULL(EGP_VALOR1,0) AS  VALOR1,ISNULL(EGP_VALOR2,0) AS  VALOR2      
  FROM CO_TB_CONCEPTO_EGP A LEFT JOIN (SELECT * FROM CO_TB_REP_EGP )B     
  ON A.CO_ID = B.EGP_IDCONCEPTO_EGP 
