
create PROC SG_CO_SP_REP_EGP      
@P_AYO INT = 2012 ,    
@P_MES INT = 7 ,    
@P_ES_MENSUAL INT = 0    
AS 
     
DECLARE @VENTAS_NETAS float  
DECLARE @COSTO_VENTAS float  
DECLARE @UTILIDAD_BRUTA float  
DECLARE @GASTOS_ADMINISTRATIVOS float  
DECLARE @GASTOS_VENTAS float  
DECLARE @UTILIDAD_OPERATIVA float  
DECLARE @INGRESOS_FINANCIEROS float  
DECLARE @GASTOS_FINANCIEROS float  
DECLARE @OTROS_INGRESOS float  
DECLARE @OTROS_GASTOS float  
DECLARE @INGRESOS_EXATRAORDINARIOS float  
DECLARE @GASTOS_EXTRAORDINARIOS float  
DECLARE @RESULTADO_ANTES float  
DECLARE @PARTICIPACIONES float  
DECLARE @IMPUESTO_RENTA float  
DECLARE @UTILIDAD_NETA float  
  
  
  
  --LIMPIAMOS LA TABLA BORRANDO LA DATA    
DELETE FROM CO_TB_REP_EGP      



--COMENZAMOS A CALCULAR LOS IMPORTES DE LOS RUBROS    
    
    
 if @P_ES_MENSUAL = 1 begin      
    
  SET @VENTAS_NETAS =      
  (      
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
   WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES   AND LEFT(AD_CUENTA,2) IN (      
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE  CC_CONCEPTO = 1)      
  )    
 end else begin    
  SET @VENTAS_NETAS =      
  (      
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
   WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES   AND LEFT(AD_CUENTA,2) IN (      
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE  CC_CONCEPTO = 1)      
  )    
 end    
      
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(1,@VENTAS_NETAS,0)      
 

  
  if @P_ES_MENSUAL = 1 begin      
 SET @COSTO_VENTAS =      
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO  and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE  CC_CONCEPTO = 2)      
  )      
    
 end else begin    
 SET @COSTO_VENTAS =      
  (    
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO  and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE  CC_CONCEPTO = 2)      
  )    
 end    
      
      
         INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(2,@COSTO_VENTAS,0)      
      
  SET @UTILIDAD_BRUTA = ISNULL(@VENTAS_NETAS - @COSTO_VENTAS,0)      
      
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(3,@UTILIDAD_BRUTA,0)      
   
   
   if @P_ES_MENSUAL = 1 begin      
      
 SET @GASTOS_ADMINISTRATIVOS =    
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 6)      
  )      
    
 end else begin    
 SET @GASTOS_ADMINISTRATIVOS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 6)      
  )    
 end    
    
   --SET @GASTOS_ADMINISTRATIVOS = @UTILIDAD_BRUTA - @GASTOS_ADMINISTRATIVOS      
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(6,@GASTOS_ADMINISTRATIVOS,0)      
   
   
    if @P_ES_MENSUAL = 1 begin      
  SET @GASTOS_VENTAS =      
   (      
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
   WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 7)      
   )      
 end else begin    
  SET @GASTOS_VENTAS =      
   (      
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
   WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 7)      
   )      
 end    
    
   --SET @GASTOS_VENTAS = @GASTOS_ADMINISTRATIVOS - @GASTOS_VENTAS      
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(7,@GASTOS_VENTAS,0)      
    
  SET @UTILIDAD_OPERATIVA = ISNULL(@UTILIDAD_BRUTA - @GASTOS_ADMINISTRATIVOS - @GASTOS_VENTAS,0)      
         
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(8,@UTILIDAD_OPERATIVA,0)      
      
      
       if @P_ES_MENSUAL = 1 begin      
    
  SET @INGRESOS_FINANCIEROS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 11)      
  )      
 end else begin    
  SET @INGRESOS_FINANCIEROS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 11)      
  )      
 end    
    
    
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(11,@INGRESOS_FINANCIEROS,0)      
      
      
      
      
 
  if @P_ES_MENSUAL = 1 begin      
  SET @GASTOS_FINANCIEROS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 12)      
  )      
 end else begin    
  SET @GASTOS_FINANCIEROS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 12)      
  )      
 end    
    
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(12,@GASTOS_FINANCIEROS,0)      
    
    
   
   
   
       
 if @P_ES_MENSUAL = 1 begin      
  SET @OTROS_INGRESOS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 13)      
  )      
 end else begin    
  SET @OTROS_INGRESOS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 13)      
  )      
 end    
    
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(13,@OTROS_INGRESOS,0)      
    
    
    
     if @P_ES_MENSUAL = 1 begin      
  SET @OTROS_GASTOS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 14)      
  )      
 end else begin    
  SET @OTROS_GASTOS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 14)      
  )      
 end    
    
  INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(14,@OTROS_GASTOS,0)      
   
   
   
   if @P_ES_MENSUAL = 1 begin      
  SET @INGRESOS_EXATRAORDINARIOS =      
   (      
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
   WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 15)      
   )      
 end else begin    
  SET @INGRESOS_EXATRAORDINARIOS =      
   (      
   SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
   FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
   WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
   SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 15)      
   )    
 end     
    
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(15,@INGRESOS_EXATRAORDINARIOS,0)    
   
   
   
    if @P_ES_MENSUAL = 1 begin      
  SET @GASTOS_EXTRAORDINARIOS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 16)      
  )      
 end else begin    
  SET @GASTOS_EXTRAORDINARIOS =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 16)      
  )    
 end    
    
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(16,@GASTOS_EXTRAORDINARIOS,0)      
      
      
        SET @RESULTADO_ANTES = @UTILIDAD_OPERATIVA + @INGRESOS_FINANCIEROS - @GASTOS_FINANCIEROS +       
        @OTROS_INGRESOS - @OTROS_GASTOS + @INGRESOS_EXATRAORDINARIOS -       
        @GASTOS_EXTRAORDINARIOS      
      
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(18,@RESULTADO_ANTES,0)     
   
   
    if @P_ES_MENSUAL = 1 begin     
  SET @PARTICIPACIONES =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 20)      
  )      
 end else begin    
  SET @PARTICIPACIONES =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 20)      
  )    
 end    
    
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(20,@PARTICIPACIONES,0)      
      
       
       
        if @P_ES_MENSUAL = 1 begin     
  SET @IMPUESTO_RENTA =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes = @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 21)      
  )      
 end else begin    
 SET @IMPUESTO_RENTA =      
  (      
  SELECT ISNULL(ABS(SUM(AD_DEBE)-SUM(AD_HABER)) ,0)      
  FROM CO_TB_ASIENTO_CAB A INNER JOIN CO_TB_ASIENTO_DET B ON A.AC_ID = B.AD_IDCAB      
  WHERE AC_ANHO = @P_AYO and ac_mes <= @P_MES  AND LEFT(AD_CUENTA,2) IN (      
  SELECT CC_CUENTA FROM CO_TB_CTA_CONCEPTO_EGP WHERE   CC_CONCEPTO = 21)      
  )    
 end    
    
   INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
   VALUES(21,@IMPUESTO_RENTA,0)  
   
   
SET @UTILIDAD_NETA = @RESULTADO_ANTES - @PARTICIPACIONES - @IMPUESTO_RENTA      
INSERT INTO CO_TB_REP_EGP(EGP_IDCONCEPTO_EGP,EGP_VALOR1,EGP_VALOR2)      
VALUES(22,@UTILIDAD_NETA,0)      

      
SELECT CO_ID,CO_DESCRIPCION,CO_TITULO,ISNULL(EGP_VALOR1,0) AS  VALOR1,ISNULL(EGP_VALOR2,0) AS  VALOR2      
FROM CO_TB_CONCEPTO_EGP A LEFT JOIN CO_TB_REP_EGP B ON A.CO_ID = B.EGP_IDCONCEPTO_EGP      

      

