CREATE PROCEDURE [dbo].[SP_COMPRPTESTINGALMART2K2]    
--DECLARE    
@EMP VARCHAR(50),    
@CODART1 VARCHAR(20),    
@CODART2 VARCHAR(20),    
@TRANS1 VARCHAR(2),    
@TRANS2 VARCHAR(2),    
@TRANS3 VARCHAR(2),    
@TRANS4 VARCHAR(2),    
@TRANS5 VARCHAR(2),    
@TRANS6 VARCHAR(2),    
@FECHA1 VARCHAR(10),    
@FECHA2 VARCHAR(10)    
AS    
EXEC('    
SELECT C.WAREHOUSE_ID, C.DOCUMENT_ID,C.TYPE_TRANS,C.NUMBER_DOCUMENT, C.DATE_DOCUMENT, C.TRANS_ID, C.DOC_ID_REF,     
C.NUM_ID_REF,C.VENDOR_ID, C.CURRENCY_TYPE, C.CURRENCY_EXCHANGE, C.VENDOR_NAME, D.PART_ID, D.PART_DESCRIPTION,     
D.UNIT_PART, D.QTY, D.AVERAGE_COST,P.ID, P.NAME,M.DESCRIPTION, M.UNIT_OF_MEASUREMENT ,M.WEIGHT,M.REFERENCE    
FROM     
['+@EMP+'].DBO.WAREHOUSE_TRANS C INNER JOIN     
['+@EMP+'].DBO.WAREHOUSE_TRANS_LINE D ON C.WAREHOUSE_ID=D.WAREHOUSE_ID AND C.DOCUMENT_ID=D.DOCUMENT_ID AND C.NUMBER_DOCUMENT=D.NUMBER_DOCUMENT LEFT JOIN    
['+@EMP+'].DBO.VENDOR   P ON C.VENDOR_ID=P.ID INNER JOIN     
['+@EMP+'].DBO.PART   M ON D.PART_ID=M.ID    
WHERE  
(C.DOCUMENT_ID=NI OR C.DOCUMENT_ID=NS) AND      
(C.TRANS_ID='+ @TRANS1 +' OR     
C.TRANS_ID='+ @TRANS2 +' OR    
C.TRANS_ID='+ @TRANS3 +' OR     
C.TRANS_ID='+ @TRANS4 +' OR     
C.TRANS_ID='+ @TRANS5 +' OR      
C.TRANS_ID='+ @TRANS6 +') AND     
D.PART_ID>='+ @CODART1 +' AND D.PART_ID<='+ @CODART2 +'  AND      
C.DATE_DOCUMENT>='+@FECHA1+' AND C.DATE_DOCUMENT<='+ @FECHA2 +'     
ORDER BY C.DATE_DOCUMENT,C.TYPE_TRANS,C.NUMBER_DOCUMENT')    
