
--SP_CARTERA_X 'BDNOVAQ','','ME','001','002','0','01','01','DEVELOPER02','24/04/2008'

CREATE PROCEDURE [dbo].[SP_CARTERA_X]  
--DECLARE  
 @EMP VARCHAR(100),  
 @DOC VARCHAR(200),  
 @MON VARCHAR(2),  
 @CLI_INI VARCHAR(11),  
 @CLI_FIN VARCHAR(11),  
 @OPT VARCHAR(1),  
 @VEN_INI varchar(2),  
 @VEN_FIN varchar(2),  
 @PC VARCHAR(60),  
 @FECHA VARCHAR(10)  
AS  
/*  
 SET @EMP='BDNOVAQ'  
 SET @DOC =''  
 SET @MON ='ME'  
 SET @CLI_INI ='001'  
 SET @CLI_FIN ='002'  
 SET @OPT='0'   
 SET @VEN_INI='01'  
 SET @VEN_FIN='01'  
 SET @PC='DEVELOPER02'
 SET @FECHA='24/04/2008'  
*/
 DECLARE @CADENA VARCHAR(2000)  
 IF @OPT='1'  
  SET @CADENA='AND C.DOCUMENT_ID IN (''' + @DOC+ ''')'  
 ELSE  
  SET @CADENA=''  
  
  
 IF EXISTS(SELECT * FROM sysobjects WHERE name=@PC+'CARTERAX')  
     --EXEC('TRUNCATE TABLE '+@PC+'')  
     EXEC('DROP TABLE '+@PC+'CARTERAX')  
  
  
  
 IF @MON='ME'  
EXEC('  
SELECT C.CUSTOMER_ID,M.NAME,C.DOCUMENT_ID,C.NUMBER_DOC,C.DOC_DATE,C.CADUCATE_DATE,C.AMOUNT_BALANCE AS SALDO,  
 C.CURRENCY_ID,C.SELL_RATE,C.AMOUNT_BALANCE_INI AS SALDOINI,V.ID,V.NAME AS NAME_V,(0) AS CHEQUE  
 INTO '+ @PC + 'CARTERAX   
 FROM ['+ @EMP+ '].DBO.CUSTOMER_BALANCE C  
 INNER JOIN ['+ @EMP + '].DBO.CUSTOMER M ON C.CUSTOMER_ID=M.ID  
 INNER JOIN ['+ @EMP + '].DBO.SALES_REP V ON C.SALES_ID=V.ID  
 WHERE C.CUSTOMER_ID>='''+@CLI_INI +''' AND C.CUSTOMER_ID<='''+@CLI_FIN+'''  
 AND C.SALES_ID>='''+@VEN_INI +''' AND C.SALES_ID<='''+@VEN_FIN+'''  
 AND (C.AMOUNT_BALANCE>0.01 OR C.AMOUNT_BALANCE<-0.01)'+@CADENA+'     
 AND C.DOC_DATE<=''' + @FECHA + '''   
   ')  
  
 IF @MON='MN'  
EXEC('  
SELECT C.CUSTOMER_ID,M.NAME,C.DOCUMENT_ID,C.NUMBER_DOC,C.DOC_DATE,C.CADUCATE_DATE,C.AMOUNT_BALANCE*C.SELL_RATE AS SALDO,  
 C.CURRENCY_ID,C.SELL_RATE,C.AMOUNT_BALANCE_INI*C.SELL_RATE AS SALDOINI,V.ID,V.NAME AS NAME_V,(0) AS CHEQUE  
 INTO '+ @PC + 'CARTERAX   
 FROM ['+ @EMP+ '].DBO.CUSTOMER_BALANCE C  
 INNER JOIN ['+ @EMP + '].DBO.CUSTOMER M ON C.CUSTOMER_ID=M.ID  
 INNER JOIN ['+ @EMP + '].DBO.SALES_REP V ON C.SALES_ID=V.ID  
 WHERE C.CUSTOMER_ID>='''+@CLI_INI +''' AND C.CUSTOMER_ID<='''+@CLI_FIN+'''  
 AND C.SALES_ID>='''+@VEN_INI +''' AND C.SALES_ID<='''+@VEN_FIN+'''  
 AND (C.AMOUNT_BALANCE>0.01 OR C.AMOUNT_BALANCE<-0.01)'+@CADENA+'    
 AND C.DOC_DATE<=''' + @FECHA + '''   
')  
  
  
  
--CREO UN CURSOR PARA ACTUALIZAR EL CAMPO DE CHEQUE  
 DECLARE @TIPO VARCHAR(2),@NUMERO VARCHAR(15)  
   
 EXEC('  
  DECLARE ACT_CHEQUE CURSOR FOR  
  SELECT DISTINCT PD.TYPE_DOC,PD.NUMBER_DOC FROM ['+ @EMP + '].dbo.RECEIVABLE_LIST_LINE PD   
  INNER JOIN ['+ @EMP + '].dbo.CUSTOMER_BALANCE C ON  
  C.DOCUMENT_ID=PD.TYPE_DOC AND C.NUMBER_DOC=PD.NUMBER_DOC  
  INNER JOIN ['+ @EMP + '].dbo.CHECKS CH ON CH.CHECK_ID=PD.NUM_REF   
  AND CH.STATUS=''D'' AND PD.DOC_REF=''CH''')  
 OPEN ACT_CHEQUE  
 FETCH NEXT FROM ACT_CHEQUE INTO @TIPO,@NUMERO  
          
 WHILE @@FETCH_STATUS=0  
  BEGIN  
   EXEC('UPDATE '+ @PC +'CARTERAX  SET CHEQUE=1  
    WHERE DOCUMENT_ID='''+@TIPO+''' AND NUMBER_DOC='''+@NUMERO+'''')  
  FETCH NEXT FROM ACT_CHEQUE INTO @TIPO,@NUMERO  
  END  
    
        CLOSE ACT_CHEQUE  
        DEALLOCATE ACT_CHEQUE  
  
  
  
  
 --Realizo sellecion de documentos  
 EXEC('SELECT * FROM '+ @PC+'CARTERAX')  
  
  