CREATE PROCEDURE SP_IVM_ACTUALIZA_ISC_CABECERA
AS

DECLARE @DOCUMENT_ID VARCHAR(2)
DECLARE @NUMBER_SERIE VARCHAR(3)
DECLARE @NUMBER_DOCUMENT VARCHAR(7)
DECLARE @ISC FLOAT

SET @ISC=0

DECLARE CURSORA CURSOR FOR
SELECT DOCUMENT_ID, NUMBER_SERIE, NUMBER_DOCUMENT FROM dbo.RECEIVABLE
WHERE STATUS<>'A' ORDER BY DOCUMENT_ID, NUMBER_SERIE, NUMBER_DOCUMENT
OPEN CURSORA
FETCH NEXT FROM CURSORA
INTO @DOCUMENT_ID,@NUMBER_SERIE,@NUMBER_DOCUMENT
WHILE @@FETCH_STATUS=0
BEGIN
	SELECT @ISC=SUM(ISC) FROM dbo.RECEIVABLE_LINE WHERE DOCUMENT_ID=@DOCUMENT_ID AND NUMBER_SERIE=@NUMBER_SERIE
	AND NUMBER_DOCUMENT=@NUMBER_DOCUMENT
	
	UPDATE dbo.RECEIVABLE SET ISC=@ISC
	WHERE DOCUMENT_ID=@DOCUMENT_ID AND NUMBER_SERIE=@NUMBER_SERIE
	AND NUMBER_DOCUMENT=@NUMBER_DOCUMENT
	
	SET @ISC=0
	
FETCH NEXT FROM CURSORA
INTO @DOCUMENT_ID,@NUMBER_SERIE,@NUMBER_DOCUMENT
END
CLOSE CURSORA
DEALLOCATE CURSORA