

create PROCEDURE [dbo].[SP_LETRAS_COBRAR_X]  
 --DECLARE  
 @EMP VARCHAR(100),  
 @CLI_INI VARCHAR(11),  
 @CLI_FIN VARCHAR(11),  
 @FEC_INI VARCHAR(10),  
 @FEC_FIN VARCHAR(10),  
 @DOC VARCHAR(200),  
 @VEN_INI VARCHAR(2),  
 @VEN_FIN VARCHAR(2),  
 @OPT VARCHAR(1)  
AS  
/* SET @EMP='002'  
 SET @DOC='CB'  
 SET @CLI_INI='0001-TMP'  
 SET @CLI_FIN='TRANSP'  
 SET @VEN_INI='00'  
 SET @VEN_FIN='06'   
 SET @FEC_INI='13/01/2006'  
 SET @FEC_FIN='13/01/2008'  
 SET @OPT='0'*/  
  
  
 DECLARE @CADENA VARCHAR(2000)  
 IF @OPT='1'  
  SET @CADENA='AND L.STATUS_ACT IN (''' + @DOC+ ''')'  
 ELSE  
  SET @CADENA=''  
  
exec('  
SELECT M.ID, M.NAME, M.VAT_REGISTRATION, C.NUMBER_DOC, C.DOC_DATE, C.CADUCATE_DATE,   
C.AMOUNT, C.AMOUNT_BALANCE, C.CURRENCY_ID, L.STATUS_ACT, S.DESCRIPTION, L.BANK_ID, L.NUMBER_BANK,B.NAME,  
V.ID,V.NAME  
FROM ['+@EMP+'].DBO.CUSTOMER M  
INNER JOIN ['+@EMP+'].DBO.CUSTOMER_BALANCE C ON M.ID = C.CUSTOMER_ID  
INNER JOIN ['+@EMP+'].DBO.LETTER L ON C.NUMBER_DOC = L.LETTER_ID  
INNER JOIN ['+@EMP+'].DBO.STATUS_LETTER S ON S.CURRENCY_ID = C.CURRENCY_ID AND S.STATUS_ID = L.STATUS_ACT   
INNER JOIN ['+ @EMP + '].DBO.SALES_REP V ON C.SALES_ID=V.ID  
LEFT JOIN ['+@EMP+'].DBO.BANK B ON L.BANK_ID=B.ID  
WHERE C.DOCUMENT_ID = ''LT''  
AND  C.DOCUMENT_ID = ''LT''   
AND C.AMOUNT_BALANCE>0   
AND M.ID >='''+@CLI_INI+'''   
AND M.ID <='''+@CLI_FIN+'''  
AND C.SALES_ID>='''+@VEN_INI +''' AND C.SALES_ID<='''+@VEN_FIN+'''  
AND C.CADUCATE_DATE >='''+@FEC_INI+'''  
AND C.CADUCATE_DATE <='''+@FEC_FIN+'''  
 '+@CADENA+'  ')  