CREATE PROCEDURE    [dbo].[SP_MIGCLIENTE_NOVAQ]        
@codigo varchar(20),      
@codigo_nq varchar(20)      
AS          
DECLARE @DESTINO VARCHAR(100)        
SET @DESTINO=(SELECT NAMEBDDESTINE  FROM TRANSFER_PARAMETERS)        
    
  if not exists(select * from drog_dany_conta.dbo.customer where id=@codigo)      
     BEGIN      
   INSERT INTO  drog_dany_conta.dbo.customer(         
   ID,DOCUMENT_TYPE_PERSON_ID,DOCUMENT_NUMBER,NAME,TRADE_NAME,FISCAL_ADDRESS,CITY,REFERENCE,        
   TELEPHONE1,FAX1,MAIL,WEBSITE,DATE_CREATION,USER_CREATE,PC,TYPE_COMPANY,NATIONALITY,CURRENCY_ID,        
   AGENTE_PERCEPCION,PRINCIPAL,IS_EXCLUDE_REGIME,IS_TAX_PREF,IS_NO_TAX_PREF,AGENTE_RETENCION,        
   BUENOS_CONTRIBUYENTES)        
   SELECT    top 1      
   @codigo,'06',ISNULL(C.vat_registration,''),ISNULL(C.NAME,''),ISNULL(C.NAME,''),ISNULL(C.DEPARTMENT,''),ISNULL(C.PROVINCE,''),ISNULL(C.CONTACT,''),        
   ISNULL(C.PHONE,''),ISNULL(C.FAX_NUMBER,''),ISNULL(C.EMAIL,''),ISNULL(C.WEBSITE,''),ISNULL(C.CREATE_DATE,''),ISNULL(C.CREATE_USER,''),'' AS PC,ISNULL(C.TYPE_COMPANY,''),ISNULL(C.COUNTRY,''),        
   ISNULL(C.CURRENCY_CREDIT_LIMIT,''),0 AS AGENTE_PERCEPCION,1 AS PRINCIPAL,0 AS IS_EXCLUDE_REGIME,0 AS IS_TAX_PREF,         
   0 AS IS_NO_TAX_PREF,ISNULL(C.RETENTION,''),0 AS BUENOS_CONTRIBUYENTES  FROM CUSTOMER  C        
   WHERE ID=@codigo_nq          
  end      
 