CREATE PROCEDURE TRANSACCIONES_DE_INVENTARIOS_SALIDAS
 AS

DECLARE @TRANS_ID VARCHAR(5)

DECLARE CURSOR1_INGRESO CURSOR FOR
SELECT DISTINCT TRANS_ID FROM TABLA_SEGUNDA_MEDIADORA_TRANSSACCIONES_DE_INVENTARIOS
WHERE IS_IN_OUT='S'
OPEN CURSOR1_INGRESO
FETCH NEXT FROM CURSOR1_INGRESO
INTO @TRANS_ID
WHILE @@FETCH_STATUS=0
BEGIN
	DECLARE @FECHA VARCHAR(10) 
	DECLARE @IN_VALUE NUMERIC(15,9)
	DECLARE @OUT_VALUE NUMERIC(15,9)

	DECLARE CURSOR2_INGRESO CURSOR FOR
	SELECT FECHA,IN_VALUE,OUT_VALUE FROM TABLA_SEGUNDA_MEDIADORA_TRANSSACCIONES_DE_INVENTARIOS WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
	OPEN CURSOR2_INGRESO
	FETCH NEXT FROM CURSOR2_INGRESO
	INTO @FECHA,@IN_VALUE,@OUT_VALUE
	WHILE @@FETCH_STATUS=0
	BEGIN
		IF LEN(@FECHA)=5
		BEGIN
			IF SUBSTRING(@FECHA,5,1)=1
			BEGIN
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN1=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=2
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN2=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=3
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN3=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=4
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN4=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=5
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN5=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=6
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN6=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=7
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN7=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=8
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN8=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=9
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN9=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END

		END
		ELSE IF LEN(@FECHA)=6
		BEGIN
			IF SUBSTRING(@FECHA,5,2)=10
			BEGIN
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN10=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			ELSE IF SUBSTRING(@FECHA,5,2)=11
			BEGIN
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN11=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END
			IF SUBSTRING(@FECHA,5,2)=12
			BEGIN
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET SALIDAS_CAN12=@OUT_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='S'
			END

		END
	FETCH NEXT FROM CURSOR2_INGRESO
	INTO @FECHA,@IN_VALUE,@OUT_VALUE
	END
	CLOSE CURSOR2_INGRESO
	DEALLOCATE CURSOR2_INGRESO
	
FETCH NEXT FROM CURSOR1_INGRESO
INTO @TRANS_ID
END
CLOSE CURSOR1_INGRESO
DEALLOCATE CURSOR1_INGRESO


UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET
INGRESO_CAN1=(CASE WHEN INGRESO_CAN1 IS NULL THEN 0 ELSE INGRESO_CAN1 END),SALIDAS_CAN1=(CASE WHEN SALIDAS_CAN1 IS NULL THEN 0 ELSE SALIDAS_CAN1 END),
INGRESO_CAN2=(CASE WHEN INGRESO_CAN2 IS NULL THEN 0 ELSE INGRESO_CAN2 END),SALIDAS_CAN2=(CASE WHEN SALIDAS_CAN2 IS NULL THEN 0 ELSE SALIDAS_CAN2 END),
INGRESO_CAN3=(CASE WHEN INGRESO_CAN3 IS NULL THEN 0 ELSE INGRESO_CAN3 END),SALIDAS_CAN3=(CASE WHEN SALIDAS_CAN3 IS NULL THEN 0 ELSE SALIDAS_CAN3 END),
INGRESO_CAN4=(CASE WHEN INGRESO_CAN4 IS NULL THEN 0 ELSE INGRESO_CAN4 END),SALIDAS_CAN4=(CASE WHEN SALIDAS_CAN4 IS NULL THEN 0 ELSE SALIDAS_CAN4 END),
INGRESO_CAN5=(CASE WHEN INGRESO_CAN5 IS NULL THEN 0 ELSE INGRESO_CAN5 END),SALIDAS_CAN5=(CASE WHEN SALIDAS_CAN5 IS NULL THEN 0 ELSE SALIDAS_CAN5 END),
INGRESO_CAN6=(CASE WHEN INGRESO_CAN6 IS NULL THEN 0 ELSE INGRESO_CAN6 END),SALIDAS_CAN6=(CASE WHEN SALIDAS_CAN6 IS NULL THEN 0 ELSE SALIDAS_CAN6 END),
INGRESO_CAN7=(CASE WHEN INGRESO_CAN7 IS NULL THEN 0 ELSE INGRESO_CAN7 END),SALIDAS_CAN7=(CASE WHEN SALIDAS_CAN7 IS NULL THEN 0 ELSE SALIDAS_CAN7 END),
INGRESO_CAN8=(CASE WHEN INGRESO_CAN8 IS NULL THEN 0 ELSE INGRESO_CAN8 END),SALIDAS_CAN8=(CASE WHEN SALIDAS_CAN8 IS NULL THEN 0 ELSE SALIDAS_CAN8 END),
INGRESO_CAN9=(CASE WHEN INGRESO_CAN9 IS NULL THEN 0 ELSE INGRESO_CAN9 END),SALIDAS_CAN9=(CASE WHEN SALIDAS_CAN9 IS NULL THEN 0 ELSE SALIDAS_CAN9 END),
INGRESO_CAN10=(CASE WHEN INGRESO_CAN10 IS NULL THEN 0 ELSE INGRESO_CAN10 END),SALIDAS_CAN10=(CASE WHEN SALIDAS_CAN10 IS NULL THEN 0 ELSE SALIDAS_CAN10 END),
INGRESO_CAN11=(CASE WHEN INGRESO_CAN11 IS NULL THEN 0 ELSE INGRESO_CAN11 END),SALIDAS_CAN11=(CASE WHEN SALIDAS_CAN11 IS NULL THEN 0 ELSE SALIDAS_CAN11 END),
INGRESO_CAN12=(CASE WHEN INGRESO_CAN12 IS NULL THEN 0 ELSE INGRESO_CAN12 END),SALIDAS_CAN12=(CASE WHEN SALIDAS_CAN12 IS NULL THEN 0 ELSE SALIDAS_CAN12 END)