CREATE PROCEDURE TRANSACCIONES_DE_INVENTARIOS_INGRESOS
 AS

DECLARE @TRANS_ID VARCHAR(5)

DECLARE CURSOR1_INGRESO CURSOR FOR
SELECT DISTINCT TRANS_ID FROM TABLA_SEGUNDA_MEDIADORA_TRANSSACCIONES_DE_INVENTARIOS
WHERE IS_IN_OUT='I'
OPEN CURSOR1_INGRESO
FETCH NEXT FROM CURSOR1_INGRESO
INTO @TRANS_ID
WHILE @@FETCH_STATUS=0
BEGIN
	DECLARE @FECHA VARCHAR(10) 
	DECLARE @IN_VALUE NUMERIC(15,9)
	DECLARE @OUT_VALUE NUMERIC(15,9)

	DECLARE CURSOR2_INGRESO CURSOR FOR
	SELECT FECHA,IN_VALUE,OUT_VALUE FROM TABLA_SEGUNDA_MEDIADORA_TRANSSACCIONES_DE_INVENTARIOS WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
	OPEN CURSOR2_INGRESO
	FETCH NEXT FROM CURSOR2_INGRESO
	INTO @FECHA,@IN_VALUE,@OUT_VALUE
	WHILE @@FETCH_STATUS=0
	BEGIN
		IF LEN(@FECHA)=5
		BEGIN
			IF SUBSTRING(@FECHA,5,1)=1
			BEGIN
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN1=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=2
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN2=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=3
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN3=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=4
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN4=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=5
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN5=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=6
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN6=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=7
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN7=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=8
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN8=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,1)=9
			BEGIN	
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN9=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END

		END
		ELSE IF LEN(@FECHA)=6
		BEGIN
			IF SUBSTRING(@FECHA,5,2)=10
			BEGIN
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN10=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			ELSE IF SUBSTRING(@FECHA,5,2)=11
			BEGIN
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN11=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END
			IF SUBSTRING(@FECHA,5,2)=12
			BEGIN
				UPDATE TABLA_FINAL_TRANSACCIONES_DE_INVENTARIOS SET INGRESO_CAN12=@IN_VALUE
				WHERE TRANS_ID=@TRANS_ID AND IS_IN_OUT='I'
			END

		END
	FETCH NEXT FROM CURSOR2_INGRESO
	INTO @FECHA,@IN_VALUE,@OUT_VALUE
	END
	CLOSE CURSOR2_INGRESO
	DEALLOCATE CURSOR2_INGRESO
	
FETCH NEXT FROM CURSOR1_INGRESO
INTO @TRANS_ID
END
CLOSE CURSOR1_INGRESO
DEALLOCATE CURSOR1_INGRESO