
CREATE PROCEDURE    [dbo].[USPListarNUMBER_DOCUMENT_PURCHASE]
AS                  
SELECT ID as CODIGO,DESCRIPTION,NUMBER_INI ,NUMBER_FIN, NUMBER , USER_ID ,NAME_FORMAT FROM  dbo.NUMBER_DOCUMENT_PURCHASE
