
CREATE PROCEDURE [dbo].[USPNUMBER_DOCUMENT_PURCHASE]
@SW     Int,
@ID    varchar(2),
@DESCRIPTION    varchar(70),
@NUMBER_INI    float,
@NUMBER_FIN    float,
@NUMBER    float,
@USER_ID    varchar(5),
@NAME_FORMAT    varchar(20)
AS 
BEGIN TRANSACTION

--****** I N S E R T A N D O   L O S    D A T O S *****--
IF @SW = 1 

          INSERT INTO dbo.NUMBER_DOCUMENT_PURCHASE(
ID , DESCRIPTION , NUMBER_INI , NUMBER_FIN , NUMBER , USER_ID , NAME_FORMAT)
VALUES (
@ID , @DESCRIPTION , @NUMBER_INI , @NUMBER_FIN , @NUMBER , @USER_ID , @NAME_FORMAT)

--***** A C T U A L I Z A N D O   L O S    D A T O S *****--
IF @SW = 2 
          UPDATE dbo.NUMBER_DOCUMENT_PURCHASE
          SET
DESCRIPTION = @DESCRIPTION , NUMBER_INI = @NUMBER_INI , NUMBER_FIN = @NUMBER_FIN , NUMBER = @NUMBER , USER_ID = @USER_ID , NAME_FORMAT = @NAME_FORMAT
WHERE ID = @ID

--***** E L I M I N A N D O   L O S    D A T O S *****--
IF @SW = 3
DELETE FROM  dbo.NUMBER_DOCUMENT_PURCHASE
WHERE ID = @ID

IF @@ERROR <> 0
          ROLLBACK TRANSACTION
ELSE
          COMMIT TRANSACTION
