CREATE PROCEDURE VER_DOCUMENTOS_CON_DATA_INCORRECTO
 AS
DECLARE @NUMBER_DOCUMENT VARCHAR(15)
DECLARE @AMOUNT_TAX NUMERIC(22,9)
DECLARE @IGV NUMERIC(22,9)
DECLARE @INDICE_UNO INT
DECLARE @INDICE_DOS INT
DECLARE @EXTRA_UNO VARCHAR(10)
DECLARE @EXTRA_DOS VARCHAR(10)
DECLARE @REDONDEADO NUMERIC(22,9)

DECLARE VER CURSOR FOR

SELECT NUMBER_DOCUMENT,AMOUNT_TAX FROM RECEIVABLE
WHERE STATUS<>'A' AND YEAR(DOCUMENT_DATE)='2010' and month(document_date)='08'
ORDER BY NUMBER_DOCUMENT

OPEN VER
FETCH NEXT FROM VER
INTO @NUMBER_DOCUMENT,@AMOUNT_TAX
WHILE @@FETCH_STATUS=0
BEGIN
	SELECT @IGV=SUM(AMOUNT_TAX) FROM RECEIVABLE_LINE WHERE NUMBER_DOCUMENT=@NUMBER_DOCUMENT	
	SET @INDICE_UNO=CHARINDEX('.',CONVERT(VARCHAR,@AMOUNT_TAX))
	SET @INDICE_DOS=CHARINDEX('.',CONVERT(VARCHAR,@IGV))
	SET @EXTRA_UNO=SUBSTRING(CONVERT(VARCHAR,@AMOUNT_TAX),1,@INDICE_UNO-1)
	SET @EXTRA_DOS=SUBSTRING(CONVERT(VARCHAR,@IGV),1,@INDICE_UNO-1)
	
	IF @EXTRA_DOS=0
	BEGIN
		SET @REDONDEADO=ROUND(@IGV,2)
	END
	IF @EXTRA_UNO<>@EXTRA_DOS
	BEGIN
		PRINT @NUMBER_DOCUMENT
	END

	FETCH NEXT FROM VER
	INTO @NUMBER_DOCUMENT,@AMOUNT_TAX
END
CLOSE VER
DEALLOCATE VER