
CREATE PROCEDURE [dbo].[W_UTILIDAD_VENTAS]
--DECLARE
	@FECHAINI VARCHAR(10),@FECHAFIN VARCHAR(10),
	@ARTINI VARCHAR(20),@ARTFIN VARCHAR(20),
	@INI VARCHAR(2), @FIN VARCHAR(2),
	@CLIINI VARCHAR(11),@CLIFIN VARCHAR(11),
	@PC VARCHAR(60),@OPC VARCHAR(1)

/*SET @FECHAINI='01/10/2007'
SET @FECHAFIN='31/10/2007'
SET @ARTINI='0001'
SET @ARTFIN='SER'
SET @INI='02'
SET @FIN='05'
SET @CLIINI='001'
SET @CLIFIN='CLI43619045'
SET @PC='DEVELOPER03'
--0 es documento 1 es contable
SET @OPC='0'
--*/AS 

IF EXISTS(SELECT * FROM tempdb.dbo.sysobjects WHERE NAME='COSTOS'+@PC)
		EXEC('DROP TABLE [tempdb].dbo.COSTOS'+@PC+'')

IF @OPC='0'
	EXEC ('SELECT FD.PART_ID,FD.PART_DESCRIPTION,FC.DOCUMENT_ID,FC.NUMBER_SERIE,FC.NUMBER_DOCUMENT,FC.CUSTOMER_ID,FC.CUSTOMER_NAME,
		FC.DOCUMENT_DATE,FD.QTY,FD.UNIT,FC.CURRENCY_ID,FD.PRICE_ORI,
		FD.PART_TAX,FC.SELL_RATE AS CFTIPCAM,FD.DISCOUNT,FD.DISCOUNT_CUSTOMER,FD.DISCOUNT_SP,
		FC.IS_GUIA_REC,V.ID,V.NAME,FC.DOCUMENT_REF,FC.SERIE_REF,FC.NUMBER_REF
		INTO [tempdb].dbo.COSTOS'+@PC+'
	FROM RECEIVABLE FC
	INNER JOIN SALES_REP V ON FC.SALES_REP_ID=V.ID
	INNER JOIN RECEIVABLE_LINE FD ON FC.DOCUMENT_ID=FD.DOCUMENT_ID
		AND FC.NUMBER_SERIE=FD.NUMBER_SERIE AND FC.NUMBER_DOCUMENT=FD.NUMBER_DOCUMENT
	INNER JOIN PART MA ON MA.ID=FD.PART_ID
	WHERE FD.PART_ID>=''' + @ARTINI + ''' AND FD.PART_ID<=''' + @ARTFIN + '''
	AND FC.DOCUMENT_DATE>=''' + @FECHAINI + ''' AND FC.DOCUMENT_DATE<=''' + @FECHAFIN + '''
	AND (FC.CUSTOMER_ID>=''' + @CLIINI + ''' AND FC.CUSTOMER_ID<=''' + @CLIFIN + ''')
	AND V.ID>=''' + @INI + ''' AND V.ID<=''' + @FIN + '''
	AND NOT(MA.IS_STOCKED=''N'' AND MA.SERIES=''N'' AND MA.IS_LOT=''N'')
	AND FC.STATUS<>''A''
	AND FD.PART_ID<>''CILIN ''
	ORDER BY FD.PART_ID ')

IF @OPC='1'
	EXEC ('SELECT FD.PART_ID,FD.PART_DESCRIPTION,FC.DOCUMENT_ID,FC.NUMBER_SERIE,FC.NUMBER_DOCUMENT,FC.CUSTOMER_ID,FC.CUSTOMER_NAME,
		FC.DOCUMENT_DATE,FD.QTY,FD.UNIT,FC.CURRENCY_ID,FD.PRICE_ORI,
		FD.PART_TAX,TC.SELL_RATE AS CFTIPCAM,FD.DISCOUNT,FD.DISCOUNT_CUSTOMER,FD.DISCOUNT_SP,
		FC.IS_GUIA_REC,V.ID,V.NAME,FC.DOCUMENT_REF,FC.SERIE_REF,FC.NUMBER_REF
		INTO [tempdb].dbo.COSTOS'+@PC+'
	FROM RECEIVABLE FC
	INNER JOIN SALES_REP V ON FC.SALES_REP_ID=V.ID
	INNER JOIN RECEIVABLE_LINE FD ON FC.DOCUMENT_ID=FD.DOCUMENT_ID
			AND FC.NUMBER_SERIE=FD.NUMBER_SERIE AND FC.NUMBER_DOCUMENT=FD.NUMBER_DOCUMENT
	INNER JOIN CURRENCY_EXCHANGE TC ON TC.CURRENCY_DATE=FC.DOCUMENT_DATE
	INNER JOIN PART MA ON MA.ID=FD.PART_ID
	WHERE FD.PART_ID>=''' + @ARTINI + ''' AND FD.PART_ID<=''' + @ARTFIN + '''
	AND FC.DOCUMENT_DATE>=''' + @FECHAINI + ''' AND FC.DOCUMENT_DATE<=''' + @FECHAFIN + '''
	AND (FC.CUSTOMER_ID>=''' + @CLIINI + ''' AND FC.CUSTOMER_ID<=''' + @CLIFIN + ''')
	AND V.ID>=''' + @INI + ''' AND V.ID<=''' + @FIN + '''
	AND NOT(MA.IS_STOCKED=''N'' AND MA.SERIES=''N'' AND MA.IS_LOT=''N'')
	AND FC.STATUS<>''A''
	AND FD.PART_ID<>''CILIN ''
	ORDER BY FD.PART_ID ')



EXEC ('ALTER TABLE [tempdb].dbo.COSTOS'+@PC+' ADD COSTOMN numeric(15,9)')
EXEC ('ALTER TABLE [tempdb].dbo.COSTOS'+@PC+' ADD COSTOME numeric(15,9)')
EXEC ('ALTER TABLE [tempdb].dbo.COSTOS'+@PC+' ADD COSTOMN_REAL numeric(15,9)')

EXEC ('UPDATE C SET C.COSTOMN = (CASE WHEN C.CURRENCY_ID=''MN'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST * CFTIPCAM END),
	     C.COSTOME = (CASE WHEN C.CURRENCY_ID=''ME'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST / CFTIPCAM END)
FROM [tempdb].dbo.COSTOS'+@PC+' C INNER JOIN WAREHOUSE_TRANS_LINE MD
ON C.PART_ID=MD.PART_ID AND C.DOCUMENT_ID=MD.DOCUMENT_ID
AND C.NUMBER_SERIE=LEFT(MD.NUMBER_DOCUMENT,3) AND C.NUMBER_DOCUMENT=RIGHT(MD.NUMBER_DOCUMENT,7)
WHERE C.IS_GUIA_REC IS NULL OR C.IS_GUIA_REC<>''S'' OR C.IS_GUIA_REC='''' OR C.IS_GUIA_REC='' ''')


EXEC ('UPDATE C SET C.COSTOMN = (CASE WHEN C.CURRENCY_ID=''MN'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST * CFTIPCAM END),
	     C.COSTOME = (CASE WHEN C.CURRENCY_ID=''ME'' THEN MD.AVERAGE_COST ELSE MD.AVERAGE_COST / CFTIPCAM END)
FROM [tempdb].dbo.COSTOS'+@PC+' C INNER JOIN WAREHOUSE_TRANS MC
INNER JOIN WAREHOUSE_TRANS_LINE MD ON MC.DOCUMENT_ID=MD.DOCUMENT_ID
AND MC.WAREHOUSE_ID=MD.WAREHOUSE_ID AND MC.NUMBER_DOCUMENT=MD.NUMBER_DOCUMENT
ON C.DOCUMENT_ID=MC.DOC_ID_REF 
AND C.NUMBER_SERIE=LEFT(MC.NUM_ID_REF,3) AND C.NUMBER_DOCUMENT=RIGHT(MC.NUM_ID_REF,7)
WHERE C.PART_ID=MD.PART_ID AND C.IS_GUIA_REC=''S''')

EXEC ('UPDATE [tempdb].dbo.COSTOS'+@PC+' SET QTY=(CASE WHEN QTY IS NULL THEN 0 ELSE QTY END),
		 PRICE_ORI=(CASE WHEN PRICE_ORI IS NULL THEN 0 ELSE PRICE_ORI END),
		 PART_TAX=(CASE WHEN PART_TAX IS NULL THEN 0 ELSE PART_TAX END),
		 CFTIPCAM=(CASE WHEN CFTIPCAM IS NULL THEN 0 ELSE CFTIPCAM END),
		 DISCOUNT=(CASE WHEN DISCOUNT IS NULL THEN 0 ELSE DISCOUNT END),
 		 DISCOUNT_CUSTOMER=(CASE WHEN DISCOUNT_CUSTOMER IS NULL THEN 0 ELSE DISCOUNT_CUSTOMER END),
		 DISCOUNT_SP=(CASE WHEN DISCOUNT_SP IS NULL THEN 0 ELSE DISCOUNT_SP END),
		 IS_GUIA_REC=(CASE WHEN IS_GUIA_REC IS NULL THEN '''' ELSE IS_GUIA_REC END),
		 COSTOMN=(CASE WHEN COSTOMN IS NULL THEN 0 ELSE COSTOMN END),
		 COSTOME=(CASE WHEN COSTOME IS NULL THEN 0 ELSE COSTOME END)')


--ACTUALIZO EL COSTO REAL EN SOLES
EXEC('UPDATE C SET COSTOMN_REAL=AVERAGE_COST
      FROM [tempdb].dbo.COSTOS'+@PC+' C
      LEFT JOIN [tempdb].dbo.'+@PC+'INVENTORY I
      ON C.DOCUMENT_ID=I.TYPE_DOC AND C.NUMBER_SERIE+C.NUMBER_DOCUMENT=I.NUMBER_DOC
      AND C.PART_ID=I.PART_ID')

--NUEVA ACTUALIZACION PARA CASO DE GUIAS
EXEC(' UPDATE C SET COSTOMN_REAL=AVERAGE_COST
       FROM [tempdb].dbo.COSTOS'+@PC+' C
       INNER JOIN [tempdb].dbo.'+@PC+'INVENTORY  I
       ON C.DOCUMENT_REF=I.TYPE_DOC AND C.SERIE_REF+C.NUMBER_REF=I.NUMBER_DOC
       AND C.PART_ID=I.PART_ID AND IS_GUIA_REC=''S''
')


--HAGO SELECT A TEMPORAL
EXEC('SELECT * FROM [tempdb].dbo.COSTOS'+@PC+' ORDER BY PART_ID,DOCUMENT_ID,NUMBER_SERIE,NUMBER_DOCUMENT')















